"""Django Expert Methodology Pack."""

from deephunter.core.types import BugClass
from deephunter.methodology.packs.base import (
    DecisionTreeBranch,
    DecisionTreeNode,
    InvestigationGoal,
    MethodologyPack,
    PackCategory,
    PackChecklist,
    PackFrameworkProfile,
    PackPlannerRule,
)

PACK = MethodologyPack(
    name="Django",
    version="1.0.0",
    category=PackCategory.FRAMEWORK,
    description="Expert methodology for security testing Django applications. Covers ORM injection, DRF serialization, mass assignment, template injection, admin interface security, and middleware analysis.",
    supported_technologies=["Django", "Python"],
    supported_frameworks=["Django"],
    supported_languages=["Python"],
    attack_surface_areas=[
        "authentication", "authorization", "api", "input validation",
        "session management", "admin interface", "file upload",
        "database", "configuration", "template injection",
    ],
    investigation_priority=85,
    dependencies=[],
    related_packs=["Session Management", "REST API", "File Upload", "JWT"],

    profile=PackFrameworkProfile(
        architecture_description="Django MTV framework with ORM, middleware stack, admin interface, and Django REST Framework for APIs.",
        authentication_components=["Django auth framework (session-based)", "DRF TokenAuthentication", "SimpleJWT", "django-allauth (social auth)", "django-rest-passwordless"],
        authorization_components=["@login_required decorator", "@permission_required", "PermissionRequiredMixin", "UserPassesTestMixin", "DRF permission classes"],
        middleware="SecurityMiddleware, SessionMiddleware, AuthenticationMiddleware, CSRFViewMiddleware, MessageMiddleware, XFrameOptionsMiddleware",
        template_engine="Django template engine: auto-escapes {{ var }}, unsafe filters (safe, escapejs), custom template tags",
        api_layer="Django REST Framework: viewsets, serializers (ModelSerializer, Serializer), permissions, throttling, pagination",
        trust_boundaries=["Middleware stack boundary", "CSRF middleware boundary", "Authentication middleware", "DRF permission/throttle boundary"],
        investigation_areas=[
            "SQL injection via extra() and raw()",
            "Mass assignment in DRF serializers",
            "Template injection (unsafe filters)",
            "Admin interface exposure",
            "DRF serializer data leakage",
            "Session cookie security",
            "File upload path traversal",
            "DEBUG=True in production",
            "CORS misconfiguration",
            "Browseable API exposure",
            "Authentication bypass in DRF",
        ],
    ),

    workflow=[
        "Django Technology Identified",
        "Architecture Review (settings, apps, middleware)",
        "URL and Route Enumeration",
        "Admin Interface Security Review",
        "Authentication Analysis (session/DRF/JWT)",
        "Authorization Analysis (permissions, decorators)",
        "ORM Injection Testing",
        "DRF Serializer Mass Assignment",
        "Template Injection Testing",
        "Session and Cookie Security Review",
        "File Upload Security Review",
        "CORS and Security Headers Review",
        "Evidence Collection",
        "Finding Preparation",
    ],

    checklists=[
        PackChecklist(
            objective="Identify Django version, settings, and debug mode",
            description="Detect Django version from headers/errors and check if DEBUG=True exposes sensitive config.",
            procedure="1. Check X-Frame-Options header (django default)\n2. Trigger 404 with invalid URL\n3. Check /admin/ for styling indicators\n4. Send malformed input to trigger debug traceback",
            priority="critical", difficulty="easy",
            required_evidence=["Debug traceback screenshot", "Django version string"],
            expected_result="Django version and debug mode identified",
            bug_classes=[BugClass.INFO_DISCLOSURE],
            tags=["recon", "django", "fingerprint"],
        ),
        PackChecklist(
            objective="Test DRF serializer mass assignment",
            description="Test DRF ModelSerializers for accepting extra fields that should be read-only or protected.",
            procedure="1. Identify DRF endpoints with POST/PUT/PATCH\n2. Add extra fields to request body (is_admin, is_staff, user_permissions)\n3. Test read_only_fields bypass by explicitly including them\n4. Check nested serializer write permissions",
            priority="critical", difficulty="medium",
            required_evidence=["Extra field accepted in request", "Field value persisted in response"],
            expected_result="Mass assignment vulnerability confirmed or ruled out",
            bug_classes=[BugClass.PRIVILEGE_ESCALATION, BugClass.IDOR],
            tags=["django", "drf", "mass assignment", "serializer"],
        ),
        PackChecklist(
            objective="Test Django ORM SQL injection",
            description="Find extra(), raw(), connection.cursor() calls and test for SQL injection.",
            procedure="1. Search for .extra(), .raw(), .cursor() usage\n2. Test filter parameters with SQL metacharacters\n3. Test order_by with raw expressions\n4. Annotate with raw SQL expressions",
            priority="critical", difficulty="hard",
            required_evidence=["SQL error response", "Time-based blind confirmation"],
            expected_result="SQL injection confirmed or ruled out",
            bug_classes=[BugClass.SQL_INJECTION],
            tags=["django", "orm", "sql injection"],
        ),
        PackChecklist(
            objective="Test Django template injection",
            description="Find unsafe template rendering where user input reaches the template engine unfiltered.",
            procedure="1. Search for render() with user-controlled template_name\n2. Check for safe, escapejs, linebreaks filters in templates\n3. Identify custom template tags accepting user input\n4. Test {{7*7}} in template-rendered user content",
            priority="high", difficulty="medium",
            required_evidence=["Template expression rendered as output", "Code execution proof"],
            expected_result="Template injection confirmed or ruled out",
            bug_classes=[BugClass.SSTI, BugClass.XSS],
            tags=["django", "template injection", "ssti"],
        ),
        PackChecklist(
            objective="Review admin interface security",
            description="Check Django admin for exposure, brute force protection, and sensitive data access.",
            procedure="1. Confirm /admin/ is accessible\n2. Test for default credentials\n3. Check brute force rate limiting\n4. Review registered models for data exposure\n5. Test for CSRF on admin actions",
            priority="high", difficulty="easy",
            required_evidence=["Admin login page screenshot", "Model list showing sensitive data"],
            expected_result="Admin interface security assessed",
            bug_classes=[BugClass.AUTH_BYPASS, BugClass.INFO_DISCLOSURE],
            tags=["django", "admin", "authentication"],
        ),
        PackChecklist(
            objective="Review DRF API authentication and permissions",
            description="Test DRF endpoints for authentication bypass and permission misconfiguration.",
            procedure="1. Enumerate all API endpoints via /api/docs, /api/schema, or browsing\n2. Test unprotected endpoints for auth-required actions\n3. Check permission classes on viewsets\n4. Test authentication token generation and validation\n5. Test throttle rates",
            priority="high", difficulty="medium",
            required_evidence=["Endpoint accessible without auth", "Throttle bypass proof"],
            expected_result="DRF authentication and permissions reviewed",
            bug_classes=[BugClass.AUTH_BYPASS],
            tags=["django", "drf", "api", "authentication"],
        ),
        PackChecklist(
            objective="Test session cookie security",
            description="Review Django session cookie configuration for CSRF protection and cookie flags.",
            procedure="1. Check CSRF_COOKIE_HTTPONLY, CSRF_COOKIE_SECURE, CSRF_COOKIE_SAMESITE\n2. Check SESSION_COOKIE_HTTPONLY, SESSION_COOKIE_SECURE, SESSION_COOKIE_SAMESITE\n3. Check SESSION_EXPIRE_AT_BROWSER_CLOSE\n4. Test CSRF token reuse and prediction",
            priority="high", difficulty="medium",
            required_evidence=["Cookie flags screenshot", "CSRF token reuse proof"],
            expected_result="Session and CSRF cookie configuration assessed",
            bug_classes=[BugClass.CSRF, BugClass.BROKEN_AUTH],
            tags=["django", "session", "cookies", "csrf"],
        ),
        PackChecklist(
            objective="Review CORS and security middleware",
            description="Check CORS configuration and security middleware headers for Django applications.",
            procedure="1. Check django-cors-headers configuration\n2. Review SECURE_SSL_REDIRECT, SECURE_HSTS_SECONDS\n3. Check Content-Security-Policy header\n4. Review X-Frame-Options setting\n5. Check SECURE_CONTENT_TYPE_NOSNIFF",
            priority="medium", difficulty="easy",
            required_evidence=["Response headers screenshot", "Missing security header list"],
            expected_result="Security header posture documented",
            bug_classes=[BugClass.CORS_MISCONFIG],
            tags=["django", "cors", "headers", "security"],
        ),
        PackChecklist(
            objective="Test file upload security",
            description="Review Django file upload handling for path traversal, extension bypass, and stored file access.",
            procedure="1. Identify upload endpoints and FileField/ImageField usage\n2. Test filename path traversal (../../../etc/passwd)\n3. Test extension validation bypass\n4. Check MEDIA_URL and MEDIA_ROOT configuration\n5. Verify stored file access controls",
            priority="high", difficulty="medium",
            required_evidence=["Uploaded file URL", "Path traversal proof"],
            expected_result="File upload security assessed",
            bug_classes=[BugClass.PATH_TRAVERSAL, BugClass.RCE],
            tags=["django", "file upload", "media"],
        ),
    ],

    decision_trees=[
        DecisionTreeNode(
            id="django-root",
            question="What Django-specific attack surface is present?",
            branches=[
                DecisionTreeBranch(
                    condition="Django REST Framework detected",
                    child=DecisionTreeNode(
                        id="django-drf",
                        question="What DRF components to analyze?",
                        branches=[
                            DecisionTreeBranch(condition="ModelSerializer", conclusion="TEST: 1. Extra fields in request 2. ReadOnly field bypass 3. Nested serializer write permissions 4. Meta.fields = '__all__'"),
                            DecisionTreeBranch(condition="Permission classes", conclusion="TEST: 1. IsAuthenticated vs AllowAny 2. Custom permission logic gaps 3. Object-level vs view-level permissions"),
                            DecisionTreeBranch(condition="Browseable API", conclusion="CHECK: 1. Disabled in production? 2. HTML rendering exposing forms 3. CSRF token requirements"),
                        ],
                    ),
                ),
                DecisionTreeBranch(
                    condition="Django Admin interface",
                    conclusion="CHECK: 1. Exposed? 2. Default credentials? 3. Rate limiting? 4. CSRF on actions 5. Model registration exposing sensitive data",
                ),
                DecisionTreeBranch(
                    condition="Class-based views with mixins",
                    conclusion="REVIEW: 1. LoginRequired mixin 2. PermissionRequired mixin 3. Method decorations bypass 4. dispatch() method override",
                ),
            ],
        ),
    ],

    planner_rules=[
        PackPlannerRule(technology="Django", description="Prioritize DRF mass assignment testing", priority_modifier=0.15, phase="input_validation"),
        PackPlannerRule(technology="Django", description="Prioritize admin interface security review", priority_modifier=0.10, phase="authentication_analysis"),
        PackPlannerRule(technology="Django", description="Prioritize Django ORM injection testing", priority_modifier=0.15, phase="input_validation"),
    ],

    references=[
        {"source": "OWASP", "id": "WSTG-INPV-05", "title": "Template Injection"},
        {"source": "CWE", "id": "CWE-915", "title": "Mass Assignment"},
        {"source": "Django", "id": "SEC", "title": "Django Security Documentation", "url": "https://docs.djangoproject.com/en/stable/topics/security/"},
        {"source": "DRF", "id": "SEC", "title": "Django REST Framework Security", "url": "https://www.django-rest-framework.org/topics/security/"},
    ],
    tags=["django", "python", "drf", "orm", "web"],
)
