"""Laravel Expert Methodology Pack.

How experienced bug bounty hunters investigate Laravel applications.
"""

from deephunter.core.types import BugClass
from deephunter.methodology.packs.base import (
    DecisionTreeBranch,
    DecisionTreeNode,
    InvestigationGoal,
    MethodologyPack,
    PackCategory,
    PackChecklist,
    PackFrameworkProfile,
    PackPlannerRule,
)

PACK = MethodologyPack(
    name="Laravel",
    version="1.0.0",
    category=PackCategory.FRAMEWORK,
    description="Expert methodology for security testing Laravel applications. Covers Eloquent ORM injection, mass assignment, Blade SSTI, Sanctum token analysis, middleware bypass, and debug mode exploitation.",
    supported_technologies=["Laravel", "PHP"],
    supported_frameworks=["Laravel"],
    supported_languages=["PHP"],
    attack_surface_areas=[
        "authentication", "authorization", "api", "input validation",
        "session management", "file upload", "database", "configuration",
        "serialization", "template injection",
    ],
    investigation_priority=85,
    dependencies=[],
    related_packs=["Session Management", "JWT", "File Upload", "REST API"],

    profile=PackFrameworkProfile(
        architecture_description="Laravel uses an MVC architecture with Eloquent ORM, a middleware pipeline, service container, and Facade pattern. Request lifecycle: incoming request -> public/index.php -> bootstrap -> kernel -> middleware -> controller -> response.",
        request_lifecycle="Request enters via public/index.php, bootstraps the framework, routes through middleware pipeline, dispatches to controller/closure, returns response through middleware in reverse.",
        authentication_components=["Laravel Sanctum (SPA/token auth)", "Laravel Jetstream", "Laravel Passport (OAuth2)", "Session-based auth", "API tokens"],
        authorization_components=["Gates (via AuthServiceProvider)", "Policies (model-based authorization)", "@can Blade directive", "can middleware", "Form request authorization"],
        routing="Routes defined in routes/web.php, routes/api.php, routes/channels.php. Supports middleware groups, prefix, name, and subdomain routing. Route::resource and Route::apiResource for CRUD.",
        middleware="Global middleware (CheckForMaintenanceMode, TrimStrings, TrustProxies), web middleware group (EncryptCookies, AddQueuedCookiesToResponse, StartSession, ShareErrorsFromSession, VerifyCsrfToken, SubstituteBindings), api middleware group (throttle:api, auth:sanctum, SubstituteBindings).",
        template_engine="Blade: {{ }} auto-escapes HTML. {!! !!} renders raw HTML (XSS vector). @php directives execute raw PHP. Blade components with anonymous components. @include, @extends, @section for layouts.",
        api_layer="Laravel Sanctum for SPA/token API auth. API Resources (Illuminate\\Http\\Resources\\Json\\JsonResource) for response transformation. Form request validation at controller level.",
        storage_layer="Eloquent ORM with MySQL/PostgreSQL/SQLite. Migrations, seeders, factories. Eloquent relationships (hasMany, belongsToMany, morphMany). Query scopes, accessors, mutators.",
        caching="Cache facade with Redis/Memcached/file/database drivers. Route caching (php artisan route:cache). Config caching (php artisan config:cache). View caching (php artisan view:cache).",
        queues="Laravel Queues with Redis/Beanstalkd/SQS/database driver. Horizon for Redis queue monitoring. Failed job table.",
        background_jobs="Laravel Scheduler (php artisan schedule:run). Queued jobs with dispatch(). Notifications (mail, database, broadcast, vonage, slack). Events and listeners.",
        deployment_patterns=["PHP-FPM behind Nginx", "Docker with Laravel Sail", "Forge/Envoyer managed VPS", "Vapor (serverless Laravel on AWS Lambda)", "Shared hosting with Apache"],
        trust_boundaries=[
            "Web middleware boundary (before/after kernel handles request)",
            "Eloquent model serialization boundary (API resources, JSON responses)",
            "Session/database boundary for authenticated state",
            "Queue worker boundary for async job processing",
            "Blade template compilation boundary",
        ],
        typical_components=["Eloquent models", "Form requests with authorization", "Blade templates", "API resources", "Artisan commands", "Mailables", "Notifications", "Events/Listeners", "Job classes", "Middleware classes"],
        technology_relationships={
            "Sanctum": ["SPA authentication", "Token-based API auth"],
            "Eloquent": ["ORM", "SQL injection via raw queries"],
            "Blade": ["Template engine", "SSTI via {!! !!}"],
            "Passport": ["OAuth2 server", "Token scopes"],
        },
        investigation_areas=[
            "Mass assignment via unguarded models",
            "Eloquent SQL injection in raw queries",
            "Blade SSTI via unescaped output",
            "Middleware misconfiguration (except/auth filters)",
            "API resource leakage (hidden fields exposed)",
            "Session fixation and remember token analysis",
            "File upload validation bypass",
            "APP_DEBUG exposed in production",
            "Serialization attacks on unserialize() calls",
            "Artisan console exposed via routes",
            "Sanctum token scoping bypass",
            "Signed route URL manipulation",
        ],
    ),

    workflow=[
        "Laravel Technology Identified",
        "Architecture Review (version, config, debug mode)",
        "Route Enumeration and Analysis",
        "Middleware Stack Analysis",
        "Authentication Review (Sanctum/Passport/Session)",
        "Authorization Review (Gates, Policies, Form Requests)",
        "Eloquent ORM Injection Testing",
        "Mass Assignment Testing",
        "Blade Template Injection Testing",
        "API Resource and Serialization Review",
        "Session and Cookie Security Review",
        "File Upload and Storage Review",
        "Queue and Job Security Review",
        "Artisan Console Exposure Check",
        "Signed Route and URL Manipulation Testing",
        "Dependency Vulnerability Review",
        "Interesting Observations Documented",
        "Evidence Collection",
        "Finding Preparation",
    ],

    checklists=[
        PackChecklist(
            objective="Detect Laravel version and debug mode",
            description="Identify Laravel version from response headers, cookie names, or error pages. Check if APP_DEBUG=true exposes full error traces.",
            procedure="1. Check for X-Powered-By or Set-Cookie with laravel_session\n2. Trigger a 404 error and inspect stack trace\n3. Check /vendor/version or composer.lock exposure\n4. Send malformed input to trigger debug error page",
            priority="critical",
            difficulty="easy",
            required_evidence=["Screenshot of debug error page", "Laravel version string"],
            expected_result="Laravel version identified; debug mode status confirmed",
            related_technologies=["Laravel", "PHP"],
            bug_classes=[BugClass.INFO_DISCLOSURE],
            tags=["recon", "fingerprint", "laravel", "debug"],
        ),
        PackChecklist(
            objective="Test Eloquent mass assignment",
            description="Identify unguarded Eloquent models and test mass assignment to escalate privileges or modify protected attributes.",
            procedure="1. Enumerate API endpoints that accept POST/PUT/PATCH JSON body\n2. Try adding extra fields like 'is_admin', 'role', 'email_verified_at'\n3. Check for $guarded = [] or $fillable omissions in model files\n4. Attempt to set remember_token to a known value",
            priority="critical",
            difficulty="medium",
            required_evidence=["Request showing extra field accepted", "Response showing field was persisted"],
            expected_result="Mass assignment vulnerability confirmed or ruled out",
            related_technologies=["Laravel", "Eloquent"],
            bug_classes=[BugClass.IDOR, BugClass.PRIVILEGE_ESCALATION],
            tags=["mass assignment", "eloquent", "laravel", "api"],
        ),
        PackChecklist(
            objective="Test Blade template injection (SSTI)",
            description="Find unescaped Blade output {!! !!} and test for Server-Side Template Injection.",
            procedure="1. Identify fields rendered via {!! $var !!} in Blade templates\n2. Inject {{7*7}} or {!!phpinfo()!!} into user-controlled fields\n3. Test custom directives for injection\n4. Check for @php blocks with user-controlled input",
            priority="critical",
            difficulty="medium",
            required_evidence=["Payload string in input", "Executed output in response"],
            expected_result="SSTI confirmed or ruled out",
            related_technologies=["Laravel", "PHP", "Blade"],
            bug_classes=[BugClass.SSTI, BugClass.RCE],
            tags=["ssti", "blade", "template injection", "laravel"],
        ),
        PackChecklist(
            objective="Test Eloquent SQL injection",
            description="Find raw SQL queries (DB::raw, whereRaw, orderByRaw) and test for SQL injection.",
            procedure="1. Search for whereRaw, orderByRaw, DB::raw, DB::select, DB::statement in code\n2. Test order parameters (order=name;select * from users)\n3. Test JSON path expressions in PostgreSQL\n4. Grouped WHERE clauses with raw expressions",
            priority="critical",
            difficulty="hard",
            required_evidence=["SQL error message from database", "Time-based blind response difference", "Out-of-band interaction"],
            expected_result="SQL injection confirmed or ruled out",
            related_technologies=["Laravel", "Eloquent", "MySQL", "PostgreSQL"],
            bug_classes=[BugClass.SQL_INJECTION],
            tags=["sql injection", "eloquent", "laravel", "database"],
        ),
        PackChecklist(
            objective="Analyze Sanctum/Passport authentication",
            description="Review Sanctum or Passport implementation for token scoping bypass, token leakage, and SPA authentication weaknesses.",
            procedure="1. Identify Sanctum vs Passport vs session auth\n2. Test token scoping (limited scope token accessing protected endpoints)\n3. Check SPA authentication (SameSite cookie, CSRF protection)\n4. Test token revocation and expiry\n5. Review ability middleware configuration",
            priority="high",
            difficulty="medium",
            required_evidence=["Token generation request/response", "Bypass proof-of-concept"],
            expected_result="Auth mechanism identified and tested for weaknesses",
            related_technologies=["Laravel", "Sanctum", "Passport"],
            bug_classes=[BugClass.AUTH_BYPASS, BugClass.BROKEN_AUTH],
            tags=["authentication", "sanctum", "passport", "laravel"],
        ),
        PackChecklist(
            objective="Review middleware and route security",
            description="Analyze middleware registration and route-to-middleware mapping for protection gaps.",
            procedure="1. List all registered middleware in app/Http/Kernel.php\n2. Check route groups for middleware assignments\n3. Look for ->except() in CSRF middleware\n4. Check throttle:api configuration\n5. Identify routes without auth middleware that require protection",
            priority="high",
            difficulty="medium",
            required_evidence=["Route list with middleware assignments", "Accessible protected endpoint proof"],
            expected_result="Middleware configuration gaps identified",
            related_technologies=["Laravel"],
            bug_classes=[BugClass.AUTH_BYPASS, BugClass.BROKEN_AUTH],
            tags=["middleware", "routes", "laravel", "authorization"],
        ),
        PackChecklist(
            objective="Test signed route URL manipulation",
            description="Laravel signed routes use HMAC for URLs. Test for signature validation bypass and URL parameter tampering.",
            procedure="1. Identify routes using ->signed middleware\n2. Capture a signed URL\n3. Tamper with query parameters\n4. Test expiration bypass (remove expires parameter)\n5. Test temporary URL access after expiry",
            priority="high",
            difficulty="medium",
            required_evidence=["Signed URL before and after tampering", "Successful access with modified URL"],
            expected_result="Signed route security validated or bypass confirmed",
            related_technologies=["Laravel"],
            bug_classes=[BugClass.AUTH_BYPASS],
            tags=["signed routes", "laravel", "hmac", "url manipulation"],
        ),
        PackChecklist(
            objective="Test file upload security",
            description="Review Laravel file upload handling for extension bypass, MIME type validation, and path traversal.",
            procedure="1. Identify upload endpoints using Storage::put, $request->file\n2. Test double extension (.jpg.php), null byte, and case variation\n3. Test MIME type spoofing (image/png with PHP payload)\n4. Test path traversal in filename\n5. Check stored file access controls",
            priority="high",
            difficulty="medium",
            required_evidence=["Uploaded file accessible", "Code execution or path traversal proof"],
            expected_result="File upload security posture assessed",
            related_technologies=["Laravel", "PHP"],
            bug_classes=[BugClass.RCE, BugClass.PATH_TRAVERSAL, BugClass.XSS],
            tags=["file upload", "laravel", "storage"],
            dependencies=["Detect Laravel version and debug mode"],
        ),
        PackChecklist(
            objective="Review serialization and unserialize calls",
            description="Find unserialize() calls in Laravel code (custom code, not framework) and test for PHP object injection.",
            procedure="1. Search codebase for unserialize() calls\n2. Check session serialization settings\n3. Review cookie session store\n4. Test encrypted cookies for deserialization\n5. Check for __wakeup() magic methods in application classes",
            priority="high",
            difficulty="hard",
            required_evidence=["unserialize call trace", "POP chain gadget identification"],
            expected_result="Unserialization vulnerabilities identified or ruled out",
            related_technologies=["Laravel", "PHP"],
            bug_classes=[BugClass.DESERIALIZATION],
            tags=["deserialization", "php", "laravel", "serialization"],
        ),
        PackChecklist(
            objective="Test session and cookie security",
            description="Review Laravel session configuration, cookie attributes, and session fixation protection.",
            procedure="1. Check session driver (file, cookie, database, redis, dynamodb)\n2. Verify cookie attributes (HttpOnly, Secure, SameSite)\n3. Test session fixation (login pre/post session ID comparison)\n4. Review session lifetime and idle timeout\n5. Test concurrent session handling",
            priority="medium",
            difficulty="easy",
            required_evidence=["Cookie attribute screenshot", "Session fixation proof"],
            expected_result="Session configuration documented and weaknesses identified",
            related_technologies=["Laravel"],
            bug_classes=[BugClass.BROKEN_AUTH, BugClass.BROKEN_AUTH],
            tags=["session", "cookies", "laravel", "authentication"],
        ),
        PackChecklist(
            objective="Review API resource exposure",
            description="Check Laravel API Resources for hidden fields, sensitive data leakage, and improper attribute filtering.",
            procedure="1. List all API Resource classes\n2. Compare Resource attributes with model attributes\n3. Test for hidden field exposure (password hashes, API tokens)\n4. Check conditional attributes for logic flaws\n5. Review pagination meta data for sensitive info",
            priority="medium",
            difficulty="medium",
            required_evidence=["API response with unexpected fields", "Sensitive data in response"],
            expected_result="API resource data exposure assessed",
            related_technologies=["Laravel"],
            bug_classes=[BugClass.INFO_DISCLOSURE],
            tags=["api", "resources", "laravel", "serialization"],
        ),
        PackChecklist(
            objective="Check for exposed Artisan commands",
            description="Test if Artisan console commands are accessible via HTTP routes, enabling code execution or info disclosure.",
            procedure="1. Check routes for Artisan call wrappers\n2. Test /artisan, /console, /command endpoints\n3. Try to trigger maintenance mode (php artisan down equivalent)\n4. Check for route:list exposure with all routes\n5. Look for Tinker/db seed endpoints",
            priority="medium",
            difficulty="easy",
            required_evidence=["Artisan command execution proof", "Route list exposure"],
            expected_result="Artisan exposure confirmed or ruled out",
            related_technologies=["Laravel"],
            bug_classes=[BugClass.RCE, BugClass.INFO_DISCLOSURE],
            tags=["artisan", "console", "laravel"],
        ),
        PackChecklist(
            objective="Check cache and config exposure",
            description="Review Laravel caching configuration for sensitive data exposure in cache files and route caching issues.",
            procedure="1. Check if bootstrap/cache/ files are web-accessible\n2. Review config.php for hardcoded secrets\n3. Test route:cache for cached route pattern disclosure\n4. Check view caching for template source exposure\n5. Review cache prefix for environment leakage",
            priority="medium",
            difficulty="easy",
            required_evidence=["Cache file accessible via web", "Sensitive data in cached files"],
            expected_result="Cache exposure assessed",
            related_technologies=["Laravel"],
            bug_classes=[BugClass.INFO_DISCLOSURE],
            tags=["cache", "config", "laravel", "exposure"],
        ),
    ],

    decision_trees=[
        DecisionTreeNode(
            id="laravel-root",
            question="What Laravel component is relevant?",
            description="Decision tree to guide Laravel testing based on discovered features",
            branches=[
                DecisionTreeBranch(
                    condition="Sanctum or Passport authentication detected",
                    description="Review the token/scoped auth flow",
                    child=DecisionTreeNode(
                        id="laravel-auth",
                        question="What authentication mechanism is used?",
                        branches=[
                            DecisionTreeBranch(
                                condition="Sanctum (SPA)",
                                conclusion="Review: 1. SPA session configuration (SameSite, CSRF) 2. Token scoping (ability middleware) 3. Token generation/revocation endpoints",
                            ),
                            DecisionTreeBranch(
                                condition="Sanctum (token)",
                                conclusion="Review: 1. Token creation endpoints 2. Token abilities/permissions 3. Token extraction from Authorization header 4. Token expiry",
                            ),
                            DecisionTreeBranch(
                                condition="Passport (OAuth2)",
                                conclusion="Review: 1. OAuth2 grant types enabled 2. Client credentials security 3. Authorization code flow PKCE 4. Token scopes 5. Redirect URI validation",
                            ),
                            DecisionTreeBranch(
                                condition="Session-based",
                                conclusion="Review: 1. Session cookie attributes 2. Session fixation 3. Session lifetime 4. Concurrent session handling",
                            ),
                        ],
                    ),
                ),
                DecisionTreeBranch(
                    condition="Eloquent ORM used heavily",
                    description="Focus on ORM security",
                    child=DecisionTreeNode(
                        id="laravel-eloquent",
                        question="What ORM patterns are present?",
                        branches=[
                            DecisionTreeBranch(
                                condition="Raw queries (DB::raw, whereRaw)",
                                conclusion="TEST: 1. SQL injection in raw query parameters 2. Order by injection 3. JSON column expression injection",
                            ),
                            DecisionTreeBranch(
                                condition="Mass assignment (unguarded/fillable)",
                                conclusion="TEST: 1. Extra parameter injection 2. Protected attribute overwrite 3. Timestamp manipulation",
                            ),
                            DecisionTreeBranch(
                                condition="Eloquent relationships",
                                conclusion="TEST: 1. Lazy loading N+1 queries 2. Relationship binding injection 3. Pivot table manipulation",
                            ),
                        ],
                    ),
                ),
                DecisionTreeBranch(
                    condition="Blade templates with user input",
                    description="Focus on template injection",
                    conclusion="TEST: 1. {{ }} vs {!! !!} usage audit 2. SSTI payload injection 3. Custom Blade directive analysis 4. @php block injection",
                ),
                DecisionTreeBranch(
                    condition="API endpoints with Sanctum/Passport",
                    description="Focus on API security",
                    child=DecisionTreeNode(
                        id="laravel-api",
                        question="What API security aspects to test?",
                        branches=[
                            DecisionTreeBranch(
                                condition="Token authentication",
                                conclusion="TEST: 1. Rate limiting (throttle middleware) 2. Token revocation 3. Scoping bypass 4. Token leakage in logs/URLs",
                            ),
                            DecisionTreeBranch(
                                condition="Form request validation",
                                conclusion="TEST: 1. Authorization policy bypass 2. Validation logic flaws 3. Empty/null value handling",
                            ),
                            DecisionTreeBranch(
                                condition="API resource serialization",
                                conclusion="TEST: 1. Hidden attribute exposure 2. Conditional attribute logic flaws 3. Pagination meta data leakage",
                            ),
                        ],
                    ),
                ),
                DecisionTreeBranch(
                    condition="File upload functionality",
                    description="Focus on upload security",
                    conclusion="TEST: 1. Extension validation bypass 2. Content-type spoofing 3. Path traversal in filename 4. Stored file access control 5. Double extension",
                ),
            ],
        ),
    ],

    planner_rules=[
        PackPlannerRule(
            technology="Laravel",
            description="Increase priority of mass assignment and SSTI testing for Laravel applications",
            priority_modifier=0.15,
            phase="input_validation",
            tags=["laravel", "ssti", "mass assignment"],
        ),
        PackPlannerRule(
            technology="Laravel",
            description="Increase priority of Sanctum/Passport authentication testing",
            priority_modifier=0.10,
            phase="authentication_analysis",
            tags=["laravel", "sanctum", "passport"],
        ),
        PackPlannerRule(
            technology="Laravel",
            description="Increase priority of API resource serialization review",
            priority_modifier=0.10,
            phase="api_analysis",
            tags=["laravel", "api", "serialization"],
        ),
    ],

    references=[
        {"source": "OWASP", "id": "WSTG-INPV-05", "title": "Template Injection Testing", "url": "https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/18-Testing_for_Server_Side_Template_Injection"},
        {"source": "OWASP", "id": "WSTG-BUSL-01", "title": "Business Logic Testing"},
        {"source": "Laravel", "id": "DOCS", "title": "Laravel Security Documentation", "url": "https://laravel.com/docs/security"},
        {"source": "CWE", "id": "CWE-915", "title": "Mass Assignment"},
        {"source": "CWE", "id": "CWE-89", "title": "SQL Injection"},
        {"source": "CWE", "id": "CWE-94", "title": "Code Injection"},
    ],

    tags=["laravel", "php", "eloquent", "blade", "sanctum", "mvc", "web"],
)
