"""ASP.NET Core knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="aspnet",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="ASP.NET Core — detailed errors in development, ViewState MAC bypass, deserialization in Newtonsoft.Json, insecure Kestrel config.",
    technology=TechnologyProfile(
        name="ASP.NET Core",
        vendor="Microsoft",
        language="C#",
        framework="ASP.NET Core",
        runtime=".NET (6, 7, 8, 9) / .NET Core",
        description="ASP.NET Core is a cross-platform, high-performance framework for building modern, cloud-based, Internet-connected applications with C# and .NET.",
        common_aliases=["aspnet-core", "aspnetcore", "dotnet-core"],
        dependencies=[".NET SDK", "NuGet packages"],
        common_integrations=["Entity Framework Core", "SignalR", "Blazor", "IdentityServer", "Azure AD", "Swagger (Swashbuckle)", "Serilog", "NLog", "AutoMapper", "FluentValidation"],
        architecture_description="Cross-platform HTTP framework with middleware pipeline, dependency injection, and Kestrel web server.",
        request_lifecycle="HTTP request -> Kestrel -> middleware pipeline -> routing -> controller action -> model binding -> filters -> response",
        documentation_url="https://learn.microsoft.com/en-us/aspnet/core/",
        tags=["csharp", "dotnet", "mvc", "blazor", "signalr"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Kestrel Web Server",
            description="Cross-platform web server for ASP.NET Core. Insecure HTTP/2 configuration, TLS bypass, header injection.",
            security_relevance="medium",
            common_vulnerabilities=["Kestrel HTTP/2 rapid reset DoS", "TLS protocol downgrade", "Insecure HTTP/2 header injection", "Kestrel request smuggling"],
            investigation_priority=75,
            tags=["kestrel", "server", "http"],
        ),
        TechnologyComponentProfile(
            name="Detailed Error Pages",
            description="Developer exception page and detailed errors enabled in production. Stack trace, query string, cookie, and header disclosure.",
            security_relevance="high",
            common_vulnerabilities=["Detailed error page in production", "Stack trace exposure", "Query string and cookie disclosure", "Exception details leaking internals"],
            investigation_priority=95,
            tags=["errors", "debug", "DeveloperExceptionPage"],
        ),
        TechnologyComponentProfile(
            name="Model Binding / Validation",
            description="Automatic model binding from HTTP requests. Mass assignment via over-posting, validation bypass via model state.",
            security_relevance="high",
            common_vulnerabilities=["Mass assignment via over-posting", "[Bind] attribute bypass", "Model state bypass via type coercion", "FluentValidation rules missed"],
            investigation_priority=85,
            tags=["models", "binding", "validation"],
        ),
        TechnologyComponentProfile(
            name="Newtonsoft.Json / System.Text.Json",
            description="JSON serialization/deserialization. Deserialization vulnerabilities, type confusion, property manipulation.",
            security_relevance="high",
            common_vulnerabilities=["Newtonsoft Json.NET TypeNameHandling deserialization RCE", "System.Text.Json property name bypass via case insensitive", "Cyclical reference DoS", "Deep object graph stack overflow"],
            investigation_priority=90,
            tags=["json", "serialization", "deserialization"],
        ),
        TechnologyComponentProfile(
            name="Entity Framework Core",
            description="Object-relational mapper for .NET. SQL injection via raw SQL queries, FromSqlRaw, LINQ injection.",
            security_relevance="high",
            common_vulnerabilities=["SQL injection via FromSqlRaw/ExecuteSqlRaw", "LINQ query injection", "Mass assignment via entity tracking", "N+1 query data leaks"],
            investigation_priority=85,
            tags=["entity-framework", "orm", "sql"],
        ),
        TechnologyComponentProfile(
            name="ASP.NET Core Identity",
            description="Membership system for authentication. User enumeration, weak password policies, token management flaws.",
            security_relevance="high",
            common_vulnerabilities=["User enumeration via login/register responses", "Weak password policy enforcement", "Email confirmation token exposure", "Two-factor authentication bypass"],
            investigation_priority=85,
            tags=["identity", "auth", "membership"],
        ),
        TechnologyComponentProfile(
            name="SignalR",
            description="Real-time web functionality via WebSockets. Hub method enumeration, unauthenticated connection, message injection.",
            security_relevance="medium",
            common_vulnerabilities=["Hub method enumeration via JS", "Unauthenticated hub connections", "SignalR message injection", "User ID spoofing via connection"],
            investigation_priority=70,
            tags=["signalr", "websocket", "realtime"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="MVC/API Controllers",
                description="All [ApiController] and [Route] decorated endpoints",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{controller}/{action}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="SignalR Hubs",
                description="WebSocket hub endpoints for real-time communication",
                protocol="WSS/HTTPS",
                method="ANY",
                path="/{hub_name}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Swagger Documentation",
                description="API documentation via Swashbuckle/Swagger",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/swagger/{version}/swagger.json",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/swagger", "/swagger/v1/swagger.json", "/api/*", "/.well-known/openid-configuration", "/.well-known/jwks", "/signin-oidc", "/Account/Login", "/Identity/Account/Login", "/admin", "/hubs/*"],
        parameters=["id", "page", "search", "q", "filter", "sort", "ReturnUrl", "culture"],
        authentication=["ASP.NET Core Identity", "JWT (Microsoft.AspNetCore.Authentication.JwtBearer)", "OpenID Connect", "Cookie authentication", "Azure AD"],
        authorization=["[Authorize] attribute", "Role-based authorization", "Policy-based authorization", "Claims-based authorization"],
        storage=["Local disk", "Azure Blob Storage", "S3", "SQL Server FileStream"],
        background_jobs=["Hangfire", "Quartz.NET", "Azure Queue Storage"],
        queues=["Azure Service Bus", "RabbitMQ", "Azure Queue Storage"],
        caches=["Redis (Microsoft.Extensions.Caching.StackExchangeRedis)", "Memory cache", "SQL Server cache"],
        admin_interfaces=["/admin", "/admin/*", "/dashboard", "/hangfire"],
        internal_apis=["/api/internal/*", "/internal/*", "/admin/api/*"],
        external_apis=["Azure AD", "Microsoft Graph", "Stripe", "SendGrid", "Twilio"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Kestrel", description="HTTP request enters Kestrel web server", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="EF Core queries to database", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-Azure", description="Azure AD and service bus connections", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Developer exception page enabled in production",
            "Newtonsoft Json.NET TypeNameHandling deserialization RCE",
            "Mass assignment via over-posting in model binding",
            "EF Core FromSqlRaw SQL injection",
            "SignalR hub unauthenticated connection",
            "Swagger UI in production exposing API",
            "User enumeration via Identity endpoints",
            "Hangfire dashboard without authentication",
            "Insecure Kestrel HTTP/2 configuration",
            ".NET deserialization via BinaryFormatter/SoapFormatter",
            "ViewState MAC validation bypass (WebForms legacy)",
            "CORS misconfiguration on API endpoints",
        ],
        investigation_areas=[
            "Check for DeveloperExceptionPage in production error pages",
            "Test JSON endpoints for deserialization via TypeNameHandling",
            "Test model binding for over-posting extra fields",
            "Audit EF Core for FromSqlRaw/ExecuteSqlRaw usage",
            "Check SignalR hub endoints for auth requirements",
            "Access /swagger for API documentation exposure",
            "Test Identity endpoints for user enumeration",
            "Check /hangfire for dashboard access",
            "Test CORS headers on API responses",
            "Check Kestrel HTTP/2 configuration for DoS vectors",
            "Test for BinaryFormatter deserialization in legacy endpoints",
            "Review [Authorize] attribute coverage on all endpoints",
        ],
        tags=["aspnet", "csharp", "dotnet", "framework", "web"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "Kestrel",
            "X-Powered-By": "ASP.NET",
            "Set-Cookie": ".AspNetCore.Identity.",
            "Set-Cookie": ".AspNetCore.Session",
            "Set-Cookie": "ARRAffinity",
            "X-ResponseTime": "pattern: [0-9]+",
        },
        cookies=[".AspNetCore.Identity.Application", ".AspNetCore.Session", "ARRAffinity", "__RequestVerificationToken"],
        js_indicators=["aspnet", "ASP.NET", "__RequestVerificationToken", "SignalR", "Blazor"],
        file_indicators=["*.cshtml", "*.csproj", "appsettings.json", "appsettings.Development.json", "web.config", "Program.cs", "Startup.cs", "Dockerfile", "NuGet.config"],
        directory_indicators=["/Controllers/", "/Views/", "/Pages/", "/Models/", "/Services/", "/Hubs/", "/wwwroot/", "/Properties/"],
        server_signatures=["Kestrel", "IIS", "ASP.NET"],
        error_page_signatures=["An error occurred while processing your request", "Development Mode", "Request ID:", "System.Exception", "System.InvalidOperationException"],
        default_paths=["/swagger", "/swagger/v1/swagger.json", "/api", "/Account/Login", "/Identity/Account/Login"],
        default_files=["appsettings.json", "appsettings.Development.json", "web.config", "Program.cs", "Startup.cs", "Dockerfile"],
        metadata_patterns={"generator": "ASP.NET Core", "dotnet-version": "pattern: [0-9]+\\.[0-9]+"},
        tags=["fingerprint", "aspnet", "dotnet"],
    ),
    recon=ReconProfile(
        directories_to_check=["/wwwroot/", "/Properties/", "/Controllers/", "/Views/", "/Pages/", "/Hubs/"],
        files_to_check=["appsettings.json", "appsettings.Development.json", "web.config", "Program.cs", "Startup.cs", "Dockerfile", "NuGet.config"],
        endpoints_to_scan=["/swagger", "/swagger/v1/swagger.json", "/api/*", "/Account/Login", "/Identity/Account/Login", "/admin", "/hangfire", "/health", "/metrics"],
        version_detection_paths=["/swagger/v1/swagger.json", "/appsettings.json"],
        debug_paths_to_check=["/swagger", "/hangfire", "/_vs", "/_framework", "/debug"],
        admin_paths_to_check=["/admin", "/admin/*", "/hangfire", "/dashboard"],
        tags=["recon", "aspnet", "dotnet"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Developer exception page enabled in production reveals stack traces, query strings, cookies, and headers",
            impact="Information disclosure of application internals, user session data, and sensitive parameters",
            attack_scenario="Trigger an error to get detailed exception page with stack traces and environment information",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Newtonsoft.Json TypeNameHandling allows remote code execution via deserialization",
            impact="Remote code execution via crafted JSON payload with type manipulation",
            attack_scenario="Send JSON payload with $type property to trigger deserialization of arbitrary .NET types",
            complexity="high",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Mass assignment via over-posting allows attackers to set restricted model properties",
            impact="Privilege escalation, unauthorized data modification",
            attack_scenario="Add unexpected properties (IsAdmin, Role, etc.) to POST/PUT request bodies",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="User enumeration via ASP.NET Core Identity responses reveals valid usernames",
            impact="Account enumeration for targeted password spraying attacks",
            attack_scenario="Compare response messages or timing on /Account/Login and /Account/Register endpoints",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Hangfire dashboard accessible without authentication allows job manipulation",
            impact="Unauthorized job management, data exposure via job state, delayed job injection",
            attack_scenario="Access /hangfire to view queued jobs, retry failed jobs, or trigger new jobs",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(target_pack_name="dotnet", relationship_type=KnowledgeRelationshipType.RUNS_ON, description="ASP.NET Core runs on .NET runtime", confidence="high"),
        KnowledgeRelationship(target_pack_name="entity-framework-core", relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH, description="ASP.NET Core uses EF Core for data access", confidence="high"),
        KnowledgeRelationship(target_pack_name="signalr", relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH, description="ASP.NET Core integrates with SignalR for real-time", confidence="high"),
        KnowledgeRelationship(target_pack_name="azure", relationship_type=KnowledgeRelationshipType.DEPLOYED_ON, description="ASP.NET Core deployed on Azure", confidence="high"),
        KnowledgeRelationship(target_pack_name="sql-server", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="ASP.NET Core uses SQL Server via EF Core", confidence="high"),
        KnowledgeRelationship(target_pack_name="postgresql", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="ASP.NET Core uses PostgreSQL via Npgsql/EF Core", confidence="high"),
        KnowledgeRelationship(target_pack_name="redis", relationship_type=KnowledgeRelationshipType.CACHES_WITH, description="ASP.NET Core caches with Redis", confidence="high"),
        KnowledgeRelationship(target_pack_name="docker", relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY, description="ASP.NET Core apps containerized with Docker", confidence="medium"),
        KnowledgeRelationship(target_pack_name="nginx", relationship_type=KnowledgeRelationshipType.PROXIED_BY, description="ASP.NET Core behind Nginx proxy", confidence="high"),
        KnowledgeRelationship(target_pack_name="iis", relationship_type=KnowledgeRelationshipType.PROXIED_BY, description="ASP.NET Core hosted on IIS via ANCM", confidence="high"),
    ],
    dependencies=[".NET SDK", "NuGet packages"],
    related_packs=["dotnet", "entity-framework-core", "signalr", "azure", "sql-server", "postgresql", "redis", "docker", "nginx", "iis"],
    workflow=[
        "1. Fingerprint ASP.NET Core via Kestrel server header and ASP.NET cookies",
        "2. Trigger an error to check for DeveloperExceptionPage in production",
        "3. Test JSON endpoints for deserialization via Newtonsoft.Json TypeNameHandling",
        "4. Test model binding for mass assignment by adding unexpected fields",
        "5. Audit EF Core for FromSqlRaw/ExecuteSqlRaw SQL injection",
        "6. Check SignalR hub endpoints for unauthenticated access",
        "7. Access /swagger for API documentation exposure",
        "8. Test Identity endpoints (Login, Register) for user enumeration",
        "9. Check /hangfire for dashboard accessibility",
        "10. Verify CORS configuration on all API endpoints",
        "11. Test [Authorize] attribute coverage on protected endpoints",
        "12. Check Kestrel HTTP/2 configuration for rapid reset DoS",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="ASPNET-01",
            category="Error Handling",
            description="Check if DeveloperExceptionPage is enabled by triggering an error",
            expected_result="Error responses should not include stack traces or detailed exception information",
            tools=["curl", "Burp Suite"],
            references=["https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling"],
        ),
        ManualTestChecklistItem(
            step_id="ASPNET-02",
            category="Deserialization",
            description="Test JSON endpoints for Newtonsoft.Json TypeNameHandling deserialization",
            expected_result="TypeNameHandling should be disabled or restricted to safe types",
            tools=["custom scripts", "Burp Suite"],
            references=["https://learn.microsoft.com/en-us/dotnet/standard/serialization/"],
        ),
        ManualTestChecklistItem(
            step_id="ASPNET-03",
            category="Mass Assignment",
            description="Test model binding for over-posting vulnerabilities",
            expected_result="Unexpected model properties should be ignored during model binding",
            tools=["Burp Suite", "custom scripts"],
            references=["https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api"],
        ),
        ManualTestChecklistItem(
            step_id="ASPNET-04",
            category="Authentication",
            description="Test ASP.NET Core Identity for user enumeration",
            expected_result="Login and register responses should be uniform for valid and invalid users",
            tools=["Burp Suite", "custom scripts"],
            references=["https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity"],
        ),
        ManualTestChecklistItem(
            step_id="ASPNET-05",
            category="Information Disclosure",
            description="Check Hangfire dashboard and Swagger UI accessibility",
            expected_result="Hangfire and Swagger should require authentication in production",
            tools=["curl", "browser"],
            references=["https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle"],
        ),
    ],
    references=[
        {"title": "ASP.NET Core Documentation", "url": "https://learn.microsoft.com/en-us/aspnet/core/"},
        {"title": "ASP.NET Core Security", "url": "https://learn.microsoft.com/en-us/aspnet/core/security/"},
        {"title": "OWASP .NET Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/DotNet_Security_Cheat_Sheet.html"},
        {"title": "Newtonsoft.Json Security", "url": "https://github.com/JamesNK/Newtonsoft.Json"},
        {"title": "CVE ASP.NET Core Collection", "url": "https://www.cve.org/KeywordSearch?keyword=ASP.NET+Core"},
    ],
    cwe_ids=["CWE-502", "CWE-200", "CWE-915", "CWE-89", "CWE-287", "CWE-79", "CWE-306", "CWE-204"],
    cve_ids=["CVE-2024-21319", "CVE-2023-38181", "CVE-2023-33142", "CVE-2022-34716", "CVE-2021-43858", "CVE-2020-1045"],
    tags=["csharp", "dotnet", "aspnet", "web", "framework", "mvc"],
)
