"""Django knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="django",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="Django Python web framework — CSRF bypass, mass assignment via ModelForms, DEBUG=True leaks, SQL injection via raw()/extra(), SSTI in Jinja2 templates, session serialization attacks.",
    technology=TechnologyProfile(
        name="Django",
        vendor="Django Software Foundation",
        language="Python",
        framework="Django",
        runtime="Python 3.x (CPython)",
        description="Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design. Built-in ORM, templating, admin interface, and authentication.",
        common_aliases=["django", "djangorestframework", "drf"],
        dependencies=["Python", "pip", "gunicorn/uWSGI", "PostgreSQL/MySQL/SQLite", "Redis"],
        common_integrations=["PostgreSQL", "MySQL", "SQLite", "Redis", "Celery", "Django REST Framework", "Django Channels", "Django Allauth", "Sentry"],
        architecture_description="MTV (Model-Template-View) pattern with middleware stack, URL dispatcher, and WSGI/ASGI server interface.",
        request_lifecycle="WSGI handler -> RequestMiddleware -> URL resolver -> View -> Middleware response -> Template rendering -> WSGI response",
        documentation_url="https://docs.djangoproject.com/en/stable/",
        tags=["python", "mtv", "orm", "admin", "wsgi", "asgi"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Django ORM",
            description="Object-Relational Mapper with query builder, migrations support, and model definitions. SQL injection via raw(), extra(), or unsafe QuerySet chaining.",
            security_relevance="high",
            common_vulnerabilities=["SQL injection via raw()", "SQL injection via extra()", "Mass assignment via ModelForm", "N+1 query data leaks"],
            investigation_priority=90,
            tags=["orm", "sql", "models"],
        ),
        TechnologyComponentProfile(
            name="Django Templates (Jinja2/DjangoTemplates)",
            description="Template engine for server-side rendering. XSS via unescaped variables, SSTI in Jinja2 configuration.",
            security_relevance="high",
            common_vulnerabilities=["XSS via safe filter", "SSTI in Jinja2", "Template path traversal", "Autoescape bypass"],
            investigation_priority=85,
            tags=["templates", "xss", "ssti", "jinja2"],
        ),
        TechnologyComponentProfile(
            name="Django Admin",
            description="Automatic admin interface with CRUD for all registered models. Exposed at /admin/ by default.",
            security_relevance="high",
            common_vulnerabilities=["Brute-force attacks", "Privilege escalation via staff flags", "Information disclosure via model listing", "CSRF on admin actions"],
            investigation_priority=90,
            tags=["admin", "auth", "crud"],
        ),
        TechnologyComponentProfile(
            name="Authentication System",
            description="Built-in auth with sessions, tokens (DRF), and password hashing. User enumeration, session hijacking, weak hashing.",
            security_relevance="high",
            common_vulnerabilities=["User enumeration via login timing", "Session cookie hijacking", "Weak password hashing (MD5/PBKDF2 config)", "CSRF token bypass"],
            investigation_priority=85,
            tags=["auth", "sessions", "csrf", "tokens"],
        ),
        TechnologyComponentProfile(
            name="Django REST Framework (DRF)",
            description="Framework for building REST APIs. API exposure, insecure serializers, missing permission checks.",
            security_relevance="high",
            common_vulnerabilities=["Mass assignment via ModelSerializer", "API endpoint exposure", "Missing permission classes", "Throttling bypass"],
            investigation_priority=85,
            tags=["api", "rest", "serializers", "permissions"],
        ),
        TechnologyComponentProfile(
            name="Debug Mode (DEBUG=True)",
            description="When DEBUG=True, Django shows detailed error pages with settings, environment variables, and stack traces.",
            security_relevance="high",
            common_vulnerabilities=["SECRET_KEY disclosure", "Database credential leakage", "Environment variable exposure", "Settings configuration dump"],
            investigation_priority=95,
            tags=["debug", "information-disclosure", "error-pages"],
        ),
        TechnologyComponentProfile(
            name="Session & Cache Framework",
            description="Session backends (database, cache, file, cookie). Session data tampering, cache poisoning, insecure session serialization.",
            security_relevance="medium",
            common_vulnerabilities=["Session data tampering (pickle deserialization)", "Session fixation", "Cache poisoning", "Insecure cookie session backend"],
            investigation_priority=75,
            tags=["sessions", "cache", "serialization"],
        ),
        TechnologyComponentProfile(
            name="Middleware Stack",
            description="Request/response middleware for security (SecurityMiddleware, CSRF, Session, Auth). Middleware ordering bugs.",
            security_relevance="medium",
            common_vulnerabilities=["CSRF middleware bypass", "SecurityMiddleware misconfiguration (HSTS, XSS filter)", "CORS middleware misconfiguration"],
            investigation_priority=70,
            tags=["middleware", "security-headers", "cors"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="URL Routes",
                description="All patterns in urlpatterns of every included urls.py",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{route}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="Admin Interface",
                description="Auto-generated admin CRUD at /admin/",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/admin/{model}/{action}",
                parameters=["id"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.PRIVILEGE_ESCALATION.value, BugClass.IDOR.value, BugClass.CSRF.value, BugClass.BROKEN_AUTH.value],
            ),
            AttackSurfaceEntry(
                name="API Views (DRF)",
                description="REST API endpoints built with DRF ViewSets or APIViews",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/api/{version}/{resource}",
                parameters=["format", "page", "search"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.IDOR.value, BugClass.BUSINESS_LOGIC.value, BugClass.AUTH_BYPASS.value, BugClass.RATE_LIMIT_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Static/Media Files",
                description="Django serves static/media files in development. Directory traversal risk.",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/static/{file_path}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.PATH_TRAVERSAL.value, BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/admin/", "/admin/login/", "/api/", "/api-auth/", "/auth/", "/login/", "/logout/", "/password-reset/", "/static/", "/media/"],
        parameters=["csrfmiddlewaretoken", "sessionid", "next", "format", "page", "id", "q", "search"],
        authentication=["Session cookies (sessionid)", "DRF Token auth", "DRF JWT (djangorestframework-simplejwt)", "OAuth via django-allauth", "Basic auth"],
        authorization=["Django permissions", "DRF PermissionClasses", "Django-guardian object-level permissions", "Group-based access", "Decorator-based (@permission_required, @login_required)"],
        storage=["Local filesystem", "S3 (django-storages)", "Azure Blob", "Google Cloud Storage"],
        background_jobs=["Celery", "Django Q", "RQ (Redis Queue)", "Huey"],
        queues=["Redis", "RabbitMQ", "Amazon SQS"],
        caches=["Redis", "Memcached", "Database (db)", "Local memory", "File-based"],
        admin_interfaces=["/admin/", "/admin/login/", "/grappelli/", "/jet/"],
        internal_apis=["/api/internal/", "/api/v1/", "/api/private/"],
        external_apis=["Stripe", "PayPal", "Twilio", "AWS", "Google APIs", "Social auth providers"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-WSGI", description="Request enters Django via WSGI handler", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="ORM queries to database backend", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-Cache", description="Cache operations to Redis/Memcached", direction="outbound", sensitivity="medium"),
            TrustBoundary(name="App-to-Queue", description="Celery tasks to message broker", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "Mass assignment via ModelForm/ModelSerializer",
            "SQL injection in raw()/extra() QuerySet methods",
            "DEBUG=True information disclosure",
            "CSRF token bypass on POST endpoints",
            "Session serialization (pickle) deserialization",
            "Template injection (SSTI) in Jinja2",
            "Admin interface brute-force and privilege escalation",
            "Static/media file directory traversal",
            "CORS misconfiguration in DRF views",
            "User enumeration via login/password-reset endpoints",
            "Cache poisoning via session key manipulation",
            "HTTP method fuzzing on API endpoints",
        ],
        investigation_areas=[
            "Check DEBUG=False in production settings",
            "Probe all views using raw() and extra() ORM methods",
            "Test ModelForm for mass assignment with unexpected fields",
            "Inspect template rendering for unescaped variables",
            "Verify CSRF token validation on all POST/PUT/DELETE routes",
            "Test admin interface for unauthorized access",
            "Check DRF permission classes on all API views",
            "Verify session cookie flags (HttpOnly, Secure, SameSite)",
            "Check static/media file serving for path traversal",
            "Test Celery task endpoint exposure",
            "Verify SECRET_KEY is not exposed in error pages",
            "Check CORS headers on API responses",
            "Test for pickle deserialization in session backends",
        ],
        tags=["django", "python", "framework", "web", "orm"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Frame-Options": "DENY",
            "X-Content-Type-Options": "nosniff",
            "Referrer-Policy": "same-origin",
            "Set-Cookie": "sessionid=",
            "Set-Cookie": "csrftoken=",
        },
        cookies=["sessionid", "csrftoken", "messages"],
        js_indicators=["django.jQuery", "window.__admin_media_prefix__", "django.catalog", "Django.ajax"],
        file_indicators=["manage.py", "requirements.txt", "Pipfile", "Pipfile.lock", "setup.cfg", "pyproject.toml", "uwsgi.ini", "gunicorn.conf.py", "Dockerfile"],
        directory_indicators=["/static/", "/media/", "/templates/", "/migrations/", "/fixtures/", "/management/", "/templatetags/"],
        server_signatures=["Django", "WSGIServer", "gunicorn", "uWSGI"],
        error_page_signatures=["Django version", "Traceback (most recent call last)", "Request Method", "Exception Type", "Request URL", "Django tried these URL patterns", "Page not found (404)"],
        default_paths=["/admin/", "/admin/login/", "/static/", "/media/", "/api/", "/api-auth/", "/login/", "/logout/"],
        default_files=["manage.py", "requirements.txt", "Dockerfile", "docker-compose.yml", ".env", ".gitignore", "Pipfile"],
        metadata_patterns={"generator": "Django", "csrf_token": "pattern: [A-Za-z0-9]{64}"},
        tags=["fingerprint", "django", "python"],
    ),
    recon=ReconProfile(
        directories_to_check=["/static/", "/static/admin/", "/media/", "/media/uploads/", "/migrations/", "/fixtures/", "/templates/", "/templatetags/"],
        files_to_check=["manage.py", "requirements.txt", ".env", ".env.example", "Pipfile", "Pipfile.lock", "docker-compose.yml", "Dockerfile", "uwsgi.ini", "gunicorn.conf.py", "pyproject.toml"],
        endpoints_to_scan=["/admin/", "/admin/login/", "/api/", "/login/", "/logout/", "/password-reset/", "/static/", "/media/", "/api-auth/"],
        version_detection_paths=["/admin/", "/static/admin/css/base.css", "/api/"],
        debug_paths_to_check=["/__debug__/", "/__reload__/", "/debug/", "/silk/", "/sentry/"],
        admin_paths_to_check=["/admin/", "/admin/login/", "/grappelli/", "/jet/", "/impersonate/"],
        tags=["recon", "django", "python"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Mass assignment via ModelForm allows setting arbitrary model fields through HTTP parameters",
            impact="Privilege escalation, unauthorized data modification, account takeover",
            attack_scenario="Add is_staff=true or is_superuser=true to a POST request during registration or profile update",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="DEBUG=True in production reveals SECRET_KEY, database passwords, and environment variables",
            impact="Full compromise of application secrets and infrastructure credentials",
            attack_scenario="Trigger any 404 or 500 error to see detailed debug page with settings dump",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Django session serialization uses pickle when configured with certain cache backends",
            impact="Remote code execution via crafted session data",
            attack_scenario="Forge a malicious session cookie containing pickle payload that deserializes on server load",
            complexity="high",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="User enumeration via timing difference in login and password reset endpoints",
            impact="Account enumeration, password spraying target identification",
            attack_scenario="Compare response times or messages between existing and non-existing usernames",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="DRF API views without explicit permission_classes allow unauthorized access",
            impact="Unauthorized data access, data leakage via unauthenticated API calls",
            attack_scenario="Access API endpoints without authentication header when permission_classes is empty list",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="python",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="Django runs on Python",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="postgresql",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="Django commonly uses PostgreSQL",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="mysql",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="Django supports MySQL database backend",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="Django uses Redis for cache, sessions, and Celery broker",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="celery",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Django integrates with Celery for async task processing",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="flask",
            relationship_type=KnowledgeRelationshipType.SIMILAR_TO,
            description="Django and Flask are both Python web frameworks",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="nginx",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Django commonly runs behind Nginx proxy",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Django applications are containerized with Docker",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="fastapi",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Django can integrate with FastAPI via ASGI middleware",
            confidence="low",
        ),
        KnowledgeRelationship(
            target_pack_name="graphql",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Django integrates with GraphQL via graphene-django",
            confidence="medium",
        ),
    ],
    dependencies=["Python", "pip", "PostgreSQL/MySQL/SQLite", "gunicorn/uWSGI"],
    related_packs=["python", "postgresql", "mysql", "redis", "celery", "flask", "fastapi", "nginx", "docker"],
    workflow=[
        "1. Fingerprint Django via sessionid/csrftoken cookies and /admin/ endpoint",
        "2. Check /admin/ and /admin/login/ for admin panel exposure",
        "3. Test DEBUG=True by requesting nonexistent paths and observing error pages",
        "4. Probe all POST endpoints for CSRF token bypass (omit/modify csrfmiddlewaretoken)",
        "5. Test ModelForm endpoints for mass assignment (add is_staff, is_superuser, etc.)",
        "6. Search for raw()/extra() usage in views — test with SQL injection payloads",
        "7. Check DRF API views for missing permission_classes",
        "8. Inspect template rendering for XSS via unescaped {{ variable }} usage",
        "9. Test static/media file serving for directory traversal (/static/../../../etc/passwd)",
        "10. Verify session cookie security attributes (HttpOnly, Secure, SameSite)",
        "11. Check for Celery task endpoint exposure and task forgery",
        "12. Test for pickle deserialization in session/cache backends",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="DJANGO-01",
            category="Information Disclosure",
            description="Check if DEBUG=True by requesting a nonexistent URL",
            expected_result="Error page should not reveal settings, environment variables, or stack traces",
            tools=["curl", "Burp Suite"],
            references=["https://docs.djangoproject.com/en/stable/ref/settings/#debug"],
        ),
        ManualTestChecklistItem(
            step_id="DJANGO-02",
            category="Mass Assignment",
            description="Test mass assignment by adding unexpected model fields to POST/PUT requests",
            expected_result="Unexpected fields should be silently ignored or rejected with validation error",
            tools=["Burp Suite", "custom scripts"],
            references=["https://docs.djangoproject.com/en/stable/topics/forms/modelforms/"],
        ),
        ManualTestChecklistItem(
            step_id="DJANGO-03",
            category="SQL Injection",
            description="Test ORM raw() and extra() methods for SQL injection",
            expected_result="User-supplied values should be parameterized, not concatenated into SQL strings",
            tools=["sqlmap", "custom scripts"],
            references=["https://docs.djangoproject.com/en/stable/topics/db/sql/"],
        ),
        ManualTestChecklistItem(
            step_id="DJANGO-04",
            category="CSRF Protection",
            description="Test CSRF token validation by removing or modifying the csrfmiddlewaretoken",
            expected_result="Requests without valid CSRF token should return 403 Forbidden",
            tools=["Burp Suite", "curl"],
            references=["https://docs.djangoproject.com/en/stable/ref/csrf/"],
        ),
        ManualTestChecklistItem(
            step_id="DJANGO-05",
            category="Authentication",
            description="Test for user enumeration via login and password-reset endpoints",
            expected_result="Responses should be identical for valid and invalid usernames",
            tools=["Burp Suite", "custom scripts"],
            references=["https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/03-Identity_Management_Testing/04-Test_for_Account_Enumeration_and_Guessable_User_Account"],
        ),
    ],
    references=[
        {"title": "Django Documentation", "url": "https://docs.djangoproject.com/en/stable/"},
        {"title": "Django Security Documentation", "url": "https://docs.djangoproject.com/en/stable/topics/security/"},
        {"title": "OWASP Django Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Django_Cheat_Sheet.html"},
        {"title": "Django REST Framework Security", "url": "https://www.django-rest-framework.org/topics/security/"},
        {"title": "CVE Django Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Django"},
    ],
    cwe_ids=["CWE-915", "CWE-89", "CWE-79", "CWE-200", "CWE-352", "CWE-502", "CWE-22", "CWE-204"],
    cve_ids=["CVE-2024-42005", "CVE-2024-38875", "CVE-2023-43665", "CVE-2022-36359", "CVE-2021-45115", "CVE-2020-7471", "CVE-2019-6975"],
    tags=["python", "django", "web", "framework", "mtv", "orm"],
)
