"""Drupal knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="drupal",
    version="1.0.0",
    category=KnowledgePackCategory.CMS,
    description="Drupal CMS — /node/ endpoint, PHP filter module, trusted host bypass, update.php access.",
    technology=TechnologyProfile(
        name="Drupal",
        vendor="Drupal Association",
        language="PHP",
        framework="Drupal",
        runtime="PHP 8.x",
        description="Drupal is a free and open-source web content management system written in PHP and distributed under the GNU General Public License.",
        common_aliases=["drupal", "drupal-cms"],
        dependencies=["PHP", "MySQL/PostgreSQL/SQLite", "Drush", "Composer"],
        common_integrations=["MySQL", "PostgreSQL", "SQLite", "Redis", "Memcached", "Varnish", "Apache Solr", "Elasticsearch", "Drush"],
        architecture_description="Modular CMS with hook system, entities, plugins (modules), themes, and the Drupal API.",
        request_lifecycle="HTTP request -> index.php -> bootstrap -> hook system -> menu router -> controller -> theme rendering -> response",
        documentation_url="https://www.drupal.org/documentation",
        tags=["php", "cms", "modules", "entities"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Node API (/node/)",
            description="Core content entity endpoint at /node/{nid}. Node ID enumeration, content access bypass, revision history disclosure.",
            security_relevance="high",
            common_vulnerabilities=["Node ID enumeration via sequential /node/{nid}", "Unpublished node access bypass", "Node revision history disclosure", "Node add/edit CSRF"],
            investigation_priority=90,
            tags=["node", "content", "entity"],
        ),
        TechnologyComponentProfile(
            name="PHP Filter Module",
            description="Allows PHP code execution within content. When enabled, any user with proper permissions can execute arbitrary PHP via node/block content.",
            security_relevance="critical",
            common_vulnerabilities=["PHP code execution via PHP Filter in content", "Arbitrary PHP execution in blocks", "Permission misconfiguration allowing PHP Filter", "Stored XSS via PHP Filter bypass"],
            investigation_priority=99,
            tags=["php-filter", "code-execution", "module"],
        ),
        TechnologyComponentProfile(
            name="User & Authentication",
            description="Drupal user system with roles and permissions. User enumeration, session hijacking, mass assignment via user register.",
            security_relevance="high",
            common_vulnerabilities=["User enumeration via /user/{uid}", "Session cookie hijacking", "Mass assignment during user registration", "Role escalation via profile edit"],
            investigation_priority=90,
            tags=["users", "auth", "roles", "sessions"],
        ),
        TechnologyComponentProfile(
            name="Drupal API / REST",
            description="RESTful API via REST UI module or Drupal Core REST. Endpoint exposure, serialization vulnerabilities, field access bypass.",
            security_relevance="high",
            common_vulnerabilities=["REST API endpoint enumeration", "Serialization via HAL/JSON/XML formats", "Field-level access bypass via REST", "Entity CRUD via REST without authorization"],
            investigation_priority=85,
            tags=["rest", "api", "serialization"],
        ),
        TechnologyComponentProfile(
            name="Update.php & Cron",
            description="Database update script and cron system. update.php access without authentication allows schema manipulation.",
            security_relevance="critical",
            common_vulnerabilities=["update.php accessible without authentication", "Database schema manipulation via update.php", "Cron.php unauthorized execution", "Cron-based code injection"],
            investigation_priority=95,
            tags=["update", "cron", "database"],
        ),
        TechnologyComponentProfile(
            name="Trusted Host Settings",
            description="Trusted host configuration for HTTP_HOST header validation. Bypass allows cache poisoning, password reset poisoning, and SSRF.",
            security_relevance="high",
            common_vulnerabilities=["Trusted host bypass via Host header injection", "Password reset poisoning via untrusted host", "Cache poisoning via Host header manipulation", "Link injection via untrusted Host"],
            investigation_priority=85,
            tags=["trusted-host", "host-header", "cache-poisoning"],
        ),
        TechnologyComponentProfile(
            name="Third-Party Modules",
            description="Community modules via Drupal.org. Vulnerable module versions, insecure module code, outdated dependencies.",
            security_relevance="high",
            common_vulnerabilities=["Outdated module with known vulnerabilities", "SQL injection via module database queries", "XSS in module output", "Module privilege escalation"],
            investigation_priority=85,
            tags=["modules", "plugins", "third-party"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Node Pages",
                description="Content pages at /node/{nid}",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/node/{nid}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.IDOR.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="User Pages",
                description="User profile pages at /user/{uid}",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/user/{uid}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Update Script",
                description="Database update script at /update.php",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/update.php",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.RCE.value, BugClass.PRIVILEGE_ESCALATION.value],
            ),
            AttackSurfaceEntry(
                name="REST API",
                description="REST API endpoints",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{entity_type}/{id}?_format={format}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.IDOR.value, BugClass.BUSINESS_LOGIC.value, BugClass.DESERIALIZATION.value],
            ),
        ],
        endpoints=["/node", "/node/{nid}", "/node/add", "/user", "/user/{uid}", "/user/login", "/user/register", "/admin", "/update.php", "/cron.php", "/admin/modules", "/admin/config", "/rest", "/api", "/.well-known"],
        parameters=["nid", "uid", "q", "destination", "render", "format", "_format", "id"],
        authentication=["Drupal session cookies (SESS*)", "Basic auth", "OAuth", "REST API keys"],
        authorization=["Drupal roles and permissions", "Node access system", "Route permissions", "Custom module access checks"],
        storage=["Local filesystem (sites/default/files)", "S3 (via module)", "CDN"],
        background_jobs=["Drupal Cron", "Ultimate Cron module"],
        queues=["Drupal Queue API", "Redis (via module)"],
        caches=["Redis", "Memcached", "Internal page cache", "Internal dynamic page cache"],
        admin_interfaces=["/admin", "/admin/content", "/admin/people", "/admin/modules", "/admin/config", "/admin/structure"],
        internal_apis=["/rest/*", "/api/*", "/node/*/edit", "/node/*/delete"],
        external_apis=["Twitter", "Facebook", "reCAPTCHA", "Mailchimp"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Drupal", description="Request enters Drupal bootstrap", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="Drupal queries to MySQL/PostgreSQL", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-Cache", description="Cache operations to Redis/Memcached", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "PHP Filter module enabling arbitrary code execution in content",
            "update.php accessible without authentication",
            "Node ID enumeration via sequential /node/{nid}",
            "User enumeration via /user/{uid}",
            "Trusted host bypass for cache/password reset poisoning",
            "REST API endpoint access without proper permissions",
            "File upload unrestricted in sites/default/files",
            "Cron.php unauthorized execution",
            "Third-party module with known vulnerabilities",
            "Drupal version disclosure via CHANGELOG.txt",
            "SQL injection via database query in custom modules",
            "Session cookie hijacking via insecure flags",
        ],
        investigation_areas=[
            "Check if PHP Filter module is enabled and who can use it",
            "Test /update.php for unauthenticated access",
            "Enumerate node IDs via /node/1, /node/2, /node/3",
            "Check /user/1, /user/2 for user enumeration",
            "Test Host header injection against the site",
            "Check REST API access for unauthorized entity operations",
            "Check /sites/default/files for directory listing",
            "Check /cron.php for unauthorized execution",
            "Check /CHANGELOG.txt for version disclosure",
            "Enumerate installed modules via /admin/modules (if auth)",
            "Test file upload for php file execution",
            "Check .htaccess in sites/default/files for security",
        ],
        tags=["drupal", "cms", "php", "web"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Powered-By": "PHP",
            "X-Drupal-Cache": "HIT|MISS",
            "X-Drupal-Dynamic-Cache": "HIT|MISS",
            "Set-Cookie": "SESS",
            "Set-Cookie": "SSESS",
        },
        cookies=["SESS*", "SSESS*", "Drupal.visitor.*"],
        js_indicators=["Drupal", "Drupal.settings", "drupalSettings", "jQuery.extend(Drupal.settings"],
        file_indicators=["CHANGELOG.txt", "INSTALL.txt", "INSTALL.mysql.txt", "INSTALL.pgsql.txt", "MAINTAINERS.txt", "UPGRADE.txt", "sites/default/settings.php", "composer.json", "composer.lock", "robots.txt"],
        directory_indicators=["/sites/", "/sites/default/", "/sites/default/files/", "/modules/", "/themes/", "/profiles/", "/core/", "/vendor/", "/misc/"],
        server_signatures=["Drupal", "PHP"],
        error_page_signatures=["Drupal", "The website encountered an unexpected error", "Page not found", "Access denied", "PDOException", "Drupal\\Core\\"],
        default_paths=["/", "/node", "/user", "/user/login", "/user/register", "/admin", "/update.php", "/cron.php"],
        default_files=["CHANGELOG.txt", "INSTALL.txt", "composer.json", "composer.lock", "robots.txt", ".htaccess"],
        metadata_patterns={"generator": "Drupal", "drupal-version": "pattern: [0-9]+\\.[0-9]+"},
        tags=["fingerprint", "drupal", "cms"],
    ),
    recon=ReconProfile(
        directories_to_check=["/sites/", "/sites/default/", "/sites/default/files/", "/modules/", "/themes/", "/core/", "/vendor/", "/profiles/"],
        files_to_check=["CHANGELOG.txt", "INSTALL.txt", "composer.json", "composer.lock", "robots.txt", ".htaccess", "sites/default/settings.php"],
        endpoints_to_scan=["/node", "/node/1", "/user/1", "/user/login", "/user/register", "/admin", "/update.php", "/cron.php", "/rest"],
        version_detection_paths=["/CHANGELOG.txt", "/core/CHANGELOG.txt", "/composer.json"],
        debug_paths_to_check=["/update.php", "/cron.php", "/devel", "/admin/reports/dblog"],
        admin_paths_to_check=["/admin", "/admin/content", "/admin/people", "/admin/modules", "/admin/config", "/admin/structure"],
        tags=["recon", "drupal", "cms"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="PHP Filter module allows users with 'use PHP for content' permission to execute arbitrary PHP code",
            impact="Remote code execution via PHP code embedded in node content or blocks",
            attack_scenario="Create or edit a node with PHP Filter input format and execute arbitrary system commands",
            complexity="low",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="/update.php accessible without authentication allows database schema manipulation",
            impact="Database schema modification, privilege escalation, site takeover",
            attack_scenario="Access /update.php to run pending database updates that can alter schema or insert admin users",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Trusted host bypass via Host header injection leads to cache and password reset poisoning",
            impact="Cache poisoning of pages, password reset link hijacking, SSRF via generated links",
            attack_scenario="Inject malicious Host header to generate password reset links pointing to attacker domain",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Node ID enumeration reveals content IDs and access to unpublished nodes",
            impact="Unauthorized reading of unpublished or restricted content",
            attack_scenario="Iterate /node/{nid} to discover unpublished nodes or content with incorrect access permissions",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="User ID enumeration via /user/{uid} reveals registered user accounts",
            impact="Target identification for social engineering and password attacks",
            attack_scenario="Iterate /user/1 through /user/1000 to enumerate registered usernames",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(target_pack_name="php", relationship_type=KnowledgeRelationshipType.RUNS_ON, description="Drupal runs on PHP", confidence="high"),
        KnowledgeRelationship(target_pack_name="mysql", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="Drupal uses MySQL/MariaDB", confidence="high"),
        KnowledgeRelationship(target_pack_name="postgresql", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="Drupal supports PostgreSQL", confidence="high"),
        KnowledgeRelationship(target_pack_name="redis", relationship_type=KnowledgeRelationshipType.CACHES_WITH, description="Drupal caches with Redis", confidence="medium"),
        KnowledgeRelationship(target_pack_name="memcached", relationship_type=KnowledgeRelationshipType.CACHES_WITH, description="Drupal caches with Memcached", confidence="medium"),
        KnowledgeRelationship(target_pack_name="wordpress", relationship_type=KnowledgeRelationshipType.COMPETES_WITH, description="Drupal competes with WordPress as CMS", confidence="medium"),
        KnowledgeRelationship(target_pack_name="nginx", relationship_type=KnowledgeRelationshipType.PROXIED_BY, description="Drupal behind Nginx", confidence="high"),
        KnowledgeRelationship(target_pack_name="apache", relationship_type=KnowledgeRelationshipType.PROXIED_BY, description="Drupal runs on Apache", confidence="high"),
        KnowledgeRelationship(target_pack_name="docker", relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY, description="Drupal containerized with Docker", confidence="medium"),
    ],
    dependencies=["PHP", "MySQL/PostgreSQL/SQLite", "Drush", "Composer"],
    related_packs=["php", "mysql", "postgresql", "redis", "memcached", "wordpress", "nginx", "apache", "docker"],
    workflow=[
        "1. Fingerprint Drupal via X-Drupal-Cache headers and CHANGELOG.txt",
        "2. Check /CHANGELOG.txt or /core/CHANGELOG.txt for version disclosure",
        "3. Enumerate node IDs at /node/1, /node/2, /node/3 etc.",
        "4. Check /user/1, /user/2 for user enumeration",
        "5. Test /update.php for unauthenticated access",
        "6. Check if PHP Filter module is available and usable",
        "7. Test Host header injection for trusted host bypass",
        "8. Check REST API endpoint for unauthorized access (/rest, /api)",
        "9. Probe /cron.php for unauthorized execution",
        "10. Check /sites/default/files for directory listing",
        "11. Enumerate modules via /modules/ and CHANGELOG.txt analysis",
        "12. Check for .htaccess in sites/default/files for security misconfig",
        "13. Test user registration for mass assignment",
        "14. Check for outdated module CVEs",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="DRUPAL-01",
            category="Code Execution",
            description="Check if PHP Filter module is enabled and who has access",
            expected_result="PHP Filter module should be disabled or restricted to trusted administrators only",
            tools=["browser", "Drush"],
            references=["https://www.drupal.org/docs/core-modules-and-themes/core-modules/php-filter-module"],
        ),
        ManualTestChecklistItem(
            step_id="DRUPAL-02",
            category="Authentication",
            description="Test /update.php for unauthenticated access",
            expected_result="/update.php should require authentication or return access denied",
            tools=["curl"],
            references=["https://www.drupal.org/docs/security-in-drupal"],
        ),
        ManualTestChecklistItem(
            step_id="DRUPAL-03",
            category="Information Disclosure",
            description="Check /node/{nid} and /user/{uid} for content/user enumeration",
            expected_result="Unpublished nodes and user profiles should not be accessible to anonymous users",
            tools=["curl", "Burp Suite"],
            references=["https://www.drupal.org/docs/user_guide/en/user-concept.html"],
        ),
        ManualTestChecklistItem(
            step_id="DRUPAL-04",
            category="Host Header Attack",
            description="Test trusted host validation via Host header injection",
            expected_result="Invalid Host headers should be rejected or redirected",
            tools=["curl", "Burp Suite"],
            references=["https://www.drupal.org/docs/installing-drupal/trusted-host-settings"],
        ),
        ManualTestChecklistItem(
            step_id="DRUPAL-05",
            category="File Security",
            description="Check /sites/default/files for directory listing and PHP execution",
            expected_result="Directory listing should be disabled; PHP files should not execute in files directory",
            tools=["curl", "browser"],
            references=["https://www.drupal.org/docs/security-in-drupal/securing-file-permissions-and-ownership"],
        ),
    ],
    references=[
        {"title": "Drupal Documentation", "url": "https://www.drupal.org/documentation"},
        {"title": "Drupal Security", "url": "https://www.drupal.org/security"},
        {"title": "OWASP Drupal Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Drupal_Cheat_Sheet.html"},
        {"title": "Drupalgeddon Vulnerabilities", "url": "https://www.drupal.org/security/SA-CORE"},
        {"title": "CVE Drupal Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Drupal"},
    ],
    cwe_ids=["CWE-94", "CWE-306", "CWE-200", "CWE-287", "CWE-352", "CWE-89", "CWE-79", "CWE-22"],
    cve_ids=["CVE-2024-37248", "CVE-2023-37190", "CVE-2022-37246", "CVE-2021-32608", "CVE-2020-13671", "CVE-2019-6340", "CVE-2018-7600"],
    tags=["php", "drupal", "cms", "web", "modules"],
)
