"""Express.js knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="express",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="Express.js Node.js — middleware order bugs, prototype pollution, helmet bypass, async error leaks, directory traversal in static file serving.",
    technology=TechnologyProfile(
        name="Express.js",
        vendor="OpenJS Foundation",
        language="JavaScript/Node.js",
        framework="Express.js",
        runtime="Node.js",
        description="Express.js is a minimal and flexible Node.js web application framework providing a robust set of features for web and mobile applications.",
        common_aliases=["express", "expressjs", "express-js"],
        dependencies=["Node.js", "npm/yarn/pnpm"],
        common_integrations=["Passport.js", "Helmet", "Morgan", "Body-parser", "CORS", "Express-session", "Socket.io", "Mongoose", "Sequelize", "EJS/Pug/Handlebars"],
        architecture_description="Middleware-based architecture with routing, request/response handling, and template engine integration.",
        request_lifecycle="HTTP request -> middleware stack (app.use) -> router -> route handler -> response (res.send/res.json/res.render)",
        documentation_url="https://expressjs.com/",
        tags=["nodejs", "javascript", "middleware", "rest"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Middleware Stack",
            description="Ordered middleware execution pipeline. Incorrect ordering can bypass security middlewares like Helmet, CORS, or auth checks.",
            security_relevance="high",
            common_vulnerabilities=["Middleware ordering bypassing auth", "Helmet misplacement exposing headers", "Error middleware skipped", "CORS middleware after route handler"],
            investigation_priority=90,
            tags=["middleware", "auth", "security-headers"],
        ),
        TechnologyComponentProfile(
            name="Body Parsers (body-parser, multer)",
            description="Request body parsing for JSON, URL-encoded, multipart. Prototype pollution via __proto__ in parsed objects.",
            security_relevance="high",
            common_vulnerabilities=["Prototype pollution via JSON body", "Unlimited payload size leading to DoS", "Multipart file upload path traversal", "JSON parse errors leaking information"],
            investigation_priority=90,
            tags=["body-parser", "prototype-pollution", "file-upload"],
        ),
        TechnologyComponentProfile(
            name="Static File Serving (express.static)",
            description="Built-in middleware for serving static files. Directory traversal and file enumeration vulnerabilities.",
            security_relevance="high",
            common_vulnerabilities=["Directory traversal via encoded paths", "File enumeration via static directory", "Source code serving (uncompiled JS)", "Symlink following"],
            investigation_priority=85,
            tags=["static", "directory-traversal", "file-serving"],
        ),
        TechnologyComponentProfile(
            name="Session Management (express-session)",
            description="Session middleware with various stores. Session hijacking, cookie tampering, store vulnerabilities.",
            security_relevance="high",
            common_vulnerabilities=["Session fixation", "Insecure cookie configuration (no HttpOnly/Secure)", "Store-specific injection (e.g., Redis command injection)", "Session ID in URL"],
            investigation_priority=85,
            tags=["sessions", "cookies", "auth"],
        ),
        TechnologyComponentProfile(
            name="Error Handling",
            description="Error-handling middleware for catching exceptions. Uncaught async errors leaking stack traces, unhandled promise rejections.",
            security_relevance="medium",
            common_vulnerabilities=["Async error stack trace leak", "Unhandled promise rejection information disclosure", "Missing error middleware crashing app", "Verbose error messages"],
            investigation_priority=75,
            tags=["errors", "async", "exceptions"],
        ),
        TechnologyComponentProfile(
            name="Routing (Express Router)",
            description="Modular route handling with params, query strings, and body processing. Route parameter injection, regex DoS.",
            security_relevance="high",
            common_vulnerabilities=["Regex DoS in route patterns", "Route parameter injection", "Mass assignment via body + params merging", "HTTP method override bypass"],
            investigation_priority=80,
            tags=["routing", "params", "regex"],
        ),
        TechnologyComponentProfile(
            name="Template Engines (EJS/Pug/Handlebars)",
            description="Server-side template rendering. SSTI in EJS, Pug injection, Handlebars helper injection.",
            security_relevance="high",
            common_vulnerabilities=["SSTI via EJS render options", "Pug template injection", "Handlebars partial injection", "XSS via unescaped output"],
            investigation_priority=85,
            tags=["templates", "ssti", "xss"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="HTTP Routes",
                description="All routes defined with app.get/post/put/delete and Router",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{path}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="Static File Endpoints",
                description="express.static serving public assets",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/{static_path}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.PATH_TRAVERSAL.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="File Upload Endpoints",
                description="Multer-based multipart upload routes",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/upload",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.PATH_TRAVERSAL.value, BugClass.OTHER.value, BugClass.RCE.value],
            ),
        ],
        endpoints=["/api/*", "/api/v1/*", "/login", "/register", "/upload", "/static/*", "/public/*", "/assets/*", "/files/*", "/auth/*", "/graphql"],
        parameters=["id", "page", "limit", "sort", "filter", "q", "token", "file", "path", "callback", "_method"],
        authentication=["Passport.js", "JWT (jsonwebtoken)", "Session cookies (express-session)", "OAuth (Passport strategies)", "API keys"],
        authorization=["Middleware-based role checks", "CASL ability-based auth", "Custom middleware guards", "Route-level authorization"],
        storage=["Local filesystem", "S3 (aws-sdk)", "Cloudinary", "MongoDB GridFS"],
        background_jobs=["Bull Queue (Redis)", "Agenda", "Kue", "Node-resque"],
        queues=["Redis", "RabbitMQ", "AWS SQS"],
        caches=["Redis (ioredis)", "Node-cache", "Memcached"],
        admin_interfaces=["/admin", "/admin/*", "/dashboard", "/admin/login"],
        internal_apis=["/internal/*", "/api/internal/*", "/admin/api/*"],
        external_apis=["Stripe", "SendGrid", "Twilio", "AWS APIs", "Google APIs", "GitHub API"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Node", description="HTTP request enters Express application", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="Mongoose/Sequelize queries to database", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-Redis", description="Session/cache/queue Redis connections", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "Prototype pollution via JSON body parsing",
            "Directory traversal in express.static",
            "Middleware ordering bypassing security",
            "Async error stack trace exposure",
            "SSTI in EJS/Pug/Handlebars templates",
            "Route parameter injection",
            "Session cookie hijacking",
            "File upload path traversal",
            "CORS misconfiguration",
            "HTTP parameter pollution",
            "Regex DoS in route definitions",
            "Unhandled promise rejection information leak",
        ],
        investigation_areas=[
            "Test JSON body parsing for prototype pollution (__proto__, constructor)",
            "Probe static file serving for path traversal (../, encoded variants)",
            "Review middleware ordering: helmet, cors, auth before routes",
            "Trigger async errors to check for stack trace leakage",
            "Test template rendering for SSTI payloads",
            "Check session cookie HttpOnly, Secure, SameSite flags",
            "Test file upload endpoints for path traversal in filename",
            "Check CORS headers for wildcard origin with credentials",
            "Test for HTTP method override vulnerability (_method parameter)",
            "Check for X-Powered-By: Express header disclosure",
            "Test URL parameters for pollution",
            "Check Helmet configuration for missing security headers",
        ],
        tags=["express", "nodejs", "javascript", "framework", "web"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Powered-By": "Express",
            "Set-Cookie": "connect.sid=",
        },
        cookies=["connect.sid", "session"],
        js_indicators=["express", "require('express')", "app.get", "app.post", "app.use", "module.exports"],
        file_indicators=["package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "node_modules/", "server.js", "app.js", "index.js", ".env", "ecosystem.config.js", "Dockerfile"],
        directory_indicators=["/node_modules/", "/routes/", "/controllers/", "/models/", "/middleware/", "/views/", "/public/", "/config/"],
        server_signatures=["Express", "Node.js"],
        error_page_signatures=["Cannot GET", "Cannot POST", "Error: ", "TypeError: ", "ReferenceError: ", "SyntaxError: ", "at ServerResponse.render"],
        default_paths=["/", "/api", "/api/v1", "/login", "/register", "/static/", "/public/", "/assets/", "/favicon.ico", "/robots.txt"],
        default_files=["package.json", "package-lock.json", "server.js", "app.js", ".env", "ecosystem.config.js", "Dockerfile", "docker-compose.yml", ".gitignore"],
        metadata_patterns={"generator": "Express", "powered-by": "Express"},
        tags=["fingerprint", "express", "nodejs"],
    ),
    recon=ReconProfile(
        directories_to_check=["/static/", "/public/", "/assets/", "/uploads/", "/files/", "/node_modules/", "/routes/", "/views/"],
        files_to_check=["package.json", "package-lock.json", ".env", ".env.example", "server.js", "app.js", "ecosystem.config.js", "Dockerfile", "docker-compose.yml", "webpack.config.js"],
        endpoints_to_scan=["/api/*", "/login", "/register", "/upload", "/static/*", "/public/*", "/admin", "/graphql"],
        version_detection_paths=["/package.json", "/api/version"],
        debug_paths_to_check=["/debug", "/_debug", "/__debug__", "/dev", "/error-test"],
        admin_paths_to_check=["/admin", "/admin/*", "/dashboard", "/admin/login"],
        tags=["recon", "express", "nodejs"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Prototype pollution via JSON body allows attackers to pollute Object.prototype globally",
            impact="Authentication bypass, privilege escalation, denial of service",
            attack_scenario="Send JSON with __proto__ or constructor.prototype to inject properties like isAdmin into all objects",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="express.static middleware misconfiguration allows directory traversal",
            impact="Arbitrary file read on the server (source code, configuration, credentials)",
            attack_scenario="Request /static/../../../etc/passwd or URL-encoded traversal sequences",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Unhandled async promise rejections and async errors leak stack traces",
            impact="Information disclosure of internal paths, database queries, and application logic",
            attack_scenario="Trigger an invalid database query or malformed input without async error middleware",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Template injection (SSTI) in EJS with user-controlled render options",
            impact="Remote code execution via crafted template payloads",
            attack_scenario="Inject EJS delimiters or Pug interpolation in user input passed to res.render() options",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="HTTP method override via _method parameter bypasses security controls",
            impact="Bypass of method-based authentication or authorization checks",
            attack_scenario="Submit a GET request with _method=DELETE to bypass method-specific middleware",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="nodejs",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="Express.js runs on Node.js",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="mongoose",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Express.js commonly uses Mongoose for MongoDB",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="passport",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="Express.js authentication via Passport.js",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="Express.js caches sessions with Redis via ioredis",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="socketio",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Express.js pairs with Socket.io for WebSockets",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="postgresql",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="Express.js uses PostgreSQL via Sequelize or pg",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="nginx",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Express.js behind Nginx reverse proxy",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Express.js apps containerized with Docker",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="graphql",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Express.js with Apollo GraphQL or express-graphql",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="helmet",
            relationship_type=KnowledgeRelationshipType.DEPENDS_ON,
            description="Express.js uses Helmet for security headers",
            confidence="medium",
        ),
    ],
    dependencies=["Node.js", "npm/yarn/pnpm"],
    related_packs=["nodejs", "mongoose", "passport", "redis", "socketio", "postgresql", "nginx", "docker", "graphql", "helmet"],
    workflow=[
        "1. Fingerprint Express via X-Powered-By header and connect.sid cookie",
        "2. Check for directory traversal in static file serving endpoints",
        "3. Test JSON API endpoints for prototype pollution (__proto__, constructor)",
        "4. Review middleware ordering by analyzing app.js source patterns",
        "5. Trigger errors to check async error handling and stack trace leaks",
        "6. Test template rendering endpoints for SSTI (EJS/Pug/Handlebars)",
        "7. Check session cookie configuration (HttpOnly, Secure, SameSite)",
        "8. Test file upload endpoints for path traversal and unrestricted upload",
        "9. Check CORS headers for wildcard with credentials misconfiguration",
        "10. Test HTTP method override via _method or X-HTTP-Method-Override",
        "11. Check Helmet configuration for missing security headers",
        "12. Test route parameters for injection and regex DoS",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="EXPRESS-01",
            category="Prototype Pollution",
            description="Test JSON endpoints for prototype pollution",
            expected_result="The server should reject or sanitize __proto__, constructor.prototype, and similar keys",
            tools=["Burp Suite", "custom scripts"],
            references=["https://cheatsheetseries.owasp.org/cheatsheets/Prototype_Pollution_Prevention_Cheat_Sheet.html"],
        ),
        ManualTestChecklistItem(
            step_id="EXPRESS-02",
            category="Path Traversal",
            description="Test static file serving for directory traversal",
            expected_result="Requests with ../ should be blocked or normalized",
            tools=["curl", "Burp Suite"],
            references=["https://expressjs.com/en/starter/static-files.html"],
        ),
        ManualTestChecklistItem(
            step_id="EXPRESS-03",
            category="Error Handling",
            description="Trigger errors to check for stack trace leakage",
            expected_result="Production error responses should not include stack traces or internal paths",
            tools=["curl", "Burp Suite"],
            references=["https://expressjs.com/en/guide/error-handling.html"],
        ),
        ManualTestChecklistItem(
            step_id="EXPRESS-04",
            category="Security Headers",
            description="Check Helmet configuration and response security headers",
            expected_result="Security headers (X-Frame-Options, CSP, HSTS) should be properly configured",
            tools=["curl", "securityheaders.com"],
            references=["https://helmetjs.github.io/"],
        ),
        ManualTestChecklistItem(
            step_id="EXPRESS-05",
            category="Session Security",
            description="Test express-session cookie security attributes",
            expected_result="Session cookies should have HttpOnly, Secure, and SameSite flags",
            tools=["Burp Suite", "curl"],
            references=["https://expressjs.com/en/resources/middleware/session.html"],
        ),
    ],
    references=[
        {"title": "Express.js Documentation", "url": "https://expressjs.com/"},
        {"title": "Express.js Security Best Practices", "url": "https://expressjs.com/en/advanced/best-practice-security.html"},
        {"title": "Node.js Security Checklist", "url": "https://nodejs.org/en/blog/security/security-best-practices/"},
        {"title": "OWASP Node.js Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Nodejs_Cheat_Sheet.html"},
        {"title": "CVE Express Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Express.js"},
    ],
    cwe_ids=["CWE-1321", "CWE-22", "CWE-200", "CWE-94", "CWE-79", "CWE-352", "CWE-400", "CWE-284"],
    cve_ids=["CVE-2024-29041", "CVE-2023-34228", "CVE-2022-25881", "CVE-2022-24994", "CVE-2021-23368", "CVE-2020-28654", "CVE-2019-10792"],
    tags=["nodejs", "express", "web", "framework", "javascript"],
)
