"""FastAPI knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="fastapi",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="FastAPI Python — OpenAPI/Swagger docs exposure, Pydantic validation bypass, async race conditions, CORS misconfiguration.",
    technology=TechnologyProfile(
        name="FastAPI",
        vendor="Sebastián Ramírez (tiangolo)",
        language="Python",
        framework="FastAPI",
        runtime="Python 3.8+ (ASGI with Uvicorn)",
        description="FastAPI is a modern, fast web framework for building APIs with Python 3.8+ based on standard Python type hints and ASGI.",
        common_aliases=["fastapi", "fast-api"],
        dependencies=["Python", "Uvicorn", "Starlette", "Pydantic"],
        common_integrations=["SQLAlchemy", "SQLModel", "Tortoise ORM", "Redis", "Celery", "PostgreSQL", "MySQL", "MongoDB", "Docker", "Kubernetes"],
        architecture_description="ASGI-based framework with dependency injection, automatic OpenAPI generation, and Pydantic-based request/response validation.",
        request_lifecycle="HTTP request -> ASGI server (Uvicorn) -> Starlette middleware -> path operation -> dependencies -> request validation (Pydantic) -> endpoint function -> response validation (Pydantic) -> HTTP response",
        documentation_url="https://fastapi.tiangolo.com/",
        tags=["python", "asgi", "openapi", "pydantic", "rest"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Pydantic Models",
            description="Data validation using Python type hints. Validation bypass via incorrect types, arbitrary code execution via validators, sensitive data exposure in error messages.",
            security_relevance="high",
            common_vulnerabilities=["Validation bypass via type coercion", "Arbitrary code execution in @validator methods", "Sensitive field leak in error messages", "Mass assignment via model fields"],
            investigation_priority=90,
            tags=["pydantic", "validation", "models"],
        ),
        TechnologyComponentProfile(
            name="OpenAPI/Swagger Docs",
            description="Automatic API documentation at /docs and /redoc. Endpoint exposure, schema leakage, parameter discovery.",
            security_relevance="high",
            common_vulnerabilities=["OpenAPI spec in production", "API endpoint enumeration via /docs", "Schema information leakage", "Try-it-out feature enabling unauthorized requests"],
            investigation_priority=90,
            tags=["openapi", "swagger", "documentation"],
        ),
        TechnologyComponentProfile(
            name="Dependency Injection",
            description="FastAPI's dependency injection system. Insecure dependency access, session leaking across requests, authentication logic flaws.",
            security_relevance="high",
            common_vulnerabilities=["Database session leaking", "Authentication bypass via dependency manipulation", "Shared state across requests", "Resource exhaustion via dependencies"],
            investigation_priority=85,
            tags=["dependencies", "di", "injection"],
        ),
        TechnologyComponentProfile(
            name="Async Endpoints",
            description="ASGI-based async request handling. Race conditions, improper locking, async context manager leaks.",
            security_relevance="high",
            common_vulnerabilities=["Race condition in async endpoints", "Async context manager resource leaks", "Coroutine swallowing exceptions", "Deadlock via improper await usage"],
            investigation_priority=85,
            tags=["async", "asgi", "race-condition"],
        ),
        TechnologyComponentProfile(
            name="CORS Middleware",
            description="Cross-Origin Resource Sharing via Starlette CORSMiddleware. Overly permissive configurations allow cross-origin attacks.",
            security_relevance="medium",
            common_vulnerabilities=["Allow-Origin: * with credentials", "Overly permissive allowed origins", "CORS misconfiguration enabling CSRF", "Preflight cache bypass"],
            investigation_priority=80,
            tags=["cors", "middleware", "cross-origin"],
        ),
        TechnologyComponentProfile(
            name="Authentication (OAuth2, JWT)",
            description="Built-in OAuth2 support with JWT bearer tokens. Token handling, scope validation, password flow security.",
            security_relevance="high",
            common_vulnerabilities=["JWT algorithm confusion", "Token theft via URL logging", "Weak token secret", "OAuth2 scope escalation", "Password flow brute-force"],
            investigation_priority=85,
            tags=["auth", "oauth2", "jwt", "tokens"],
        ),
        TechnologyComponentProfile(
            name="Background Tasks / Celery",
            description="Background task processing. Task forgery, insecure task parameters, async task race conditions.",
            security_relevance="medium",
            common_vulnerabilities=["BackgroundTasks forgery via request", "Task parameter injection", "Unprivileged task execution", "Result backend exposure"],
            investigation_priority=70,
            tags=["background-tasks", "celery", "async"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Path Operations",
                description="All @app.get/post/put/delete and APIRouter endpoints",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{path}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="OpenAPI Documentation",
                description="Interactive API docs at /docs and /redoc",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/docs",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="OpenAPI JSON Spec",
                description="Raw OpenAPI schema at /openapi.json",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/openapi.json",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/docs", "/redoc", "/openapi.json", "/api/*", "/api/v1/*", "/auth/*", "/login", "/register", "/token", "/health", "/metrics"],
        parameters=["q", "skip", "limit", "id", "token", "page", "size", "sort", "filter", "search"],
        authentication=["OAuth2 with JWT (Bearer)", "OAuth2 Password flow", "API keys in headers", "HTTP Basic", "Session cookies"],
        authorization=["Dependency-based role checks", "OAuth2 scopes", "Custom middleware authorization", "Route-level Depends() guards"],
        storage=["Local disk", "S3", "Google Cloud Storage", "Azure Blob"],
        background_jobs=["BackgroundTasks", "Celery", "RQ", "ARQ"],
        queues=["Redis", "RabbitMQ", "Amazon SQS"],
        caches=["Redis (aioredis)", "Memcached"],
        admin_interfaces=["/admin", "/admin/*", "/dashboard", "/admin/login"],
        internal_apis=["/internal/*", "/api/internal/*", "/admin/api/*"],
        external_apis=["Stripe", "SendGrid", "Twilio", "AWS APIs", "Google APIs", "OpenAI API"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-ASGI", description="HTTP request enters Uvicorn ASGI server", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="SQLAlchemy async queries to database", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-Redis", description="Redis connections for cache and queues", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "OpenAPI/Swagger docs exposure in production",
            "Pydantic validation bypass via type coercion",
            "Async race conditions in concurrent endpoints",
            "CORS misconfiguration allowing cross-origin attacks",
            "OAuth2 JWT token algorithm confusion",
            "Dependency injection session leaking",
            "Background task parameter forgery",
            "Sensitive field exposure in validation errors",
            "Mass assignment via Pydantic model fields",
            "Rate limiting bypass via async concurrency",
            "WebSocket endpoint message injection",
            "Middleware-based security control bypass",
        ],
        investigation_areas=[
            "Check /docs and /redoc accessibility in production",
            "Test Pydantic models for validation bypass with invalid types",
            "Check for race conditions in async endpoint state management",
            "Verify CORS middleware configuration",
            "Test JWT token handling (algorithm none, weak secret)",
            "Check dependency injection for session/resource leaking",
            "Test background tasks for injection vulnerabilities",
            "Verify validation error messages don't expose schema details",
            "Check for mass assignment in Pydantic model parsing",
            "Test rate limiting under concurrent requests",
            "Check WebSocket endpoint authentication",
            "Test file upload endpoints for path traversal",
        ],
        tags=["fastapi", "python", "asgi", "framework", "web"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "server": "uvicorn",
            "content-type": "application/json",
        },
        cookies=[],
        js_indicators=["fastapi", "FastAPI", "openapi"],
        file_indicators=["main.py", "app.py", "requirements.txt", "pyproject.toml", "Dockerfile", "docker-compose.yml", ".env", "alembic.ini", "alembic/"],
        directory_indicators=["/app/", "/api/", "/routers/", "/models/", "/schemas/", "/services/", "/migrations/", "/alembic/"],
        server_signatures=["uvicorn", "FastAPI"],
        error_page_signatures=["422 Validation Error", "detail", "loc", "msg", "type", "assertion error", "pydantic"],
        default_paths=["/docs", "/redoc", "/openapi.json", "/api", "/health", "/metrics", "/"],
        default_files=["main.py", "app.py", "requirements.txt", "pyproject.toml", "Dockerfile", ".env", "alembic.ini"],
        metadata_patterns={"openapi": "pattern: [0-9]+\\.[0-9]+\\.[0-9]+", "fastapi-version": "pattern: [0-9]+\\.[0-9]+\\.[0-9]+"},
        tags=["fingerprint", "fastapi", "python"],
    ),
    recon=ReconProfile(
        directories_to_check=["/docs/", "/redoc/", "/openapi.json", "/api/", "/routers/", "/models/", "/schemas/"],
        files_to_check=["requirements.txt", "pyproject.toml", ".env", "main.py", "app.py", "Dockerfile", "docker-compose.yml", "alembic.ini"],
        endpoints_to_scan=["/docs", "/redoc", "/openapi.json", "/api/*", "/health", "/metrics", "/auth/*", "/login", "/token"],
        version_detection_paths=["/openapi.json", "/docs"],
        debug_paths_to_check=["/docs", "/redoc", "/openapi.json", "/debug", "/__debug__"],
        admin_paths_to_check=["/admin", "/admin/*", "/dashboard"],
        tags=["recon", "fastapi", "python"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="OpenAPI/Swagger documentation accessible in production exposes entire API surface",
            impact="Full API endpoint enumeration, parameter discovery, and schema information leakage",
            attack_scenario="Access /docs or /openapi.json to map all API endpoints, parameters, and data models",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Pydantic validation bypass via type coercion allows unexpected data through",
            impact="Business logic bypass, mass assignment, data corruption",
            attack_scenario="Pass integer values for boolean fields or overly large numbers to bypass validation constraints",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Race condition in async endpoints allows concurrent state manipulation",
            impact="Data corruption, privilege escalation, double-spend scenarios",
            attack_scenario="Send multiple concurrent requests to the same endpoint that modifies shared state without locks",
            complexity="medium",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="Pydantic validator execution with arbitrary code allows injection",
            impact="Remote code execution via crafted input processed by @validator decorated methods",
            attack_scenario="Inject code execution payloads into string fields processed by custom validators",
            complexity="high",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="CORS middleware with allow_origins=['*'] and allow_credentials=True enables cross-origin data theft",
            impact="Cross-origin data exfiltration, CSRF-like attacks on authenticated endpoints",
            attack_scenario="Malicious site makes credentialed requests to the API and reads responses via CORS permissions",
            complexity="low",
            requires_authentication=True,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="python",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="FastAPI runs on Python",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="starlette",
            relationship_type=KnowledgeRelationshipType.DEPENDS_ON,
            description="FastAPI is built on Starlette ASGI framework",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="pydantic",
            relationship_type=KnowledgeRelationshipType.DEPENDS_ON,
            description="FastAPI uses Pydantic for data validation",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="postgresql",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="FastAPI uses PostgreSQL via SQLAlchemy/SQLModel",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="django",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="FastAPI competes with Django REST Framework",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="flask",
            relationship_type=KnowledgeRelationshipType.SIMILAR_TO,
            description="FastAPI is conceptually similar to Flask but async-native",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="FastAPI caches with Redis via aioredis",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="celery",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="FastAPI integrates with Celery for background tasks",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="FastAPI apps containerized with Docker",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="graphql",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="FastAPI can serve GraphQL via Strawberry or Graphene",
            confidence="low",
        ),
    ],
    dependencies=["Python", "Uvicorn", "Starlette", "Pydantic"],
    related_packs=["python", "starlette", "pydantic", "postgresql", "redis", "celery", "django", "flask", "docker", "graphql"],
    workflow=[
        "1. Fingerprint FastAPI via /docs, /redoc, or /openapi.json endpoints",
        "2. Access /docs and /openapi.json to map all API endpoints and schemas",
        "3. Test Pydantic validation by sending type-coerced values to endpoints",
        "4. Check for race conditions by sending concurrent requests to async endpoints",
        "5. Verify CORS headers are not allowing * with credentials",
        "6. Test JWT token endpoints for algorithm confusion (none, RS256->HS256)",
        "7. Review dependency injection for authentication logic bypass",
        "8. Test validation error messages for sensitive field leakage",
        "9. Check file upload endpoints for path traversal and unrestricted upload",
        "10. Test for mass assignment in Pydantic models through extra fields",
        "11. Verify rate limiting under concurrent connections",
        "12. Check WebSocket endpoints for unauthenticated access",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="FASTAPI-01",
            category="Information Disclosure",
            description="Check /docs, /redoc, and /openapi.json accessibility in production",
            expected_result="API documentation should be disabled or require authentication in production",
            tools=["curl", "browser"],
            references=["https://fastapi.tiangolo.com/how-to/custom-docs-ui-assets/"],
        ),
        ManualTestChecklistItem(
            step_id="FASTAPI-02",
            category="Input Validation",
            description="Test Pydantic validation bypass via type coercion and edge cases",
            expected_result="Invalid input types should be rejected with 422, not silently coerced",
            tools=["curl", "custom scripts"],
            references=["https://docs.pydantic.dev/latest/"],
        ),
        ManualTestChecklistItem(
            step_id="FASTAPI-03",
            category="Race Conditions",
            description="Test for race conditions by sending concurrent requests to the same endpoint",
            expected_result="Shared state modifications should use proper locking mechanisms",
            tools=["custom scripts", "parallel request tools"],
            references=["https://fastapi.tiangolo.com/advanced/async-tests/"],
        ),
        ManualTestChecklistItem(
            step_id="FASTAPI-04",
            category="CORS Configuration",
            description="Check CORS headers on API responses for overly permissive settings",
            expected_result="Access-Control-Allow-Origin should not be * with allowedCredentials true",
            tools=["curl", "Burp Suite"],
            references=["https://fastapi.tiangolo.com/tutorial/cors/"],
        ),
        ManualTestChecklistItem(
            step_id="FASTAPI-05",
            category="Authentication",
            description="Test JWT token handling for algorithm confusion attacks",
            expected_result="JWT tokens with algorithm 'none' should be rejected",
            tools=["jwt_tool", "custom scripts"],
            references=["https://fastapi.tiangolo.com/tutorial/security/"],
        ),
    ],
    references=[
        {"title": "FastAPI Documentation", "url": "https://fastapi.tiangolo.com/"},
        {"title": "FastAPI Security", "url": "https://fastapi.tiangolo.com/tutorial/security/"},
        {"title": "OWASP REST Security Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html"},
        {"title": "Pydantic Documentation", "url": "https://docs.pydantic.dev/"},
        {"title": "CVE FastAPI Collection", "url": "https://www.cve.org/KeywordSearch?keyword=FastAPI"},
    ],
    cwe_ids=["CWE-200", "CWE-94", "CWE-362", "CWE-942", "CWE-287", "CWE-915", "CWE-22", "CWE-400"],
    cve_ids=["CVE-2024-33899", "CVE-2024-27312", "CVE-2023-45987", "CVE-2022-32545", "CVE-2021-32821"],
    tags=["python", "fastapi", "web", "asgi", "framework", "api"],
)
