"""Flask knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="flask",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="Flask Python — debug mode Werkzeug console, session cookie tampering, SSTI in Jinja2, static file traversal.",
    technology=TechnologyProfile(
        name="Flask",
        vendor="Pallets Project",
        language="Python",
        framework="Flask",
        runtime="Python 3.x (WSGI with Werkzeug)",
        description="Flask is a lightweight WSGI web application framework. It is designed to make getting started quick and easy, with the ability to scale up to complex applications.",
        common_aliases=["flask", "flask-app"],
        dependencies=["Python", "Werkzeug", "Jinja2", "itsdangerous", "click"],
        common_integrations=["SQLAlchemy", "Flask-SQLAlchemy", "Flask-Login", "Flask-Admin", "Flask-RESTful", "Flask-Security", "Flask-WTF", "Redis", "Celery", "MongoEngine"],
        architecture_description="WSGI-based microframework with pluggable extensions, Jinja2 templating, and Werkzeug utility library.",
        request_lifecycle="WSGI server -> Werkzeug routing -> request context -> view function -> response -> template rendering (Jinja2) -> WSGI response",
        documentation_url="https://flask.palletsprojects.com/",
        tags=["python", "wsgi", "microframework", "jinja2"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Werkzeug Debugger",
            description="Interactive debugger when debug=True. Allows arbitrary code execution via the console, stack trace exposure.",
            security_relevance="critical",
            common_vulnerabilities=["Werkzeug debugger RCE via interactive console", "Stack trace leakage", "Source code exposure via debugger frames", "PIN bypass for debugger console"],
            investigation_priority=99,
            tags=["debug", "werkzeug", "rce", "console"],
        ),
        TechnologyComponentProfile(
            name="Jinja2 Templates",
            description="Server-side template engine. SSTI via unescaped user input in templates, XSS via autoescape bypass.",
            security_relevance="high",
            common_vulnerabilities=["SSTI (Server-Side Template Injection)", "XSS via safe filter or autoescape off", "Template caching poisoning", "Template path traversal with {% include %}"],
            investigation_priority=95,
            tags=["templates", "ssti", "jinja2", "xss"],
        ),
        TechnologyComponentProfile(
            name="Session Cookies (itsdangerous)",
            description="Signed session cookies stored client-side. Cookie tampering via known secret key, session data manipulation.",
            security_relevance="high",
            common_vulnerabilities=["Session cookie tampering", "Weak/known SECRET_KEY brute-force", "Session data deserialization (pickle)", "Session fixation"],
            investigation_priority=90,
            tags=["sessions", "cookies", "itsdangerous"],
        ),
        TechnologyComponentProfile(
            name="Flask-Login / Authentication",
            description="User session management extension. Session persistence, remember-me token exposure, user loader bypass.",
            security_relevance="high",
            common_vulnerabilities=["Remember-me token leakage", "Session permanence without logout", "User loader callback injection", "Weak session protection"],
            investigation_priority=85,
            tags=["auth", "login", "sessions"],
        ),
        TechnologyComponentProfile(
            name="Flask-Admin",
            description="Admin interface for model management. Unauthenticated exposure, mass assignment, privilege escalation.",
            security_relevance="high",
            common_vulnerabilities=["Admin panel without authentication", "Mass assignment via model views", "CSRF missing on admin actions", "File upload unrestricted"],
            investigation_priority=85,
            tags=["admin", "crud", "models"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Route Endpoints",
                description="All routes defined with @app.route decorators",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{route}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="Werkzeug Debugger Console",
                description="Interactive Python console at /console when debug=True",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/console",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.RCE.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Static File Serving",
                description="Flask static files served via /static/ route",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/static/{file_path}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.PATH_TRAVERSAL.value],
            ),
        ],
        endpoints=["/", "/login", "/admin", "/admin/*", "/admin/login", "/static/*", "/console", "/api/*", "/api/v1/*"],
        parameters=["id", "page", "q", "next", "token", "file", "name", "action"],
        authentication=["Session cookies (session)", "Flask-Login", "Flask-HTTPAuth", "Flask-JWT-Extended", "OAuth via Flask-Dance"],
        authorization=["Flask-Principal", "Flask-Security roles", "Decorator-based (@login_required)", "Custom middleware checks"],
        storage=["Local disk", "S3", "Cloud storage"],
        background_jobs=["Celery", "RQ", "Flask-Executor"],
        queues=["Redis", "RabbitMQ", "Amazon SQS"],
        caches=["Redis (Flask-Caching)", "Memcached", "File system cache"],
        admin_interfaces=["/admin", "/admin/*", "/admin/login"],
        internal_apis=["/internal/*", "/api/internal/*"],
        external_apis=["Stripe", "SendGrid", "Twilio", "AWS APIs"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-WSGI", description="Request enters WSGI server", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="SQLAlchemy queries to database", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-Cache", description="Cache operations to Redis/Memcached", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "Werkzeug debugger RCE console",
            "Jinja2 SSTI vulnerability",
            "Session cookie tampering via known secret",
            "Static file directory traversal",
            "Admin panel without authentication",
            "CSRF token missing on forms",
            "CORS misconfiguration",
            "File upload unrestricted",
            "SQL injection via SQLAlchemy raw queries",
            "Debug mode stack trace leaks",
            "Clickjacking via missing X-Frame-Options",
        ],
        investigation_areas=[
            "Check if app runs with debug=True (Werkzeug console at /console)",
            "Test Jinja2 template rendering for SSTI payloads",
            "Decode session cookie to check for tampering potential",
            "Probe static file serving for directory traversal",
            "Check admin panel authentication requirements",
            "Verify CSRF protection on all forms",
            "Check CORS headers on API responses",
            "Test file upload endpoints for unrestricted file types",
            "Check SQLAlchemy queries for raw SQL injection",
            "Verify SECRET_KEY strength and rotation",
            "Check for missing security headers (HSTS, X-Frame-Options)",
        ],
        tags=["flask", "python", "framework", "web", "wsgi"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Set-Cookie": "session=",
            "X-Powered-By": "Werkzeug",
        },
        cookies=["session"],
        js_indicators=["flask", "csrf_token", "{{ csrf_token() }}"],
        file_indicators=["app.py", "application.py", "requirements.txt", "Pipfile", "Pipfile.lock", "config.py", "config.cfg", "Dockerfile", "docker-compose.yml", ".env"],
        directory_indicators=["/static/", "/templates/", "/views/", "/blueprints/", "/models/", "/controllers/"],
        server_signatures=["Werkzeug", "gunicorn", "Flask"],
        error_page_signatures=["Not Found", "Method Not Allowed", "Internal Server Error", "The requested URL was not found on the server", "Werkzeug"],
        default_paths=["/", "/login", "/admin", "/admin/login", "/static/", "/api", "/console"],
        default_files=["app.py", "requirements.txt", "config.py", ".env", "Dockerfile", "docker-compose.yml"],
        metadata_patterns={"generator": "Flask"},
        tags=["fingerprint", "flask", "python"],
    ),
    recon=ReconProfile(
        directories_to_check=["/static/", "/static/css/", "/static/js/", "/static/img/", "/templates/", "/uploads/", "/admin/"],
        files_to_check=["app.py", "requirements.txt", "config.py", ".env", ".env.example", "Pipfile", "Dockerfile", "docker-compose.yml"],
        endpoints_to_scan=["/", "/login", "/admin", "/admin/login", "/api", "/console", "/static/"],
        version_detection_paths=["/static/", "/api"],
        debug_paths_to_check=["/console", "/debug", "/__debug__", "/_debug_toolbar"],
        admin_paths_to_check=["/admin", "/admin/login", "/admin/dashboard"],
        tags=["recon", "flask", "python"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Werkzeug debugger console enabled in production allows arbitrary Python code execution",
            impact="Remote code execution, full server compromise",
            attack_scenario="Navigate to /console and use the interactive Python debugger to execute system commands",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="SSTI in Jinja2 templates allows template injection via user input",
            impact="Remote code execution via Jinja2 sandbox escape",
            attack_scenario="Inject {{ config.__class__.__init__.__globals__['os'].popen('id').read() }} into user-controllable template variables",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Flask session cookies are signed but not encrypted, allowing data visibility and tampering with known secret",
            impact="Session data manipulation, privilege escalation, account takeover",
            attack_scenario="Decode session cookie with flask-unsign, modify contents, re-sign with weak/known SECRET_KEY",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Static file directory traversal allows reading arbitrary files on the server",
            impact="Source code disclosure, configuration file reading, credential extraction",
            attack_scenario="Request /static/../../../etc/passwd or URL-encoded traversal sequences",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Flask-Admin panel exposed without authentication allows CRUD access to all registered models",
            impact="Database manipulation, privilege escalation, data exfiltration",
            attack_scenario="Access /admin directly to create/view/modify/delete database records",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="python",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="Flask runs on Python",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="werkzeug",
            relationship_type=KnowledgeRelationshipType.DEPENDS_ON,
            description="Flask depends on Werkzeug WSGI toolkit",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="jinja2",
            relationship_type=KnowledgeRelationshipType.DEPENDS_ON,
            description="Flask uses Jinja2 template engine",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="postgresql",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="Flask uses PostgreSQL via SQLAlchemy",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="django",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="Flask competes with Django as Python web framework",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="Flask caches with Redis via Flask-Caching",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="celery",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Flask integrates with Celery for background tasks",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="nginx",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Flask commonly runs behind Nginx proxy",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Flask apps containerized with Docker",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="fastapi",
            relationship_type=KnowledgeRelationshipType.SIMILAR_TO,
            description="Flask and FastAPI are both Python web frameworks",
            confidence="medium",
        ),
    ],
    dependencies=["Python", "Werkzeug", "Jinja2", "itsdangerous"],
    related_packs=["python", "werkzeug", "jinja2", "postgresql", "redis", "celery", "django", "fastapi", "nginx", "docker"],
    workflow=[
        "1. Fingerprint Flask via session cookie and Werkzeug error pages",
        "2. Check /console for Werkzeug debugger console access",
        "3. Test for SSTI in all template-rendering endpoints with Jinja2 payloads",
        "4. Decode and attempt to tamper with session cookie using flask-unsign",
        "5. Probe static file serving for directory traversal",
        "6. Check /admin endpoints for authentication requirements",
        "7. Test all forms for CSRF token validation",
        "8. Check CORS headers on API responses",
        "9. Test file upload endpoints for unrestricted file types",
        "10. Check for SQL injection in SQLAlchemy raw queries",
        "11. Verify SECRET_KEY strength via session decoding attempts",
        "12. Check for Flask-Security/Flask-Login configuration flaws",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="FLASK-01",
            category="Debug Mode",
            description="Check if Werkzeug debugger is enabled (/console endpoint)",
            expected_result="/console should not be accessible or should require authentication",
            tools=["curl", "browser"],
            references=["https://flask.palletsprojects.com/en/stable/debugging/"],
        ),
        ManualTestChecklistItem(
            step_id="FLASK-02",
            category="Template Injection",
            description="Test Jina2 template rendering for SSTI vulnerability",
            expected_result="User input should not be evaluated as template expressions",
            tools=["Burp Suite", "custom scripts"],
            references=["https://jinja.palletsprojects.com/en/stable/"],
        ),
        ManualTestChecklistItem(
            step_id="FLASK-03",
            category="Session Security",
            description="Decode session cookie and test for SECRET_KEY brute-force",
            expected_result="Session data should not be tamperable; SECRET_KEY should be strong and unpredictable",
            tools=["flask-unsign", "custom scripts"],
            references=["https://flask.palletsprojects.com/en/stable/quickstart/#sessions"],
        ),
        ManualTestChecklistItem(
            step_id="FLASK-04",
            category="Path Traversal",
            description="Test static file serving for directory traversal",
            expected_result="Path traversal sequences should be blocked or normalized",
            tools=["curl", "Burp Suite"],
            references=["https://flask.palletsprojects.com/en/stable/quickstart/#static-files"],
        ),
        ManualTestChecklistItem(
            step_id="FLASK-05",
            category="Admin Panel",
            description="Check Flask-Admin panel for unauthorized access",
            expected_result="Admin panel should require authentication for all operations",
            tools=["curl", "browser"],
            references=["https://flask-admin.readthedocs.io/"],
        ),
    ],
    references=[
        {"title": "Flask Documentation", "url": "https://flask.palletsprojects.com/"},
        {"title": "Flask Security Considerations", "url": "https://flask.palletsprojects.com/en/stable/security/"},
        {"title": "OWASP Flask Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Flask_Cheat_Sheet.html"},
        {"title": "Jinja2 Template Documentation", "url": "https://jinja.palletsprojects.com/"},
        {"title": "CVE Flask Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Flask"},
    ],
    cwe_ids=["CWE-94", "CWE-79", "CWE-22", "CWE-200", "CWE-352", "CWE-306", "CWE-502", "CWE-284"],
    cve_ids=["CVE-2024-49768", "CVE-2023-46136", "CVE-2023-25577", "CVE-2022-42920", "CVE-2020-28724", "CVE-2019-1010083"],
    tags=["python", "flask", "web", "framework", "wsgi", "microframework"],
)
