"""Laravel Knowledge Pack."""

from deephunter.core.types import (
    AttackSurfaceEntry,
    BusinessLogicConcern,
    BugClass,
    ManualTestChecklistItem,
    TrustBoundary,
)
from deephunter.knowledge.packs.base import (
    AttackSurfaceProfile,
    FingerprintProfile,
    KnowledgePack,
    KnowledgePackCategory,
    KnowledgeRelationship,
    KnowledgeRelationshipType,
    ReconProfile,
    TechnologyComponentProfile,
    TechnologyProfile,
)

PACK = KnowledgePack(
    name="laravel",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="Laravel PHP framework — mass assignment, query builder injection, debug mode leaks, and Eloquent ORM vulnerabilities.",
    technology=TechnologyProfile(
        name="Laravel",
        vendor="Laravel LLC",
        language="PHP",
        framework="Laravel",
        runtime="PHP 8.x",
        description="Laravel is a PHP web application framework with expressive syntax. Known for Eloquent ORM, Blade templating, and Artisan CLI.",
        common_aliases=["laravel", "lumen"],
        dependencies=["PHP", "Composer", "MySQL/PostgreSQL", "Redis"],
        common_integrations=["MySQL", "PostgreSQL", "Redis", "Mailhog", "Sanctum", "Passport", "Horizon", "Telescope"],
        architecture_description="MVC pattern with service providers, facades, and dependency injection container.",
        request_lifecycle="public/index.php -> bootstrap/app.php -> Kernel -> Middleware stack -> Route -> Controller -> Response",
        documentation_url="https://laravel.com/docs",
        tags=["php", "mvc", "orm", "blade", "eloquent", "artisan"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Eloquent ORM",
            description="ActiveRecord-style ORM with query builder. SQL injection via raw queries and mass assignment vulnerabilities.",
            security_relevance="high",
            common_vulnerabilities=["Mass assignment", "SQL injection via raw where clauses", "N+1 query attacks", "Eager loading data leaks"],
            investigation_priority=90,
            tags=["orm", "sql", "mass-assignment"],
        ),
        TechnologyComponentProfile(
            name="Blade Templates",
            description="Template engine supporting server-side rendering. XSS via unescaped output, SSTI in edge cases.",
            security_relevance="high",
            common_vulnerabilities=["XSS", "SSTI with custom directives", "Path traversal in @include"],
            investigation_priority=85,
            tags=["templates", "xss", "ssti"],
        ),
        TechnologyComponentProfile(
            name="Authentication (Sanctum/Passport)",
            description="Sanctum for SPA/token-based auth, Passport for OAuth2. Token exposure, CSRF bypass, session fixation.",
            security_relevance="high",
            common_vulnerabilities=["Token disclosure", "CSRF bypass", "Session fixation", "Weak token generation"],
            investigation_priority=85,
            tags=["auth", "sanctum", "passport", "tokens"],
        ),
        TechnologyComponentProfile(
            name="Artisan Console",
            description="CLI tool for migrations, commands, and maintenance. Debug commands exposed in production.",
            security_relevance="medium",
            common_vulnerabilities=[" Debug mode leaks", "Environment variable exposure via tinker"],
            investigation_priority=70,
            tags=["cli", "debug", "artisan"],
        ),
        TechnologyComponentProfile(
            name="Debug Mode (APP_DEBUG)",
            description="When enabled, exposes full error pages with stack traces, env vars, and query logs.",
            security_relevance="high",
            common_vulnerabilities=["Information disclosure", "Stack trace exposure", "DB credential leaks"],
            investigation_priority=95,
            tags=["debug", "information-disclosure"],
        ),
        TechnologyComponentProfile(
            name="File Uploads",
            description="File upload handling via Requests. Path traversal, MIME type spoofing, unrestricted file upload.",
            security_relevance="medium",
            common_vulnerabilities=["Path traversal", "MIME type spoofing", "Unrestricted file upload"],
            investigation_priority=75,
            tags=["file-upload", "path-traversal"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Web Routes",
                description="All routes defined in routes/web.php and routes/api.php",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{route}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="API Routes (Sanctum)",
                description="Token-authenticated API routes via Sanctum",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/api/{route}",
                parameters=[],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.IDOR.value, BugClass.AUTH_BYPASS.value, BugClass.BROKEN_AUTH.value],
            ),
            AttackSurfaceEntry(
                name="Admin Panel",
                description="Admin routes under /admin or custom prefix",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/admin/{route}",
                parameters=[],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.PRIVILEGE_ESCALATION.value, BugClass.IDOR.value, BugClass.BROKEN_AUTH.value],
            ),
        ],
        endpoints=["/login", "/register", "/password/reset", "/admin", "/api/*", "/_debugbar/*", "/telescope/*", "/nova/*"],
        parameters=["_token", "remember_token", "api_token", "page", "id", "user_id", "file", "path"],
        authentication=["Sanctum tokens", "Session cookies", "Passport OAuth", "API tokens"],
        authorization=["Gates", "Policies", "Middleware (auth, can)", "Roles via Spatie/laravel-permission"],
        storage=["Local disk", "S3", "Cloud CDN"],
        background_jobs=["Horizon queues", "Laravel Queues (database, redis, sqs)"],
        queues=["Horizon", "Redis", "Beanstalkd", "SQS"],
        caches=["Redis", "File", "Memcached", "Database"],
        admin_interfaces=["/admin", "/nova", "/backpack", "/voyager"],
        internal_apis=["/api/internal", "/api/v1/*"],
        external_apis=["Stripe", "PayPal", "Twilio", "Socialite providers"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-App", description="Request enters Laravel kernel", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="Eloquent queries to database", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-Cache", description="Cache driver interaction", direction="outbound", sensitivity="low"),
        ],
        attack_surface_areas=[
            "Route parameter injection",
            "Mass assignment via request input",
            "Debug mode information disclosure",
            "Blade template injection",
            "Eloquent query builder injection",
            "File upload path traversal",
            "Session token fixation",
            "CSRF token bypass",
            "API token exposure in URLs",
            "Environment variable leakage",
        ],
        investigation_areas=[
            "Check APP_DEBUG = true in production",
            "Test mass assignment on all Model::create/update calls",
            "Probe Blade templates for unescaped {{ }}",
            "Test file upload endpoints for path traversal",
            "Check Sanctum token transmission security",
            "Verify CSRF token validation on POST routes",
            "Test admin panel for privilege escalation",
            "Check Telescope/Horizon/Nova exposure",
            "Test API routes for IDOR",
            "Check .env file accessibility",
        ],
        tags=["laravel", "php", "framework", "web"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Powered-By": "PHP",
            "Set-Cookie": "laravel_session",
            "Set-Cookie": "XSRF-TOKEN",
        },
        cookies=["laravel_session", "XSRF-TOKEN", "remember_web_*"],
        js_indicators=["Laravel.csrfToken", "window.Laravel", "laravelVersion"],
        file_indicators=["artisan", ".env", ".env.example", "composer.json", "composer.lock", "package.json", "webpack.mix.js", "vite.config.js"],
        directory_indicators=["/storage", "/bootstrap", "/vendor", "/resources", "/routes", "/config", "/database/migrations"],
        server_signatures=["Laravel"],
        error_page_signatures=["Whoops\\! There was an error.", "laravel", "QueryException in", "SQLSTATE["],
        default_paths=["/login", "/register", "/password/reset", "/_debugbar", "/telescope", "/nova", "/sanctum/csrf-cookie"],
        default_files=[".env", ".env.example", "artisan", "composer.json", "composer.lock", "webpack.mix.js", "vite.config.js", "phpunit.xml"],
        metadata_patterns={"generator": "Laravel", "csrf_token": "pattern: [A-Za-z0-9]{40}"},
        tags=["fingerprint", "laravel", "php"],
    ),
    recon=ReconProfile(
        directories_to_check=["/storage", "/storage/logs", "/bootstrap/cache", "/config", "/resources/views", "/database/migrations", "/public/storage", "/vendor"],
        files_to_check=[".env", ".env.example", "artisan", "composer.json", "composer.lock", "package.json", "phpunit.xml", "webpack.mix.js", "vite.config.js"],
        endpoints_to_scan=["/login", "/register", "/password/reset", "/admin", "/api/*", "/_debugbar/*", "/telescope/*", "/nova/*", "/sanctum/csrf-cookie", "/_ignition*"],
        version_detection_paths=["/composer.json", "/artisan", "/_debugbar/assets/javascript"],
        debug_paths_to_check=["/_debugbar/*", "/_ignition*", "/telescope/*", "/nova/*", "/clockwork/*"],
        admin_paths_to_check=["/admin", "/nova", "/backpack", "/voyager", "/admin/login"],
        tags=["recon", "laravel", "php"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Mass assignment allows attackers to set guarded attributes via HTTP parameters",
            impact="Privilege escalation, unauthorized data modification",
            attack_scenario="Add role=admin or is_admin=true to a POST/PUT request",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Debug mode reveals environment variables and database credentials on error",
            impact="Full credential exposure, data breach",
            attack_scenario="Trigger an error (e.g., invalid route, SQL error) with APP_DEBUG=true",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Cached config exposes sensitive data in world-readable files",
            impact="Credential leakage from bootstrap/cache/config.php",
            attack_scenario="Download bootstrap/cache/config.php directly",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="php",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="Laravel runs on PHP",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="mysql",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="Laravel commonly uses MySQL via Eloquent",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="Laravel uses Redis for cache, sessions, queues",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="jwt",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="Laravel API auth via JWT (tymon/jwt-auth)",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="oauth",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="Laravel Passport implements OAuth2",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Laravel Sail uses Docker for development",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="nginx",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Nginx commonly proxies Laravel applications",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="graphql",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Lighthouse PHP GraphQL server for Laravel",
            confidence="medium",
        ),
    ],
    dependencies=["PHP", "Composer", "MySQL/PostgreSQL"],
    related_packs=["php", "mysql", "redis", "jwt", "oauth", "nginx", "docker"],
    workflow=[
        "1. Identify Laravel via cookies (laravel_session, XSRF-TOKEN) or _debugbar",
        "2. Check /_debugbar/*, /telescope/*, /nova/ for debug/admin interfaces",
        "3. Probe .env and .env.example for credential leaks",
        "4. Test all routes for mass assignment on POST/PUT/PATCH",
        "5. Check APP_DEBUG by triggering 404/500 errors",
        "6. Test file upload endpoints with path traversal payloads",
        "7. Check Sanctum token transmission (URL vs Authorization header)",
        "8. Probe admin routes for privilege escalation",
        "9. Test CSRF token validation by omitting/modifying _token",
        "10. Check Blade template rendering for XSS",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="LARAVEL-01",
            category="Information Disclosure",
            description="Check if APP_DEBUG is enabled by triggering an error",
            expected_result="Error page should not reveal stack traces or env vars",
            tools=["curl", "Burp Suite"],
            references=["https://laravel.com/docs/errors"],
        ),
        ManualTestChecklistItem(
            step_id="LARAVEL-02",
            category="Mass Assignment",
            description="Test mass assignment by adding unexpected fields to POST requests",
            expected_result="Unexpected fields should be rejected or ignored",
            tools=["Burp Suite", "custom scripts"],
            references=["https://laravel.com/docs/eloquent#mass-assignment"],
        ),
        ManualTestChecklistItem(
            step_id="LARAVEL-03",
            category="File Upload",
            description="Test file upload endpoints for path traversal",
            expected_result="Uploaded files should be confined to upload directory",
            tools=["curl", "Burp Suite"],
            references=["https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/11-Business_Logic_Testing/01-Test_Business_Logic_Data_Validation"],
        ),
        ManualTestChecklistItem(
            step_id="LARAVEL-04",
            category="Debug Mode",
            description="Check Telescope, Horizon, Debugbar accessibility",
            expected_result="Debug tools should not be accessible in production",
            tools=["curl", "browser"],
            references=["https://laravel.com/docs/telescope"],
        ),
        ManualTestChecklistItem(
            step_id="LARAVEL-05",
            category="Authentication",
            description="Test Sanctum token security (transmission, storage, expiration)",
            expected_result="Tokens should be sent via Authorization header, not URL",
            tools=["Burp Suite", "custom scripts"],
            references=["https://laravel.com/docs/sanctum"],
        ),
    ],
    references=[
        {"title": "Laravel Documentation", "url": "https://laravel.com/docs"},
        {"title": "OWASP Laravel Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Laravel_Cheat_Sheet.html"},
        {"title": "Laravel Security Best Practices", "url": "https://laravel.com/docs/security"},
        {"title": "Laravel Debug Mode", "url": "https://laravel.com/docs/errors#configuration"},
        {"title": "CVE Laravel Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Laravel"},
    ],
    cwe_ids=["CWE-915", "CWE-89", "CWE-79", "CWE-200", "CWE-22"],
    cve_ids=["CVE-2022-31279", "CVE-2021-3129", "CVE-2020-15227", "CVE-2021-43560"],
    tags=["php", "laravel", "web", "framework", "mvc"],
)
