"""Magento knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="magento",
    version="1.0.0",
    category=KnowledgePackCategory.CMS,
    description="Magento CMS — admin panel enumeration, SOAP/REST API, payment gateway manipulation, SQL injection via EAV.",
    technology=TechnologyProfile(
        name="Magento",
        vendor="Adobe (formerly Magento Inc.)",
        language="PHP",
        framework="Magento",
        runtime="PHP 8.x",
        description="Magento (Adobe Commerce) is an open-source e-commerce platform written in PHP. Known for its modular architecture, EAV data model, and extensive marketplace.",
        common_aliases=["magento", "adobe-commerce", "magento2", "m1", "m2"],
        dependencies=["PHP", "MySQL/MariaDB", "Elasticsearch/OpenSearch", "Redis", "RabbitMQ", "Composer"],
        common_integrations=["MySQL", "MariaDB", "Elasticsearch", "OpenSearch", "Redis", "RabbitMQ", "Varnish", "Nginx", "PayPal", "Stripe", "Braintree", "Authorize.net"],
        architecture_description="Modular e-commerce platform with EAV (Entity-Attribute-Value) data model, plugin system (interceptors), service contracts, and UI components.",
        request_lifecycle="HTTP request -> index.php -> Magento bootstrap -> front controller -> router -> controller action -> service contract -> EAV model -> plugin pipeline -> layout -> block rendering -> response",
        documentation_url="https://devdocs.magento.com/",
        tags=["php", "ecommerce", "eav", "adobe", "shop"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Admin Panel",
            description="Admin dashboard at /admin or custom path. Brute-force, default credentials, admin path disclosure via response headers.",
            security_relevance="critical",
            common_vulnerabilities=["Admin panel path enumeration via X-Magento-Vary header", "Default admin credentials", "Admin login brute-force without rate limiting", "Admin CSRF on configuration changes"],
            investigation_priority=99,
            tags=["admin", "login", "brute-force"],
        ),
        TechnologyComponentProfile(
            name="EAV Data Model",
            description="Entity-Attribute-Value database model for products, customers, and categories. SQL injection via EAV attribute queries and custom option manipulation.",
            security_relevance="high",
            common_vulnerabilities=["SQL injection via EAV attribute filtering", "EAV collection method injection", "Custom option SQL injection", "EAV entity load manipulation"],
            investigation_priority=95,
            tags=["eav", "database", "attributes", "sql"],
        ),
        TechnologyComponentProfile(
            name="REST & SOAP API",
            description="Web API interfaces (REST and SOAP). Unauthenticated API access, token leakage, mass assignment via API calls.",
            security_relevance="high",
            common_vulnerabilities=["API endpoint without authentication", "SOAP PHP object injection", "REST API mass assignment via product/customer endpoints", "API token leakage in URLs"],
            investigation_priority=90,
            tags=["api", "rest", "soap", "web-api"],
        ),
        TechnologyComponentProfile(
            name="Payment Processing",
            description="Payment gateway integration (PayPal, Braintree, Stripe, etc.). Payment manipulation, order tampering, gateway parameter injection.",
            security_relevance="critical",
            common_vulnerabilities=["Payment method bypass via parameter manipulation", "Order total manipulation", "Refund/reversal CSRF", "Gateway credentials exposure in config"],
            investigation_priority=99,
            tags=["payment", "checkout", "gateway"],
        ),
        TechnologyComponentProfile(
            name="Customer & Checkout",
            description="Customer accounts, shopping cart, and checkout process. Account takeover via mass assignment, cart manipulation, promotion abuse.",
            security_relevance="high",
            common_vulnerabilities=["Customer account mass assignment", "Shopping cart manipulation via API", "Promotion/discount code abuse", "Guest-to-customer account escalation"],
            investigation_priority=90,
            tags=["customer", "checkout", "cart", "orders"],
        ),
        TechnologyComponentProfile(
            name="Cache & Full Page Caching",
            description="Built-in cache system with Varnish, Redis, and built-in cache. Cache poisoning, cache key manipulation, customer data leakage via cached pages.",
            security_relevance="medium",
            common_vulnerabilities=["Cache poisoning via HTTP headers", "Customer data leakage in cached pages", "Cache key manipulation to view restricted data", "Varnish purge without authentication"],
            investigation_priority=75,
            tags=["cache", "varnish", "redis", "fpc"],
        ),
        TechnologyComponentProfile(
            name="Configuration & Environment",
            description="Magento configuration via app/etc/env.php and core_config_data. Sensible data exposure, encryption key leakage, database credential exposure.",
            security_relevance="high",
            common_vulnerabilities=["app/etc/env.php file exposure", "core_config_data decryption key access", "Encryption key leakage via var/export", "Database credential exposure in configuration"],
            investigation_priority=90,
            tags=["config", "env", "encryption"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Store Frontend",
                description="Public-facing catalog, product, cart, and checkout pages",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{url_key}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.SQL_INJECTION.value, BugClass.XSS.value, BugClass.LFI.value],
            ),
            AttackSurfaceEntry(
                name="Admin Panel",
                description="Magento admin dashboard",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{admin_route}",
                parameters=[],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.PRIVILEGE_ESCALATION.value, BugClass.CSRF.value, BugClass.OTHER.value],
            ),
            AttackSurfaceEntry(
                name="REST API",
                description="REST web API endpoints under /rest/",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/rest/{version}/{resource}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.IDOR.value, BugClass.BUSINESS_LOGIC.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="SOAP API",
                description="SOAP web API endpoint",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/soap/{version}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.DESERIALIZATION.value, BugClass.AUTH_BYPASS.value],
            ),
        ],
        endpoints=["/", "/admin", "/admin/dashboard", "/customer/account/login", "/customer/account/create", "/checkout/cart", "/checkout/onepage", "/rest/", "/rest/V1/", "/rest/V1/products", "/rest/V1/customers", "/rest/V1/orders", "/soap/default", "/graphql", "/static/version/", "/app/etc/env.php", "/var/log/system.log"],
        parameters=["id", "product_id", "customer_id", "order_id", "sku", "page", "limit", "q", "token", "form_key"],
        authentication=["Admin session cookies (admin)", "Integration tokens (Bearer)", "Customer session cookies", "OAuth 1.0a for third-party integrations"],
        authorization=["Admin roles and permissions", "ACL resources", "Integration permissions", "Customer group-based access"],
        storage=["Local filesystem (pub/media)", "S3", "CDN"],
        background_jobs=["Magento Cron (cron.php)", "RabbitMQ message queues"],
        queues=["RabbitMQ", "MySQL (message queue)"],
        caches=["Redis (config, layout, block, full page)", "Varnish (full page cache)", "Built-in var/cache"],
        admin_interfaces=["/admin", "/admin/*", "/admin/dashboard", "/admin/catalog/product", "/admin/customer", "/admin/sales/order"],
        internal_apis=["/rest/V1/*", "/rest/default/V1/*", "/soap/default"],
        external_apis=["PayPal", "Braintree", "Stripe", "Authorize.net", "FedEx", "UPS", "USPS", "DHL"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Magento", description="Request enters Magento front controller", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="Magento queries to MySQL via EAV", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-Payment", description="Payment gateway API calls", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-Cache", description="Cache operations to Redis/Varnish", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "Admin panel path enumeration via X-Magento-Vary header",
            "REST API mass assignment on product/customer endpoints",
            "SOAP PHP deserialization vulnerability",
            "EAV SQL injection via product attribute filtering",
            "Payment gateway parameter manipulation",
            "Customer account takeover via mass assignment",
            "app/etc/env.php file exposure via path traversal",
            "Cache poisoning via Varnish header injection",
            "Unrestricted file upload via media gallery",
            "Promotion/coupon code abuse",
            "Admin CSRF on system configuration",
            "Elasticsearch injection via search parameter",
        ],
        investigation_areas=[
            "Check response headers for X-Magento-Vary to discover admin path",
            "Test REST API endpoints for unauthenticated access",
            "Test SOAP endpoint for deserialization payloads",
            "Audit EAV attribute queries for SQL injection",
            "Test checkout/payment endpoints for price manipulation",
            "Try mass assignment on customer registration endpoint",
            "Check /app/etc/env.php file exposure",
            "Test Varnish cache poisoning via HTTP headers",
            "Check /pub/media for unrestricted file upload",
            "Test promotion code abuse via quantity manipulation",
            "Check admin CSRF tokens on configuration forms",
            "Test GraphQL endpoint for introspection",
        ],
        tags=["magento", "adobe-commerce", "cms", "ecommerce", "php"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Powered-By": "PHP",
            "X-Magento-Vary": "pattern: [a-f0-9]+",
            "X-Magento-Tags": "pattern: [a-z0-9_]+",
            "Set-Cookie": "PHPSESSID",
            "Set-Cookie": "admin",
            "Set-Cookie": "form_key",
        },
        cookies=["PHPSESSID", "admin", "form_key", "X-Magento-Tags"],
        js_indicators=["Magento", "requirejs-config", "mixins", "mage/", "Magento_Ui", "Magento_PageCache"],
        file_indicators=["app/etc/env.php", "app/etc/config.php", "composer.json", "composer.lock", "pub/static/version", "nginx.conf.sample", ".htaccess.sample", "index.php", "grunt-config.json", "package.json"],
        directory_indicators=["/app/", "/app/code/", "/app/design/", "/app/etc/", "/pub/", "/pub/media/", "/pub/static/", "/var/", "/var/log/", "/var/cache/", "/vendor/"],
        server_signatures=["Magento", "Adobe Commerce", "PHP"],
        error_page_signatures=["There has been an error processing your request", "Exception printing is disabled by default", "Magento\\Framework\\", "SQLSTATE[", "Notice: Undefined index", "Warning: include("],
        default_paths=["/", "/admin", "/customer/account/login", "/checkout/cart", "/rest/V1/", "/soap/default", "/graphql", "/static/version/"],
        default_files=["app/etc/env.php", "app/etc/config.php", "composer.json", "composer.lock", "index.php", "nginx.conf.sample", ".htaccess.sample", "grunt-config.json"],
        metadata_patterns={"generator": "Magento", "magento-version": "pattern: [0-9]+\\.[0-9]+\\.[0-9]+"},
        tags=["fingerprint", "magento", "adobe-commerce"],
    ),
    recon=ReconProfile(
        directories_to_check=["/app/etc/", "/pub/media/", "/pub/static/", "/var/log/", "/var/cache/", "/vendor/", "/app/code/"],
        files_to_check=["app/etc/env.php", "app/etc/config.php", "composer.json", "composer.lock", "index.php", "nginx.conf.sample", ".htaccess.sample", "grunt-config.json", "package.json"],
        endpoints_to_scan=["/rest/V1/", "/rest/V1/products", "/soap/default", "/graphql", "/admin", "/customer/account/login", "/checkout/cart"],
        version_detection_paths=["/composer.json", "/pub/static/version/"],
        debug_paths_to_check=["/var/log/system.log", "/var/log/exception.log", "/var/log/debug.log", "/admin"],
        admin_paths_to_check=["/admin", "/admin/dashboard", "/admin/admin", "/backend", "/magento"],
        tags=["recon", "magento", "adobe-commerce"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Magento admin panel path can be discovered via X-Magento-Vary header, enabling targeted admin attacks",
            impact="Admin panel discovery enabling brute-force, CSRF, and configuration manipulation attacks",
            attack_scenario="Check response header X-Magento-Vary for hash used to compute admin path, then access /admin/{hash}",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="REST API mass assignment allows setting arbitrary product/customer attributes via API calls",
            impact="Product price manipulation, customer data modification, privilege escalation",
            attack_scenario="Include extra attributes in REST API POST/PUT requests to product or customer endpoints",
            complexity="medium",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="SOAP API PHP deserialization via object injection leads to RCE",
            impact="Remote code execution via crafted SOAP payload with PHP object injection",
            attack_scenario="Send malicious SOAP XML with PHP object serialization payloads to /soap/default",
            complexity="high",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Payment gateway parameter manipulation allows price modification during checkout",
            impact="Order total manipulation, free products, negative pricing",
            attack_scenario="Intercept and modify payment parameters (amount, currency, item price) during checkout POST requests",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="app/etc/env.php file exposure reveals database credentials and encryption keys",
            impact="Full database access, encrypted data decryption, admin session hijacking",
            attack_scenario="Access /app/etc/env.php via path traversal or misconfiguration to read database credentials and encryption key",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(target_pack_name="php", relationship_type=KnowledgeRelationshipType.RUNS_ON, description="Magento runs on PHP", confidence="high"),
        KnowledgeRelationship(target_pack_name="mysql", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="Magento uses MySQL/MariaDB", confidence="high"),
        KnowledgeRelationship(target_pack_name="elasticsearch", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="Magento uses Elasticsearch/OpenSearch for product search", confidence="high"),
        KnowledgeRelationship(target_pack_name="redis", relationship_type=KnowledgeRelationshipType.CACHES_WITH, description="Magento caches with Redis", confidence="high"),
        KnowledgeRelationship(target_pack_name="varnish", relationship_type=KnowledgeRelationshipType.CACHES_WITH, description="Magento full page cache with Varnish", confidence="high"),
        KnowledgeRelationship(target_pack_name="rabbitmq", relationship_type=KnowledgeRelationshipType.QUEUES_WITH, description="Magento message queues with RabbitMQ", confidence="medium"),
        KnowledgeRelationship(target_pack_name="nginx", relationship_type=KnowledgeRelationshipType.PROXIED_BY, description="Magento commonly runs on Nginx", confidence="high"),
        KnowledgeRelationship(target_pack_name="paypal", relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH, description="Magento integrates with PayPal payments", confidence="high"),
        KnowledgeRelationship(target_pack_name="docker", relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY, description="Magento containerized with Docker", confidence="medium"),
    ],
    dependencies=["PHP", "MySQL/MariaDB", "Elasticsearch/OpenSearch", "Redis", "Composer"],
    related_packs=["php", "mysql", "elasticsearch", "redis", "varnish", "rabbitmq", "nginx", "paypal", "docker"],
    workflow=[
        "1. Fingerprint Magento via X-Magento-Vary and X-Magento-Tags headers",
        "2. Extract admin panel path from X-Magento-Vary response header",
        "3. Check /app/etc/env.php for credential and encryption key exposure",
        "4. Test REST API at /rest/V1/ for unauthenticated endpoint access",
        "5. Test SOAP API at /soap/default for deserialization payloads",
        "6. Explore /rest/V1/products for product listing without auth",
        "7. Test customer registration endpoint for mass assignment",
        "8. Check checkout process for payment parameter manipulation",
        "9. Test admin panel access via discovered admin path",
        "10. Check /pub/media for directory listing and file upload",
        "11. Test Elasticsearch injection via search parameters",
        "12. Check GraphQL endpoint for introspection and data extraction",
        "13. Review cache poisoning via HTTP header injection",
        "14. Check /var/log/system.log and /var/log/exception.log for leaks",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="MAGENTO-01",
            category="Admin Security",
            description="Check for admin panel path enumeration and brute-force protection",
            expected_result="Admin panel should use strong path, rate limiting, and CAPTCHA",
            tools=["curl", "Burp Suite"],
            references=["https://devdocs.magento.com/guides/v2.4/config-guide/secy/secy-admin.html"],
        ),
        ManualTestChecklistItem(
            step_id="MAGENTO-02",
            category="API Security",
            description="Test REST and SOAP API endpoints for unauthenticated access",
            expected_result="API endpoints should require valid authentication tokens",
            tools=["curl", "Postman", "Burp Suite"],
            references=["https://devdocs.magento.com/guides/v2.4/get-started/authentication/"],
        ),
        ManualTestChecklistItem(
            step_id="MAGENTO-03",
            category="Payment Manipulation",
            description="Test checkout for payment parameter manipulation",
            expected_result="Price, quantity, and payment parameters should be validated server-side",
            tools=["Burp Suite", "custom scripts"],
            references=["https://experienceleague.adobe.com/docs/commerce-operations/security-and-compliance/best-practices.html"],
        ),
        ManualTestChecklistItem(
            step_id="MAGENTO-04",
            category="Mass Assignment",
            description="Test customer and product API endpoints for mass assignment",
            expected_result="Only allowed attributes should be writable via API requests",
            tools=["Burp Suite", "custom scripts"],
            references=["https://devdocs.magento.com/guides/v2.4/rest/retrieve-filtered-responses.html"],
        ),
        ManualTestChecklistItem(
            step_id="MAGENTO-05",
            category="Configuration Exposure",
            description="Check for app/etc/env.php and var/log file exposure",
            expected_result="Configuration files and logs should not be accessible from the web",
            tools=["curl", "Burp Suite"],
            references=["https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/overview.html"],
        ),
    ],
    references=[
        {"title": "Magento DevDocs", "url": "https://devdocs.magento.com/"},
        {"title": "Adobe Commerce Security", "url": "https://experienceleague.adobe.com/docs/commerce-operations/security-and-compliance/overview.html"},
        {"title": "OWASP Magento Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Magento_Cheat_Sheet.html"},
        {"title": "Magento Security Center", "url": "https://magento.com/security"},
        {"title": "CVE Magento Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Magento"},
    ],
    cwe_ids=["CWE-200", "CWE-306", "CWE-502", "CWE-89", "CWE-287", "CWE-352", "CWE-79", "CWE-22"],
    cve_ids=["CVE-2024-34102", "CVE-2024-20720", "CVE-2023-38214", "CVE-2022-35698", "CVE-2021-36026", "CVE-2020-24407", "CVE-2019-8111"],
    tags=["php", "magento", "adobe-commerce", "cms", "ecommerce", "shop"],
)
