"""Mongoose ODM Knowledge Pack — MongoDB object-document mapper for Node.js."""

from deephunter.core.types import (
    AttackSurfaceEntry,
    BusinessLogicConcern,
    BugClass,
    ManualTestChecklistItem,
    TrustBoundary,
)
from deephunter.knowledge.packs.base import (
    AttackSurfaceProfile,
    FingerprintProfile,
    KnowledgePack,
    KnowledgePackCategory,
    KnowledgeRelationship,
    KnowledgeRelationshipType,
    ReconProfile,
    TechnologyComponentProfile,
    TechnologyProfile,
)

PACK = KnowledgePack(
    name="mongoose",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="Mongoose ODM for MongoDB — NoSQL injection via query selector manipulation, mass assignment, schema validation bypass, prototype pollution in query helpers, and unsafe serialization of Mongoose documents.",
    technology=TechnologyProfile(
        name="Mongoose",
        vendor="Mongoose MongoDB",
        language="JavaScript/TypeScript",
        framework="Mongoose ODM",
        runtime="Node.js",
        description="Mongoose is an Object Data Modeling (ODM) library for MongoDB and Node.js. Provides a schema-based solution to model application data with built-in type casting, validation, and hooks.",
        common_aliases=["mongoose", "mongoosejs", "mongoose-odm"],
        dependencies=["Node.js", "MongoDB", "mongodb driver"],
        common_integrations=["Express", "Fastify", "NestJS", "GraphQL (Apollo)", "MongoDB Atlas"],
        architecture_description="Mongoose connects to MongoDB via the official mongodb driver. Schemas define document structure with types, validation, and middleware hooks. Models are compiled from schemas for CRUD operations.",
        request_lifecycle="Application -> Mongoose Model query -> Schema validation -> MongoDB driver -> MongoDB -> Document returned -> Middleware hooks -> Application",
        documentation_url="https://mongoosejs.com/docs/guide.html",
        tags=["mongodb", "nosql", "orm", "odm", "nodejs"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Schema Validation Bypass",
            description="Client-supplied data merged into query without schema validation. NoSQL injection via query operators ($ne, $gt, $regex, $where).",
            security_relevance="critical",
            common_vulnerabilities=["NoSQL injection via query operator injection", "Schema validation bypass with raw objects", "Type coercion bypass", "Query selector manipulation for auth bypass"],
            investigation_priority=99,
            tags=["nosql-injection", "validation-bypass", "auth-bypass"],
        ),
        TechnologyComponentProfile(
            name="Mass Assignment",
            description="Creating/updating documents with raw req.body without selecting allowed fields. Setting sensitive fields like isAdmin, role, permissions.",
            security_relevance="high",
            common_vulnerabilities=["Mass assignment setting protected fields", "Role escalation via user input", "Privilege elevation by setting admin flags", "Direct assignment bypassing validation"],
            investigation_priority=90,
            tags=["mass-assignment", "auth-bypass", "privilege-escalation"],
        ),
        TechnologyComponentProfile(
            name="Query Injection",
            description="User input directly interpolated into Mongoose queries. Query selectors ($ne, $in, $regex, $where) manipulated for unauthorized access.",
            security_relevance="critical",
            common_vulnerabilities=["NoSQL injection via query selector operators", "$where injection for arbitrary JS execution", "$regex DoS in MongoDB queries", "Query injection bypassing authentication"],
            investigation_priority=95,
            tags=["nosql", "query-injection", "auth-bypass"],
        ),
        TechnologyComponentProfile(
            name="Middleware/Hooks",
            description="Mongoose pre/post hooks for document lifecycle. Hooks can be exploited to modify data flow or escalate privileges.",
            security_relevance="medium",
            common_vulnerabilities=["Hook manipulation for data modification", "Bypassing save hooks", "Injecting logic into pre/post middleware", "Async hook race conditions"],
            investigation_priority=70,
            tags=["hooks", "middleware", "lifecycle"],
        ),
        TechnologyComponentProfile(
            name="Aggregation Pipeline",
            description="Mongoose aggregate() for complex queries. Pipeline injection via user-supplied stages.",
            security_relevance="high",
            common_vulnerabilities=["Aggregation pipeline injection", "$lookup/$graphLookup for data exfiltration", "Unchecked $unionWith for cross-collection access", "Pipeline stages enabling privilege escalation"],
            investigation_priority=85,
            tags=["aggregation", "nosql", "data-exfiltration"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="REST API with Mongoose Models",
                description="API routes using Mongoose Models for CRUD operations",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/api/*",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.NO_SQL_INJECTION.value, BugClass.AUTH_BYPASS.value, BugClass.IDOR.value],
            ),
        ],
        endpoints=["/api/*", "/api/users/*", "/api/posts/*", "/api/admin/*"],
        parameters=["_id", "limit", "skip", "sort", "select", "populate", "where", "find", "filter"],
        authentication=["JWT", "Session cookies", "API keys"],
        authorization=["Application-level checks", "Mongoose middleware"],
        storage=["MongoDB"],
        background_jobs=[],
        queues=[],
        caches=["Redis", "Memcached"],
        admin_interfaces=["/admin/*"],
        internal_apis=["/internal/*"],
        external_apis=[],
        trust_boundaries=[
            TrustBoundary(name="App-to-MongoDB", description="Mongoose Model queries to MongoDB", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "NoSQL injection via query selector operators",
            "Mass assignment bypassing role checks",
            "Aggregation pipeline injection",
            "$where injection for arbitrary JavaScript execution",
            "Prototype pollution in query helper methods",
            "Type coercion in query parameters",
            "Schema validation bypass with raw objects",
        ],
        investigation_areas=[
            "Test query operators for NoSQL injection ($ne, $gt, $lt, $regex, $where, $exists)",
            "Test mass assignment by adding role/admin fields to request body",
            "Check aggregation pipelines for user-supplied stages",
            "Test $where clauses for JavaScript injection",
            "Verify schema select() is enforced on all write operations",
            "Test for type coercion in _id and numeric parameters",
            "Check for prototype pollution in query helpers",
        ],
        tags=["mongoose", "mongodb", "nosql", "nodejs"],
    ),
    fingerprints=FingerprintProfile(
        js_indicators=["mongoose", "Schema(", "model(", "findOne", "findById", "aggregate(["],
        file_indicators=["models/", "schemas/", "mongoose.connect", "mongodb://", ".env"],
        server_signatures=["mongoose", "mongodb"],
        error_page_signatures=["CastError:", "ValidationError:", "MongoServerError:", "MongoError:", "E11000 duplicate key"],
        metadata_patterns={"odm": "mongoose", "db": "mongodb"},
        tags=["fingerprint", "mongoose", "mongodb"],
    ),
    recon=ReconProfile(
        files_to_check=[".env", "models/", "schemas/"],
        tags=["recon", "mongoose", "mongodb"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="NoSQL injection via query operator injection allows bypassing authentication and authorization",
            impact="Authentication bypass, data exfiltration, privilege escalation",
            attack_scenario="Send {\"password\": {\"$ne\": null}} or {\"isAdmin\": {\"$gte\": 0}} in JSON body to bypass auth checks",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Mass assignment via raw request body allows setting protected fields like isAdmin or role",
            impact="Privilege escalation, full account takeover",
            attack_scenario="Add isAdmin=true or role=admin to POST/PUT body when creating user document",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="$where injection in MongoDB queries allows arbitrary JavaScript execution",
            impact="Full MongoDB server compromise, data exfiltration",
            attack_scenario="Use $where with user input like 'this.field' + malicious_js to execute on MongoDB server",
            complexity="medium",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="nodejs",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="Mongoose runs on Node.js",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="express",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Mongoose is commonly used with Express.js",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="mongodb",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="Mongoose provides an interface to MongoDB",
            confidence="high",
        ),
    ],
    dependencies=["Node.js", "MongoDB", "mongodb driver"],
    related_packs=["nodejs", "express", "mongodb"],
    workflow=[
        "1. Identify Mongoose via error messages (CastError, ValidationError) and model/collection patterns",
        "2. Test query parameters for NoSQL injection with operators like $ne, $gt, $regex, $where",
        "3. Test mass assignment by adding unexpected fields to POST/PUT bodies",
        "4. Check aggregation pipelines for user-supplied stages",
        "5. Test $where clauses for JavaScript injection",
        "6. Verify schema select() is enforced on all operations",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="MONGO-01",
            category="NoSQL Injection",
            description="Test query selectors for NoSQL injection with operator manipulation",
            expected_result="Query operators in user input must be stripped or rejected; use parameterized queries",
            tools=["NoSQLMap", "custom scripts", "Burp Suite"],
            references=["https://mongoosejs.com/docs/guide.html"],
        ),
        ManualTestChecklistItem(
            step_id="MONGO-02",
            category="Mass Assignment",
            description="Test mass assignment by adding protected fields to request body",
            expected_result="Model.create() must use strict schema validation and select() to whitelist fields",
            tools=["Burp Suite", "custom scripts"],
            references=["https://mongoosejs.com/docs/tutorials/findoneandupdate.html"],
        ),
    ],
    references=[
        {"title": "Mongoose Documentation", "url": "https://mongoosejs.com/docs/guide.html"},
        {"title": "NoSQL Injection in MongoDB", "url": "https://owasp.org/www-community/attacks/ NOSQL_Injection"},
        {"title": "PortSwigger NoSQL Injection", "url": "https://portswigger.net/web-security/nosql-injection"},
    ],
    cwe_ids=["CWE-943", "CWE-915", "CWE-287", "CWE-89", "CWE-94"],
    cve_ids=[],
    tags=["mongoose", "mongodb", "nosql", "nodejs"],
)