"""NestJS knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="nestjs",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="NestJS Node.js — reflector metadata exposure, GraphQL resolver introspection, class-validator bypass.",
    technology=TechnologyProfile(
        name="NestJS",
        vendor="NestJS (Kamil Mysliwiec)",
        language="TypeScript/JavaScript",
        framework="NestJS",
        runtime="Node.js (18+)",
        description="NestJS is a progressive Node.js framework for building efficient, reliable, and scalable server-side applications. Built with TypeScript and heavily inspired by Angular.",
        common_aliases=["nestjs", "nest-js", "nest"],
        dependencies=["Node.js", "npm/yarn/pnpm", "TypeScript"],
        common_integrations=["TypeORM", "Prisma", "Mongoose", "GraphQL (Apollo/Mercurius)", "Passport.js", "Redis", "PostgreSQL", "MongoDB", "RabbitMQ", "Kafka", "Swagger"],
        architecture_description="Modular architecture with controllers, providers, guards, interceptors, pipes, filters, and GraphQL resolver support.",
        request_lifecycle="HTTP request -> middleware -> guards -> interceptor (before) -> pipe -> controller handler -> interceptor (after) -> exception filter -> response",
        documentation_url="https://docs.nestjs.com/",
        tags=["typescript", "nodejs", "graphql", "microservices", "decorators"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Reflector & Metadata",
            description="NestJS uses Reflect.defineMetadata for decorator-based configuration. Metadata exposure via Reflect.getMetadata, unintended privilege reflection.",
            security_relevance="high",
            common_vulnerabilities=["Reflector metadata injection", "Role/permission metadata spoofing", "Insecure Reflect.getMetadata access", "Metadata inheritance bypass"],
            investigation_priority=90,
            tags=["reflector", "metadata", "decorators"],
        ),
        TechnologyComponentProfile(
            name="GraphQL Resolvers",
            description="GraphQL resolvers for query and mutation handling. Introspection leakage, resolver injection, field authorization bypass.",
            security_relevance="high",
            common_vulnerabilities=["GraphQL introspection enabled in production", "Resolver authorization bypass via query depth", "Field-level permission missing", "SQL injection via GraphQL args", "Batch query DoS via batching"],
            investigation_priority=95,
            tags=["graphql", "resolvers", "introspection", "query"],
        ),
        TechnologyComponentProfile(
            name="class-validator / class-transformer",
            description="DTO validation using decorator-based validators. Validation bypass via whitelist/forbidNonWhitelisted misconfig, type transformation attacks.",
            security_relevance="high",
            common_vulnerabilities=["Validation bypass via whitelist: false", "Type transformation injection", "Missing forbidNonWhitelisted exposing extra fields", "Mass assignment via untransformed properties"],
            investigation_priority=90,
            tags=["validation", "dto", "class-validator", "pipes"],
        ),
        TechnologyComponentProfile(
            name="Auth Guards & Passport.js",
            description="Authentication guards and Passport.js strategies. JWT token handling, guard bypass, strategy misconfiguration.",
            security_relevance="high",
            common_vulnerabilities=["JWT algorithm confusion (none)", "Guard missing on resolver", "Role guard logic bypass via metadata", "Passport strategy validation flaws", "Session fixation"],
            investigation_priority=85,
            tags=["auth", "guards", "passport", "jwt"],
        ),
        TechnologyComponentProfile(
            name="Swagger/OpenAPI Module",
            description="API documentation generated via @nestjs/swagger. Endpoint exposure, schema leakage, DTO information disclosure.",
            security_relevance="medium",
            common_vulnerabilities=["Swagger UI enabled in production", "DTO schema leakage via OpenAPI spec", "API key exposure in documentation", "Endpoint details aiding attack"],
            investigation_priority=80,
            tags=["swagger", "openapi", "documentation"],
        ),
        TechnologyComponentProfile(
            name="Exception Filters",
            description="Global exception handling filters. Stack trace leakage, inconsistent error responses aiding enumeration.",
            security_relevance="medium",
            common_vulnerabilities=["Verbose exception messages exposing internals", "Stack trace leakage in error responses", "Inconsistent error responses for user enumeration", "Unhandled exception DoS"],
            investigation_priority=70,
            tags=["exceptions", "errors", "handling"],
        ),
        TechnologyComponentProfile(
            name="Dependency Injection",
            description="Provider-based DI system. Circular dependency information leaks, provider scope confusion, singleton state leakage.",
            security_relevance="medium",
            common_vulnerabilities=["Request-scoped provider confusion", "Singleton state leakage across users", "Module import privilege inheritance", "Dynamic module parameter injection"],
            investigation_priority=70,
            tags=["di", "providers", "modules"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="REST Controllers",
                description="All @Controller decorator-based endpoints",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{route}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="GraphQL Endpoint",
                description="GraphQL endpoint (usually /graphql) for queries and mutations",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/graphql",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value, BugClass.SQL_INJECTION.value],
            ),
            AttackSurfaceEntry(
                name="Swagger UI",
                description="Swagger documentation endpoint",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/api",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/api", "/api/*", "/graphql", "/graphql/sdl", "/docs", "/swagger", "/docs/swagger-ui"],
        parameters=["query", "variables", "operationName", "id", "limit", "offset", "sort", "filter"],
        authentication=["Passport.js strategies", "JWT (Bearer)", "OAuth2", "Session cookies", "API keys"],
        authorization=["@Roles() decorator", "@UseGuards()", "AuthGuard", "GraphQL field-level guards"],
        storage=["Local disk", "S3", "Cloud storage"],
        background_jobs=["Bull queue", "RabbitMQ", "Kafka"],
        queues=["Bull (Redis)", "RabbitMQ", "Kafka"],
        caches=["Redis (ioredis)", "Memcached"],
        admin_interfaces=["/admin", "/admin/*", "/api/admin"],
        internal_apis=["/internal/*", "/api/internal/*"],
        external_apis=["Stripe", "SendGrid", "Twilio", "Auth0", "AWS APIs"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Node", description="Request enters NestJS application", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="TypeORM/Prisma queries to database", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-MQ", description="Messages to RabbitMQ/Kafka", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "GraphQL introspection enabled in production",
            "class-validator whitelist/forbidNonWhitelisted bypass",
            "Reflector metadata privilege escalation",
            "Swagger/OpenAPI endpoint exposure",
            "JWT algorithm confusion in guards",
            "Guard missing on GraphQL resolvers",
            "DTO mass assignment via missing validation",
            "Verbose exception messages leaking internals",
            "GraphQL batching/resolver injection",
            "Type transformation via class-transformer",
            "Dynamic module parameter injection",
            "Microservice message pattern enumeration",
        ],
        investigation_areas=[
            "Send introspection query to /graphql to check if enabled in production",
            "Test class-validator by sending extra fields with whitelist disabled",
            "Check Reflect.defineMetadata for role/permission manipulation",
            "Access /api and /docs for Swagger endpoint exposure",
            "Test JWT validation with algorithm=none token",
            "Check guards on all resolvers and controllers",
            "Test DTO validation bypass with type coercion",
            "Trigger exceptions to check verbosity of error messages",
            "Check GraphQL query depth limits and batching",
            "Test for type transformation injection via class-transformer",
            "Inspect dynamic module imports for parameter injection",
            "Check microservice TCP/RabbitMQ pattern exposure",
        ],
        tags=["nestjs", "typescript", "nodejs", "framework", "web"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Powered-By": "NestJS",
        },
        cookies=[],
        js_indicators=["NestJS", "useValue", "useFactory", "@Module", "@Controller", "@Injectable"],
        file_indicators=["nest-cli.json", "nestconfig.json", "tsconfig.json", "tsconfig.build.json", "package.json", ".eslintrc.js", ".prettierrc", "Dockerfile"],
        directory_indicators=["/src/", "/src/controllers/", "/src/resolvers/", "/src/services/", "/src/modules/", "/src/guards/", "/src/interceptors/", "/dist/"],
        server_signatures=["NestJS", "Node.js"],
        error_page_signatures=["Cannot GET", "Method not allowed", "NotFoundException", "BadRequestException", "InternalServerErrorException", "UnauthorizedException"],
        default_paths=["/api", "/graphql", "/docs", "/swagger"],
        default_files=["nest-cli.json", "package.json", "tsconfig.json", ".env"],
        metadata_patterns={"nestjs-version": "pattern: [0-9]+\\.[0-9]+\\.[0-9]+"},
        tags=["fingerprint", "nestjs", "typescript"],
    ),
    recon=ReconProfile(
        directories_to_check=["/api/", "/graphql/", "/docs/", "/swagger/", "/src/", "/dist/"],
        files_to_check=["nest-cli.json", "package.json", "tsconfig.json", ".env"],
        endpoints_to_scan=["/api", "/graphql", "/docs", "/swagger"],
        version_detection_paths=["/package.json", "/api"],
        debug_paths_to_check=["/api", "/graphql?query={__schema{types{name}}}"],
        admin_paths_to_check=["/admin", "/admin/*"],
        tags=["recon", "nestjs", "typescript"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="GraphQL introspection enabled in production allows full schema dump",
            impact="Complete API schema discovery including hidden resolvers, mutations, and field types",
            attack_scenario="Send __schema introspection query to /graphql to dump all types, queries, mutations, and subscriptions",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="class-validator whitelist mode disabled allows mass assignment bypass",
            impact="Extra fields passed in DTO bypass validation and may be stored in database",
            attack_scenario="Add unexpected fields like role, isAdmin, or status to POST/PUT request bodies",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Reflector metadata manipulation allows privilege escalation via decorator spoofing",
            impact="Bypass of @Roles() and @Permissions() decorator checks",
            attack_scenario="Manipulate metadata keys to assume unauthorized roles or permissions",
            complexity="high",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="JWT algorithm confusion attack on guards that don't restrict algorithms",
            impact="Authentication bypass by forging arbitrary valid JWTs",
            attack_scenario="Send token with {alg: 'none' } or swap RS256 public key to HS256 with known public key",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Type transformation via class-transformer enables prototype pollution",
            impact="Prototype property injection via __proto__ in transformed JSON bodies",
            attack_scenario="Send JSON with __proto__ or constructor.prototype keys in request body",
            complexity="medium",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(target_pack_name="nodejs", relationship_type=KnowledgeRelationshipType.RUNS_ON, description="NestJS runs on Node.js", confidence="high"),
        KnowledgeRelationship(target_pack_name="typescript", relationship_type=KnowledgeRelationshipType.DEPENDS_ON, description="NestJS is built with TypeScript", confidence="high"),
        KnowledgeRelationship(target_pack_name="express", relationship_type=KnowledgeRelationshipType.DEPENDS_ON, description="NestJS uses Express.js under the hood (default)", confidence="high"),
        KnowledgeRelationship(target_pack_name="graphql", relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH, description="NestJS integrates with GraphQL via @nestjs/graphql", confidence="high"),
        KnowledgeRelationship(target_pack_name="passport", relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH, description="NestJS auth via Passport.js strategies", confidence="high"),
        KnowledgeRelationship(target_pack_name="postgresql", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="NestJS uses PostgreSQL via TypeORM/Prisma", confidence="high"),
        KnowledgeRelationship(target_pack_name="typeorm", relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH, description="NestJS integrates with TypeORM", confidence="high"),
        KnowledgeRelationship(target_pack_name="docker", relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY, description="NestJS apps containerized with Docker", confidence="medium"),
        KnowledgeRelationship(target_pack_name="spring-boot", relationship_type=KnowledgeRelationshipType.SIMILAR_TO, description="NestJS architecture inspired by Spring Boot", confidence="medium"),
    ],
    dependencies=["Node.js", "npm/yarn/pnpm", "TypeScript"],
    related_packs=["nodejs", "typescript", "express", "graphql", "passport", "postgresql", "typeorm", "docker", "spring-boot"],
    workflow=[
        "1. Fingerprint NestJS via X-Powered-By header and /api or /graphql endpoints",
        "2. Send introspection query to /graphql to dump the full schema",
        "3. Test DTO validation by sending extra fields in request bodies",
        "4. Attempt JWT algorithm confusion (none algorithm, RS256->HS256)",
        "5. Check Swagger/OpenAPI at /api and /docs for endpoint documentation",
        "6. Test reflector metadata manipulation for role bypass",
        "7. Check class-transformer for prototype pollution via __proto__",
        "8. Trigger errors to check exception filter verbosity",
        "9. Test guards on GraphQL resolvers vs REST endpoints",
        "10. Check for GraphQL query depth limits and batching attacks",
        "11. Test type transformation injection via class-transformer",
        "12. Check microservice endpoint exposure pattern",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="NESTJS-01",
            category="GraphQL",
            description="Check if GraphQL introspection is enabled in production",
            expected_result="Introspection should be disabled in production environments",
            tools=["curl", "graphql-playground", "Burp Suite"],
            references=["https://docs.nestjs.com/graphql/quick-start"],
        ),
        ManualTestChecklistItem(
            step_id="NESTJS-02",
            category="Validation",
            description="Test class-validator whitelist bypass with unexpected fields",
            expected_result="Unexpected fields should be stripped or rejected by validation pipe",
            tools=["Burp Suite", "custom scripts"],
            references=["https://docs.nestjs.com/pipes"],
        ),
        ManualTestChecklistItem(
            step_id="NESTJS-03",
            category="Authentication",
            description="Test JWT validation for algorithm confusion",
            expected_result="Tokens with algorithm 'none' should be rejected",
            tools=["jwt_tool", "custom scripts"],
            references=["https://docs.nestjs.com/security/authentication"],
        ),
        ManualTestChecklistItem(
            step_id="NESTJS-04",
            category="Information Disclosure",
            description="Check Swagger/OpenAPI endpoint accessibility",
            expected_result="API documentation should not be accessible in production",
            tools=["curl", "browser"],
            references=["https://docs.nestjs.com/openapi/introduction"],
        ),
        ManualTestChecklistItem(
            step_id="NESTJS-05",
            category="Error Handling",
            description="Check exception filter for verbose error messages",
            expected_result="Error messages should not reveal internal paths, stack traces, or database details",
            tools=["curl", "Burp Suite"],
            references=["https://docs.nestjs.com/exception-filters"],
        ),
    ],
    references=[
        {"title": "NestJS Documentation", "url": "https://docs.nestjs.com/"},
        {"title": "NestJS Security", "url": "https://docs.nestjs.com/security/authentication"},
        {"title": "NestJS GraphQL", "url": "https://docs.nestjs.com/graphql/quick-start"},
        {"title": "NestJS OpenAPI/Swagger", "url": "https://docs.nestjs.com/openapi/introduction"},
        {"title": "CVE NestJS Collection", "url": "https://www.cve.org/KeywordSearch?keyword=NestJS"},
    ],
    cwe_ids=["CWE-200", "CWE-915", "CWE-287", "CWE-94", "CWE-1321", "CWE-79", "CWE-306"],
    cve_ids=["CVE-2024-32548", "CVE-2024-29453", "CVE-2023-45397", "CVE-2022-24434", "CVE-2021-2275"],
    tags=["typescript", "nestjs", "web", "framework", "nodejs", "graphql"],
)
