"""Next.js knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="nextjs",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="Next.js React — SSR data leakage, API route exposure, middleware bypass, _next/static directory traversal.",
    technology=TechnologyProfile(
        name="Next.js",
        vendor="Vercel",
        language="TypeScript/JavaScript",
        framework="Next.js",
        runtime="Node.js (18+)",
        description="Next.js is a React framework for production-grade web applications with server-side rendering, static site generation, and API routes.",
        common_aliases=["nextjs", "next-js", "next.js"],
        dependencies=["Node.js", "React", "npm/yarn/pnpm"],
        common_integrations=["React", "TypeScript", "Tailwind CSS", "Prisma", "tRPC", "NextAuth.js", "Stripe", "Vercel", "MongoDB", "PostgreSQL"],
        architecture_description="Hybrid rendering with SSG, SSR, ISR, React Server Components, App Router, and API route support.",
        request_lifecycle="HTTP request -> Next.js server -> middleware -> route handler (pages/api or app/api) -> server component/page -> client component hydration -> HTTP response",
        documentation_url="https://nextjs.org/docs",
        tags=["react", "ssr", "ssg", "typescript", "vercel"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Server-Side Rendering (SSR)",
            description="Pages rendered on the server. SSR data leakage via getServerSideProps, hydration mismatch, sensitive props exposure.",
            security_relevance="high",
            common_vulnerabilities=["Sensitive data in SSR props sent to client", "API keys in getServerSideProps returned to client", "getServerSideProps URL parameter injection", "SSR Cross-Site Scripting via HTML injection"],
            investigation_priority=95,
            tags=["ssr", "server-side", "props"],
        ),
        TechnologyComponentProfile(
            name="API Routes",
            description="Serverless API endpoints under /pages/api or /app/api. Unauthenticated exposure, SSRF, injection vulnerabilities.",
            security_relevance="high",
            common_vulnerabilities=["API route without authentication", "SSRF via API route outgoing requests", "Body parsing injection", "Serverless function timeout DoS", "Environment variable leakage"],
            investigation_priority=90,
            tags=["api", "serverless", "routes"],
        ),
        TechnologyComponentProfile(
            name="Middleware (src/middleware.ts)",
            description="Edge/functions middleware for request preprocessing. Middleware bypass via URL manipulation.",
            security_relevance="high",
            common_vulnerabilities=["Middleware bypass via trailing slash", "Middleware bypass via URL encoding", "Missing middleware on certain routes", "Edge function logic flaws"],
            investigation_priority=85,
            tags=["middleware", "edge", "auth"],
        ),
        TechnologyComponentProfile(
            name="Static File Serving (_next/static)",
            description="Next.js compiled static assets under /_next/static. Directory traversal, source map exposure, chunk enumeration.",
            security_relevance="high",
            common_vulnerabilities=["Source map exposure (.js.map)", "Directory traversal via _next/static", "Webpack chunk enumeration revealing page structure", "CSS/JS version fingerprinting"],
            investigation_priority=85,
            tags=["static", "source-maps", "webpack"],
        ),
        TechnologyComponentProfile(
            name="Image Optimization",
            description="Next.js built-in image optimization (next/image). SSRF via image URL parameter.",
            security_relevance="medium",
            common_vulnerabilities=["SSRF via image src URL", "Local file disclosure via image optimization", "DoS via image manipulation"],
            investigation_priority=75,
            tags=["images", "ssrf", "optimization"],
        ),
        TechnologyComponentProfile(
            name="NextAuth.js",
            description="Authentication for Next.js applications. JWT session handling, callback URL validation.",
            security_relevance="high",
            common_vulnerabilities=["Callback URL open redirect", "JWT session tampering", "CSRF on auth callbacks", "Provider account takeover via email mismatch"],
            investigation_priority=85,
            tags=["auth", "nextauth", "oauth", "jwt"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="API Routes",
                description="Serverless API functions in /pages/api/* or /app/api/*",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/api/{route}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="SSR Pages",
                description="Pages with getServerSideProps or getInitialProps",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/{page}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.SSTI.value, BugClass.XSS.value],
            ),
            AttackSurfaceEntry(
                name="Server Actions",
                description="React Server Actions in App Router",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/{action}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.CSRF.value, BugClass.IDOR.value],
            ),
        ],
        endpoints=["/api/*", "/api/auth/*", "/api/graphql", "/_next/static/*", "/_next/data/*", "/_next/image/*", "/favicon.ico", "/robots.txt", "/sitemap.xml"],
        parameters=["id", "slug", "page", "limit", "search", "q", "callback", "next", "redirect", "image"],
        authentication=["NextAuth.js", "Clerk", "Supabase Auth", "JWT tokens", "OAuth providers"],
        authorization=["Middleware checks", "Route-level guards", "Role-based access via components"],
        storage=["Vercel Blob", "S3", "Cloudinary", "Local filesystem"],
        background_jobs=["Vercel Cron", "QStash", "BullMQ"],
        queues=["Redis", "BullMQ"],
        caches=["Vercel Edge Cache", "Redis", "CDN (Vercel/Cloudflare)"],
        admin_interfaces=["/admin", "/admin/*", "/dashboard"],
        internal_apis=["/api/internal/*", "/api/admin/*", "/_next/data/*"],
        external_apis=["Stripe", "Sanity", "Contentful", "Supabase", "Firebase", "Clerk", "Auth0"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Edge", description="Request enters Next.js edge/server", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="Server-to-Client", description="SSR props transmitted to client", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-DB", description="Prisma/ORM queries to database", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "SSR props containing sensitive server-side data",
            "API routes accessible without authentication",
            "Middleware bypass via URL edge cases",
            "Static file traversal via _next/static",
            "Source map exposure via .js.map files",
            "SSRF via Image component src parameter",
            "Server Actions without CSRF protection",
            "NextAuth callback URL open redirect",
            "Webpack chunk enumeration revealing page structure",
            "Environment variable leakage in JS bundles",
            "API route SSRF to internal services",
            "ISR cache poisoning",
        ],
        investigation_areas=[
            "Check SSR pages for sensitive data in server-rendered HTML/JSON",
            "Test all API routes for authentication requirements",
            "Try to bypass middleware via URL-encoded paths and trailing slashes",
            "Probe _next/static for directory traversal and source maps",
            "Check _next/data for preview/ISR payload data",
            "Test Image component for SSRF via malicious URLs",
            "Check Server Actions for CSRF protection",
            "Test NextAuth callback URLs for open redirect",
            "Check __NEXT_DATA__ script tag embedded in SSR HTML",
            "Verify ISR configuration to prevent unintended cache access",
            "Check for API route SSRF opportunities",
            "Test middleware missing on specific routes or HTTP methods",
        ],
        tags=["nextjs", "react", "ssr", "framework", "web"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "x-powered-by": "Next.js",
            "x-vercel-id": "pattern: [a-z0-9-]+",
            "x-nextjs-cache": "HIT|MISS|STALE",
        },
        cookies=["next-auth.session-token", "next-auth.callback-url", "__next_preview_data"],
        js_indicators=["__NEXT_DATA__", "__NEXT_LOADED_PAGES__", "next: {", "self.__next_"],
        file_indicators=["next.config.js", "next.config.mjs", "next-env.d.ts", "package.json", "tsconfig.json", "middleware.ts", "postcss.config.js", "tailwind.config.js"],
        directory_indicators=["/pages/", "/app/", "/components/", "/public/", "/styles/", "/api/", "/_next/"],
        server_signatures=["Next.js", "Vercel"],
        error_page_signatures=["Application error: a client-side exception has occurred", "500 - Internal Server Error", "404 - This page could not be found"],
        default_paths=["/", "/api", "/_next/static/", "/favicon.ico", "/robots.txt", "/sitemap.xml"],
        default_files=["next.config.js", "package.json", "tsconfig.json", ".env.local", "middleware.ts", "tailwind.config.js"],
        metadata_patterns={"generator": "Next.js", "next-version": "pattern: [0-9]+\\.[0-9]+\\.[0-9]+"},
        tags=["fingerprint", "nextjs", "react"],
    ),
    recon=ReconProfile(
        directories_to_check=["/_next/", "/_next/static/", "/_next/static/chunks/", "/_next/static/css/", "/_next/data/", "/public/", "/api/"],
        files_to_check=["next.config.js", "package.json", ".env.local", "middleware.ts", "tsconfig.json", "tailwind.config.js"],
        endpoints_to_scan=["/api/*", "/_next/static/*", "/_next/data/*", "/favicon.ico", "/robots.txt", "/sitemap.xml"],
        version_detection_paths=["/_next/static/chunks/", "/package.json"],
        debug_paths_to_check=["/_next/", "/api/debug", "/debug", "/_next/data/*"],
        admin_paths_to_check=["/admin", "/admin/*", "/dashboard"],
        tags=["recon", "nextjs", "react"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="SSR pages leak server-side data via getServerSideProps embedded in HTML",
            impact="Sensitive server data exposed in client-side HTML via __NEXT_DATA__",
            attack_scenario="View page source and inspect __NEXT_DATA__ script tag for leaked server props containing API keys or tokens",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="API routes without authentication allow unauthorized data access",
            impact="Unauthorized data access, data exfiltration, privilege escalation",
            attack_scenario="Access /api/admin/users or similar API endpoints directly without authentication headers",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Middleware bypass via URL encoding or trailing slash manipulation",
            impact="Bypass of authentication, authorization, or redirect middleware logic",
            attack_scenario="Access protected routes with URL-encoded characters or trailing slashes to skip middleware",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Next.js Image optimization SSRF via external image URL parameter",
            impact="Server-side request forgery to internal networks or cloud metadata endpoints",
            attack_scenario="Use image URL pointing to internal services (e.g., http://169.254.169.254/latest/meta-data/)",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Source map files expose original source code including API routes and logic",
            impact="Full application source code disclosure, API route discovery, business logic understanding",
            attack_scenario="Download _next/static/chunks/pages/*.js.map files and reverse to original TypeScript source",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(target_pack_name="react", relationship_type=KnowledgeRelationshipType.DEPENDS_ON, description="Next.js is a React framework", confidence="high"),
        KnowledgeRelationship(target_pack_name="nodejs", relationship_type=KnowledgeRelationshipType.RUNS_ON, description="Next.js runs on Node.js", confidence="high"),
        KnowledgeRelationship(target_pack_name="express", relationship_type=KnowledgeRelationshipType.COMPETES_WITH, description="Next.js API routes compete with Express.js", confidence="medium"),
        KnowledgeRelationship(target_pack_name="vercel", relationship_type=KnowledgeRelationshipType.DEPLOYED_ON, description="Next.js commonly deployed on Vercel", confidence="high"),
        KnowledgeRelationship(target_pack_name="postgresql", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="Next.js uses PostgreSQL via Prisma ORM", confidence="high"),
        KnowledgeRelationship(target_pack_name="prisma", relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH, description="Next.js commonly uses Prisma ORM", confidence="high"),
        KnowledgeRelationship(target_pack_name="docker", relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY, description="Next.js apps containerized with Docker", confidence="medium"),
        KnowledgeRelationship(target_pack_name="nuxt", relationship_type=KnowledgeRelationshipType.SIMILAR_TO, description="Next.js is the React equivalent of Nuxt.js for Vue", confidence="high"),
    ],
    dependencies=["Node.js", "React", "npm/yarn/pnpm"],
    related_packs=["react", "nodejs", "vercel", "prisma", "postgresql", "express", "nuxt", "docker"],
    workflow=[
        "1. Fingerprint Next.js via X-Powered-By header and __NEXT_DATA__ in page source",
        "2. Check page source for __NEXT_DATA__ script tag containing SSR props",
        "3. Enumerate all API routes under /api/ using common path lists",
        "4. Test API routes for authentication requirements",
        "5. Attempt middleware bypass via URL-encoded paths, trailing slashes, and double slashes",
        "6. Probe /_next/static/ for directory traversal and source map access",
        "7. Download and analyze .js.map files for source code disclosure",
        "8. Test Image component with external image URLs for SSRF",
        "9. Check /_next/data/ for ISR/preview data leaks",
        "10. Test Server Actions (POST) for CSRF protection",
        "11. Check NextAuth callback URLs for open redirect",
        "12. Inspect webpack chunk files for page structure enumeration",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="NEXTJS-01",
            category="Information Disclosure",
            description="Check SSR pages for sensitive data in __NEXT_DATA__ script tag",
            expected_result="No sensitive server-side data (API keys, tokens, database records) should be present in client HTML",
            tools=["browser DevTools", "curl"],
            references=["https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props"],
        ),
        ManualTestChecklistItem(
            step_id="NEXTJS-02",
            category="Authentication",
            description="Test API routes for missing authentication",
            expected_result="Protected API routes should require valid authentication",
            tools=["curl", "Burp Suite"],
            references=["https://nextjs.org/docs/pages/building-your-application/routing/api-routes"],
        ),
        ManualTestChecklistItem(
            step_id="NEXTJS-03",
            category="Middleware",
            description="Attempt middleware bypass via URL manipulation",
            expected_result="Middleware should execute consistently regardless of URL encoding or trailing slashes",
            tools=["curl", "custom scripts"],
            references=["https://nextjs.org/docs/app/building-your-application/routing/middleware"],
        ),
        ManualTestChecklistItem(
            step_id="NEXTJS-04",
            category="Path Traversal",
            description="Test /_next/static for directory traversal and source map exposure",
            expected_result="Directory traversal should be blocked; source maps should not be accessible in production",
            tools=["curl", "Burp Suite"],
            references=["https://nextjs.org/docs/pages/building-your-application/optimizing/static-assets"],
        ),
        ManualTestChecklistItem(
            step_id="NEXTJS-05",
            category="SSRF",
            description="Test next/image component for SSRF via src parameter",
            expected_result="External image URLs should be validated and restricted to allowed domains",
            tools=["custom scripts", "Burp Suite"],
            references=["https://nextjs.org/docs/pages/building-your-application/optimizing/images"],
        ),
    ],
    references=[
        {"title": "Next.js Documentation", "url": "https://nextjs.org/docs"},
        {"title": "Next.js Security Headers", "url": "https://nextjs.org/docs/app/api-reference/config/next-config-js/headers"},
        {"title": "OWASP React Security", "url": "https://cheatsheetseries.owasp.org/cheatsheets/React_Security_Cheat_Sheet.html"},
        {"title": "CVE Next.js Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Next.js"},
    ],
    cwe_ids=["CWE-200", "CWE-306", "CWE-918", "CWE-22", "CWE-352", "CWE-601", "CWE-79"],
    cve_ids=["CVE-2024-34351", "CVE-2024-23833", "CVE-2023-46293", "CVE-2022-33021", "CVE-2021-31200"],
    tags=["react", "nextjs", "web", "framework", "ssr", "typescript"],
)
