"""Node.js Knowledge Pack — base runtime for Express, NestJS, Fastify, and other Node.js frameworks."""

from deephunter.core.types import (
    AttackSurfaceEntry,
    BusinessLogicConcern,
    BugClass,
    ManualTestChecklistItem,
    TrustBoundary,
)
from deephunter.knowledge.packs.base import (
    AttackSurfaceProfile,
    FingerprintProfile,
    KnowledgePack,
    KnowledgePackCategory,
    KnowledgeRelationship,
    KnowledgeRelationshipType,
    ReconProfile,
    TechnologyComponentProfile,
    TechnologyProfile,
)

PACK = KnowledgePack(
    name="nodejs",
    version="1.0.0",
    category=KnowledgePackCategory.LANGUAGE,
    description="Node.js — prototype pollution, command injection, path traversal, prototype pollution in JSON body, eval() with user input, regex DoS, HTTP request smuggling, and npm package vulnerabilities.",
    technology=TechnologyProfile(
        name="Node.js",
        vendor="OpenJS Foundation",
        language="JavaScript/TypeScript",
        runtime="Node.js (V8 JavaScript engine)",
        description="Node.js is a JavaScript runtime built on the V8 engine that executes server-side JavaScript. Event-driven, non-blocking I/O model. Ships with npm, yarn, pnpm package managers. Supports CommonJS and ES modules.",
        common_aliases=["node", "node.js", "nodejs"],
        dependencies=["Node.js runtime", "npm/yarn/pnpm"],
        common_integrations=["Express", "Fastify", "NestJS", "Socket.io", "Mongoose", "Sequelize", "TypeORM", "Prisma", "ioredis"],
        architecture_description="Event loop with non-blocking I/O. Single-threaded event loop with worker threads for CPU-intensive tasks. Module system (require/module.exports or import/export). Streams for data processing.",
        request_lifecycle="HTTP request -> Event loop -> Router -> Middleware -> Handler -> Response (async/await or callbacks)",
        documentation_url="https://nodejs.org/en/docs/",
        tags=["nodejs", "javascript", "runtime", "server-side"],
    ),
    components=[
        TechnologyComponentProfile(
            name="npm/yarn/pnpm",
            description="Package managers for Node.js. Typosquatting, malicious packages, dependency confusion, and arbitrary code execution in install scripts.",
            security_relevance="high",
            common_vulnerabilities=["Malicious npm packages", "Dependency confusion attacks", "Typosquatting (await, expresss)", "Arbitrary code in postinstall scripts", "npm token theft for supply chain attacks"],
            investigation_priority=90,
            tags=["npm", "supply-chain", "packages"],
        ),
        TechnologyComponentProfile(
            name="Event Loop & Async",
            description="Node.js event loop with async/await, promises, callbacks. Unhandled promise rejections leak stack traces. Race conditions in async code.",
            security_relevance="medium",
            common_vulnerabilities=["Unhandled promise rejection crashes", "Race conditions in concurrent async operations", "Callback hell leading to error mishandling", "Async local storage context leaks"],
            investigation_priority=70,
            tags=["async", "event-loop", "promises"],
        ),
        TechnologyComponentProfile(
            name="vm/eval Sandbox",
            description="V8 sandbox for running untrusted JavaScript. vm module bypasses, prototype pollution in sandbox context.",
            security_relevance="high",
            common_vulnerabilities=["vm module sandbox escape", "Prototype pollution in eval() context", "Code injection via Function() constructor", "Sandbox context isolation bypass"],
            investigation_priority=95,
            tags=["sandbox", "eval", "rce"],
        ),
        TechnologyComponentProfile(
            name="Node.js Crypto Module",
            description="Built-in crypto for hashing, HMAC, encryption, signatures. Deprecated algorithms, weak random, timing attacks.",
            security_relevance="high",
            common_vulnerabilities=["Use of deprecated crypto algorithms", "Predictable random for tokens/secrets", "Timing attacks on HMAC comparison", "Hardcoded secrets in crypto operations"],
            investigation_priority=85,
            tags=["crypto", "random", "secrets"],
        ),
        TechnologyComponentProfile(
            name="File System Access (fs module)",
            description="fs module for reading/writing files. Path traversal, symlink attacks, race conditions (TOCTOU).",
            security_relevance="high",
            common_vulnerabilities=["Path traversal in file paths", "TOCTOU race conditions", "Symlink following attacks", "Arbitrary file read via user input", "Writing outside intended directory"],
            investigation_priority=85,
            tags=["filesystem", "path-traversal", "lfi"],
        ),
        TechnologyComponentProfile(
            name="Child Process (child_process)",
            description="Spawning OS processes via exec(), execSync(), spawn(), fork(). Command injection when shell option is enabled with user input.",
            security_relevance="critical",
            common_vulnerabilities=["Command injection via shell metacharacters", "Shell injection with shell: true option", "Argument injection", "Environment variable injection"],
            investigation_priority=99,
            tags=["rce", "command-injection", "os-command"],
        ),
        TechnologyComponentProfile(
            name="HTTP/HTTPS Client (fetch, axios, node-fetch)",
            description="Making outbound HTTP requests. SSRF via user-controlled URLs, credential leakage, response handling.",
            security_relevance="high",
            common_vulnerabilities=["SSRF via user-controlled URL", "DNS rebinding attacks", "HTTP request splitting", "Unintended credential leakage in headers", "Open redirect following"],
            investigation_priority=90,
            tags=["ssrf", "http-client", "network"],
        ),
        TechnologyComponentProfile(
            name="Package.json / node_modules",
            description="Application dependencies and scripts in package.json. Malicious install scripts, vulnerable transitive dependencies, .npmrc token exposure.",
            security_relevance="high",
            common_vulnerabilities=["Vulnerable dependencies (npm audit)", "Malicious postinstall scripts", ".npmrc with API token leakage", "npm token theft for supply chain attacks"],
            investigation_priority=80,
            tags=["dependencies", "supply-chain", "npm"],
        ),
        TechnologyComponentProfile(
            name="Prototype Pollution",
            description="JavaScript prototype chain pollution via __proto__, constructor.prototype, or Object merge operations. Global impact on all objects.",
            security_relevance="critical",
            common_vulnerabilities=["__proto__ pollution in parsed JSON", "constructor.prototype merge pollution", "Deep merge functions without prototype checks", "Pollution affecting hasOwnProperty checks"],
            investigation_priority=99,
            tags=["prototype-pollution", "auth-bypass", "rce"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="All HTTP Endpoints",
                description="Any route handler in a Node.js application",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/*",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="CLI Tools",
                description="Node.js command-line tools and scripts",
                protocol="CLI",
                method="ANY",
                path="/usr/local/bin/*",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.COMMAND_INJECTION.value, BugClass.RCE.value],
            ),
            AttackSurfaceEntry(
                name="WebSocket / Socket.io",
                description="Real-time bidirectional communication",
                protocol="WS/WSS",
                method="ANY",
                path="/*",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.XSS.value, BugClass.AUTH_BYPASS.value],
            ),
        ],
        endpoints=["/api/*", "/graphql", "/socket.io/*", "/health", "/metrics"],
        parameters=["id", "page", "limit", "q", "search", "filter", "token", "file", "path", "url", "callback", "json"],
        authentication=["JWT (jsonwebtoken)", "Session cookies (express-session)", "OAuth (Passport.js)", "API keys"],
        authorization=["Middleware-based", "Custom guards", "Role-based in application code"],
        storage=["MongoDB (Mongoose)", "PostgreSQL (Sequelize/TypeORM/Prisma)", "Redis (ioredis)", "MySQL"],
        background_jobs=["Bull (Redis)", "Agenda", "Bree", "node-cron"],
        queues=["Redis", "RabbitMQ", "AWS SQS", "BullMQ"],
        caches=["Redis (ioredis)", "node-cache", "Memcached"],
        admin_interfaces=["/admin", "/dashboard", "/manage"],
        internal_apis=["/internal/*", "/api/internal/*", "/admin/api/*"],
        external_apis=["Stripe", "Twilio", "SendGrid", "AWS APIs"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Node", description="HTTP request enters Node.js event loop", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="Node-to-DB", description="Node.js queries database", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Node-to-FS", description="Node.js reads/writes filesystem", direction="bidirectional", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Prototype pollution via JSON body parsing",
            "Command injection in child_process.exec/spawn",
            "Path traversal via user-controlled file paths",
            "SSRF via user-controlled URLs in fetch/axios",
            "Prototype pollution in merge/clone utilities",
            "Regex DoS (ReDoS) in route patterns or input validation",
            "HTTP request smuggling via malformed headers",
            "Type confusion in JavaScript comparisons",
            "Eval/code injection via Function() or vm",
            "Session hijacking via cookie tampering",
            "Template injection in template engines",
            "Hardcoded secrets in environment variables",
            "Vulnerable dependencies from npm packages",
        ],
        investigation_areas=[
            "Test JSON body parsing for prototype pollution (__proto__, constructor.prototype)",
            "Test child_process calls for command injection",
            "Check path traversal in fs module operations",
            "Probe HTTP client functions for SSRF",
            "Test prototype pollution in deep merge/deep clone utilities",
            "Check for ReDoS in regex patterns",
            "Test for HTTP request smuggling with malformed headers",
            "Check eval/Function/vm for sandbox escape",
            "Review package.json for vulnerable dependencies (npm audit)",
            "Test session management for hijacking",
            "Check for hardcoded secrets in environment",
            "Test template engines for SSTI",
        ],
        tags=["nodejs", "javascript", "language", "server-side"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Powered-By": "Express" or "Node.js",
            "Content-Type": "application/json",
        },
        cookies=["connect.sid", "session", "jwt"],
        js_indicators=["node", "require('express')", "module.exports", "process.env", "__dirname", "__filename"],
        file_indicators=["package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "node_modules", "server.js", "app.js", "index.js", ".env", ".npmrc"],
        directory_indicators=["/node_modules/", "/src/", "/routes/", "/controllers/", "/models/", "/middleware/", "/views/", "/public/"],
        server_signatures=["Node.js", "Express", "V8"],
        error_page_signatures=["TypeError: ", "ReferenceError: ", "SyntaxError: ", "Error: ", "at processTicksAndRejections", "at node:", "UnhandledPromiseRejection"],
        default_paths=["/", "/api", "/api/v1", "/health", "/metrics", "/package.json"],
        default_files=["package.json", "package-lock.json", "server.js", "app.js", "index.js", ".env", ".npmrc", "ecosystem.config.js", "Dockerfile", "docker-compose.yml"],
        metadata_patterns={"engine": "node", "node": "pattern: v[0-9]+\\.[0-9]+"},
        tags=["fingerprint", "nodejs", "language"],
    ),
    recon=ReconProfile(
        directories_to_check=["/node_modules/", "/src/", "/routes/", "/controllers/", "/models/", "/middleware/", "/public/", "/views/"],
        files_to_check=["package.json", "package-lock.json", ".env", ".env.example", "server.js", "app.js", ".npmrc", "ecosystem.config.js", "Dockerfile", "docker-compose.yml", "webpack.config.js"],
        endpoints_to_scan=["/api/*", "/health", "/metrics", "/graphql", "/.well-known/jwks.json"],
        version_detection_paths=["/package.json"],
        debug_paths_to_check=["/debug", "/__debug__", "/?debug=1", "/api/debug"],
        admin_paths_to_check=["/admin", "/dashboard", "/manage", "/admin/login"],
        tags=["recon", "nodejs", "javascript"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Prototype pollution via JSON body allows attackers to inject properties into Object.prototype, affecting all object operations",
            impact="Authentication bypass, privilege escalation, denial of service, RCE in some cases",
            attack_scenario="Send JSON body with '__proto__.isAdmin': true or 'constructor.prototype.isAdmin': true to pollute the global prototype chain",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Command injection in child_process.exec/spawn with shell option enabled",
            impact="Full OS-level command execution on the server",
            attack_scenario="Pass user input containing shell metacharacters (; | & ` $()) to exec() or spawn() with shell: true",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Path traversal in fs module operations allows arbitrary file read",
            impact="Sensitive file read (source code, credentials, SSH keys, .env)",
            attack_scenario="Use ../ sequences in file paths passed to fs.readFile or res.sendFile",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="SSRF via user-controlled URLs in fetch/axios/node-fetch",
            impact="Internal network access, credential theft from metadata services, port scanning",
            attack_scenario="Pass internal URLs (http://169.254.169.254, http://localhost:5432) to fetch()",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Regex DoS (ReDoS) via crafted input in vulnerable regex patterns",
            impact="Denial of service by exploiting exponential backtracking in regex",
            attack_scenario="Send input like 'aaaaaaaaaaaaaaaaa!' to a regex with catastrophic backtracking",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="express",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="Express.js is a Node.js framework",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="mongodb",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="Node.js commonly uses MongoDB via Mongoose",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="Node.js uses Redis for sessions and caching via ioredis",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="postgresql",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="Node.js uses PostgreSQL via Sequelize, pg, or Prisma",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="nginx",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Node.js applications are often behind Nginx reverse proxy",
            confidence="medium",
        ),
    ],
    dependencies=["Node.js", "npm/yarn/pnpm"],
    related_packs=["express", "nestjs", "fastapi", "mongodb", "redis", "postgresql", "graphql"],
    workflow=[
        "1. Identify Node.js via X-Powered-By header and package.json files",
        "2. Test JSON endpoints for prototype pollution (__proto__, constructor.prototype)",
        "3. Probe child_process calls for command injection",
        "4. Check file system operations for path traversal",
        "5. Test HTTP client functions for SSRF",
        "6. Review package.json for vulnerable dependencies",
        "7. Test regex patterns for ReDoS vulnerabilities",
        "8. Check for hardcoded secrets in .env files",
        "9. Probe for eval/Function/vm sandbox escape",
        "10. Test session management security",
        "11. Check for HTTP request smuggling in proxy configurations",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="NODEJS-01",
            category="Prototype Pollution",
            description="Test all JSON endpoints for prototype pollution",
            expected_result="The server must reject or sanitize __proto__, constructor.prototype, and similar prototype chain keys",
            tools=["Burp Suite", "custom scripts", "nodejs-prototype-pollution"],
            references=["https://portswigger.net/web-security/prototype-pollution"],
        ),
        ManualTestChecklistItem(
            step_id="NODEJS-02",
            category="Command Injection",
            description="Test child_process.exec and spawn for command injection",
            expected_result="User input must not reach shell execution without strict validation and sanitization",
            tools=["Burp Suite", "commix", "custom scripts"],
            references=["https://owasp.org/www-community/attacks/Command_Injection"],
        ),
        ManualTestChecklistItem(
            step_id="NODEJS-03",
            category="SSRF",
            description="Test fetch/axios/node-fetch for SSRF via user-controlled URLs",
            expected_result="URLs must be validated against an allowlist; internal IPs and metadata endpoints must be blocked",
            tools=["Burp Suite", "SSRFmap"],
            references=["https://owasp.org/www-community/attacks/Server_Side_Request_Forgery"],
        ),
        ManualTestChecklistItem(
            step_id="NODEJS-04",
            category="ReDoS",
            description="Test regex patterns for catastrophic backtracking",
            expected_result="Regex patterns must not have exponential backtracking on crafted input",
            tools=["Burp Suite", "regexploit", "custom scripts"],
            references=["https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service"],
        ),
        ManualTestChecklistItem(
            step_id="NODEJS-05",
            category="Dependencies",
            description="Check package.json for vulnerable dependencies (npm audit equivalent)",
            expected_result="All dependencies should be up-to-date with no known CVEs",
            tools=["npm audit", "snyk", "trivy"],
            references=["https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities"],
        ),
    ],
    references=[
        {"title": "Node.js Documentation", "url": "https://nodejs.org/en/docs/"},
        {"title": "Node.js Security Best Practices", "url": "https://nodejs.org/en/blog/security/security-best-practices/"},
        {"title": "OWASP Node.js Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Nodejs_Cheat_Sheet.html"},
        {"title": "Node.js Prototype Pollution", "url": "https://portswigger.net/web-security/prototype-pollution"},
        {"title": "CVE Node.js Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Node.js"},
    ],
    cwe_ids=["CWE-1321", "CWE-78", "CWE-22", "CWE-918", "CWE-94", "CWE-79", "CWE-400", "CWE-344", "CWE-287", "CWE-89"],
    cve_ids=["CVE-2024-29041", "CVE-2023-30557", "CVE-2023-30558", "CVE-2023-30559", "CVE-2022-21824", "CVE-2021-23364", "CVE-2020-8203", "CVE-2019-10794"],
    tags=["nodejs", "javascript", "language", "server-side"],
)