"""Nuxt.js knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="nuxt",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="Nuxt.js Vue — SSR data leakage, Universal mode API exposure, middleware bypass, static file enumeration.",
    technology=TechnologyProfile(
        name="Nuxt.js",
        vendor="Nuxt Labs",
        language="TypeScript/JavaScript",
        framework="Nuxt.js",
        runtime="Node.js (18+)",
        description="Nuxt.js is a Vue.js framework for building modern web applications with server-side rendering, static generation, and universal mode.",
        common_aliases=["nuxt", "nuxtjs", "nuxt-js"],
        dependencies=["Node.js", "Vue.js", "npm/yarn/pnpm"],
        common_integrations=["Vue.js", "Vite", "Pinia", "Vue Router", "Tailwind CSS", "Prisma", "Drizzle", "Supabase", "Auth.js", "PostgreSQL", "MongoDB"],
        architecture_description="Universal (SSR/SSG) Vue framework with file-based routing, auto-imports, and server engine (Nitro).",
        request_lifecycle="HTTP request -> Nitro server -> middleware -> page component -> asyncData/fetch -> server route -> Vue SSR render -> client hydration -> HTTP response",
        documentation_url="https://nuxt.com/docs",
        tags=["vue", "ssr", "ssg", "universal", "typescript"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Server Routes (Nitro)",
            description="API/server routes under /server/api/. Exposure of sensitive endpoints, SSRF, injection vulnerabilities.",
            security_relevance="high",
            common_vulnerabilities=["Unauthenticated server route access", "SSRF via server route outgoing requests", "Body parsing injection", "Server route parameter injection"],
            investigation_priority=90,
            tags=["api", "nitro", "server", "routes"],
        ),
        TechnologyComponentProfile(
            name="SSR / Universal Rendering",
            description="Vue components rendered on the server. Data leakage via asyncData/fetch, hydration mismatch, sensitive state exposure in HTML.",
            security_relevance="high",
            common_vulnerabilities=["Sensitive data injection in HTML via asyncData", "API keys leaked in rendered HTML", "State hydration attacks", "CSRF via Universal fetch calls"],
            investigation_priority=95,
            tags=["ssr", "asyncData", "hydration", "universal"],
        ),
        TechnologyComponentProfile(
            name="Middleware",
            description="Route middleware for auth, redirect, and guard logic. Middleware bypass via route manipulation.",
            security_relevance="high",
            common_vulnerabilities=["Middleware bypass via route path manipulation", "Missing middleware on dynamic routes", "Middleware logic errors", "._redirect handling bypass"],
            investigation_priority=85,
            tags=["middleware", "auth", "routing"],
        ),
        TechnologyComponentProfile(
            name="Static File Serving",
            description="Static assets in /public/ and compiled output in /.nuxt/. Directory scanning, source map exposure.",
            security_relevance="medium",
            common_vulnerabilities=["Static file enumeration via /_nuxt/", "Source map exposure (.js.map)", "Public directory file listing", "Webpack/Vite chunk enumeration"],
            investigation_priority=80,
            tags=["static", "assets", "public"],
        ),
        TechnologyComponentProfile(
            name="Auth.js (Nuxt Auth)",
            description="Authentication module for Nuxt. Session handling, OAuth callbacks, token management.",
            security_relevance="high",
            common_vulnerabilities=["OAuth callback URL hijacking", "Session token leakage", "JWT session tampering", "CSRF on auth callbacks"],
            investigation_priority=85,
            tags=["auth", "oauth", "sessions", "jwt"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Server Routes",
                description="API routes in /server/api/ handled by Nitro engine",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/api/{route}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="SSR Pages",
                description="Pages with asyncData or server-side fetching",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/{page}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.XSS.value],
            ),
            AttackSurfaceEntry(
                name="Static Assets",
                description="Public directory and compiled Nuxt assets",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/{asset_path}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.PATH_TRAVERSAL.value, BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/api/*", "/api/auth/*", "/_nuxt/*", "/public/*", "/favicon.ico", "/robots.txt", "/sitemap.xml"],
        parameters=["id", "page", "limit", "search", "q", "callback", "redirect"],
        authentication=["Auth.js (Nuxt Auth)", "Supabase Auth", "Clerk", "JWT tokens"],
        authorization=["Middleware guards", "Route-level role checks", "Server-side auth validation"],
        storage=["Local filesystem", "S3", "Cloud storage"],
        background_jobs=["Nitro tasks", "BullMQ", "Redis Queue"],
        queues=["Redis", "BullMQ"],
        caches=["Redis", "CDN cache", "Vite manifest cache"],
        admin_interfaces=["/admin", "/admin/*", "/dashboard"],
        internal_apis=["/api/internal/*", "/api/admin/*"],
        external_apis=["Stripe", "Supabase", "Contentful", "Sanity", "Auth0"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Nitro", description="Request enters Nitro server engine", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="Server-to-Client", description="SSR data transmitted to client via hydration", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-DB", description="Database queries from server routes", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "SSR data leakage via asyncData/fetch in rendered HTML",
            "Server route authentication bypass",
            "Middleware bypass via route path manipulation",
            "Static file enumeration via /_nuxt/ chunk files",
            "Source map exposure via .js.map files",
            "Auth.js callback URL manipulation",
            "Environment variable leakage in server routes",
            "CORS misconfiguration on server routes",
            "Universal fetch CSRF vulnerability",
            "Nitro task endpoint exposure",
            "Hydration state manipulation",
            "Route collision with /api/* and /_nuxt/*",
        ],
        investigation_areas=[
            "Check rendered page HTML for leaked asyncData state (window.__NUXT__)",
            "Test all server routes for authentication requirements",
            "Attempt middleware bypass via URL-encoded paths",
            "Probe /_nuxt/ for build file enumeration and source maps",
            "Check Auth.js callback URLs for open redirect",
            "Test server routes for SSRF to internal services",
            "Verify CORS headers on server route responses",
            "Check window.__NUXT__ script tag for sensitive data",
            "Inspect _nuxt chunk manifest for page enumeration",
            "Test file enumeration via /public/ directory",
            "Check Nitro task endpoints for unauthorized access",
            "Test route collision vulnerabilities",
        ],
        tags=["nuxt", "vue", "ssr", "framework", "web"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "x-powered-by": "Nuxt",
            "x-nitro": "pattern: [0-9]+\\.[0-9]+",
        },
        cookies=["nuxt-session", "authjs.session-token"],
        js_indicators=["window.__NUXT__", "__NUXT__", "nuxt-app", "useNuxtApp", "$nuxt"],
        file_indicators=["nuxt.config.ts", "nuxt.config.js", "package.json", "tsconfig.json", ".env", ".nuxt/", "nitro.config.ts"],
        directory_indicators=["/pages/", "/components/", "/composables/", "/server/", "/server/api/", "/public/", "/.nuxt/"],
        server_signatures=["Nuxt", "Nitro"],
        error_page_signatures=["Nuxt Error", "Page not found", "500 - Internal Server Error", "404 - Not Found"],
        default_paths=["/", "/api/*", "/_nuxt/", "/favicon.ico", "/robots.txt", "/sitemap.xml"],
        default_files=["nuxt.config.ts", "nuxt.config.js", "package.json", "tsconfig.json", ".env"],
        metadata_patterns={"generator": "Nuxt", "nuxt-version": "pattern: [0-9]+\\.[0-9]+\\.[0-9]+"},
        tags=["fingerprint", "nuxt", "vue"],
    ),
    recon=ReconProfile(
        directories_to_check=["/_nuxt/", "/_nuxt/builds/", "/_nuxt/static/", "/public/", "/server/", "/server/api/", "/.nuxt/"],
        files_to_check=["nuxt.config.ts", "nuxt.config.js", "package.json", ".env", "tsconfig.json", "nitro.config.ts"],
        endpoints_to_scan=["/api/*", "/_nuxt/*", "/robots.txt", "/favicon.ico", "/sitemap.xml"],
        version_detection_paths=["/package.json", "/_nuxt/"],
        debug_paths_to_check=["/_nuxt/", "/api/_debug", "/__nuxt_dev__", "/__webpack_hmr"],
        admin_paths_to_check=["/admin", "/admin/*", "/dashboard"],
        tags=["recon", "nuxt", "vue"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="SSR data leakage via window.__NUXT__ exposes server-side fetch results in client HTML",
            impact="Sensitive API responses, tokens, and user data exposed in page source",
            attack_scenario="View page source and extract data from window.__NUXT__ JSON embedded in HTML",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Server routes accessible without authentication expose backend logic",
            impact="Unauthorized access to database operations, file manipulation, or third-party API calls",
            attack_scenario="Access /api/users or similar server routes directly without session headers",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Middleware bypass via path manipulation allows access to protected routes",
            impact="Bypass of authentication and authorization middleware checks",
            attack_scenario="Access protected pages with URL encoding or path traversal in route",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Auth.js callback URL open redirect enables phishing attacks",
            impact="Session token theft via malicious OAuth callback redirect",
            attack_scenario="Craft malicious callback URL that redirects to attacker-controlled domain after OAuth flow",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Universal fetch performed on server side without proper origin validation",
            impact="Server-side request forgery via manipulated fetch URLs",
            attack_scenario="Inject malicious URLs into asyncData fetch calls that are executed server-side",
            complexity="medium",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(target_pack_name="vue", relationship_type=KnowledgeRelationshipType.DEPENDS_ON, description="Nuxt.js is built on Vue.js", confidence="high"),
        KnowledgeRelationship(target_pack_name="nodejs", relationship_type=KnowledgeRelationshipType.RUNS_ON, description="Nuxt.js runs on Node.js", confidence="high"),
        KnowledgeRelationship(target_pack_name="nextjs", relationship_type=KnowledgeRelationshipType.SIMILAR_TO, description="Nuxt.js is the Vue equivalent of Next.js for React", confidence="high"),
        KnowledgeRelationship(target_pack_name="postgresql", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="Nuxt uses PostgreSQL via Prisma/Drizzle", confidence="high"),
        KnowledgeRelationship(target_pack_name="prisma", relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH, description="Nuxt commonly integrates with Prisma ORM", confidence="high"),
        KnowledgeRelationship(target_pack_name="express", relationship_type=KnowledgeRelationshipType.COMPETES_WITH, description="Nuxt server routes compete with Express.js", confidence="medium"),
        KnowledgeRelationship(target_pack_name="docker", relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY, description="Nuxt apps containerized with Docker", confidence="medium"),
        KnowledgeRelationship(target_pack_name="vercel", relationship_type=KnowledgeRelationshipType.DEPLOYED_ON, description="Nuxt deployed on Vercel platform", confidence="medium"),
    ],
    dependencies=["Node.js", "Vue.js", "npm/yarn/pnpm"],
    related_packs=["vue", "nodejs", "nextjs", "postgresql", "prisma", "express", "docker", "vercel"],
    workflow=[
        "1. Fingerprint Nuxt via window.__NUXT__ in page source and X-Powered-By header",
        "2. Inspect page HTML for window.__NUXT__ containing server-side data",
        "3. Enumerate all server routes under /api/",
        "4. Test server routes for authentication requirements",
        "5. Attempt middleware bypass via URL-encoded paths and route manipulation",
        "6. Probe /_nuxt/ for build chunk enumeration and source maps",
        "7. Download and analyze .js.map files for source code disclosure",
        "8. Check Auth.js callback URLs for open redirect",
        "9. Test server routes for SSRF to internal services",
        "10. Check CORS headers on server route responses",
        "11. Test route collision between /api/* and page routes",
        "12. Check for Nitro task endpoint exposure",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="NUXT-01",
            category="Information Disclosure",
            description="Check window.__NUXT__ in page source for leaked server-side data",
            expected_result="No sensitive server data (API keys, tokens, DB records) should appear in __NUXT__ JS object",
            tools=["browser DevTools", "curl"],
            references=["https://nuxt.com/docs/getting-started/data-fetching"],
        ),
        ManualTestChecklistItem(
            step_id="NUXT-02",
            category="Authentication",
            description="Test server routes for unauthenticated access",
            expected_result="Protected server routes should require valid authentication",
            tools=["curl", "Burp Suite"],
            references=["https://nuxt.com/docs/guide/directory-structure/server"],
        ),
        ManualTestChecklistItem(
            step_id="NUXT-03",
            category="Middleware",
            description="Test middleware bypass via URL manipulation",
            expected_result="Middleware should execute consistently for all route variations",
            tools=["curl", "custom scripts"],
            references=["https://nuxt.com/docs/guide/directory-structure/middleware"],
        ),
        ManualTestChecklistItem(
            step_id="NUXT-04",
            category="Static Files",
            description="Probe /_nuxt/ for build file enumeration",
            expected_result="Build files should not reveal sensitive information or be guessable",
            tools=["curl", "Burp Suite"],
            references=["https://nuxt.com/docs/guide/concepts/static-assets"],
        ),
        ManualTestChecklistItem(
            step_id="NUXT-05",
            category="SSRF",
            description="Test server routes for server-side request forgery",
            expected_result="Fetch requests should validate and restrict destination URLs",
            tools=["custom scripts"],
            references=["https://nuxt.com/docs/getting-started/data-fetching"],
        ),
    ],
    references=[
        {"title": "Nuxt.js Documentation", "url": "https://nuxt.com/docs"},
        {"title": "Nuxt Deployment Security", "url": "https://nuxt.com/deploy"},
        {"title": "OWASP Vue.js Security", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Vue_Security_Cheat_Sheet.html"},
        {"title": "CVE Nuxt.js Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Nuxt.js"},
    ],
    cwe_ids=["CWE-200", "CWE-306", "CWE-918", "CWE-22", "CWE-601", "CWE-79", "CWE-352"],
    cve_ids=["CVE-2024-34352", "CVE-2023-47387", "CVE-2022-47411", "CVE-2021-29436"],
    tags=["vue", "nuxt", "web", "framework", "ssr", "typescript"],
)
