"""Phoenix knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="phoenix",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="Phoenix Elixir — LiveView websocket injection, Ecto SQL injection, CSRF token bypass.",
    technology=TechnologyProfile(
        name="Phoenix",
        vendor="Phoenix Framework (Chris McCord)",
        language="Elixir",
        framework="Phoenix",
        runtime="Erlang VM (BEAM)",
        description="Phoenix is a web framework for the Elixir programming language, leveraging the Erlang VM for fault-tolerance and real-time capabilities via LiveView.",
        common_aliases=["phoenix", "phoenix-framework"],
        dependencies=["Elixir", "Erlang/OTP", "mix", "hex"],
        common_integrations=["Ecto", "Phoenix LiveView", "Phoenix PubSub", "Phoenix Channels", "PostgreSQL", "Redis", "Absinthe GraphQL", "Phoenix LiveDashboard"],
        architecture_description="Server-rendered MVC framework with real-time support via WebSockets (LiveView, Channels). Actor-based concurrency on the BEAM VM.",
        request_lifecycle="HTTP request -> Phoenix Endpoint -> Router -> Pipeline -> Controller -> View -> Template -> HTTP response (or LiveView mount/update for WebSocket connections)",
        documentation_url="https://hexdocs.pm/phoenix/",
        tags=["elixir", "erlang", "beam", "realtime", "liveview"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Phoenix LiveView",
            description="Real-time web UI via WebSockets. LiveView websocket message injection, state manipulation, cross-connection data leaks.",
            security_relevance="high",
            common_vulnerabilities=["LiveView WebSocket message injection", "LiveView state manipulation via forged diffs", "Cross-connection session data leakage", "LiveView DoS via rapid updates"],
            investigation_priority=95,
            tags=["liveview", "websocket", "realtime"],
        ),
        TechnologyComponentProfile(
            name="Ecto ORM",
            description="Database wrapper and query generator for Elixir. SQL injection via raw SQL, fragment injection, unsafe query building.",
            security_relevance="high",
            common_vulnerabilities=["SQL injection via Ecto.Adapters.SQL.query!", "Fragment injection via Ecto.Query.API.fragment", "SQL injection in Repo.all/Repo.one with raw conditions", "N+1 query data leaks"],
            investigation_priority=90,
            tags=["ecto", "orm", "sql", "database"],
        ),
        TechnologyComponentProfile(
            name="Phoenix Channels",
            description="WebSocket channels for real-time bidirectional communication. Channel topic enumeration, unauthorized subscription, message injection.",
            security_relevance="high",
            common_vulnerabilities=["Channel topic enumeration", "Unauthorized channel subscription", "Channel message injection", "Channel state leaking across rooms"],
            investigation_priority=85,
            tags=["channels", "websocket", "pubsub"],
        ),
        TechnologyComponentProfile(
            name="CSRF Protection",
            description="Built-in CSRF token validation via Plug.CSRFProtection. Token bypass via HTTPS downgrade, missing SameSite cookie, token reuse.",
            security_relevance="high",
            common_vulnerabilities=["CSRF token bypass via HTTPS->HTTP downgrade", "CSRF token reuse vulnerability", "Missing CSRF protection on API endpoints", "SameSite cookie misconfiguration"],
            investigation_priority=85,
            tags=["csrf", "protection", "plug"],
        ),
        TechnologyComponentProfile(
            name="Phoenix Router & Pipelines",
            description="Router with pipeline macros for plug composition. Pipeline bypass via route ordering, missing authentication plugs.",
            security_relevance="high",
            common_vulnerabilities=["Pipeline bypass via route ordering", "Missing :auth plug on routes", "Router scope leakage", "Non-RESTful method override in routes"],
            investigation_priority=80,
            tags=["router", "pipeline", "plugs"],
        ),
        TechnologyComponentProfile(
            name="Phoenix LiveDashboard",
            description="Real-time dashboard for monitoring Phoenix applications. Unauthenticated access exposes system metrics and process information.",
            security_relevance="medium",
            common_vulnerabilities=["LiveDashboard without authentication", "Process information leakage", "System metrics exposure", "Distribution node enumeration"],
            investigation_priority=80,
            tags=["dashboard", "monitoring", "phoenix-live-dashboard"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="HTTP Routes",
                description="All routes defined in router.ex with pipeline macros",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{route}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="LiveView WebSocket",
                description="Phoenix LiveView WebSocket connections",
                protocol="WSS",
                method="ANY",
                path="/live",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Channel WebSocket",
                description="WebSocket channels for real-time features",
                protocol="WSS",
                method="ANY",
                path="/socket/{channel}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.IDOR.value, BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/", "/login", "/register", "/admin", "/live", "/socket/*", "/dashboard", "/api/*", "/graphql"],
        parameters=["_csrf_token", "id", "page", "q", "session_id", "channel"],
        authentication=["Phoenix.Token", "Session cookies", "LiveView mounts with assigns", "Basic auth"],
        authorization=["Plug-based auth pipelines", "Controller-level authorization", "LiveView mount authorization"],
        storage=["Local disk", "S3", "Cloud storage"],
        background_jobs=["Oban", "Exq", "Toniq"],
        queues=["Redis", "PG"],
        caches=["ETS (Erlang Term Storage)", "Redis"],
        admin_interfaces=["/admin", "/dashboard", "/live_dashboard"],
        internal_apis=["/api/internal/*", "/internal/*"],
        external_apis=["Stripe", "SendGrid", "Twilio"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Elixir", description="HTTP/WS request enters Phoenix Endpoint", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="Ecto queries to PostgreSQL", direction="outbound", sensitivity="high"),
            TrustBoundary(name="WS-to-LiveView", description="LiveView WebSocket state diffs", direction="bidirectional", sensitivity="high"),
        ],
        attack_surface_areas=[
            "LiveView WebSocket message injection",
            "Ecto SQL injection via fragment/raw queries",
            "CSRF token bypass on state-changing requests",
            "Channel topic enumeration and unauthorized subscription",
            "LiveDashboard unauthenticated access",
            "Router pipeline bypass via route ordering",
            "LiveView state manipulation via forged diffs",
            "Session cookie without secure flags",
            "Phoenix.Token static/weak secret",
            "Absinthe GraphQL introspection",
            "OTP node name enumeration",
            "Erlang cookie exposure",
        ],
        investigation_areas=[
            "Test LiveView WebSocket endpoints for message injection",
            "Check Ecto queries for raw SQL and fragment usage",
            "Verify CSRF token validation on all POST/PUT/DELETE",
            "Enumerate channel topics via WebSocket connections",
            "Check /dashboard and /live_dashboard for auth",
            "Test route pipeline ordering for auth bypass",
            "Check LiveView assigns for sensitive data leakage",
            "Verify session cookie HttpOnly, Secure, SameSite",
            "Check Phoenix.Token secret strength",
            "Test GraphQL endpoint for introspection",
            "Check .iex.exs and .erlang.cookie exposure",
            "Test for OTP distribution node access",
        ],
        tags=["phoenix", "elixir", "erlang", "framework", "web"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Powered-By": "Phoenix",
            "x-request-id": "pattern: [a-f0-9-]{36}",
        },
        cookies=["_phoenix_key", "_csrf_token", "_liveview_token"],
        js_indicators=["Phoenix", "liveSocket", "LiveSocket", "csrfToken", "live_view"],
        file_indicators=["mix.exs", "mix.lock", "config.exs", "router.ex", "endpoint.ex", "schema.ex", "phoenix.js", "phoenix_live_view.js", "Dockerfile", "docker-compose.yml"],
        directory_indicators=["/lib/", "/lib/app_web/", "/lib/app/", "/config/", "/priv/", "/priv/static/", "/test/"],
        server_signatures=["Phoenix", "Cowboy"],
        error_page_signatures=["Something went wrong", "Internal Server Error", "No route matches", "Phoenix.Router.NoRouteError", "Ecto.NoResultsError"],
        default_paths=["/", "/login", "/register", "/admin", "/live", "/socket", "/dashboard", "/api"],
        default_files=["mix.exs", "mix.lock", "config.exs", "Dockerfile", "docker-compose.yml"],
        metadata_patterns={"phoenix-version": "pattern: [0-9]+\\.[0-9]+\\.[0-9]+"},
        tags=["fingerprint", "phoenix", "elixir"],
    ),
    recon=ReconProfile(
        directories_to_check=["/live/", "/socket/", "/dashboard/", "/api/", "/admin/", "/priv/", "/priv/static/"],
        files_to_check=["mix.exs", "mix.lock", "config.exs", ".env", "Dockerfile", "docker-compose.yml"],
        endpoints_to_scan=["/", "/login", "/register", "/admin", "/live", "/socket", "/dashboard", "/api"],
        version_detection_paths=["/mix.exs", "/api"],
        debug_paths_to_check=["/live", "/dashboard", "/api/debug", "/live_dashboard"],
        admin_paths_to_check=["/admin", "/admin/*", "/dashboard", "/live_dashboard"],
        tags=["recon", "phoenix", "elixir"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="LiveView WebSocket message injection allows forged diffs to manipulate server state",
            impact="State manipulation, privilege escalation, cross-user data visibility",
            attack_scenario="Craft malicious LiveView diff messages to modify assigns or trigger unintended server callbacks",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Ecto SQL injection via Ecto.Query.API.fragment allows arbitrary SQL execution",
            impact="Database compromise, data exfiltration, authentication bypass",
            attack_scenario="Inject SQL payloads in fragment function arguments concatenated with user input",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="CSRF token validation can be bypassed via HTTPS to HTTP downgrade or missing SameSite cookie",
            impact="Cross-site request forgery on state-changing operations",
            attack_scenario="Submit cross-origin form with missing Origin/Referer headers targeting HTTP endpoints",
            complexity="low",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="Channel topic enumeration reveals available real-time rooms and their access patterns",
            impact="Unauthorized access to private channels and real-time data feeds",
            attack_scenario="Systematically join channel topics via WebSocket to discover valid channels",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="LiveDashboard unauthenticated exposes system metrics, ETS tables, and process information",
            impact="Information disclosure of system internals, OTP processes, and database connection pools",
            attack_scenario="Access /dashboard or /live_dashboard to view live system metrics and process tree",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(target_pack_name="elixir", relationship_type=KnowledgeRelationshipType.RUNS_ON, description="Phoenix runs on Elixir/Erlang VM", confidence="high"),
        KnowledgeRelationship(target_pack_name="ecto", relationship_type=KnowledgeRelationshipType.DEPENDS_ON, description="Phoenix uses Ecto ORM", confidence="high"),
        KnowledgeRelationship(target_pack_name="postgresql", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="Phoenix uses PostgreSQL via Ecto", confidence="high"),
        KnowledgeRelationship(target_pack_name="redis", relationship_type=KnowledgeRelationshipType.CACHES_WITH, description="Phoenix uses Redis for PubSub and caching", confidence="high"),
        KnowledgeRelationship(target_pack_name="absinthe", relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH, description="Phoenix GraphQL via Absinthe", confidence="medium"),
        KnowledgeRelationship(target_pack_name="graphql", relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH, description="Phoenix GraphQL integration with Absinthe", confidence="medium"),
        KnowledgeRelationship(target_pack_name="docker", relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY, description="Phoenix apps containerized with Docker", confidence="medium"),
        KnowledgeRelationship(target_pack_name="express", relationship_type=KnowledgeRelationshipType.COMPETES_WITH, description="Phoenix competes with Express.js for real-time apps", confidence="low"),
        KnowledgeRelationship(target_pack_name="rails", relationship_type=KnowledgeRelationshipType.SIMILAR_TO, description="Phoenix is similar to Ruby on Rails in philosophy", confidence="medium"),
    ],
    dependencies=["Elixir", "Erlang/OTP", "mix", "hex"],
    related_packs=["elixir", "ecto", "postgresql", "redis", "absinthe", "graphql", "rails", "docker"],
    workflow=[
        "1. Fingerprint Phoenix via _phoenix_key cookie and Cowboy server header",
        "2. Check LiveView WebSocket endpoint at /live for access",
        "3. Test LiveView for message injection via forged diffs",
        "4. Audit Ecto queries for fragment/raw SQL injection vectors",
        "5. Verify CSRF token validation on all state-changing requests",
        "6. Enumerate channel topics via WebSocket connections",
        "7. Check /dashboard and /live_dashboard for unauthenticated access",
        "8. Test router pipeline bypass via route ordering manipulation",
        "9. Check session cookie security attributes (HttpOnly, Secure, SameSite)",
        "10. Test GraphQL endpoint (if Absinthe) for introspection",
        "11. Check for .erlang.cookie file exposure",
        "12. Test for OTP distribution port exposure",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="PHOENIX-01",
            category="LiveView",
            description="Test LiveView WebSocket for message injection and state manipulation",
            expected_result="LiveView diffs should be validated to prevent forged state changes",
            tools=["browser DevTools", "custom scripts", "WebSocket client"],
            references=["https://hexdocs.pm/phoenix_live_view/security.html"],
        ),
        ManualTestChecklistItem(
            step_id="PHOENIX-02",
            category="SQL Injection",
            description="Test Ecto fragment and raw query usage for SQL injection",
            expected_result="User input in fragments should be parameterized, not concatenated",
            tools=["custom scripts", "manual review"],
            references=["https://hexdocs.pm/ecto/Ecto.Query.API.html#fragment/1"],
        ),
        ManualTestChecklistItem(
            step_id="PHOENIX-03",
            category="CSRF",
            description="Test CSRF token validation on POST/PUT/DELETE requests",
            expected_result="Requests without valid CSRF token should be rejected",
            tools=["Burp Suite", "curl"],
            references=["https://hexdocs.pm/phoenix/security.html#cross-site-request-forgery"],
        ),
        ManualTestChecklistItem(
            step_id="PHOENIX-04",
            category="Information Disclosure",
            description="Check /dashboard and /live_dashboard for unauthorized access",
            expected_result="LiveDashboard should require authentication in production",
            tools=["curl", "browser"],
            references=["https://hexdocs.pm/phoenix_live_dashboard/"],
        ),
        ManualTestChecklistItem(
            step_id="PHOENIX-05",
            category="WebSocket",
            description="Enumerate channel topics via WebSocket connections",
            expected_result="Channel topics should not be guessable and should require authorization",
            tools=["WebSocket client", "custom scripts"],
            references=["https://hexdocs.pm/phoenix/channels.html"],
        ),
    ],
    references=[
        {"title": "Phoenix Framework Documentation", "url": "https://hexdocs.pm/phoenix/"},
        {"title": "Phoenix LiveView Security", "url": "https://hexdocs.pm/phoenix_live_view/security.html"},
        {"title": "Phoenix Security Guide", "url": "https://hexdocs.pm/phoenix/security.html"},
        {"title": "Ecto Documentation", "url": "https://hexdocs.pm/ecto/"},
        {"title": "CVE Phoenix Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Phoenix+Framework"},
    ],
    cwe_ids=["CWE-89", "CWE-352", "CWE-200", "CWE-287", "CWE-306", "CWE-79", "CWE-94"],
    cve_ids=["CVE-2024-32479", "CVE-2023-49285", "CVE-2022-36222", "CVE-2021-32669", "CVE-2020-35713"],
    tags=["elixir", "phoenix", "web", "framework", "beam", "liveview"],
)
