"""Python Knowledge Pack — base runtime for Django, Flask, FastAPI, and other Python frameworks."""

from deephunter.core.types import (
    AttackSurfaceEntry,
    BusinessLogicConcern,
    BugClass,
    ManualTestChecklistItem,
    TrustBoundary,
)
from deephunter.knowledge.packs.base import (
    AttackSurfaceProfile,
    FingerprintProfile,
    KnowledgePack,
    KnowledgePackCategory,
    KnowledgeRelationship,
    KnowledgeRelationshipType,
    ReconProfile,
    TechnologyComponentProfile,
    TechnologyProfile,
)

PACK = KnowledgePack(
    name="python",
    version="1.0.0",
    category=KnowledgePackCategory.LANGUAGE,
    description="Python — pickle deserialization RCE, SSTI in Jinja2, YAML deserialization attacks, SQL injection, YAML unsafe load, pickle/rjob deserialization, template injection, unsafe redirects, and eval/code injection.",
    technology=TechnologyProfile(
        name="Python",
        vendor="Python Software Foundation",
        language="Python",
        runtime="CPython 3.x",
        description="Python is a high-level interpreted language. Used for web (Django, Flask, FastAPI), scripting, data processing, and AI. Dynamic typing with GIL. Rich package ecosystem via pip. Supports async via asyncio.",
        common_aliases=["python", "python3", "cpython", "pypy"],
        dependencies=["Python 3.x", "pip"],
        common_integrations=["Django", "Flask", "FastAPI", "Pydantic", "SQLAlchemy", "Celery", "Redis", "PostgreSQL"],
        architecture_description="Interpreted execution with CPython runtime. GIL limits true parallelism. Virtual environments for dependency isolation. Async/await for concurrency. Package management via pip and Poetry/PDMs.",
        request_lifecycle="HTTP request -> WSGI/ASGI server -> Python framework -> Route handler -> Template rendering -> Response",
        documentation_url="https://docs.python.org/3/",
        tags=["python", "language", "server-side", "scripting"],
    ),
    components=[
        TechnologyComponentProfile(
            name="pickle Serialization",
            description="Python's pickle module for object serialization. Unpickling untrusted data allows arbitrary code execution via malicious class __reduce__ methods.",
            security_relevance="critical",
            common_vulnerabilities=["Pickle RCE via __reduce__ in untrusted data", "pyYAML unsafe_load/unsafe_load_all", "marshal.loads on untrusted data", " shelve module with dbm backend"],
            investigation_priority=99,
            tags=["pickle", "deserialization", "rce"],
        ),
        TechnologyComponentProfile(
            name="pip/PyPI",
            description="Python package installer and PyPI repository. Typosquatting, malicious packages, dependency confusion, and arbitrary code in setup.py/post-install scripts.",
            security_relevance="high",
            common_vulnerabilities=["Typosquatting (apt-get, requestx)", "Malicious packages with setup.py scripts", "Dependency confusion", "Pypi token theft for supply chain attacks", "Compromised PyPI packages"],
            investigation_priority=90,
            tags=["pip", "pypi", "supply-chain"],
        ),
        TechnologyComponentProfile(
            name="eval/exec",
            description="Dynamic code execution in Python. eval() with user input allows arbitrary code execution. Dynamic importlib.import_module with user input.",
            security_relevance="critical",
            common_vulnerabilities=["Code injection via eval()", "Module injection via __import__", "Attribute traversal for arbitrary module access", "globals()/locals() exploitation"],
            investigation_priority=99,
            tags=["eval", "rce", "code-execution"],
        ),
        TechnologyComponentProfile(
            name="SQLAlchemy ORM",
            description="SQLAlchemy SQL expression language and ORM. SQL injection via raw SQL, ORM query injection, and unsafe string formatting.",
            security_relevance="high",
            common_vulnerabilities=["SQL injection via text() raw SQL", "SQLAlchemy SQL injection via .format()", "N+1 query data leaks", "ORM bypass for authorization checks"],
            investigation_priority=85,
            tags=["sql", "sqli", "orm"],
        ),
        TechnologyComponentProfile(
            name="Jinja2 Template Engine",
            description="Jinja2 templating used by Flask, Django, and standalone. SSTI via template environment configuration or user-controlled template paths.",
            security_relevance="critical",
            common_vulnerabilities=["SSTI via environment configuration", "SSTI in Flask via render_template_string", "XSS via mark_safe bypassing escaping", "Template path traversal"],
            investigation_priority=95,
            tags=["ssti", "jinja2", "templates", "xss"],
        ),
        TechnologyComponentProfile(
            name="Subprocess (subprocess module)",
            description="Running external OS commands from Python. shell=True with user input allows command injection.",
            security_relevance="critical",
            common_vulnerabilities=["Command injection with shell=True", "Argument injection with shell=False", "Environment variable injection", "Path injection in subprocess calls"],
            investigation_priority=99,
            tags=["command-injection", "rce", "subprocess"],
        ),
        TechnologyComponentProfile(
            name="YAML (PyYAML / ruamel.yaml)",
            description="YAML parsing and serialization. yaml.unsafe_load() executes Python objects from YAML, leading to RCE.",
            security_relevance="critical",
            common_vulnerabilities=["yaml.unsafe_load() RCE via !!python/object/apply", "YAML deserialization to arbitrary objects", "Remote code execution via malicious YAML", "YAML template injection"],
            investigation_priority=99,
            tags=["yaml", "deserialization", "rce"],
        ),
        TechnologyComponentProfile(
            name="HTTP Client (requests, httpx, urllib)",
            description="Making outbound HTTP requests. SSRF via user-controlled URLs, credential leakage, insecure redirects.",
            security_relevance="high",
            common_vulnerabilities=["SSRF via user-controlled URL", "HTTP redirection to internal services", "Credential leakage in Authorization header", "DNS rebinding attacks"],
            investigation_priority=90,
            tags=["ssrf", "http-client"],
        ),
        TechnologyComponentProfile(
            name="Cryptography (cryptography, pyopenssl)",
            description="Cryptographic operations in Python. Use of deprecated algorithms, weak random, hardcoded keys, and padding oracle attacks.",
            security_relevance="high",
            common_vulnerabilities=["Use of insecure cryptographic algorithms", "Hardcoded secrets in source or config", "Predictable random for tokens/secrets", "Padding oracle with custom crypto"],
            investigation_priority=85,
            tags=["crypto", "secrets", "random"],
        ),
        TechnologyComponentProfile(
            name="File Operations (open, os.path)",
            description="Reading/writing files and path manipulation. Path traversal, TOCTOU race conditions, and arbitrary file access.",
            security_relevance="high",
            common_vulnerabilities=["Path traversal in file operations", "TOCTOU race conditions", "Symbolic link attacks", "Arbitrary file read via path traversal"],
            investigation_priority=85,
            tags=["lfi", "path-traversal", "filesystem"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="WSGI/ASGI Endpoints",
                description="All routes in a Python web application served via WSGI (Gunicorn/uWSGI) or ASGI (Uvicorn/Hypercorn)",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/*",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="CLI Scripts",
                description="Python CLI tools invoked via cron, systemd, or web hooks",
                protocol="CLI",
                method="ANY",
                path="/usr/local/bin/*",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.COMMAND_INJECTION.value, BugClass.RCE.value],
            ),
        ],
        endpoints=["/*.py", "/api/*", "/health", "/metrics", "/docs", "/openapi.json"],
        parameters=["id", "page", "limit", "q", "search", "filter", "file", "path", "url", "data", "json", "yaml", "query"],
        authentication=["Session cookies", "JWT (PyJWT)", "HTTP Basic/Digest", "API keys"],
        authorization=["Decorator-based (e.g., @login_required)", "Middleware-based", "Custom permission classes"],
        storage=["PostgreSQL (psycopg2/SQLAlchemy)", "MySQL (mysql-connector)", "SQLite", "Redis", "MongoDB (pymongo)"],
        background_jobs=["Celery", "APScheduler", "RQ", " Dramatic"],
        queues=["Redis (Celery)", "RabbitMQ", "AWS SQS"],
        caches=["Redis", "Memcached", "dogpile.cache"],
        admin_interfaces=["/admin", "/manage", "/django-admin"],
        internal_apis=["/internal/*", "/api/internal/*"],
        external_apis=["Stripe", "Twilio", "AWS", "OpenAI"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Python", description="WSGI/ASGI server passes request to Python app", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="Python-to-DB", description="Python queries database", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Python-to-FS", description="Python reads/writes filesystem", direction="bidirectional", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Pickle deserialization RCE from untrusted data",
            "YAML unsafe_load() RCE via python/object/apply",
            "SSTI via Jinja2 render_template_string or environment config",
            "Command injection in subprocess.run with shell=True",
            "SQL injection via raw SQL text() or .format()",
            "Path traversal via user-controlled file paths",
            "SSRF via user-controlled URLs in requests/httpx",
            "Eval/code injection via eval/exec with user input",
            "Module injection via __import__ or importlib",
            "Hardcoded secrets in environment variables or config",
            "Cookie tampering with insecure signing",
            "XSS via mark_safe bypassing Jinja2 escaping",
            "Mass assignment via unsorted kwargs to model constructors",
        ],
        investigation_areas=[
            "Test pickle.loads() with untrusted data for RCE",
            "Test yaml.unsafe_load() for deserialization RCE",
            "Test render_template_string for SSTI",
            "Check subprocess.run calls for shell=True and user input",
            "Test SQLAlchemy text() raw SQL for injection",
            "Check path traversal in open() and os.path.join",
            "Test SSRF via requests/httpx with user-controlled URLs",
            "Test eval/exec for code injection",
            "Check for hardcoded secrets in environment",
            "Test template rendering for XSS",
            "Check pickle/cPickle usage with untrusted input",
            "Test YAML loading with user-controlled content",
        ],
        tags=["python", "language", "server-side"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "Gunicorn|uWSGI|Daphne|Uvicorn|Hypercorn",
            "Content-Type": "application/json",
        },
        cookies=["sessionid", "csrftoken", "jwt"],
        js_indicators=["python", "django", "flask", "fastapi", "import flask", "from django"],
        file_indicators=["requirements.txt", "pyproject.toml", "Pipfile", ".env", "manage.py", "app.py", "wsgi.py", "asgi.py", "__init__.py"],
        directory_indicators=["/app/", "/src/", "/venv/", "/env/", "/.git/", "/tests/", "/migrations/"],
        server_signatures=["Python", "gunicorn", "uwsgi", "uvicorn", "daphne", "Django", "Flask"],
        error_page_signatures=["Traceback (most recent call last)", "ImportError:", "ModuleNotFoundError:", "TypeError:", "ValueError:", "AttributeError:", "Exception happened during processing", "Django AssertionError"],
        default_paths=["/", "/admin", "/health", "/metrics", "/api/v1", "/docs", "/openapi.json", "/manage.py"],
        default_files=["requirements.txt", "pyproject.toml", "Pipfile", ".env", "manage.py", "app.py", "wsgi.py", "asgi.py", "setup.py"],
        metadata_patterns={"python": "pattern: Python/[0-9]\\.[0-9]+"},
        tags=["fingerprint", "python", "language"],
    ),
    recon=ReconProfile(
        directories_to_check=["/app/", "/src/", "/venv/", "/env/", "/.git/", "/tests/", "/migrations/", "/static/", "/media/"],
        files_to_check=["requirements.txt", "pyproject.toml", "Pipfile.lock", ".env", "manage.py", "app.py", "wsgi.py", "asgi.py", ".gitignore", "setup.py", "Dockerfile"],
        endpoints_to_scan=["/api/*", "/admin", "/health", "/metrics", "/docs", "/openapi.json"],
        version_detection_paths=["/requirements.txt", "/pyproject.toml", "/app.py"],
        debug_paths_to_check=["/debug", "/?debug=1", "/manage.py", "/__debug__"],
        admin_paths_to_check=["/admin", "/manage", "/django-admin", "/admin/login"],
        tags=["recon", "python", "language"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Unpickling untrusted data with pickle.loads() allows arbitrary code execution via __reduce__",
            impact="Full RCE on the server",
            attack_scenario="Create a Python object with malicious __reduce__ method that executes os.system(), pickle it, send to server",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="yaml.unsafe_load() deserializes arbitrary Python objects from YAML, enabling RCE",
            impact="RCE via YAML deserialization",
            attack_scenario="Send YAML with !!python/object/apply:os.system [args] to trigger code execution",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="SSTI via render_template_string in Flask or Jinja2 environment configuration",
            impact="RCE via server-side template injection",
            attack_scenario="Inject {{ config.items() }} or {{ ''.__class__.__mro__[1].__subclasses__() }} to access server resources",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Command injection in subprocess.run/shell=True with user input",
            impact="Full OS command execution",
            attack_scenario="Pass user input with shell metacharacters (; | & $ `) to subprocess.run(cmd, shell=True)",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="SQL injection via raw SQL in SQLAlchemy text() or Python .format() in SQL queries",
            impact="Full database read/write, potentially RCE via xp_cmdshell",
            attack_scenario="Use text('SELECT * FROM users WHERE id=' + user_input) to inject SQL",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="django",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="Django is a Python web framework",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="flask",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="Flask is a Python microframework",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="fastapi",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="FastAPI is a Python ASGI framework",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="postgresql",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="Python applications commonly use PostgreSQL via psycopg2 or SQLAlchemy",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="Python uses Redis for caching and Celery broker",
            confidence="medium",
        ),
    ],
    dependencies=["Python 3.x", "pip", "virtualenv/venv"],
    related_packs=["django", "flask", "fastapi", "postgresql", "redis", "mongodb"],
    workflow=[
        "1. Identify Python via Server header (Gunicorn/uWSGI) and .py file extensions",
        "2. Test pickle.unserialize() with untrusted data for RCE",
        "3. Probe yaml.unsafe_load() for YAML deserialization RCE",
        "4. Test render_template_string for SSTI in Flask/Jinja2",
        "5. Check subprocess.run for shell=True and user input",
        "6. Test SQLAlchemy text() raw SQL for injection",
        "7. Check path traversal in file open() operations",
        "8. Test SSRF via requests/httpx with user-controlled URLs",
        "9. Check for hardcoded secrets in environment variables",
        "10. Test eval/exec for code injection",
        "11. Review requirements.txt for vulnerable dependencies",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="PY-01",
            category="Deserialization",
            description="Test pickle.loads() and yaml.unsafe_load() with untrusted data",
            expected_result="Server must not unpickle or unsafe-load untrusted data; use yaml.safe_load() and JSON instead of pickle",
            tools=["pickletools", "Python RCE gadgets", "custom scripts"],
            references=["https://docs.python.org/3/library/pickle.html", "https://pyyaml.org/wiki/PyYAMLDocumentation"],
        ),
        ManualTestChecklistItem(
            step_id="PY-02",
            category="SSTI",
            description="Test Jinja2 template rendering for SSTI",
            expected_result="Templates must not render user input directly; use autoescape and sandbox",
            tools=["Jinja2 SSTI payloads", "TplMap", "custom scripts"],
            references=["https://jinja.palletsprojects.com/en/3.1.x/templates/"],
        ),
        ManualTestChecklistItem(
            step_id="PY-03",
            category="Command Injection",
            description="Test subprocess.run calls for command injection",
            expected_result="User input must not reach shell=True subprocess calls; use shell=False with list args",
            tools=["Burp Suite", "commix", "custom scripts"],
            references=["https://docs.python.org/3/library/subprocess.html"],
        ),
        ManualTestChecklistItem(
            step_id="PY-04",
            category="SQL Injection",
            description="Test SQLAlchemy text() raw SQL for injection",
            expected_result="Use parameterized queries; avoid string interpolation in SQL",
            tools=["SQLMap", "custom scripts", "Burp Suite"],
            references=["https://docs.sqlalchemy.org/en/20/core/sqlelement.html"],
        ),
        ManualTestChecklistItem(
            step_id="PY-05",
            category="SSRF",
            description="Test requests/httpx for SSRF via user-controlled URLs",
            expected_result="URLs must be validated against allowlist; internal IPs must be blocked",
            tools=["Burp Suite", "SSRFmap"],
            references=["https://docs.python-requests.org/en/latest/"],
        ),
    ],
    references=[
        {"title": "Python Documentation", "url": "https://docs.python.org/3/"},
        {"title": "OWASP Python Security Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Python_Security_Cheat_Sheet.html"},
        {"title": "Python Security Wiki", "url": "https://pythonsecurity.readthedocs.io/"},
        {"title": "Python Deserialization Attacks", "url": "https://www.geeksforgeeks.org/python-pickle-vulnerability-and-its-malicious-exploitation/"},
        {"title": "CVE Python Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Python"},
    ],
    cwe_ids=["CWE-502", "CWE-78", "CWE-89", "CWE-94", "CWE-22", "CWE-79", "CWE-287", "CWE-918", "CWE-200", "CWE-344", "CWE-601"],
    cve_ids=["CVE-2020-26174", "CVE-2020-13254", "CVE-2020-5934", "CVE-2019-20907", "CVE-2019-9740", "CVE-2018-1060", "CVE-2018-1061"],
    tags=["python", "language", "server-side", "rce"],
)