"""Ruby on Rails knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="rails",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="Ruby on Rails — mass assignment via attr_accessible/bypass, YAML deserialization in ActiveRecord, CSRF token leakage, Sprockets/asset pipeline debug, SQL injection via find_by_sql.",
    technology=TechnologyProfile(
        name="Ruby on Rails",
        vendor="Rails Core Team (Basecamp)",
        language="Ruby",
        framework="Ruby on Rails",
        runtime="Ruby (CRuby/MRI, JRuby)",
        description="Ruby on Rails is a server-side MVC web application framework. Convention over configuration, Active Record ORM, Action View templating, and integrated testing.",
        common_aliases=["rails", "ror", "ruby-on-rails"],
        dependencies=["Ruby", "Bundler", "gem", "PostgreSQL/MySQL/SQLite", "Redis"],
        common_integrations=["PostgreSQL", "MySQL", "SQLite", "Redis", "Sidekiq", "Devise", "Paperclip/ActiveStorage", "RSpec", "Capybara", "Webpacker/Importmap"],
        architecture_description="MVC (Model-View-Controller) with RESTful routing, middleware stack (Rack), and asset pipeline (Sprockets/Propshaft).",
        request_lifecycle="Rack server -> middleware stack -> router -> controller action -> model (ActiveRecord) -> view template (ERB/Slim/Haml) -> HTTP response",
        documentation_url="https://guides.rubyonrails.org/",
        tags=["ruby", "mvc", "orm", "rack", "rest"],
    ),
    components=[
        TechnologyComponentProfile(
            name="ActiveRecord ORM",
            description="ORM layer for database interactions. SQL injection via find_by_sql, unsafe string interpolation in where(), YAML deserialization in serialized columns.",
            security_relevance="high",
            common_vulnerabilities=["SQL injection via find_by_sql", "SQL injection via string interpolation in where()", "YAML deserialization in serialized attributes", "N+1 query vector"],
            investigation_priority=90,
            tags=["orm", "sql", "serialization", "active-record"],
        ),
        TechnologyComponentProfile(
            name="Action View / ERB Templates",
            description="Template rendering engine. XSS via raw()/html_safe, partial path traversal, injection in render() calls.",
            security_relevance="high",
            common_vulnerabilities=["XSS via raw() or html_safe", "Path traversal in template rendering", "Injection via render inline:", "JSON escaping bypass"],
            investigation_priority=85,
            tags=["templates", "xss", "erb"],
        ),
        TechnologyComponentProfile(
            name="Devise / Authentication",
            description="Standard Rails authentication gem. User enumeration, session hijacking, rememberable token exposure.",
            security_relevance="high",
            common_vulnerabilities=["User enumeration via sign-in", "Rememberable token leakage in URLs", "Session fixation", "Weak password reset tokens"],
            investigation_priority=85,
            tags=["auth", "devise", "authentication"],
        ),
        TechnologyComponentProfile(
            name="Strong Parameters / Mass Assignment",
            description="Parameter sanitization for mass assignment. Bypass via permit! or incorrect permit() usage, nested attributes abuse.",
            security_relevance="high",
            common_vulnerabilities=["Mass assignment via nested attributes", "permit! allowing all parameters","admin flag setting", "Accepting nested params without strong parameters"],
            investigation_priority=90,
            tags=["mass-assignment", "strong-params", "sanitization"],
        ),
        TechnologyComponentProfile(
            name="Sprockets / Asset Pipeline",
            description="Asset pipeline for CSS/JS compilation. Debug mode in production exposing source maps, cached assets with sensitive comments.",
            security_relevance="medium",
            common_vulnerabilities=["Source map exposure via asset pipeline", "Cached asset disclosure", "Compiled asset secrets leakage"],
            investigation_priority=70,
            tags=["assets", "sprockets", "source-maps"],
        ),
        TechnologyComponentProfile(
            name="Rack Middleware",
            description="Rack-based middleware stack. Cookie tampering via signed/encrypted cookie stores, session deserialization.",
            security_relevance="medium",
            common_vulnerabilities=["Cookie deserialization (marshaled Ruby objects)", "Session cookie tampering", "Rack::Protection bypass"],
            investigation_priority=75,
            tags=["rack", "middleware", "cookies", "sessions"],
        ),
        TechnologyComponentProfile(
            name="Action Cable / WebSockets",
            description="WebSocket framework for real-time features. Unauthenticated channel subscription, channel ID enumeration.",
            security_relevance="medium",
            common_vulnerabilities=["Unauthenticated channel access", "Channel ID enumeration", "WebSocket CSRF (cross-origin WebSocket)"],
            investigation_priority=70,
            tags=["websockets", "realtime", "action-cable"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="REST Routes",
                description="All routes defined in config/routes.rb",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{controller}/{action}/{id}",
                parameters=["id", "format"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="API Endpoints",
                description="API routes under /api/v1/ or similar namespaces",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/api/{version}/{resource}",
                parameters=["page", "per_page", "q", "id"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.IDOR.value, BugClass.BUSINESS_LOGIC.value, BugClass.BROKEN_AUTH.value],
            ),
            AttackSurfaceEntry(
                name="ActiveStorage Uploads",
                description="Direct upload endpoints for file attachments",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/rails/active_storage/{endpoint}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.PATH_TRAVERSAL.value, BugClass.OTHER.value, BugClass.IDOR.value],
            ),
        ],
        endpoints=["/login", "/signup", "/users/sign_in", "/users/password", "/admin", "/api/*", "/rails/active_storage/*", "/assets/*", "/cable", "/sidekiq"],
        parameters=["utf8", "authenticity_token", "id", "user_id", "page", "per_page", "q", "file", "format"],
        authentication=["Devise session cookies", "JWT (_rails_jwt)", "API tokens", "HTTP Basic Auth", "OAuth (Doorkeeper)"],
        authorization=["Pundit policies", "CanCanCan abilities", "Role-based (rolify)", "ActionController authorization callbacks"],
        storage=["Local disk", "ActiveStorage S3/GCS/Azure", "Cloudinary", "Paperclip storage"],
        background_jobs=["Sidekiq", "Resque", "Delayed Job", "Good Job"],
        queues=["Redis", "RabbitMQ", "PostgreSQL (Good Job)"],
        caches=["Redis", "Memcached", "FileStore", "MemoryStore"],
        admin_interfaces=["/admin", "/admin/login", "/active_admin", "/rails_admin"],
        internal_apis=["/api/internal", "/api/private", "/api/v1/admin/*"],
        external_apis=["Stripe", "PayPal", "AWS", "SendGrid", "Twilio", "GitHub OAuth"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Rack", description="Request enters Rack middleware stack", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="ActiveRecord queries to database", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-Redis", description="Sidekiq and caching via Redis", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "Mass assignment via nested parameters",
            "SQL injection in find_by_sql and interpolated where()",
            "YAML deserialization in serialized ActiveRecord columns",
            "CSRF token leakage in URLs and headers",
            "Source map leakage via Sprockets asset pipeline",
            "ActiveStorage direct upload bypass",
            "Admin panel (ActiveAdmin/RailsAdmin) exposure",
            "Sidekiq dashboard without authentication",
            "Cookie session deserialization (marshal)",
            "Rememberable token exposure in authentication links",
            "User enumeration via Devise sign-in responses",
            "CORS misconfiguration on API endpoints",
        ],
        investigation_areas=[
            "Check all POST/PUT/PATCH endpoints for mass assignment vulnerabilities",
            "Audit all usages of find_by_sql and where() with string interpolation",
            "Check for serialize :attribute with YAML coder in models",
            "Verify CSRF token validation on state-changing requests",
            "Check config.assets.debug and config.assets.compile in production",
            "Test ActiveStorage direct upload endpoints for authorization",
            "Check Sidekiq/Rails Admin for authentication requirement",
            "Verify cookie store configuration (signed vs encrypted)",
            "Test user enumeration via Devise login responses",
            "Check CORS headers on API responses",
            "Verify session cookie HttpOnly, Secure, SameSite flags",
            "Inspect Gemfile for vulnerable gem versions",
        ],
        tags=["rails", "ruby", "framework", "web", "mvc"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Powered-By": "Phusion Passenger",
            "Server": "nginx/1.18.0 + Phusion Passenger",
            "Set-Cookie": "_session_id=",
            "Set-Cookie": "_rails_session=",
            "X-Frame-Options": "SAMEORIGIN",
            "X-XSS-Protection": "1; mode=block",
            "X-Content-Type-Options": "nosniff",
            "X-Request-Id": "pattern: [a-f0-9-]{36}",
            "X-Runtime": "pattern: [0-9.]+",
        },
        cookies=["_session_id", "_rails_session", "_app_session", "remember_token"],
        js_indicators=["Rails", "rails-ujs", "data-remote", "data-method", "csrf-token", "csrf-param"],
        file_indicators=["Gemfile", "Gemfile.lock", "config/routes.rb", "config/database.yml", "config/secrets.yml", "config/credentials.yml.enc", "Rakefile", "app/", "db/schema.rb", "package.json"],
        directory_indicators=["/app/", "/config/", "/db/", "/lib/", "/vendor/", "/app/assets/", "/app/views/", "/app/controllers/"],
        server_signatures=["Phusion Passenger", "WEBrick", "Puma", "Unicorn", "Thin"],
        error_page_signatures=["We're sorry, but something went wrong.", "ActionController::RoutingError", "ActiveRecord::RecordNotFound", "No route matches", "Routing Error"],
        default_paths=["/login", "/signup", "/users/sign_in", "/users/password", "/assets/application", "/rails/active_storage", "/cable", "/sidekiq", "/admin"],
        default_files=["Gemfile", "Gemfile.lock", "config/database.yml", "Rakefile", ".env", ".ruby-version", "package.json"],
        metadata_patterns={"csrf-param": "authenticity_token", "csrf-token": "pattern: [A-Za-z0-9+/=]{44}"},
        tags=["fingerprint", "rails", "ruby"],
    ),
    recon=ReconProfile(
        directories_to_check=["/assets/", "/packs/", "/uploads/", "/system/", "/storage/", "/app/", "/config/"],
        files_to_check=["Gemfile", "Gemfile.lock", "config/database.yml", "config/secrets.yml", "config/credentials.yml.enc", ".env", ".ruby-version", "Rakefile", "Procfile", "docker-compose.yml"],
        endpoints_to_scan=["/login", "/signup", "/users/sign_in", "/users/password", "/admin", "/rails/active_storage/*", "/cable", "/sidekiq", "/api/*"],
        version_detection_paths=["/assets/application-*.js", "/Gemfile.lock", "/rails/info/properties"],
        debug_paths_to_check=["/rails/info/routes", "/rails/info/properties", "/rails/info", "/_debug_", "/letter_opener"],
        admin_paths_to_check=["/admin", "/admin/login", "/active_admin", "/rails_admin", "/admin/dashboard"],
        tags=["recon", "rails", "ruby"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Mass assignment via nested attributes allows setting associated model attributes",
            impact="Privilege escalation, unauthorized model association modification",
            attack_scenario="Submit nested attributes for roles or permissions through accepts_nested_attributes_for",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="YAML deserialization in ActiveRecord serialized columns leads to RCE",
            impact="Remote code execution via crafted serialized data",
            attack_scenario="Inject YAML payload into a serialized column parameter that leverages Ruby YAML.load() behavior",
            complexity="high",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="User enumeration via Devise sign-in response differences",
            impact="Account enumeration enabling targeted attacks",
            attack_scenario="Compare error messages or response timing between existing and non-existing emails",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="ActiveRecord session store deserialization of marshaled Ruby objects",
            impact="Remote code execution via forged session cookie",
            attack_scenario="Craft a malicious marshaled Ruby object as the session cookie value",
            complexity="high",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Source map files from asset pipeline expose original JavaScript source",
            impact="Exposure of API keys, internal routes, and business logic embedded in JS",
            attack_scenario="Access .map files corresponding to compiled JS bundles",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="ruby",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="Rails runs on Ruby",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="postgresql",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="Rails defaults to PostgreSQL via ActiveRecord",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="Rails uses Redis for cache, sessions, and Sidekiq",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="sidekiq",
            relationship_type=KnowledgeRelationshipType.QUEUES_WITH,
            description="Rails uses Sidekiq for background job processing",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="jwt",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="Rails API authentication via JWT (devise-jwt)",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="oauth",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="Rails OAuth with Doorkeeper gem",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="nginx",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Rails application behind Nginx with Phusion Passenger",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Rails apps containerized via Docker",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="graphql",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Rails integrates with GraphQL via graphql-ruby",
            confidence="medium",
        ),
    ],
    dependencies=["Ruby", "Bundler", "PostgreSQL/MySQL/SQLite", "Redis"],
    related_packs=["ruby", "postgresql", "mysql", "redis", "sidekiq", "jwt", "oauth", "nginx", "docker"],
    workflow=[
        "1. Fingerprint Rails via _session_id cookie, X-Runtime header, and /rails/info/routes",
        "2. Check /rails/info/routes and /rails/info/properties for debug route exposure",
        "3. Test mass assignment on all POST/PUT endpoints with nested attributes",
        "4. Audit ActiveRecord queries for string interpolation in where() calls",
        "5. Check for YAML serialize columns in models and test deserialization payloads",
        "6. Verify CSRF authenticity_token validation on all state-changing requests",
        "7. Test Devise sign-in endpoints for user enumeration",
        "8. Check Sidekiq dashboard at /sidekiq for missing authentication",
        "9. Probe asset pipeline for source map files (*.js.map or *.css.map)",
        "10. Test ActiveStorage direct upload endpoints for authorization bypass",
        "11. Review cookie store configuration for marshal deserialization risk",
        "12. Check admin panels (ActiveAdmin, RailsAdmin) for unauthorized access",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="RAILS-01",
            category="Mass Assignment",
            description="Test mass assignment by adding unexpected nested attributes to POST/PUT requests",
            expected_result="Unexpected attributes should be rejected or raise ParameterMissing error",
            tools=["Burp Suite", "custom scripts"],
            references=["https://guides.rubyonrails.org/security.html#mass-assignment"],
        ),
        ManualTestChecklistItem(
            step_id="RAILS-02",
            category="SQL Injection",
            description="Test find_by_sql and unsafe where() string interpolation",
            expected_result="User inputs should be parameterized, not interpolated into SQL strings",
            tools=["sqlmap", "manual testing"],
            references=["https://guides.rubyonrails.org/security.html#sql-injection"],
        ),
        ManualTestChecklistItem(
            step_id="RAILS-03",
            category="Deserialization",
            description="Check for YAML/JSON serialized columns and test deserialization payloads",
            expected_result="Serialized columns should use safe deserialization, not YAML.load()",
            tools=["custom scripts"],
            references=["https://guides.rubyonrails.org/security.html#serialized-attributes"],
        ),
        ManualTestChecklistItem(
            step_id="RAILS-04",
            category="Information Disclosure",
            description="Check /rails/info/routes and source map files for sensitive info",
            expected_result="Debug routes and source maps should not be accessible in production",
            tools=["curl", "browser"],
            references=["https://guides.rubyonrails.org/security.html#default-headers"],
        ),
        ManualTestChecklistItem(
            step_id="RAILS-05",
            category="Authentication",
            description="Test Devise user enumeration via sign-in and password-reset responses",
            expected_result="Responses should be uniform for existing and non-existing accounts",
            tools=["Burp Suite"],
            references=["https://github.com/heartcombo/devise#security"],
        ),
    ],
    references=[
        {"title": "Ruby on Rails Security Guide", "url": "https://guides.rubyonrails.org/security.html"},
        {"title": "OWASP Rails Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Ruby_on_Rails_Cheat_Sheet.html"},
        {"title": "Rails Documentation", "url": "https://guides.rubyonrails.org/"},
        {"title": "Brakeman Static Analysis", "url": "https://brakemanscanner.org/"},
        {"title": "CVE Rails Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Ruby+on+Rails"},
    ],
    cwe_ids=["CWE-915", "CWE-89", "CWE-502", "CWE-352", "CWE-200", "CWE-79", "CWE-204", "CWE-22"],
    cve_ids=["CVE-2023-22799", "CVE-2023-22795", "CVE-2022-44566", "CVE-2022-32224", "CVE-2021-44528", "CVE-2020-8163", "CVE-2019-5420"],
    tags=["ruby", "rails", "web", "framework", "mvc", "orm"],
)
