"""Spring Boot knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="spring_boot",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="Spring Boot Java — actuator endpoints exposure, SpEL injection, JDBC deserialization, H2 console, Swagger/OpenAPI leak.",
    technology=TechnologyProfile(
        name="Spring Boot",
        vendor="VMware (Broadcom)",
        language="Java",
        framework="Spring Boot",
        runtime="JVM (Java 8+, GraalVM)",
        description="Spring Boot is an opinionated Java framework for building stand-alone, production-grade Spring-based applications with embedded servers.",
        common_aliases=["spring-boot", "springboot", "spring", "sb"],
        dependencies=["Java JDK", "Maven/Gradle", "Spring Framework", "Embedded Tomcat/Jetty/Undertow"],
        common_integrations=["Spring Data JPA", "Spring Security", "Spring MVC", "Spring Cloud", "Hibernate", "H2", "PostgreSQL", "MySQL", "Redis", "Kafka", "RabbitMQ"],
        architecture_description="Auto-configured Spring ApplicationContext with embedded servlet container, component scanning, and conditional bean configuration.",
        request_lifecycle="HTTP request -> embedded container -> DispatcherServlet -> HandlerMapping -> Controller -> Service -> Repository -> ResponseBody/ViewResolver -> HTTP response",
        documentation_url="https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/",
        tags=["java", "spring", "microservices", "jvm"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Spring Boot Actuator",
            description="Production-ready endpoints for monitoring and management. Exposes health, info, env, beans, mappings, and more.",
            security_relevance="high",
            common_vulnerabilities=["Actuator endpoint exposure (env, heapdump, metrics)", "Information disclosure via /actuator/env", "Heap dump containing secrets", "/actuator/health open access"],
            investigation_priority=95,
            tags=["actuator", "monitoring", "management"],
        ),
        TechnologyComponentProfile(
            name="Spring MVC / REST Controllers",
            description="Web MVC framework with REST support. Parameter binding attacks, SpEL injection, path traversal.",
            security_relevance="high",
            common_vulnerabilities=["SpEL injection in @Value", "Parameter binding via @RequestParam", "Path traversal in @PathVariable", "Mass assignment via @ModelAttribute"],
            investigation_priority=90,
            tags=["mvc", "rest", "controllers"],
        ),
        TechnologyComponentProfile(
            name="Spring Security",
            description="Authentication and authorization framework. Misconfigured security chains, missing CSRF protection, JWT issues.",
            security_relevance="high",
            common_vulnerabilities=["Missing CSRF protection", "Misconfigured security filter chain", "JWT token parsing vulnerabilities", "Role/authority mismatch", "Insecure HTTP basic auth"],
            investigation_priority=90,
            tags=["security", "auth", "jwt", "csrf"],
        ),
        TechnologyComponentProfile(
            name="H2 Console",
            description="In-memory database console accessible at /h2-console. Unauthenticated access allows SQL execution.",
            security_relevance="high",
            common_vulnerabilities=["Unauthenticated H2 console access", "SQL execution via JDBC URL manipulation", "RCE via H2 database init scripts"],
            investigation_priority=95,
            tags=["database", "console", "h2", "sql"],
        ),
        TechnologyComponentProfile(
            name="Swagger/OpenAPI",
            description="API documentation endpoints (Swagger UI, OpenAPI JSON/YAML). Endpoint information disclosure and API surface mapping.",
            security_relevance="medium",
            common_vulnerabilities=["Swagger UI access in production", "OpenAPI spec disclosure of all endpoints", "API key exposure in docs", "Endpoint details aiding attack planning"],
            investigation_priority=80,
            tags=["api", "documentation", "swagger", "openapi"],
        ),
        TechnologyComponentProfile(
            name="JDBC / JPA / Hibernate",
            description="Database access layer. SQL injection via JPQL/ Criteria API, deserialization vulnerability in JDBC drivers.",
            security_relevance="high",
            common_vulnerabilities=["SQL injection via native queries", "JDBC deserialization (H2, MySQL drivers)", "Hibernate injection via HQL", "Second-order injection"],
            investigation_priority=85,
            tags=["database", "jpa", "hibernate", "sql"],
        ),
        TechnologyComponentProfile(
            name="Spring Cloud Config",
            description="Externalized configuration management. Config server exposure, encrypted property key access.",
            security_relevance="medium",
            common_vulnerabilities=["Config server unauthenticated access", "Encrypted property key exposure", "Config file path traversal"],
            investigation_priority=75,
            tags=["cloud", "configuration", "config-server"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="REST Controllers",
                description="All @RequestMapping/@GetMapping/@PostMapping endpoints",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{endpoint}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="Actuator Endpoints",
                description="Spring Boot Actuator management endpoints",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/actuator/{endpoint}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="H2 Console",
                description="H2 database web console at /h2-console",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/h2-console",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.SQL_INJECTION.value, BugClass.RCE.value],
            ),
            AttackSurfaceEntry(
                name="Swagger UI",
                description="Swagger API documentation and testing interface",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/swagger-ui/{path}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/actuator", "/actuator/health", "/actuator/info", "/actuator/env", "/actuator/beans", "/actuator/mappings", "/actuator/heapdump", "/h2-console", "/swagger-ui.html", "/swagger-ui/", "/v3/api-docs", "/v2/api-docs"],
        parameters=["page", "size", "sort", "id", "search", "q", "access_token"],
        authentication=["Spring Security filter chain", "JWT (jjwt, nimbus)", "OAuth2 (Spring Security OAuth)", "HTTP Basic", "Session cookies (JSESSIONID)"],
        authorization=["Spring Security @PreAuthorize", "@Secured annotations", "Method security (hasRole, hasAuthority)", "AntMatchers in WebSecurityConfigurerAdapter"],
        storage=["Local disk", "S3 (AWS SDK)", "Cloud storage (GCS, Azure)"],
        background_jobs=["Spring @Async", "Spring Cloud Task", "Quartz Scheduler"],
        queues=["RabbitMQ", "Apache Kafka", "ActiveMQ", "Amazon SQS"],
        caches=["Redis (Spring Cache)", "Ehcache", "Caffeine", "Hazelcast"],
        admin_interfaces=["/actuator/*", "/admin/*", "/h2-console"],
        internal_apis=["/internal/*", "/api/internal/*", "/admin/api/*"],
        external_apis=["Stripe", "Twilio", "AWS APIs", "Google APIs"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Container", description="Request enters embedded Tomcat/Jetty/Undertow", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="JPA/Hibernate queries to database", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-MQ", description="Messages to RabbitMQ/Kafka", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "Actuator endpoint information disclosure",
            "H2 console unauthenticated access",
            "Swagger/OpenAPI specification exposure",
            "SpEL injection in controller parameters",
            "JDBC deserialization via driver protocol",
            "Spring Security filter chain misconfig",
            "JWT token parsing vulnerabilities",
            "CORS misconfiguration on API endpoints",
            "Heapdump containing credentials and secrets",
            "Framework-managed cookie session (JSESSIONID) attacks",
            "Spring Expression Language injection",
            "Insecure deserialization in messaging",
        ],
        investigation_areas=[
            "Probe /actuator, /actuator/env, /actuator/heapdump for information disclosure",
            "Check /h2-console accessibility and default credentials",
            "Access /swagger-ui.html and /v3/api-docs for API documentation",
            "Test for SpEL injection in URL parameters and request bodies",
            "Verify Spring Security filter chain configuration",
            "Check CORS headers on all endpoints",
            "Test for JWT algorithm confusion (none algorithm, RS256 -> HS256)",
            "Check for insecure deserialization in RabbitMQ/Kafka messages",
            "Verify CSRF protection is enabled for state-changing endpoints",
            "Check for missing authentication on actuator endpoints",
            "Test SQL injection in JPA native queries and @Query annotations",
            "Check Spring Cloud Config server for unauthenticated access",
        ],
        tags=["spring-boot", "java", "framework", "web", "microservices"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Application-Context": "pattern: application.*",
            "Set-Cookie": "JSESSIONID=",
            "X-Content-Type-Options": "nosniff",
            "X-XSS-Protection": "1; mode=block",
            "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",
        },
        cookies=["JSESSIONID", "SESSION"],
        js_indicators=["Spring Web MVC", "springBootVersion", "react.js (common pairing)"],
        file_indicators=["pom.xml", "build.gradle", "settings.gradle", "application.properties", "application.yml", "bootstrap.properties", "bootstrap.yml", "mvnw", "gradlew"],
        directory_indicators=["/WEB-INF/", "/META-INF/", "/BOOT-INF/", "/org/springframework/"],
        server_signatures=["Apache Tomcat", "Spring Boot", "Jetty", "Undertow"],
        error_page_signatures=["Whitelabel Error Page", "There was an unexpected error", "Spring Boot", "org.springframework.", "Type=Not Found", "status=404"],
        default_paths=["/actuator", "/actuator/health", "/actuator/info", "/h2-console", "/swagger-ui.html", "/swagger-ui/", "/v3/api-docs", "/v2/api-docs"],
        default_files=["pom.xml", "build.gradle", "application.properties", "application.yml", "bootstrap.yml", "mvnw", "gradlew", "Dockerfile"],
        metadata_patterns={"spring-boot-version": "pattern: [0-9]+\\.[0-9]+\\.[0-9]+", "java-version": "pattern: [0-9]+"},
        tags=["fingerprint", "spring-boot", "java"],
    ),
    recon=ReconProfile(
        directories_to_check=["/actuator/", "/h2-console/", "/swagger-ui/", "/WEB-INF/", "/META-INF/"],
        files_to_check=["pom.xml", "build.gradle", "application.properties", "application.yml", "bootstrap.yml", "Dockerfile", "mvnw", "gradlew"],
        endpoints_to_scan=["/actuator", "/actuator/health", "/actuator/info", "/actuator/env", "/actuator/beans", "/actuator/mappings", "/actuator/heapdump", "/h2-console", "/swagger-ui.html", "/v3/api-docs", "/v2/api-docs"],
        version_detection_paths=["/actuator/info", "/pom.xml", "/build.gradle"],
        debug_paths_to_check=["/actuator/", "/actuator/conditions", "/actuator/configprops", "/actuator/beans"],
        admin_paths_to_check=["/actuator", "/actuator/shutdown", "/admin", "/h2-console"],
        tags=["recon", "spring-boot", "java"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Spring Boot Actuator endpoints exposed without authentication reveal environment variables and configuration",
            impact="Exposure of database credentials, API keys, and application secrets",
            attack_scenario="Access /actuator/env to read all environment properties including passwords and API keys",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="H2 console available without authentication allows arbitrary SQL execution",
            impact="Database compromise via arbitrary SQL queries, potential RCE via JDBC URL manipulation",
            attack_scenario="Navigate to /h2-console, enter H2 JDBC URL, and execute arbitrary SQL statements",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Spring Expression Language (SpEL) injection allows expression evaluation via user input",
            impact="Remote code execution by injecting malicious SpEL expressions",
            attack_scenario="Inject #{T(java.lang.Runtime).getRuntime().exec('cmd')} into parameters evaluated with SpEL",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Heap dump file at /actuator/heapdump contains all runtime objects including secrets",
            impact="Complete exposure of in-memory secrets, tokens, and sensitive data",
            attack_scenario="Download /actuator/heapdump and analyze with Eclipse MAT to extract credentials and tokens",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Swagger/OpenAPI documentation exposes complete API surface including parameters and schemas",
            impact="Full API mapping aiding attack vector identification and parameter manipulation",
            attack_scenario="Access /v3/api-docs to obtain complete API specification and identify injection points",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="java",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="Spring Boot runs on JVM (Java)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="spring-framework",
            relationship_type=KnowledgeRelationshipType.DEPENDS_ON,
            description="Spring Boot is built on Spring Framework",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="postgresql",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="Spring Boot uses PostgreSQL via Spring Data JPA",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="h2",
            relationship_type=KnowledgeRelationshipType.STORES_DATA_IN,
            description="Spring Boot commonly uses H2 for development/testing",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="Spring Boot caches with Redis via Spring Cache",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="kafka",
            relationship_type=KnowledgeRelationshipType.QUEUES_WITH,
            description="Spring Boot integrates with Kafka via Spring Kafka",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="rabbitmq",
            relationship_type=KnowledgeRelationshipType.QUEUES_WITH,
            description="Spring Boot uses RabbitMQ via Spring AMQP",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Spring Boot apps containerized with Docker",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="kubernetes",
            relationship_type=KnowledgeRelationshipType.DEPLOYED_ON,
            description="Spring Boot deployed on Kubernetes with Spring Cloud Kubernetes",
            confidence="medium",
        ),
    ],
    dependencies=["Java JDK", "Maven/Gradle", "Spring Framework"],
    related_packs=["java", "spring-framework", "postgresql", "h2", "redis", "kafka", "rabbitmq", "docker", "kubernetes"],
    workflow=[
        "1. Fingerprint Spring Boot via X-Application-Context header and Whitelabel Error Page",
        "2. Probe /actuator endpoint list (/actuator, /actuator/health, /actuator/info)",
        "3. Check /actuator/env and /actuator/configprops for credential leaks",
        "4. Download and analyze /actuator/heapdump for sensitive data",
        "5. Check /h2-console for unauthenticated database access",
        "6. Access /swagger-ui.html or /v3/api-docs for API documentation",
        "7. Test for SpEL injection in controller parameters and request bodies",
        "8. Check JSESSIONID cookie security flags and session management",
        "9. Verify Spring Security filter chain for missing authentication on endpoints",
        "10. Test CORS headers for overly permissive configurations",
        "11. Check JWT token handling (algorithm confusion, missing validation)",
        "12. Test SQL injection in JPA @Query and native query methods",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="SPRING-01",
            category="Information Disclosure",
            description="Check actuator endpoints for sensitive data exposure",
            expected_result="Actuator endpoints should require authentication and not expose secrets",
            tools=["curl", "Burp Suite", "Spring Boot Actuator Scanner"],
            references=["https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html"],
        ),
        ManualTestChecklistItem(
            step_id="SPRING-02",
            category="Database Console",
            description="Check if H2 console is accessible at /h2-console",
            expected_result="H2 console should not be accessible in production environments",
            tools=["curl", "browser"],
            references=["https://www.h2database.com/html/quickstart.html"],
        ),
        ManualTestChecklistItem(
            step_id="SPRING-03",
            category="Injection",
            description="Test for SpEL injection in controller parameters and request bodies",
            expected_result="User input should not be evaluated as SpEL expressions",
            tools=["custom scripts", "Burp Suite"],
            references=["https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#expressions"],
        ),
        ManualTestChecklistItem(
            step_id="SPRING-04",
            category="API Documentation",
            description="Check Swagger UI and OpenAPI spec endpoint accessibility",
            expected_result="API documentation should be disabled or require authentication in production",
            tools=["curl", "browser"],
            references=["https://springdoc.org/"],
        ),
        ManualTestChecklistItem(
            step_id="SPRING-05",
            category="JWT Security",
            description="Test JWT token handling for algorithm confusion and missing validation",
            expected_result="JWT tokens should be validated with proper algorithm whitelisting",
            tools=["jwt_tool", "Burp Suite"],
            references=["https://portswigger.net/web-security/jwt"],
        ),
    ],
    references=[
        {"title": "Spring Boot Documentation", "url": "https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/"},
        {"title": "Spring Security Documentation", "url": "https://docs.spring.io/spring-security/reference/"},
        {"title": "OWASP Spring Boot Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Spring_Boot_Cheat_Sheet.html"},
        {"title": "CVE Spring Boot Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Spring+Boot"},
        {"title": "Spring Actuator Security", "url": "https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints"},
    ],
    cwe_ids=["CWE-200", "CWE-94", "CWE-502", "CWE-89", "CWE-306", "CWE-352", "CWE-79", "CWE-22"],
    cve_ids=["CVE-2024-38819", "CVE-2024-22262", "CVE-2023-34055", "CVE-2022-22978", "CVE-2022-22965", "CVE-2022-22947", "CVE-2021-22118", "CVE-2020-5421"],
    tags=["java", "spring-boot", "web", "framework", "microservices", "jvm"],
)
