"""Starlette Knowledge Pack — lightweight ASGI framework and foundation for FastAPI."""

from deephunter.core.types import (
    AttackSurfaceEntry,
    BusinessLogicConcern,
    BugClass,
    ManualTestChecklistItem,
    TrustBoundary,
)
from deephunter.knowledge.packs.base import (
    AttackSurfaceProfile,
    FingerprintProfile,
    KnowledgePack,
    KnowledgePackCategory,
    KnowledgeRelationship,
    KnowledgeRelationshipType,
    ReconProfile,
    TechnologyComponentProfile,
    TechnologyProfile,
)

PACK = KnowledgePack(
    name="starlette",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="Starlette ASGI framework — HTTP request smuggling via pipelining, path traversal in StaticFiles, SSRF via user-controlled URLs, template injection via Jinja2, and CORS misconfiguration.",
    technology=TechnologyProfile(
        name="Starlette",
        vendor="Encode",
        language="Python",
        runtime="Python 3.8+",
        description="Starlette is a lightweight ASGI framework/toolkit for building async Python web services. Provides request/response objects, routing, sessions, templates, and ORM integration. Used by FastAPI as its foundation.",
        common_aliases=["starlette", "fastapi"],
        dependencies=["Python 3.8+", "anyio", "httpx", "jinja2"],
        common_integrations=["FastAPI", "Uvicorn", "Hypercorn", "Databases", "SQLAlchemy", "Pydantic", "Starlette Sessions"],
        architecture_description="ASGI application with middleware stack. Fully async request/response cycle. WebSocket support, server-sent events, GraphQL integration. Route parameters with type hints.",
        request_lifecycle="ASGI server (Uvicorn) -> Starlette ASGI app -> Middleware stack -> Route matching -> Handler (async) -> Response",
        documentation_url="https://www.starlette.io/",
        tags=["python", "asgi", "async", "framework"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Request/Response Objects",
            description="Starlette request/response objects. Request data accessible via .query_params, .path_params, .body(), .json(). Response via JSONResponse, HTMLResponse.",
            security_relevance="medium",
            common_vulnerabilities=["Request smuggling via pipelined requests", "Large body DoS via unvalidated .stream()", "JSON parsing errors exposing stack traces"],
            investigation_priority=70,
            tags=["request", "response", "smuggling"],
        ),
        TechnologyComponentProfile(
            name="Routing & Path Parameters",
            description="Path parameter extraction with type hints. Regex route patterns. Route parameter injection if not validated.",
            security_relevance="medium",
            common_vulnerabilities=["Route parameter injection", "Regex DoS in route patterns", "Path traversal via unvalidated params"],
            investigation_priority=75,
            tags=["routing", "params", "regex"],
        ),
        TechnologyComponentProfile(
            name="Static Files (StaticFiles)",
            description="Serving static files from disk. Path traversal via malicious URLs, directory listing, and MIME type confusion.",
            security_relevance="high",
            common_vulnerabilities=["Directory traversal via ../ in URLs", "MIME type confusion attacks", "Serving sensitive files outside web root", "Path normalization issues"],
            investigation_priority=85,
            tags=["static-files", "path-traversal", "lfi"],
        ),
        TechnologyComponentProfile(
            name="Templates (Jinja2Templates)",
            description="Jinja2 template rendering. SSTI if template name or content is user-controlled. XSS via mark_safe bypassing autoescape.",
            security_relevance="critical",
            common_vulnerabilities=["SSTI via user-controlled template name", "XSS via mark_safe bypassing escaping", "Template path traversal"],
            investigation_priority=95,
            tags=["templates", "ssti", "xss", "jinja2"],
        ),
        TechnologyComponentProfile(
            name="Sessions",
            description="Signed cookie sessions. HMAC-based signing, insecure secret key, session fixation.",
            security_relevance="high",
            common_vulnerabilities=["Weak session signing secret", "Session forgery", "Session fixation attacks", "Insecure cookie flags"],
            investigation_priority=85,
            tags=["sessions", "cookies", "auth"],
        ),
        TechnologyComponentProfile(
            name="CORS Middleware",
            description="Cross-Origin Resource Sharing configuration. Wildcard origins with credentials, improper allowlist.",
            security_relevance="high",
            common_vulnerabilities=["CORS wildcard with credentials", "Allowing arbitrary origins", "Exposing credentials to foreign domains"],
            investigation_priority=80,
            tags=["cors", "xss", "csrf"],
        ),
        TechnologyComponentProfile(
            name="HTTP Client (httpx integration)",
            description="Outbound HTTP requests via Starlette's HTTP client integration. SSRF via user-controlled redirect URLs.",
            security_relevance="high",
            common_vulnerabilities=["SSRF via user-controlled URLs", "DNS rebinding attacks", "Following redirects to internal services"],
            investigation_priority=85,
            tags=["ssrf", "http-client"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="ASGI Endpoints",
                description="All routes registered with Starlette app",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/*",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
        ],
        endpoints=["/*"],
        parameters=["id", "page", "limit", "q", "search", "file", "path"],
        authentication=["JWT (via middleware)", "Session cookies", "API keys"],
        authorization=["Middleware-based", "Custom dependency injection"],
        storage=["PostgreSQL", "MySQL", "SQLite", "MongoDB", "Redis"],
        background_jobs=["Celery", "APScheduler"],
        queues=["Redis (Celery)", "RabbitMQ"],
        caches=["Redis", "Memcached"],
        admin_interfaces=["/admin/*"],
        internal_apis=["/internal/*"],
        external_apis=[],
        trust_boundaries=[
            TrustBoundary(name="ASGI-to-DB", description="Starlette app queries database", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Path traversal in StaticFiles",
            "SSTI via Jinja2 template name injection",
            "CORS misconfiguration",
            "Session forgery with weak secret",
            "SSRF via HTTP client",
            "HTTP request smuggling",
            "XSS via mark_safe bypassing autoescape",
        ],
        investigation_areas=[
            "Test StaticFiles for path traversal with ../ sequences",
            "Probe template rendering for SSTI via template name",
            "Check CORS configuration for wildcard with credentials",
            "Test session signing for weak secrets",
            "Test SSRF via HTTP client redirects",
            "Check for HTTP request smuggling in middleware",
        ],
        tags=["starlette", "python", "asgi", "framework"],
    ),
    fingerprints=FingerprintProfile(
        server_signatures=["starlette", "uvicorn", "hypercorn"],
        js_indicators=["python", "starlette", "fastapi", "uvicorn"],
        file_indicators=["requirements.txt", "app.py", "main.py", ".env"],
        error_page_signatures=["starlette", "uvicorn", "SyntaxError:", "ImportError:"],
        tags=["fingerprint", "starlette", "python"],
    ),
    recon=ReconProfile(
        files_to_check=["requirements.txt", "pyproject.toml", "app.py", "main.py", ".env"],
        tags=["recon", "starlette", "python"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="StaticFiles path traversal via ../ in URL allows reading arbitrary files outside web root",
            impact="Sensitive file read (source code, credentials, SSH keys, /etc/passwd)",
            attack_scenario="Request /static/../../../etc/passwd to read system files",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="SSTI via Jinja2 template name injection when template name is user-controlled",
            impact="Remote code execution via template injection",
            attack_scenario="Set template name to ../../templates/exploit to inject malicious Jinja2 code",
            complexity="medium",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="python",
            relationship_type=KnowledgeRelationshipType.RUNS_ON,
            description="Starlette is a Python ASGI framework",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="fastapi",
            relationship_type=KnowledgeRelationshipType.EXTENDS,
            description="FastAPI is built on top of Starlette",
            confidence="high",
        ),
    ],
    dependencies=["Python 3.8+", "anyio", "httpx", "jinja2"],
    related_packs=["python", "fastapi"],
    workflow=[
        "1. Identify Starlette/FastAPI via Server header and patterns",
        "2. Test StaticFiles for path traversal",
        "3. Check CORS configuration for wildcard origins with credentials",
        "4. Test session signing for weak secrets",
        "5. Probe template rendering for SSTI",
        "6. Test HTTP client redirects for SSRF",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="STAR-01",
            category="Path Traversal",
            description="Test StaticFiles for directory traversal",
            expected_result="StaticFiles must not serve files outside designated directory; normalize paths and reject ../",
            tools=["curl", "ffuf", "custom scripts"],
            references=["https://www.starlette.io/staticfiles/"],
        ),
        ManualTestChecklistItem(
            step_id="STAR-02",
            category="CORS",
            description="Check CORS middleware for wildcard with credentials",
            expected_result="CORS must not use wildcard origins with allow_credentials=True",
            tools=["curl", "browser DevTools"],
            references=["https://www.starlette.io/middleware/"],
        ),
    ],
    references=[
        {"title": "Starlette Documentation", "url": "https://www.starlette.io/"},
        {"title": "Starlette GitHub", "url": "https://github.com/encode/starlette"},
    ],
    cwe_ids=["CWE-22", "CWE-79", "CWE-287", "CWE-918", "CWE-352"],
    cve_ids=[],
    tags=["starlette", "python", "asgi", "framework"],
)