"""Symfony knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="symfony",
    version="1.0.0",
    category=KnowledgePackCategory.FRAMEWORK,
    description="Symfony PHP — profiler toolbar exposure, .env leakage, serializer deserialization.",
    technology=TechnologyProfile(
        name="Symfony",
        vendor="Symfony SAS",
        language="PHP",
        framework="Symfony",
        runtime="PHP 8.x",
        description="Symfony is a PHP framework for web applications and microservices, known for reusable components, Doctrine ORM, Twig templating, and the Symfony profiler.",
        common_aliases=["symfony", "symfony-php"],
        dependencies=["PHP", "Composer", "Doctrine ORM", "Twig", "MySQL/PostgreSQL"],
        common_integrations=["Doctrine", "Twig", "Monolog", "SwiftMailer/Mailer", "Redis", "RabbitMQ", "API Platform", "EasyAdmin", "Sonata Admin", "FOSRestBundle", "NelmioApiDoc"],
        architecture_description="Full-stack PHP framework with bundles, dependency injection (DI), event dispatcher, and HTTP kernel.",
        request_lifecycle="public/index.php -> Kernel -> EventDispatcher -> ControllerResolver -> Controller -> EventDispatcher -> Response",
        documentation_url="https://symfony.com/doc/current/",
        tags=["php", "mvc", "doctrine", "twig", "bundles"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Symfony Profiler / Debug Toolbar",
            description="Development toolbar with request details, SQL queries, memory usage, and configuration. Exposed in production reveals sensitive data.",
            security_relevance="high",
            common_vulnerabilities=["Profiler toolbar exposed in production", "SQL query log disclosure in toolbar", "Configuration parameters leak", "Route mapping exposure"],
            investigation_priority=95,
            tags=["profiler", "debug", "toolbar"],
        ),
        TechnologyComponentProfile(
            name="Twig Templating",
            description="Template engine with autoescaping. XSS via raw filter, SSTI via template injection, path traversal in includes.",
            security_relevance="high",
            common_vulnerabilities=["XSS via raw filter bypassing autoescape", "SSTI via rendered template injection", "Path traversal in {% include %} with user input", "Template caching poisoning"],
            investigation_priority=85,
            tags=["twig", "templates", "ssti", "xss"],
        ),
        TechnologyComponentProfile(
            name="Doctrine ORM / DBAL",
            description="Database abstraction and ORM. SQL injection via NativeQuery, DQL injection, second-order injection.",
            security_relevance="high",
            common_vulnerabilities=["SQL injection via NativeQuery with concatenation", "Doctrine DQL injection via user input", "Second-order SQL injection", "Mass assignment via entity hydration"],
            investigation_priority=85,
            tags=["doctrine", "orm", "sql", "entity"],
        ),
        TechnologyComponentProfile(
            name="Serializer Component",
            description="Object serialization/deserialization. Insecure deserialization via PHP serialization format, XML/JSON deserialization attacks.",
            security_relevance="high",
            common_vulnerabilities=["PHP deserialization via Symfony Serializer", "XML deserialization XXE vulnerability", "JSON deserialization object injection", "Type confusion via serialization groups"],
            investigation_priority=90,
            tags=["serializer", "deserialization", "serialize"],
        ),
        TechnologyComponentProfile(
            name=".env / Environment Configuration",
            description="Environment variable management via .env files. File exposure leading to credential leakage.",
            security_relevance="high",
            common_vulnerabilities=[".env file accessible via web root", "APP_SECRET disclosure", "Database credential leakage via .env", "Environment variable dump in profiler"],
            investigation_priority=90,
            tags=["env", "configuration", "secrets"],
        ),
        TechnologyComponentProfile(
            name="API Platform",
            description="REST/GraphQL API platform built on Symfony. Exposed API endpoints, schema leakage, parameter tampering.",
            security_relevance="high",
            common_vulnerabilities=["API endpoint enumeration without auth", "Schema/metadata exposure via /api/docs", "Mass assignment via API Platform denormalization", "GraphQL introspection enabled"],
            investigation_priority=85,
            tags=["api-platform", "rest", "graphql", "api"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="HTTP Routes",
                description="All routes defined in config/routes.yaml and controller annotations",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{route}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[b.value for b in BugClass],
            ),
            AttackSurfaceEntry(
                name="Profiler Debug Endpoints",
                description="Symfony profiler toolbar (loaded via _wdt and _profiler)",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/_profiler/{token}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="API Platform",
                description="API Platform resource endpoints",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/api/{resource}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.IDOR.value, BugClass.BUSINESS_LOGIC.value],
            ),
        ],
        endpoints=["/", "/login", "/admin", "/_profiler/*", "/_wdt/*", "/api/*", "/api/docs", "/api/doc", "/admin/*", "/logout", "/register"],
        parameters=["_token", "id", "page", "format", "sort", "order", "q", "search"],
        authentication=["Session cookies", "JWT (LexikJWTAuthenticationBundle)", "OAuth (HWIOAuthBundle)", "API keys (NelmioApiKeyBundle)"],
        authorization=["Voters (Symfony Security)", "Roles", "ACL", "IsGranted annotations", "Access control in security.yaml"],
        storage=["Local disk", "S3 (AWS SDK)", "GCS"],
        background_jobs=["Symfony Messenger", "Enqueue", "RabbitMQ"],
        queues=["RabbitMQ", "Redis", "Amazon SQS", "Doctrine (Messenger)"],
        caches=["Redis (PHP Redis)", "Memcached", "APCu", "File system"],
        admin_interfaces=["/admin", "/admin/*", "/sonata", "/easyadmin", "/admin/dashboard"],
        internal_apis=["/api/internal/*", "/internal/*"],
        external_apis=["Stripe", "PayPal", "Twilio", "SendGrid"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-Kernel", description="Request enters Symfony HTTP kernel", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="Doctrine queries to database", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-Cache", description="Cache operations to Redis/Memcached", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "Profiler toolbar accessible in production",
            ".env file exposed via web directory",
            "Serializer deserialization attack vector",
            "Doctrine NativeQuery SQL injection",
            "Twig SSTI via template injection",
            "API Platform mass assignment",
            "PHP deserialization via unserialize() calls",
            "XML external entity (XXE) in deserialization",
            "Route/method preflight bypass",
            "Voter authorization logic bypass",
            "Session fixation and hijacking",
            "Monolog log file exposure",
        ],
        investigation_areas=[
            "Check /_profiler/* and /_wdt/* for debug toolbar in production",
            "Probe .env and .env.local files for credential leakage",
            "Test serializer endpoints for insecure deserialization",
            "Audit Doctrine NativeQuery and DQL for injection vectors",
            "Check Twig templates for user-controlled template paths",
            "Test API Platform endpoints for mass assignment",
            "Check session cookie security flags (HttpOnly, Secure, SameSite)",
            "Test Voter authorization for bypass scenarios",
            "Check monolog log file location for exposure",
            "Verify security.yaml access control patterns",
            "Test for PHP deserialization via Symfony Serializer component",
            "Check EasyAdmin/Sonata Admin for authentication requirements",
        ],
        tags=["symfony", "php", "framework", "web"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Powered-By": "PHP",
            "X-Debug-Token": "pattern: [a-f0-9]+",
            "X-Debug-Token-Link": "pattern: /_profiler/[a-f0-9]+",
            "Set-Cookie": "PHPSESSID=",
            "Set-Cookie": "symfony=",
        },
        cookies=["PHPSESSID", "symfony", "REMEMBERME"],
        js_indicators=["Symfony", "sf-", "sf_admin", "sf_toolbar"],
        file_indicators=[".env", ".env.local", ".env.test", "composer.json", "composer.lock", "symfony.lock", "config/packages/", "src/Controller/", "src/Entity/", "src/Repository/", "Dockerfile"],
        directory_indicators=["/var/", "/var/cache/", "/var/log/", "/config/", "/src/", "/templates/", "/translations/", "/vendor/"],
        server_signatures=["Symfony", "PHP"],
        error_page_signatures=["Symfony\\Component\\HttpKernel\\Exception", "No route found", "NotFoundHttpException", "AccessDeniedException", "An exception occurred"],
        default_paths=["/", "/login", "/admin", "/_profiler", "/_wdt", "/api", "/api/docs"],
        default_files=[".env", ".env.local", "composer.json", "composer.lock", "Dockerfile", "phpunit.xml", ".gitignore"],
        metadata_patterns={"generator": "Symfony", "sf_version": "pattern: [0-9]+\\.[0-9]+\\.[0-9]+"},
        tags=["fingerprint", "symfony", "php"],
    ),
    recon=ReconProfile(
        directories_to_check=["/var/", "/var/log/", "/var/cache/", "/config/", "/templates/", "/translations/", "/vendor/", "/public/uploads/"],
        files_to_check=[".env", ".env.local", ".env.test", "composer.json", "composer.lock", "symfony.lock", "Dockerfile", "phpunit.xml"],
        endpoints_to_scan=["/", "/login", "/admin", "/_profiler/*", "/_wdt/*", "/api/*", "/api/docs"],
        version_detection_paths=["/composer.json", "/_profiler/", "/api/docs"],
        debug_paths_to_check=["/_profiler/*", "/_wdt/*", "/_error/*", "/__debug__"],
        admin_paths_to_check=["/admin", "/admin/*", "/sonata", "/easyadmin", "/admin/login", "/admin/dashboard"],
        tags=["recon", "symfony", "php"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Symfony profiler toolbar exposed in production reveals database queries, configuration, and request data",
            impact="Complete disclosure of SQL queries, parameters, configuration, and session data",
            attack_scenario="Access /_profiler/ URLs to view detailed request profiles including SQL logs and config parameters",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description=".env file accessible via web root exposes database credentials and APP_SECRET",
            impact="Full credential disclosure leading to database compromise and session signing",
            attack_scenario="Request /.env or /.env.local to read all environment variables and secrets",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Symfony Serializer PHP deserialization leads to RCE via gadget chains",
            impact="Remote code execution via crafted serialized payload",
            attack_scenario="Send PHP serialized object payload to endpoints using Symfony Serializer with PHP format",
            complexity="high",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="API Platform mass assignment allows setting restricted entity properties via API requests",
            impact="Privilege escalation, unauthorized data modification via denormalization groups",
            attack_scenario="Add unexpected entity fields to API Platform POST/PUT requests to modify restricted properties",
            complexity="medium",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="Monolog log files accessible via directory listing or predictable paths",
            impact="Log file disclosure containing user data, stack traces, and debug information",
            attack_scenario="Access /var/log/prod.log or /var/log/dev.log to read application logs",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(target_pack_name="php", relationship_type=KnowledgeRelationshipType.RUNS_ON, description="Symfony runs on PHP", confidence="high"),
        KnowledgeRelationship(target_pack_name="twig", relationship_type=KnowledgeRelationshipType.DEPENDS_ON, description="Symfony uses Twig templating", confidence="high"),
        KnowledgeRelationship(target_pack_name="doctrine", relationship_type=KnowledgeRelationshipType.DEPENDS_ON, description="Symfony uses Doctrine ORM/DBAL", confidence="high"),
        KnowledgeRelationship(target_pack_name="postgresql", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="Symfony uses PostgreSQL via Doctrine", confidence="high"),
        KnowledgeRelationship(target_pack_name="mysql", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="Symfony uses MySQL via Doctrine", confidence="high"),
        KnowledgeRelationship(target_pack_name="redis", relationship_type=KnowledgeRelationshipType.CACHES_WITH, description="Symfony caches with Redis", confidence="high"),
        KnowledgeRelationship(target_pack_name="nginx", relationship_type=KnowledgeRelationshipType.PROXIED_BY, description="Symfony behind Nginx proxy", confidence="high"),
        KnowledgeRelationship(target_pack_name="docker", relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY, description="Symfony apps containerized with Docker", confidence="medium"),
        KnowledgeRelationship(target_pack_name="laravel", relationship_type=KnowledgeRelationshipType.COMPETES_WITH, description="Symfony competes with Laravel as PHP framework", confidence="medium"),
    ],
    dependencies=["PHP", "Composer", "Doctrine ORM", "Twig"],
    related_packs=["php", "twig", "doctrine", "postgresql", "mysql", "redis", "nginx", "docker", "laravel"],
    workflow=[
        "1. Fingerprint Symfony via X-Debug-Token header and PHPSESSID cookie",
        "2. Check /_profiler/* and /_wdt/* for debug toolbar exposure",
        "3. Probe .env, .env.local files for credential leaks",
        "4. Test serializer endpoints for insecure deserialization payloads",
        "5. Audit Doctrine NativeQuery usage for SQL injection",
        "6. Check Twig templates for SSTI via {{ }} injection in user input",
        "7. Test API Platform endpoints for mass assignment via extra fields",
        "8. Check /api/docs for API schema leakage",
        "9. Test session cookie security flags (HttpOnly, Secure, SameSite)",
        "10. Verify security.yaml access control patterns for privilege escalation",
        "11. Check monolog log files at /var/log/ for exposure",
        "12. Test EasyAdmin/Sonata Admin for authentication bypass",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="SYMFONY-01",
            category="Information Disclosure",
            description="Check Symfony profiler toolbar accessibility via /_profiler/*",
            expected_result="Profiler URLs should return 404 or require authentication in production",
            tools=["curl", "Burp Suite"],
            references=["https://symfony.com/doc/current/profiler.html"],
        ),
        ManualTestChecklistItem(
            step_id="SYMFONY-02",
            category="Configuration",
            description="Check .env file accessibility via web root",
            expected_result=".env files should not be accessible via HTTP requests",
            tools=["curl", "Burp Suite"],
            references=["https://symfony.com/doc/current/configuration.html#the-env-file-environment-variables"],
        ),
        ManualTestChecklistItem(
            step_id="SYMFONY-03",
            category="Deserialization",
            description="Test Symfony Serializer for insecure deserialization",
            expected_result="Deserialization of untrusted data should be prevented or validated",
            tools=["PHPGGC", "custom scripts"],
            references=["https://symfony.com/doc/current/components/serializer.html"],
        ),
        ManualTestChecklistItem(
            step_id="SYMFONY-04",
            category="Mass Assignment",
            description="Test API Platform endpoints for mass assignment vulnerabilities",
            expected_result="Only allowed entity fields should be writable via API requests",
            tools=["Burp Suite", "custom scripts"],
            references=["https://api-platform.com/docs/core/serialization/"],
        ),
        ManualTestChecklistItem(
            step_id="SYMFONY-05",
            category="SQL Injection",
            description="Test Doctrine NativeQuery and DQL for injection vulnerabilities",
            expected_result="User input in queries must be parameterized",
            tools=["sqlmap", "custom scripts"],
            references=["https://www.doctrine-project.org/projects/doctrine-orm/en/current/reference/native-sql.html"],
        ),
    ],
    references=[
        {"title": "Symfony Documentation", "url": "https://symfony.com/doc/current/"},
        {"title": "Symfony Security", "url": "https://symfony.com/doc/current/security.html"},
        {"title": "OWASP Symfony Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Symfony_Cheat_Sheet.html"},
        {"title": "Symfony Serializer Component", "url": "https://symfony.com/doc/current/components/serializer.html"},
        {"title": "CVE Symfony Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Symfony"},
    ],
    cwe_ids=["CWE-200", "CWE-502", "CWE-89", "CWE-94", "CWE-79", "CWE-915", "CWE-22", "CWE-352"],
    cve_ids=["CVE-2024-28860", "CVE-2024-22329", "CVE-2023-46730", "CVE-2022-24894", "CVE-2021-36796", "CVE-2020-15079"],
    tags=["php", "symfony", "web", "framework", "mvc", "doctrine"],
)
