"""WordPress knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="wordpress",
    version="1.0.0",
    category=KnowledgePackCategory.CMS,
    description="WordPress CMS — XML-RPC, wp-json REST API, plugin/theme enumeration, debug.log, wp-config.php backups, user enumeration.",
    technology=TechnologyProfile(
        name="WordPress",
        vendor="WordPress Foundation (Automattic)",
        language="PHP",
        framework="WordPress",
        runtime="PHP 8.x",
        description="WordPress is the most popular CMS and web platform, powering over 40% of the web. Known for its plugin/theme ecosystem and block-based editor.",
        common_aliases=["wordpress", "wp"],
        dependencies=["PHP", "MySQL/MariaDB", "Apache/Nginx"],
        common_integrations=["MySQL", "MariaDB", "WooCommerce", "Yoast SEO", "Elementor", "ACF", "WP Rocket", "Redis", "Varnish", "Cloudflare"],
        architecture_description="Plugin and theme-based CMS with hook system (actions/filters), REST API, and WP-CLI.",
        request_lifecycle="HTTP request -> index.php -> wp-blog-header.php -> wp-load.php -> wp-config.php -> wp-settings.php -> template loader -> theme template -> response",
        documentation_url="https://developer.wordpress.org/",
        tags=["php", "cms", "blog", "plugins", "themes"],
    ),
    components=[
        TechnologyComponentProfile(
            name="WordPress REST API (wp-json)",
            description="JSON REST API introduced in WP 4.7. Exposes posts, users, comments, and plugin meta. User enumeration, data leakage, mass assignment.",
            security_relevance="high",
            common_vulnerabilities=["User enumeration via /wp-json/wp/v2/users", "Post content leakage via REST API", "Plugin meta endpoint data exposure", "Mass assignment via REST API requests"],
            investigation_priority=95,
            tags=["rest-api", "wp-json", "api"],
        ),
        TechnologyComponentProfile(
            name="XML-RPC",
            description="Legacy XML-RPC endpoint at /xmlrpc.php. Authentication brute-force, system.listMethods pingback DDoS, SSRF.",
            security_relevance="high",
            common_vulnerabilities=["XML-RPC brute-force via system.multicall", "Pingback SSRF vulnerability", "XML-RPC system.listMethods information leak", "Pingback port scanning"],
            investigation_priority=95,
            tags=["xmlrpc", "xml-rpc", "rpc"],
        ),
        TechnologyComponentProfile(
            name="Plugin & Theme System",
            description="Extensible via plugins and themes. Vulnerable plugins, outdated versions, nulled themes, and undisclosed vulnerabilities.",
            security_relevance="high",
            common_vulnerabilities=["Vulnerable plugin versions", "Outdated theme vulnerabilities", "Plugin/theme directory enumeration", "Plugin activation/deactivation via CSRF", "File inclusion via plugin paths"],
            investigation_priority=90,
            tags=["plugins", "themes", "extensions"],
        ),
        TechnologyComponentProfile(
            name="Authentication & User System",
            description="User management with roles, capabilities, and password hashing. User enumeration, weak password policy, privilege escalation.",
            security_relevance="high",
            common_vulnerabilities=["User enumeration via author archives", "User enumeration via REST API", "Privilege escalation via user role manipulation", "Password reset token prediction"],
            investigation_priority=90,
            tags=["auth", "users", "roles"],
        ),
        TechnologyComponentProfile(
            name="wp-config.php",
            description="Core configuration file containing database credentials, salts, and keys. File exposure leads to full database compromise.",
            security_relevance="critical",
            common_vulnerabilities=["wp-config.php backup exposure (.bak, .old, ~)", "Database credential leakage via wp-config", "Salt and key exposure", "Direct wp-config.php access via misconfiguration"],
            investigation_priority=99,
            tags=["config", "credentials", "secrets"],
        ),
        TechnologyComponentProfile(
            name="WordPress Admin (wp-admin)",
            description="Administration dashboard at /wp-admin. Brute-force, CSRF on admin actions, privileged function exposure.",
            security_relevance="high",
            common_vulnerabilities=["wp-admin brute-force login", "Admin AJAX action CSRF", "Media library file upload bypass", "Plugin activation/deactivation via AJAX"],
            investigation_priority=90,
            tags=["admin", "dashboard", "login"],
        ),
        TechnologyComponentProfile(
            name="Debug Log (debug.log)",
            description="Debug log file located at /wp-content/debug.log. PHP errors, warnings, database queries, and credential exposure.",
            security_relevance="high",
            common_vulnerabilities=["debug.log accessible via web", "PHP error messages exposing credentials", "Database query log leakage", "Stack trace disclosure"],
            investigation_priority=90,
            tags=["debug", "logs", "errors"],
        ),
        TechnologyComponentProfile(
            name="Cron System (wp-cron)",
            description="Virtual cron system for scheduled tasks. wp-cron DoS, malicious cron job registration, authentication bypass.",
            security_relevance="medium",
            common_vulnerabilities=["wp-cron.php DoS", "Unauthenticated cron job execution", "Cron job injection via plugin", "wp-cron.php resource exhaustion"],
            investigation_priority=65,
            tags=["cron", "scheduling"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="WordPress Frontend",
                description="Public pages and posts served by WordPress",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/{post_name}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.XSS.value, BugClass.SQL_INJECTION.value, BugClass.LFI.value],
            ),
            AttackSurfaceEntry(
                name="WP-Admin",
                description="WordPress administration dashboard at /wp-admin",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/wp-admin/{page}",
                parameters=[],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.PRIVILEGE_ESCALATION.value, BugClass.CSRF.value, BugClass.OTHER.value, BugClass.SQL_INJECTION.value],
            ),
            AttackSurfaceEntry(
                name="XML-RPC",
                description="XML-RPC API endpoint at /xmlrpc.php",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/xmlrpc.php",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.SSRF.value, BugClass.AUTH_BYPASS.value, BugClass.DOS.value],
            ),
            AttackSurfaceEntry(
                name="REST API",
                description="WordPress REST API at /wp-json/",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/wp-json/{namespace}/{route}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.IDOR.value, BugClass.BUSINESS_LOGIC.value],
            ),
        ],
        endpoints=["/wp-admin", "/wp-login.php", "/xmlrpc.php", "/wp-json/", "/wp-json/wp/v2/users", "/wp-json/wp/v2/posts", "/wp-content/", "/wp-includes/", "/wp-cron.php", "/readme.html", "/license.txt", "/wp-config.php.bak"],
        parameters=["s", "p", "page_id", "cat", "tag", "author", "m", "post_type", "rest_route", "action", "_wpnonce"],
        authentication=["WordPress cookies (wordpress_*, wordpress_logged_in_*)", "Application passwords", "OAuth (WPOAuth Server)"],
        authorization=["Roles and capabilities", "User levels", "Custom capability checks"],
        storage=["Local filesystem (wp-content/uploads)", "S3 (via plugin)", "CDN"],
        background_jobs=["WP-Cron", "Action Scheduler"],
        queues=["Action Scheduler (MySQL)"],
        caches=["Redis (via plugin)", "Varnish", "CDN", "Transients API"],
        admin_interfaces=["/wp-admin", "/wp-admin/admin.php", "/wp-admin/edit.php", "/wp-admin/post-new.php"],
        internal_apis=["/wp-json/wp/v2/*", "/wp-admin/admin-ajax.php"],
        external_apis=["Jetpack", "Akismet", "Stripe (WooCommerce)", "PayPal", "Google APIs"],
        trust_boundaries=[
            TrustBoundary(name="Web-to-WP", description="Request enters WordPress index.php", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="App-to-DB", description="WordPress queries to MySQL/MariaDB", direction="outbound", sensitivity="high"),
            TrustBoundary(name="App-to-Plugin", description="Plugin-internal API calls", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "XML-RPC brute-force and SSRF via pingback",
            "REST API user enumeration at /wp-json/wp/v2/users",
            "Plugin/theme version enumeration from readme.txt and style.css",
            "debug.log accessible at /wp-content/debug.log",
            "wp-config.php backup file exposure (.bak, .old, ~, .swp)",
            "User enumeration via author archives (/author/{id})",
            "Media library file upload unrestricted",
            "Cron job unauthorized execution via wp-cron.php",
            "Admin AJAX actions without authentication check",
            "Password reset token brute-force",
            "SQL injection in poorly coded plugins/themes",
            "XSS in post/page content and comment forms",
        ],
        investigation_areas=[
            "Check /xmlrpc.php with system.listMethods for enabled methods",
            "Call /wp-json/wp/v2/users to enumerate registered users",
            "Probe /wp-content/debug.log for PHP error logs",
            "Check /wp-config.php backup files (.bak, .old, .swp, ~)",
            "Enumerate plugin versions from readme.txt files",
            "Enumerate themes from /wp-content/themes/",
            "Check author archives for user enumeration",
            "Test /wp-login.php for user enumeration via error messages",
            "Check /wp-admin/admin-ajax.php for unauthenticated actions",
            "Check /readme.html for WordPress version disclosure",
            "Test media upload for unrestricted file types",
            "Check /wp-json/ for all registered REST routes",
            "Test for SQL injection via s parameter in search",
        ],
        tags=["wordpress", "cms", "php", "web"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "X-Powered-By": "PHP",
            "Link": 'rel="https://api.w.org/"',
            "Set-Cookie": "wordpress_",
            "Set-Cookie": "wordpress_logged_in_",
            "Set-Cookie": "wp-settings-",
        },
        cookies=["wordpress_*", "wordpress_logged_in_*", "wp-settings-*", "wp-settings-time-*"],
        js_indicators=["wp-includes", "wp-content", "wp-emoji", "wp-embed", "wp-api"],
        file_indicators=["wp-config.php", "wp-config.php.bak", ".htaccess", "readme.html", "license.txt", "wp-admin/", "wp-content/", "wp-includes/", "index.php", "xmlrpc.php", "wp-cron.php", "wp-login.php"],
        directory_indicators=["/wp-admin/", "/wp-content/", "/wp-content/plugins/", "/wp-content/themes/", "/wp-content/uploads/", "/wp-includes/"],
        server_signatures=["WordPress", "PHP"],
        error_page_signatures=["WordPress", "There has been a critical error on this website", "Error establishing a database connection", "WordPress database error"],
        default_paths=["/", "/wp-admin", "/wp-login.php", "/xmlrpc.php", "/wp-json/", "/wp-content/", "/wp-includes/", "/readme.html"],
        default_files=["readme.html", "license.txt", "wp-config.php", "xmlrpc.php", "wp-cron.php", "wp-login.php", "index.php", ".htaccess", "debug.log"],
        metadata_patterns={"generator": "WordPress", "wp-version": "pattern: [0-9]+\\.[0-9]+(\\.[0-9]+)?"},
        tags=["fingerprint", "wordpress", "cms"],
    ),
    recon=ReconProfile(
        directories_to_check=["/wp-content/", "/wp-content/plugins/", "/wp-content/themes/", "/wp-content/uploads/", "/wp-includes/", "/wp-admin/"],
        files_to_check=["readme.html", "license.txt", "wp-config.php", "wp-config.php.bak", "wp-config.php.old", "xmlrpc.php", "wp-cron.php", "wp-login.php", "debug.log", ".htaccess"],
        endpoints_to_scan=["/wp-json/", "/wp-json/wp/v2/users", "/wp-json/wp/v2/posts", "/xmlrpc.php", "/wp-admin", "/wp-login.php", "/readme.html"],
        version_detection_paths=["/readme.html", "/wp-json/", "/wp-admin/css/colors.min.css"],
        debug_paths_to_check=["/wp-content/debug.log", "/wp-content/error.log", "/wp-content/php_error.log"],
        admin_paths_to_check=["/wp-admin", "/wp-admin/admin.php", "/wp-admin/network/"],
        tags=["recon", "wordpress", "cms"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="WordPress user enumeration via REST API exposes all user IDs and usernames",
            impact="Username collection for targeted brute-force and password spraying attacks",
            attack_scenario="GET /wp-json/wp/v2/users returns list of all users with IDs, names, and avatars",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="XML-RPC pingback SSRF allows internal network scanning and DDoS amplification",
            impact="Server-side request forgery to internal services, port scanning, and distributed DoS attacks",
            attack_scenario="Use pingback system.multicall to send requests to internal IP addresses via crafted XML payloads",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="WordPress debug.log file accessible publicly reveals PHP errors and warnings",
            impact="Exposure of PHP errors containing database queries, table names, and potential credentials",
            attack_scenario="Access /wp-content/debug.log to read PHP error messages, deprecation warnings, and database query logs",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="WordPress author archive URL pattern allows user ID enumeration",
            impact="Username enumeration via sequential author IDs at /author/{username}/",
            attack_scenario="Visit /author/1, /author/2 etc. or /?author=1 to discover usernames",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="wp-config.php backup files expose database credentials, salts, and authentication keys",
            impact="Full database credential exposure leads to data breach and potential RCE via SQL",
            attack_scenario="Request wp-config.php.bak, wp-config.php.old, wp-config.php~, or .wp-config.php.swp",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(target_pack_name="php", relationship_type=KnowledgeRelationshipType.RUNS_ON, description="WordPress runs on PHP", confidence="high"),
        KnowledgeRelationship(target_pack_name="mysql", relationship_type=KnowledgeRelationshipType.STORES_DATA_IN, description="WordPress uses MySQL/MariaDB", confidence="high"),
        KnowledgeRelationship(target_pack_name="apache", relationship_type=KnowledgeRelationshipType.PROXIED_BY, description="WordPress commonly runs on Apache", confidence="high"),
        KnowledgeRelationship(target_pack_name="nginx", relationship_type=KnowledgeRelationshipType.PROXIED_BY, description="WordPress commonly runs on Nginx", confidence="high"),
        KnowledgeRelationship(target_pack_name="redis", relationship_type=KnowledgeRelationshipType.CACHES_WITH, description="WordPress caches with Redis via plugin", confidence="medium"),
        KnowledgeRelationship(target_pack_name="woocommerce", relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH, description="WordPress integrates with WooCommerce e-commerce", confidence="high"),
        KnowledgeRelationship(target_pack_name="docker", relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY, description="WordPress containerized with Docker", confidence="medium"),
        KnowledgeRelationship(target_pack_name="drupal", relationship_type=KnowledgeRelationshipType.COMPETES_WITH, description="WordPress competes with Drupal as CMS platform", confidence="medium"),
    ],
    dependencies=["PHP", "MySQL/MariaDB", "Apache/Nginx"],
    related_packs=["php", "mysql", "apache", "nginx", "redis", "woocommerce", "docker", "drupal"],
    workflow=[
        "1. Fingerprint WordPress via /readme.html, generator meta tag, and wp-json Link header",
        "2. Check /wp-json/wp/v2/users for user enumeration",
        "3. Probe /xmlrpc.php with system.listMethods to discover available methods",
        "4. Check /wp-content/debug.log for PHP error logs",
        "5. Look for wp-config.php backup files (.bak, .old, ~, .swp)",
        "6. Enumerate plugins from /wp-content/plugins/{plugin}/readme.txt",
        "7. Enumerate themes from /wp-content/themes/{theme}/style.css",
        "8. Test /wp-login.php for user enumeration via error messages",
        "9. Check author archives (/author/{id}/ or /?author={id})",
        "10. Test search functionality for SQL injection via s parameter",
        "11. Check /wp-admin/admin-ajax.php for unauthenticated AJAX actions",
        "12. Check for wp-cron.php unauthorized execution",
        "13. Test login form for brute-force protection",
        "14. Check for version disclosure in /readme.html",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="WP-01",
            category="Information Disclosure",
            description="Check /wp-json/wp/v2/users for user listing",
            expected_result="User endpoints should be restricted or disabled if users should not be public",
            tools=["curl", "browser"],
            references=["https://developer.wordpress.org/rest-api/reference/users/"],
        ),
        ManualTestChecklistItem(
            step_id="WP-02",
            category="XML-RPC",
            description="Check /xmlrpc.php for enabled methods and brute-force protection",
            expected_result="XML-RPC should be disabled or protected against brute-force via system.multicall",
            tools=["curl", "Burp Suite"],
            references=["https://wordpress.org/documentation/article/xml-rpc/"],
        ),
        ManualTestChecklistItem(
            step_id="WP-03",
            category="Debug Files",
            description="Check /wp-content/debug.log for error log exposure",
            expected_result="debug.log should not be accessible from the web",
            tools=["curl"],
            references=["https://wordpress.org/documentation/"],
        ),
        ManualTestChecklistItem(
            step_id="WP-04",
            category="Configuration Backups",
            description="Check for wp-config.php backup files (.bak, .old, ~)",
            expected_result="No backup files of wp-config.php should be accessible",
            tools=["curl", "Burp Suite"],
            references=["https://wordpress.org/documentation/article/editing-wp-config-php/"],
        ),
        ManualTestChecklistItem(
            step_id="WP-05",
            category="User Enumeration",
            description="Test for user enumeration via author archives and login errors",
            expected_result="Login errors should not reveal whether the username exists",
            tools=["curl", "Burp Suite"],
            references=["https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/03-Identity_Management_Testing/04-Test_for_Account_Enumeration_and_Guessable_User_Account"],
        ),
    ],
    references=[
        {"title": "WordPress Developer Documentation", "url": "https://developer.wordpress.org/"},
        {"title": "WordPress REST API", "url": "https://developer.wordpress.org/rest-api/"},
        {"title": "OWASP WordPress Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/WordPress_Security_Cheat_Sheet.html"},
        {"title": "WPScan Vulnerability Database", "url": "https://wpscan.com/"},
        {"title": "CVE WordPress Collection", "url": "https://www.cve.org/KeywordSearch?keyword=WordPress"},
    ],
    cwe_ids=["CWE-200", "CWE-287", "CWE-352", "CWE-89", "CWE-79", "CWE-22", "CWE-918", "CWE-204"],
    cve_ids=["CVE-2024-44000", "CVE-2024-27982", "CVE-2023-45156", "CVE-2022-35941", "CVE-2021-39200", "CVE-2020-28037"],
    tags=["php", "wordpress", "cms", "blog", "web"],
)
