"""GraphQL knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="graphql",
    version="1.0.0",
    category=KnowledgePackCategory.API,
    description="GraphQL API: introspection query, batching attacks, deep query nesting DoS, missing auth on mutations, N+1 injection, GraphiQL exposure, field suggestions.",
    technology=TechnologyProfile(
        name="GraphQL",
        vendor="GraphQL Foundation (Linux Foundation)",
        language="",
        runtime="",
        description="GraphQL is a query language for APIs and a runtime for executing those queries with existing data. Clients can request exactly the data they need, making APIs flexible and efficient.",
        common_aliases=["graphql", "gql", "graphql-api"],
        dependencies=[],
        common_integrations=["Apollo Server", "Apollo Client", "Relay", "GraphQL Yoga", "Hasura", "Postgraphile", "Prisma", "GraphQL Mesh", "urql"],
        architecture_description="Single HTTP endpoint (usually /graphql) that accepts POST requests with JSON bodies containing query, variables, and operationName fields. The server parses, validates, and executes queries against a schema.",
        request_lifecycle="HTTP POST -> /graphql endpoint -> parse query -> validate against schema -> execute resolvers -> return JSON response",
        documentation_url="https://graphql.org/",
        tags=["graphql", "api", "query-language", "runtime"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Introspection System",
            description="Built-in schema introspection via __schema and __type queries. Exposes all types, fields, arguments, and directives. Often left enabled in production.",
            security_relevance="high",
            common_vulnerabilities=["Full schema disclosure via introspection query", "Field suggestion leakage", "Type name enumeration", "Argument discovery for attacks"],
            investigation_priority=95,
            tags=["introspection", "schema", "disclosure"],
        ),
        TechnologyComponentProfile(
            name="GraphiQL IDE",
            description="Interactive in-browser GraphQL IDE. Provides query editor, schema documentation, and result panel. Often accessible at /graphiql or /graphql.",
            security_relevance="high",
            common_vulnerabilities=["Unauthenticated access to GraphiQL", "Interactive query execution", "Schema browsing by attackers", "Query history leakage"],
            investigation_priority=90,
            tags=["graphiql", "ide", "interactive"],
        ),
        TechnologyComponentProfile(
            name="Resolver Layer",
            description="Functions that resolve each field in a GraphQL query. Resolvers can introduce N+1 query problems, insecure data access, and business logic flaws.",
            security_relevance="high",
            common_vulnerabilities=["N+1 injection via deeply nested queries", "Insecure direct object references in resolvers", "Missing authorization at field level", "Resolver-level data leakage", "Batching attack exploitation"],
            investigation_priority=90,
            tags=["resolvers", "n-plus-one", "data-fetching"],
        ),
        TechnologyComponentProfile(
            name="Query Complexity / Depth Analysis",
            description="Mechanisms to limit query complexity, depth, and aliases. Absence allows deep nesting DoS and resource exhaustion.",
            security_relevance="high",
            common_vulnerabilities=["Deep query nesting DoS", "Alias-based query duplication", "Excessive query cost via recursive fragments", "Circular fragment DoS", "Query batching abuse"],
            investigation_priority=85,
            tags=["complexity", "depth", "dos", "rate-limiting"],
        ),
        TechnologyComponentProfile(
            name="Mutation Layer",
            description="GraphQL mutations for data modification. Often lack consistent authentication and authorization checks.",
            security_relevance="high",
            common_vulnerabilities=["Missing auth on mutations", "Mutation-based mass assignment", "Inconsistent auth between queries and mutations", "IDOR in mutation parameters", "Mutation field exposure"],
            investigation_priority=90,
            tags=["mutations", "write-operations", "auth"],
        ),
        TechnologyComponentProfile(
            name="Subscription System",
            description="Real-time GraphQL subscriptions over WebSocket. Can expose sensitive data streams if unauthenticated.",
            security_relevance="medium",
            common_vulnerabilities=["Unauthenticated subscription access", "Subscription message injection", "Real-time data stream interception", "WebSocket connection hijacking"],
            investigation_priority=70,
            tags=["subscriptions", "websocket", "real-time"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="GraphQL Endpoint",
                description="Primary GraphQL endpoint accepting POST with JSON query payload",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/graphql",
                parameters=["query", "variables", "operationName"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.DOS.value, BugClass.AUTH_BYPASS.value, BugClass.IDOR.value, BugClass.BUSINESS_LOGIC.value],
            ),
            AttackSurfaceEntry(
                name="GraphiQL Interface",
                description="Interactive GraphQL IDE accessible in browser",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/graphiql",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Introspection Query",
                description="Schema introspection via __schema or __type queries",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/graphql",
                parameters=["query"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/graphql", "/graphiql", "/graphql/console", "/playground", "/v1/graphql", "/api/graphql", "/query", "/gql"],
        parameters=["query", "variables", "operationName", "extensions", "batch"],
        authentication=["JWT", "API key in header", "Session cookie", "Bearer token", "Custom auth header"],
        authorization=["Per-field authorization", "Resolver-level role checks", "Schema directive-based auth", "Middleware auth"],
        storage=["Database", "Cache (Redis/Memcached)", "Object storage"],
        background_jobs=["Async resolvers", "DataLoader batch jobs"],
        queues=["Message queues for subscriptions"],
        caches=["GraphQL response caching", "DataLoader cache"],
        admin_interfaces=["/graphiql", "/playground", "/graphql/console", "/admin/graphql"],
        internal_apis=["/internal/graphql", "/admin/graphql"],
        external_apis=["Federated GraphQL services", "Apollo Federation subgraphs"],
        trust_boundaries=[
            TrustBoundary(name="Client-to-GraphQL", description="Client sends queries to the GraphQL endpoint", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="Resolver-to-Database", description="Resolvers fetch data from databases", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Resolver-to-External-API", description="Resolvers call external REST/gRPC services", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "Introspection query enabled in production",
            "GraphiQL accessible without authentication",
            "Deep query nesting allowing DoS via expensive queries",
            "Missing authentication on mutation endpoints",
            "N+1 injection via deeply nested relational queries",
            "Field suggestion leakage via error messages",
            "Query batching / aliasing for brute-force attacks",
            "Circular fragment and recursive fragment DoS",
            "Inconsistent authorization between queries and mutations",
            "IDOR in resolver-level data access",
            "Mass assignment via mutation input types",
            "Subscription channel without auth",
        ],
        investigation_areas=[
            "Test for introspection query availability (query { __schema { types { name } } })",
            "Check /graphiql and /playground accessibility in production",
            "Send deeply nested query to measure DoS resilience",
            "Test mutations for missing authentication headers",
            "Probe for N+1 injection with nested list queries",
            "Send invalid field names to observe suggestions",
            "Use query aliasing to batch identical operations",
            "Test circular fragment definitions",
            "Verify authorization consistency across queries and mutations",
            "Test resolvers for IDOR via parameter manipulation",
            "Check mutation inputs for mass assignment vulnerabilities",
            "Test subscription endpoints for unauthenticated access",
        ],
        tags=["graphql", "api", "query-language"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "content-type": "application/json",
        },
        cookies=[],
        js_indicators=["graphql", "GraphQL", "Apollo", "Relay", "gql"],
        file_indicators=["schema.graphql", "schema.gql", "graphql.config.js", ".graphqlrc", "graphql.config.json", "codegen.yml", "graphql.schema"],
        directory_indicators=["/graphql/", "/graphiql/", "/resolvers/", "/schema/", "/typedefs/", "/mutations/", "/queries/", "/subscriptions/"],
        server_signatures=["graphql", "apollo", "express-graphql", "graphql-yoga", "hasura"],
        error_page_signatures=["Cannot query field", "Cannot return null for non-nullable field", "Field \"", "Unknown argument", "is not defined by type", "GraphQLError", "Validation error of type"],
        default_paths=["/graphql", "/graphiql", "/playground", "/api/graphql", "/v1/graphql", "/query", "/gql", "/graphql/console"],
        default_files=["schema.graphql", "schema.gql", "graphql.config.js", ".graphqlrc", "codegen.yml"],
        metadata_patterns={"graphql-version": "pattern: [0-9]+\\.[0-9]+(\\.[0-9]+)?"},
        tags=["fingerprint", "graphql"],
    ),
    recon=ReconProfile(
        directories_to_check=["/graphql/", "/graphiql/", "/playground/", "/api/graphql/", "/v1/graphql/"],
        files_to_check=["schema.graphql", "schema.gql", ".graphqlrc", "graphql.config.js", "codegen.yml", "graphql.schema"],
        endpoints_to_scan=["/graphql", "/graphiql", "/playground", "/api/graphql", "/v1/graphql", "/query", "/gql", "/graphql/console"],
        version_detection_paths=["/graphql"],
        debug_paths_to_check=["/graphql?query={__schema{types{name}}}", "/graphiql", "/playground"],
        admin_paths_to_check=["/admin/graphql", "/graphql/admin", "/graphiql", "/playground"],
        tags=["recon", "graphql"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Introspection schema disclosure reveals entire API surface",
            impact="Full knowledge of all types, fields, arguments, and relationships enables targeted attacks",
            attack_scenario="Send query { __schema { types { name fields { name args { name } } } } } to map the entire schema",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Deep query nesting causes database and resolver load DoS",
            impact="Resource exhaustion, database overload, denial of service",
            attack_scenario="Send deeply nested query like { user { posts { comments { author { posts { comments { ... } } } } } } } with 10+ levels",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Missing authentication on mutations allows unauthorized data modification",
            impact="Unauthorized create, update, or delete of data",
            attack_scenario="Identify unprotected mutation and send mutation { deleteUser(id: 1) { success } } without auth token",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="N+1 injection via list queries enables relational data scraping",
            impact="Excessive database queries, data leakage across relations, performance degradation",
            attack_scenario="Fetch list of entities then deeply nest relational fields to force N+1 query pattern",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Field suggestion from error messages reveals valid field names",
            impact="Discovery of hidden or undocumented fields via error hints",
            attack_scenario="Query { invalidField } and observe 'Cannot query field \"invalidField\" on type \"User\". Did you mean \"id\", \"name\", \"email\"?'",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Query batching via aliases enables brute-force attacks",
            impact="Credential brute-force, rate limiting bypass, data enumeration",
            attack_scenario="Use aliases to send hundreds of login queries in a single request: { a: login(pw: \"a\") ... zzz: login(pw: \"zzz\") }",
            complexity="medium",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="rest",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="GraphQL competes with REST as an API paradigm",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="jwt",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="GraphQL APIs commonly use JWT for authentication",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="oauth",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="GraphQL APIs can use OAuth2 for authentication",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="oauth",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Hasura, Apollo, and other GraphQL servers integrate with OAuth2",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="saml",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="Enterprise GraphQL deployments may use SAML SSO",
            confidence="low",
        ),
    ],
    dependencies=[],
    related_packs=["rest", "jwt", "oauth", "saml", "oidc"],
    workflow=[
        "1. Discover GraphQL endpoint via common paths (/graphql, /graphiql, /playground)",
        "2. Test for introspection query: query { __schema { types { name } } }",
        "3. If introspection disabled, use field fuzzing to discover fields and types",
        "4. Map all queries, mutations, and subscriptions from the schema",
        "5. Send deeply nested query to test query depth limits",
        "6. Test query batching with aliases for brute-force or DoS",
        "7. Verify authentication on all mutations (send mutation without auth)",
        "8. Test for N+1 injection via deeply nested list fields",
        "9. Check error messages for field suggestion leakage",
        "10. Test circular fragment definitions for parser DoS",
        "11. Verify authorization consistency across fields",
        "12. Test subscription endpoints for unauthenticated access",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="GQL-01",
            category="Schema Disclosure",
            description="Check if introspection query is enabled: query { __schema { types { name } } }",
            expected_result="Introspection should be disabled in production or require authentication",
            tools=["curl", "GraphQL IDE", "Altair", "graphql-voyager"],
            references=["https://graphql.org/learn/introspection/", "https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html"],
        ),
        ManualTestChecklistItem(
            step_id="GQL-02",
            category="Information Disclosure",
            description="Check if /graphiql or /playground are accessible",
            expected_result="Interactive IDEs should be disabled in production",
            tools=["browser", "curl"],
            references=["https://www.apollographql.com/docs/apollo-server/testing/graphql-playground/"],
        ),
        ManualTestChecklistItem(
            step_id="GQL-03",
            category="Denial of Service",
            description="Test for deep query nesting DoS with 10+ level nested queries",
            expected_result="Server should reject or limit deeply nested queries",
            tools=["curl", "custom scripts"],
            references=["https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html#depth-limit"],
        ),
        ManualTestChecklistItem(
            step_id="GQL-04",
            category="Authentication",
            description="Test mutations without authentication headers",
            expected_result="Mutations should require authentication and authorization",
            tools=["curl", "Burp Suite"],
            references=["https://graphql.org/learn/mutations/"],
        ),
        ManualTestChecklistItem(
            step_id="GQL-05",
            category="Business Logic",
            description="Test for N+1 injection via deeply nested relational queries",
            expected_result="Server should limit query depth and complexity",
            tools=["custom scripts", "curl"],
            references=["https://shopify.engineering/solving-the-n-1-problem-for-graphql"],
        ),
        ManualTestChecklistItem(
            step_id="GQL-06",
            category="Information Disclosure",
            description="Send invalid field names to check for field suggestions in error messages",
            expected_result="Error messages should not suggest valid field names",
            tools=["curl"],
            references=["https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html#field-suggestion"],
        ),
        ManualTestChecklistItem(
            step_id="GQL-07",
            category="Rate Limiting",
            description="Test query batching with aliases to bypass rate limits",
            expected_result="Server should limit or cost-analyze batched queries",
            tools=["custom scripts", "curl"],
            references=["https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html#batching-attacks"],
        ),
    ],
    references=[
        {"title": "GraphQL Specification", "url": "https://spec.graphql.org/"},
        {"title": "OWASP GraphQL Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html"},
        {"title": "GraphQL Security Guide", "url": "https://graphql.org/learn/security/"},
        {"title": "Escape - GraphQL Security", "url": "https://escape.tech/blog/graphql-security/"},
        {"title": "Apollo Server Security", "url": "https://www.apollographql.com/docs/apollo-server/security/"},
    ],
    cwe_ids=["CWE-200", "CWE-400", "CWE-862", "CWE-863", "CWE-284", "CWE-639", "CWE-915", "CWE-770"],
    cve_ids=["CVE-2023-34092", "CVE-2022-23524", "CVE-2022-23525", "CVE-2022-23526", "CVE-2021-29053"],
    tags=["graphql", "api", "query-language", "cross-cutting"],
)
