"""JWT knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="jwt",
    version="1.0.0",
    category=KnowledgePackCategory.AUTHENTICATION,
    description="JWT: alg=none attack, RS256 to HS256 confusion, weak secret brute-force, kid injection, jku header SSRF, sub manipulation, missing expiration, token in URL.",
    technology=TechnologyProfile(
        name="JWT (JSON Web Token)",
        vendor="IETF (RFC 7519)",
        language="",
        runtime="",
        description="JSON Web Token (JWT) is a compact, URL-safe means of representing claims between two parties. Tokens are signed using HMAC, RSA, or ECDSA and can be encrypted using JWE.",
        common_aliases=["jwt", "json-web-token", "jwt-token", "jose"],
        dependencies=[],
        common_integrations=["Auth0", "Okta", "Keycloak", "Firebase Auth", "AWS Cognito", "Azure AD", "Supabase Auth", "Logto"],
        architecture_description="Stateless authentication where a server issues a signed token containing claims (e.g., user ID, role, expiration). The client presents this token on subsequent requests, and the server verifies the signature without session storage.",
        request_lifecycle="Client authenticates -> Server issues signed JWT -> Client includes JWT in Authorization header -> Server verifies signature and claims -> Access granted/denied",
        documentation_url="https://jwt.io/introduction/",
        tags=["jwt", "authentication", "authorization", "token"],
    ),
    components=[
        TechnologyComponentProfile(
            name="JWT Header",
            description="Contains algorithm (alg) and key ID (kid). Alg=none attack allows arbitrary signatures. Kid injection enables path traversal or SQL injection.",
            security_relevance="high",
            common_vulnerabilities=["alg=none attack allowing forged tokens", "RS256 to HS256 confusion (public key as HMAC secret)", "kid header injection (SQLi, path traversal, command injection)", "typ header manipulation", "jku/jwk header SSRF"],
            investigation_priority=95,
            tags=["header", "alg", "kid", "none-attack"],
        ),
        TechnologyComponentProfile(
            name="JWT Payload",
            description="Contains claims (sub, name, iat, exp, etc.). Sub manipulation allows impersonation. Weak claims enable authorization bypass.",
            security_relevance="high",
            common_vulnerabilities=["sub manipulation for user impersonation", "Missing expiration (exp) claim", "Weak or predictable claims", "Role/scope escalation via claim modification", "jti reuse (replay protection bypass)"],
            investigation_priority=90,
            tags=["payload", "claims", "sub", "impersonation"],
        ),
        TechnologyComponentProfile(
            name="JWT Signature",
            description="Cryptographic signature using HMAC, RSA, or ECDSA. Weak secrets allow brute-force. Algorithm confusion enables signature forgery.",
            security_relevance="high",
            common_vulnerabilities=["Weak HMAC secret brute-force", "RS256 to HS256 algorithm confusion", "ECDSA nonce reuse (private key recovery)", "Signature stripping in header", "Null signature acceptance"],
            investigation_priority=95,
            tags=["signature", "hmac", "rsa", "ecdsa", "brute-force"],
        ),
        TechnologyComponentProfile(
            name="Token Transport",
            description="How JWTs are transmitted between client and server. Insecure transport can leak tokens.",
            security_relevance="high",
            common_vulnerabilities=["Token in URL query string (logging exposure)", "Token in GET request body", "Token leakage via Referrer header", "Token stored in insecure localStorage", "Token transmitted over unencrypted HTTP", "Missing token revocation mechanism"],
            investigation_priority=85,
            tags=["transport", "url", "leakage", "storage"],
        ),
        TechnologyComponentProfile(
            name="Key Management",
            description="How signing keys are stored, rotated, and distributed. Leaked or hardcoded keys compromise all tokens.",
            security_relevance="high",
            common_vulnerabilities=["Hardcoded secret in source code", "Weak public key for algorithm confusion", "Missing JWKS endpoint authentication", "kid path traversal to read arbitrary files", "jku/jwk header pointing to attacker-controlled URL (SSRF)"],
            investigation_priority=90,
            tags=["key-management", "secret", "jwks", "ssrf"],
        ),
        TechnologyComponentProfile(
            name="Token Validation Logic",
            description="Server-side validation of JWT tokens. Flawed validation logic undermines security.",
            security_relevance="high",
            common_vulnerabilities=["Missing signature verification", "Wrong algorithm enforcement (none or HS256 allowed on RS256 expected)", "Expired token acceptance", "Missing audience (aud) validation", "Missing issuer (iss) validation", "Non-constant-time signature comparison"],
            investigation_priority=95,
            tags=["validation", "verification", "bypass"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Login/Auth Endpoint",
                description="Endpoint that issues JWT tokens upon successful authentication",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/api/auth/login",
                parameters=["username", "password", "client_id", "grant_type"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.BROKEN_AUTH.value, BugClass.RATE_LIMIT_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Token Verification Endpoint",
                description="Endpoint that accepts and verifies JWT tokens for protected resources",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/api/*",
                parameters=["Authorization", "token", "access_token"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.BROKEN_AUTH.value, BugClass.INFO_DISCLOSURE.value, BugClass.PRIVILEGE_ESCALATION.value],
            ),
            AttackSurfaceEntry(
                name="Token Introspection Endpoint",
                description="OAuth2 token introspection/introspection endpoint (RFC 7662)",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/api/auth/introspect",
                parameters=["token"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
        ],
        endpoints=["/api/auth/login", "/api/auth/token", "/api/auth/refresh", "/api/auth/verify", "/api/auth/introspect", "/api/auth/logout", "/api/auth/revoke", "/.well-known/jwks.json", "/.well-known/openid-configuration"],
        parameters=["Authorization", "token", "access_token", "refresh_token", "id_token", "bearer", "jwt", "api_key", "auth"],
        authentication=["JWT Bearer token (Authorization header)", "JWT in cookie", "JWT in URL parameter", "JWT in POST body"],
        authorization=["Role claim based", "Scope claim based", "Permission claim based", "Custom claims"],
        storage=["Token blacklist/revocation list", "Session store", "Redis"],
        background_jobs=["Token cleanup jobs"],
        queues=[],
        caches=["Token cache", "JWKS cache"],
        admin_interfaces=["/api/auth/admin/*", "/admin/tokens"],
        internal_apis=["/internal/token/verify", "/internal/token/decode"],
        external_apis=["Auth0", "Okta", "Azure AD", "AWS Cognito", "Keycloak", "Firebase Auth"],
        trust_boundaries=[
            TrustBoundary(name="Client-to-Server", description="Client sends JWT to the server", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="Server-to-Auth-Provider", description="Server authenticates with external identity provider", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Server-to-JWKS-Endpoint", description="Server fetches JWKS keys from remote endpoint", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "alg=none attack allowing arbitrary JWT forgery",
            "RS256 to HS256 algorithm confusion using public key",
            "Weak HMAC secret brute-force via dictionary attack",
            "kid header injection (path traversal, SQL injection)",
            "jku/jwk header SSRF to attacker-controlled endpoints",
            "sub claim manipulation for user impersonation",
            "Missing expiration (exp) allowing infinite token lifetime",
            "Token in URL query string exposed in server logs",
            "Hardcoded JWT secret in source code or config files",
            "Missing signature verification in JWT library",
            "Token stored in insecure client-side storage (localStorage)",
            "Missing audience (aud) or issuer (iss) validation",
        ],
        investigation_areas=[
            "Test alg=none attack by modifying token header",
            "Test RS256 to HS256 confusion using server's public key",
            "Brute-force weak HMAC secret with wordlist",
            "Inject path traversal payloads in kid header",
            "Set jku header to attacker server for SSRF",
            "Modify sub claim to impersonate other users",
            "Use expired token and check if accepted",
            "Check for token in URL query parameters",
            "Search source code for hardcoded JWT secrets",
            "Strip signature from token and test acceptance",
            "Check token storage mechanism (localStorage vs httpOnly cookie)",
            "Verify aud and iss claim validation",
        ],
        tags=["jwt", "authentication", "token"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "authorization": "Bearer eyJ",
            "set-cookie": "eyJ",
        },
        cookies=["token", "access_token", "jwt", "session", "auth"],
        js_indicators=["jwt", "jsonwebtoken", "JWT", "accessToken", "refreshToken", "idToken", "auth0", "keycloak", "okta", "cognito", "firebase.auth"],
        file_indicators=["jwt.js", "jwt.py", "auth.js", "auth.py", "middleware/auth.js", ".env", "config/auth.js", "jwt_secret", "private.pem", "public.pem", "jwks.json"],
        directory_indicators=["/auth/", "/token/", "/.well-known/", "/jwks/"],
        server_signatures=["jwt", "auth0", "keycloak", "okta"],
        error_page_signatures=["jwt expired", "invalid token", "invalid signature", "token malformed", "unauthorized", "invalid algorithm", "secret or public key must be provided", "JsonWebTokenError", "TokenExpiredError"],
        default_paths=["/.well-known/jwks.json", "/.well-known/openid-configuration", "/.well-known/oauth-authorization-server", "/auth", "/login", "/token"],
        default_files=[".env", "jwks.json", "public.pem", "private.pem", "auth.js", "auth.py", "middleware/auth.js", "config/auth.js"],
        metadata_patterns={"jwks": "pattern: [A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+"},
        tags=["fingerprint", "jwt", "authentication"],
    ),
    recon=ReconProfile(
        directories_to_check=["/.well-known/", "/auth/", "/token/", "/jwks/", "/api/auth/"],
        files_to_check=[".env", "jwks.json", "public.pem", "private.pem", "auth.js", "auth.py", "middleware/auth.js", "config/auth.js"],
        endpoints_to_scan=["/.well-known/jwks.json", "/.well-known/openid-configuration", "/api/auth/login", "/api/auth/token", "/api/auth/refresh", "/api/auth/verify"],
        version_detection_paths=["/.well-known/openid-configuration", "/.well-known/jwks.json"],
        debug_paths_to_check=["/api/auth/debug", "/api/auth/decode", "/api/auth/verify?debug=true"],
        admin_paths_to_check=["/api/auth/admin", "/admin/tokens", "/admin/jwt", "/api/admin/auth"],
        tags=["recon", "jwt", "authentication"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="alg=none attack allows forging arbitrary JWT tokens without knowing the secret",
            impact="Complete authentication bypass, arbitrary user impersonation",
            attack_scenario="Decode a valid JWT, change alg to 'none', remove signature, re-encode and present as valid token",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="RS256 to HS256 algorithm confusion uses the public key to sign tokens",
            impact="Authentication bypass by forging tokens with the publicly known public key as HMAC secret",
            attack_scenario="Fetch server's public key (often from /jwks.json), change alg from RS256 to HS256, sign token with public key material",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Weak HMAC secret allows offline brute-force of JWT tokens",
            impact="Token forgery, user impersonation, privileged access",
            attack_scenario="Capture a valid JWT, extract the HMAC signature, brute-force the secret offline using hashcat or john",
            complexity="medium",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="kid header injection enables path traversal or SQL injection in key lookup",
            impact="Arbitrary file read, SQL injection, authentication bypass",
            attack_scenario="Set kid to '../../../../etc/passwd' for path traversal or ' UNION SELECT ...' for SQL injection in key lookup query",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="jku/jwk header SSRF allows server to fetch keys from attacker-controlled URL",
            impact="Server-side request forgery, internal network scanning, authentication bypass",
            attack_scenario="Set jku header to https://attacker.com/keys.json and host a JWKS set with your own public key",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Missing expiration (exp) claim allows indefinite token validity",
            impact="Token never expires, persistent unauthorized access if token is stolen",
            attack_scenario="Intercept a JWT token, check if exp claim is present. If missing, token is valid forever",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Token in URL query string leaks via server logs, referrer headers, and browser history",
            impact="Token theft via log inspection, referrer leakage, shoulder surfing",
            attack_scenario="Check if token appears in URL parameters like /api/data?token=eyJ..., which leaks via Referrer header and server logs",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="oauth",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="JWT is commonly used as OAuth2 access token format",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="oidc",
            relationship_type=KnowledgeRelationshipType.IMPLEMENTS,
            description="OIDC ID tokens are JWTs with specific claims",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="saml",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="JWT competes with SAML as a token format",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="rest",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="JWT authenticates REST API requests",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="graphql",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="JWT authenticates GraphQL API requests",
            confidence="high",
        ),
    ],
    dependencies=[],
    related_packs=["oauth", "oidc", "saml", "rest", "graphql"],
    workflow=[
        "1. Capture a JWT token from the application",
        "2. Decode the JWT to inspect header and payload claims",
        "3. Test alg=none: modify header to {'alg':'none'} and empty signature",
        "4. Fetch server's public key from /.well-known/jwks.json",
        "5. Test RS256->HS256 confusion using public key for HMAC",
        "6. Brute-force weak HMAC secret using jwt_tool or hashcat",
        "7. Test kid injection with path traversal and SQLi payloads",
        "8. Set jku/jwk header to attacker-controlled URL for SSRF",
        "9. Modify sub claim to impersonate other users",
        "10. Check for presence of exp, nbf, aud, iss claims",
        "11. Check if token appears in URL query parameters",
        "12. Send request with stripped/modified signature",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="JWT-01",
            category="Algorithm Confusion",
            description="Test alg=none attack by setting algorithm to none with empty signature",
            expected_result="Server must reject tokens with alg=none",
            tools=["jwt_tool", "jwt.io", "custom scripts"],
            references=["https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/"],
        ),
        ManualTestChecklistItem(
            step_id="JWT-02",
            category="Algorithm Confusion",
            description="Test RS256 to HS256 confusion using public key as HMAC secret",
            expected_result="Server must enforce expected algorithm and reject wrong algorithm type",
            tools=["jwt_tool", "custom scripts", "jwt.io"],
            references=["https://www.sjoerdlangkemper.nl/2016/09/28/attacking-jwt-authentication/"],
        ),
        ManualTestChecklistItem(
            step_id="JWT-03",
            category="Weak Secret",
            description="Brute-force weak HMAC secret using common password lists",
            expected_result="HMAC secrets should be strong (>=256 bits) and not in common password lists",
            tools=["hashcat", "john", "jwt_tool", "crackjwt"],
            references=["https://github.com/ticarpi/jwt_tool", "https://github.com/brendan-rius/c-jwt-cracker"],
        ),
        ManualTestChecklistItem(
            step_id="JWT-04",
            category="Injection",
            description="Test kid header injection with path traversal and SQLi payloads",
            expected_result="Server must validate kid values and prevent injection attacks",
            tools=["curl", "custom scripts"],
            references=["https://www.nccgroup.com/us/research-blog/json-web-token-jwt-attacks/"],
        ),
        ManualTestChecklistItem(
            step_id="JWT-05",
            category="SSRF",
            description="Test jku/jwk header by pointing to attacker-controlled URL",
            expected_result="Server must not fetch keys from user-supplied URLs",
            tools=["curl", "custom scripts", "request catcher"],
            references=["https://portswigger.net/research/json-web-token-attacks"],
        ),
        ManualTestChecklistItem(
            step_id="JWT-06",
            category="Authorization",
            description="Modify sub claim to impersonate other users",
            expected_result="Server must validate sub claim against actual user identity",
            tools=["jwt.io", "jwt_tool", "custom scripts"],
            references=["https://owasp.org/www-project-web-security-testing-guide/"],
        ),
        ManualTestChecklistItem(
            step_id="JWT-07",
            category="Token Management",
            description="Check if token is transmitted in URL query parameters",
            expected_result="Tokens must be transmitted in HTTP headers (Authorization) only",
            tools=["browser DevTools", "Burp Suite", "curl"],
            references=["https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_Cheat_Sheet_for_Java.html"],
        ),
        ManualTestChecklistItem(
            step_id="JWT-08",
            category="Token Management",
            description="Check for missing expiration (exp) claim in JWT",
            expected_result="All JWT tokens must have an exp claim with reasonable validity period",
            tools=["jwt.io", "Burp Suite", "custom scripts"],
            references=["https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4"],
        ),
    ],
    references=[
        {"title": "JWT.io Introduction", "url": "https://jwt.io/introduction/"},
        {"title": "RFC 7519 - JSON Web Token", "url": "https://datatracker.ietf.org/doc/html/rfc7519"},
        {"title": "OWASP JWT Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html"},
        {"title": "jwt_tool", "url": "https://github.com/ticarpi/jwt_tool"},
        {"title": "Auth0 JWT Vulnerabilities", "url": "https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/"},
        {"title": "JWT Attacks Guide (PortSwigger)", "url": "https://portswigger.net/web-security/jwt"},
    ],
    cwe_ids=["CWE-287", "CWE-290", "CWE-327", "CWE-328", "CWE-330", "CWE-345", "CWE-613", "CWE-200", "CWE-918", "CWE-89", "CWE-22", "CWE-798"],
    cve_ids=["CVE-2022-23529", "CVE-2022-23528", "CVE-2022-23526", "CVE-2022-23520", "CVE-2020-28043", "CVE-2020-28502", "CVE-2019-7644", "CVE-2018-0114"],
    tags=["jwt", "authentication", "token", "cross-cutting"],
)
