"""OAuth2 knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="oauth",
    version="1.0.0",
    category=KnowledgePackCategory.AUTHENTICATION,
    description="OAuth2: CSRF on redirect URI, state parameter missing, token leakage via referrer, code injection, PKCE downgrade, scope escalation, client secret leakage.",
    technology=TechnologyProfile(
        name="OAuth 2.0",
        vendor="IETF (RFC 6749)",
        language="",
        runtime="",
        description="OAuth 2.0 is an authorization framework that enables applications to obtain limited access to user accounts on an HTTP service. It works by delegating user authentication to the service that hosts the user account and authorizing third-party applications access.",
        common_aliases=["oauth2", "oauth", "oauth-2.0"],
        dependencies=[],
        common_integrations=["Auth0", "Okta", "Keycloak", "Google Identity Platform", "Microsoft Identity Platform", "AWS Cognito", "Facebook Login", "GitHub OAuth", "Apple Sign In"],
        architecture_description="OAuth 2.0 defines four roles: resource owner (user), client (application), authorization server, and resource server. Tokens are issued via authorization grant flows: authorization code, implicit, client credentials, resource owner password, and device code.",
        request_lifecycle="Client initiates flow -> Resource owner authenticates -> Authorization issues code -> Client exchanges code for tokens -> Client uses access token to call resource server -> Resource server validates token",
        documentation_url="https://oauth.net/2/",
        tags=["oauth", "oauth2", "authorization", "authentication"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Authorization Code Flow",
            description="The most common OAuth2 flow. Involves redirecting the user, receiving an authorization code, and exchanging it for tokens. Prone to CSRF, code interception, and injection.",
            security_relevance="high",
            common_vulnerabilities=["CSRF via missing or weak state parameter", "Authorization code interception via redirect URI manipulation", "Code injection via open redirect", "PKCE downgrade attack (S256 to plain)", "Code reuse via missing code_challenge validation"],
            investigation_priority=95,
            tags=["authorization-code", "redirect", "csrf", "pkce"],
        ),
        TechnologyComponentProfile(
            name="Redirect URI Handling",
            description="The URI where the authorization server sends the user after authorization. Insecure redirect URI validation enables code theft.",
            security_relevance="high",
            common_vulnerabilities=["CSRF on redirect URI by accepting attacker-controlled URIs", "Open redirect via wildcard URI patterns", "Redirect URI path traversal", "Unsafe redirect URI scheme acceptance (http, data, javascript)", "Multiple redirect URIs with different security levels"],
            investigation_priority=95,
            tags=["redirect-uri", "csrf", "open-redirect"],
        ),
        TechnologyComponentProfile(
            name="Token Handling / Storage",
            description="How access tokens, refresh tokens, and ID tokens are transmitted and stored. Insecure handling leads to token theft.",
            security_relevance="high",
            common_vulnerabilities=["Token leakage via Referrer header on redirect", "Token in URL fragment (implicit flow)", "Token stored in insecure localStorage", "Token in browser history", "Token leakage via third-party analytics", "Token exfiltration via injected scripts"],
            investigation_priority=90,
            tags=["token-storage", "leakage", "referrer", "fragment"],
        ),
        TechnologyComponentProfile(
            name="PKCE (Proof Key for Code Exchange)",
            description="Extension to authorization code flow to prevent interception attacks. Downgrade from S256 to plain or disabled completely.",
            security_relevance="high",
            common_vulnerabilities=["PKCE downgrade from S256 to plain", "PKCE entirely disabled/absent", "Missing code_challenge verification", "Reuse of code_verifier across multiple requests", "Weak code_verifier generation"],
            investigation_priority=85,
            tags=["pkce", "s256", "plain", "downgrade"],
        ),
        TechnologyComponentProfile(
            name="Scope / Permission System",
            description="OAuth2 scopes define what resources the client can access. Scope escalation allows accessing more resources than authorized.",
            security_relevance="high",
            common_vulnerabilities=["Scope escalation by manipulating scope parameter", "Granularity bypass via excessive scope requests", "Scope downgrade attack (requesting less access)", "Custom scope injection", "Unintended scope inheritance in refresh tokens"],
            investigation_priority=85,
            tags=["scope", "permissions", "escalation"],
        ),
        TechnologyComponentProfile(
            name="Client Secrets",
            description="Secret keys used by confidential clients to authenticate with the authorization server. Leaked secrets allow token issuance.",
            security_relevance="high",
            common_vulnerabilities=["Client secret leakage in source code / GitHub", "Client secret in URL parameters", "Client secret exposed in mobile app decompilation", "Missing client authentication on token endpoint", "Client secret reuse across environments"],
            investigation_priority=90,
            tags=["client-secret", "leakage", "credential-stuffing"],
        ),
        TechnologyComponentProfile(
            name="Token Endpoint",
            description="Endpoint where authorization codes are exchanged for tokens. Insecure implementation enables injection and token theft.",
            security_relevance="high",
            common_vulnerabilities=["Code injection via code parameter tampering", "Refresh token rotation bypass", "Token replay via missing token binding", "Missing client authentication", "Unvalidated redirect_uri in token exchange"],
            investigation_priority=90,
            tags=["token-endpoint", "code-exchange", "injection"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Authorization Endpoint",
                description="OAuth2 authorization endpoint where users authenticate and consent",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/oauth/authorize",
                parameters=["client_id", "redirect_uri", "response_type", "scope", "state", "code_challenge", "code_challenge_method"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.CSRF.value, BugClass.OPEN_REDIRECT.value, BugClass.BROKEN_AUTH.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Token Endpoint",
                description="OAuth2 token endpoint for exchanging codes and refreshing tokens",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/oauth/token",
                parameters=["grant_type", "code", "redirect_uri", "client_id", "client_secret", "code_verifier", "refresh_token"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.BROKEN_AUTH.value, BugClass.INFO_DISCLOSURE.value, BugClass.BUSINESS_LOGIC.value],
            ),
            AttackSurfaceEntry(
                name="Token Revocation Endpoint",
                description="OAuth2 token revocation endpoint (RFC 7009)",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/oauth/revoke",
                parameters=["token", "token_type_hint"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value],
            ),
        ],
        endpoints=["/oauth/authorize", "/oauth/token", "/oauth/revoke", "/oauth/introspect", "/oauth/userinfo", "/.well-known/oauth-authorization-server", "/.well-known/openid-configuration"],
        parameters=["client_id", "redirect_uri", "response_type", "scope", "state", "code", "code_challenge", "code_challenge_method", "code_verifier", "grant_type", "client_secret", "refresh_token", "access_token", "token_type_hint"],
        authentication=["Client authentication (client_secret)", "Client assertion (private_key_jwt)", "Public client (no auth)", "Bearer token"],
        authorization=["OAuth2 scopes", "Role-based claims", "Attribute-based claims"],
        storage=["Token database", "Auth code store", "Refresh token store", "Client registration store"],
        background_jobs=["Token cleanup", "Session management"],
        queues=[],
        caches=["Token cache", "JWKS cache", "Authorization code cache"],
        admin_interfaces=["/admin/oauth/clients", "/admin/oauth/tokens", "/admin/oauth/scopes"],
        internal_apis=["/internal/oauth/verify", "/internal/oauth/introspect", "/internal/oauth/clients"],
        external_apis=["Google Identity", "Microsoft Identity", "GitHub OAuth", "Facebook Login", "Apple Sign In", "Auth0", "Okta", "Keycloak"],
        trust_boundaries=[
            TrustBoundary(name="Client-to-Authorization-Server", description="Client communicates with authorization server", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="Browser-to-Authorization-Server", description="User's browser redirected to authorization server", direction="inbound", sensitivity="high"),
            TrustBoundary(name="Authorization-Server-to-Resource-Server", description="Authorization server issues tokens for resource server", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "CSRF via missing or weak state parameter in authorization flow",
            "Open redirect via unvalidated redirect_uri",
            "Token leakage via Referrer header on redirect back to client",
            "PKCE downgrade from S256 to plain or disabled PKCE",
            "Scope escalation by manipulating scope parameter",
            "Client secret leakage in source code or URL parameters",
            "Code injection via code parameter tampering",
            "Authorization code interception via redirect URI manipulation",
            "Missing client authentication on token endpoint",
            "Refresh token rotation bypass",
            "Token replay across different client applications",
            "Consent screen bypass via auto-approval",
        ],
        investigation_areas=[
            "Test state parameter presence and CSRF resistance",
            "Fuzz redirect_uri for open redirect and SSRF",
            "Check Referrer header for token leakage",
            "Attempt PKCE downgrade by omitting or changing code_challenge_method",
            "Escalate scope by adding privileges to scope parameter",
            "Search for client_secret in public repositories and code",
            "Intercept and modify code parameter during exchange",
            "Test redirect_uri path traversal and scheme injection",
            "Try token endpoint without client authentication",
            "Reuse refresh token after rotation",
            "Replay access token across different client IDs",
            "Test for auto-approved consent without user interaction",
        ],
        tags=["oauth", "oauth2", "authorization", "authentication"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "location": "/oauth/authorize",
            "www-authenticate": "Bearer",
        },
        cookies=["oauth_state", "oauth_session", "auth_session", "connect.sid"],
        js_indicators=["oauth", "OAuth", "auth0", "okta", "keycloak", "passport.authenticate", "OAuth2", "grant_type", "client_id", "redirect_uri"],
        file_indicators=["oauth.js", "oauth.py", "auth_config.js", "authConfig.js", "auth0_config.js", "okta_config.js", "firebase.js", ".env", "oauth_client_secret"],
        directory_indicators=["/oauth/", "/auth/", "/.well-known/", "/authorize/", "/token/", "/login/", "/callback/"],
        server_signatures=["oauth2", "auth0", "okta", "keycloak", "cognito", "spring-security", "doorkeeper"],
        error_page_signatures=["invalid_grant", "invalid_request", "invalid_client", "invalid_scope", "unauthorized_client", "access_denied", "unsupported_grant_type", "OAuth2Error", "redirect_uri_mismatch"],
        default_paths=["/oauth/authorize", "/oauth/token", "/oauth/revoke", "/.well-known/oauth-authorization-server", "/.well-known/openid-configuration", "/login", "/callback", "/auth/callback"],
        default_files=["auth_config.js", "auth.config.js", ".env", "firebase.js", "auth0_config.json", "okta.config.js", "oauth_client.js"],
        metadata_patterns={"oauth2": "pattern: [0-9]+\\.[0-9]+"},
        tags=["fingerprint", "oauth", "oauth2", "authentication"],
    ),
    recon=ReconProfile(
        directories_to_check=["/oauth/", "/auth/", "/.well-known/", "/callback/", "/login/", "/token/"],
        files_to_check=["auth_config.js", "auth.config.js", ".env", "firebase.js", "auth0_config.json", "okta.config.js", "oauth_client.js"],
        endpoints_to_scan=["/.well-known/oauth-authorization-server", "/.well-known/openid-configuration", "/oauth/authorize", "/oauth/token", "/oauth/revoke", "/oauth/introspect", "/oauth/userinfo"],
        version_detection_paths=["/.well-known/oauth-authorization-server", "/.well-known/openid-configuration"],
        debug_paths_to_check=["/oauth/debug", "/oauth/token?debug=true", "/oauth/authorize?debug=true"],
        admin_paths_to_check=["/admin/oauth", "/admin/oauth/clients", "/admin/oauth/tokens", "/admin/oauth/scopes"],
        tags=["recon", "oauth", "oauth2", "authentication"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="CSRF on OAuth redirect due to missing state parameter",
            impact="Attacker can bind their account to a victim's session, leading to account takeover",
            attack_scenario="Initiate OAuth flow without state parameter, intercept and replace authorization code to bind attacker's social account to victim",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Missing or weak state parameter allows CSRF on authorization callback",
            impact="Account linking attacks, unauthorized token binding",
            attack_scenario="Start OAuth flow, intercept redirect, swap state value, and force victim to complete flow binding attacker's identity",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Token leakage via Referrer header during OAuth redirect",
            impact="Access token theft via Referrer header exposed to third-party sites",
            attack_scenario="Victim clicks malicious link after OAuth callback, Referrer header contains token from callback URL fragment",
            complexity="low",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="PKCE downgrade from S256 to plain allows code interception",
            impact="Authorization code interception attack succeeds without PKCE protection",
            attack_scenario="Modify code_challenge_method from S256 to plain or remove it, then intercept the authorization code",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Scope escalation via scope parameter manipulation",
            impact="Privileged access to resources beyond consent",
            attack_scenario="Add admin scopes (e.g., 'admin:write', 'user:delete') to the scope parameter during authorization",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Client secret leakage enables token issuance for any user",
            impact="Full account takeover, arbitrary token generation, data breach",
            attack_scenario="Find exposed client_secret in public GitHub repo or mobile app, then use it to initiate OAuth flows as any user",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Code injection via manipulated authorization code allows token theft",
            impact="Attacker can exchange intercepted code for tokens belonging to the victim",
            attack_scenario="Intercept the authorization code, modify it, and exchange at token endpoint with modified redirect_uri",
            complexity="high",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="jwt",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="OAuth2 commonly uses JWT as access token format",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="oidc",
            relationship_type=KnowledgeRelationshipType.EXTENDS,
            description="OIDC is an identity layer on top of OAuth2",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="saml",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="OAuth2 competes with SAML for SSO and authorization",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="rest",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="OAuth2 authorizes REST API access",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="graphql",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="OAuth2 authorizes GraphQL API access",
            confidence="high",
        ),
    ],
    dependencies=[],
    related_packs=["jwt", "oidc", "saml", "rest", "graphql"],
    workflow=[
        "1. Discover OAuth endpoints via /.well-known/oauth-authorization-server or /.well-known/openid-configuration",
        "2. Identify OAuth flow type (authorization code, implicit, client credentials)",
        "3. Test CSRF by initiating flow without state parameter",
        "4. Fuzz redirect_uri with open redirect payloads",
        "5. Check Referrer header for token leakage after callback",
        "6. Attempt PKCE downgrade by modifying code_challenge_method",
        "7. Escalate scope by adding privileged scopes",
        "8. Search for client_secret in source code, config files, and public repos",
        "9. Intercept and modify authorization code during exchange",
        "10. Test token endpoint for missing client authentication",
        "11. Test refresh token reuse and rotation",
        "12. Check for auto-approved consent without user interaction",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="OAUTH-01",
            category="CSRF",
            description="Test for missing or weak state parameter in authorization request",
            expected_result="State parameter with sufficient entropy must be present and validated",
            tools=["Burp Suite", "custom scripts", "curl"],
            references=["https://datatracker.ietf.org/doc/html/rfc6749#section-10.12"],
        ),
        ManualTestChecklistItem(
            step_id="OAUTH-02",
            category="Open Redirect",
            description="Fuzz redirect_uri parameter for open redirect and SSRF",
            expected_result="Only registered redirect URIs should be accepted",
            tools=["curl", "Burp Suite Intruder", "custom scripts"],
            references=["https://owasp.org/www-community/attacks/Open_Redirect"],
        ),
        ManualTestChecklistItem(
            step_id="OAUTH-03",
            category="Information Disclosure",
            description="Check for token in Referrer header after OAuth callback",
            expected_result="Tokens should not leak via Referrer header",
            tools=["Burp Suite", "browser DevTools"],
            references=["https://portswigger.net/web-security/oauth"],
        ),
        ManualTestChecklistItem(
            step_id="OAUTH-04",
            category="PKCE",
            description="Attempt PKCE downgrade by removing code_challenge_method or changing S256 to plain",
            expected_result="PKCE with S256 should be enforced, plain should not be downgradable",
            tools=["custom scripts", "curl"],
            references=["https://datatracker.ietf.org/doc/html/rfc7636"],
        ),
        ManualTestChecklistItem(
            step_id="OAUTH-05",
            category="Authorization",
            description="Test scope escalation by adding privileged scopes to authorization request",
            expected_result="Server must validate scope against client's allowed scopes and user's permissions",
            tools=["curl", "custom scripts"],
            references=["https://datatracker.ietf.org/doc/html/rfc6749#section-3.3"],
        ),
        ManualTestChecklistItem(
            step_id="OAUTH-06",
            category="Information Disclosure",
            description="Search for client_secret in source code, configs, and public repositories",
            expected_result="Client secrets must not be exposed in client-side code or public locations",
            tools=["repo scanning tools", "Gitleaks", "TruffleHog", "git-secrets"],
            references=["https://cheatsheetseries.owasp.org/cheatsheets/OAuth_2.0_Cheat_Sheet.html"],
        ),
        ManualTestChecklistItem(
            step_id="OAUTH-07",
            category="Authentication",
            description="Test token endpoint for missing client authentication",
            expected_result="Confidential clients must authenticate at the token endpoint",
            tools=["curl", "custom scripts"],
            references=["https://datatracker.ietf.org/doc/html/rfc6749#section-2.3"],
        ),
        ManualTestChecklistItem(
            step_id="OAUTH-08",
            category="Token Management",
            description="Test refresh token reuse and check for proper rotation",
            expected_result="Refresh tokens should be rotated after use or revoked on reuse",
            tools=["custom scripts", "curl"],
            references=["https://datatracker.ietf.org/doc/html/rfc6749#section-1.5"],
        ),
    ],
    references=[
        {"title": "OAuth 2.0 Specification (RFC 6749)", "url": "https://datatracker.ietf.org/doc/html/rfc6749"},
        {"title": "OAuth 2.0 Threat Model (RFC 6819)", "url": "https://datatracker.ietf.org/doc/html/rfc6819"},
        {"title": "PKCE (RFC 7636)", "url": "https://datatracker.ietf.org/doc/html/rfc7636"},
        {"title": "OWASP OAuth 2.0 Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/OAuth_2.0_Cheat_Sheet.html"},
        {"title": "OAuth 2.0 Security Best Practices", "url": "https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics"},
        {"title": "PortSwigger OAuth Attacks", "url": "https://portswigger.net/web-security/oauth"},
    ],
    cwe_ids=["CWE-352", "CWE-601", "CWE-200", "CWE-757", "CWE-287", "CWE-271", "CWE-798", "CWE-270", "CWE-523", "CWE-613", "CWE-345"],
    cve_ids=["CVE-2022-23526", "CVE-2022-20607", "CVE-2021-27906", "CVE-2020-5261", "CVE-2019-10076", "CVE-2019-10073", "CVE-2018-0489", "CVE-2017-5636"],
    tags=["oauth", "oauth2", "authentication", "authorization", "cross-cutting"],
)
