"""OIDC knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="oidc",
    version="1.0.0",
    category=KnowledgePackCategory.AUTHENTICATION,
    description="OIDC (OpenID Connect): nonce replay, acr_values manipulation, audience confusion, bearer token interception, signed vs encrypted hybrid attacks.",
    technology=TechnologyProfile(
        name="OpenID Connect (OIDC)",
        vendor="OpenID Foundation",
        language="",
        runtime="",
        description="OpenID Connect (OIDC) is a simple identity layer on top of the OAuth 2.0 protocol. It allows clients to verify the identity of the end-user based on the authentication performed by an authorization server, as well as to obtain basic profile information about the end-user.",
        common_aliases=["oidc", "openid-connect", "openid"],
        dependencies=["OAuth 2.0"],
        common_integrations=["Auth0", "Okta", "Keycloak", "Google Identity Platform", "Microsoft Entra ID", "AWS Cognito", "Ping Identity", "ForgeRock", "Dex", "Hydra"],
        architecture_description="OIDC extends OAuth 2.0 by adding an ID token (JWT) containing user identity claims. Flows include authorization code, implicit, hybrid, and the newer authorization code with PKCE for native/mobile apps.",
        request_lifecycle="Client initiates OIDC request -> User authenticates at OP -> OP returns ID token + access token -> Client validates ID token signature, nonce, aud, iss -> Client uses access token for API calls",
        documentation_url="https://openid.net/connect/",
        tags=["oidc", "openid", "authentication", "identity", "sso"],
    ),
    components=[
        TechnologyComponentProfile(
            name="ID Token",
            description="JWT containing identity claims about the authenticated user. Must be validated for signature, nonce, audience, issuer, and expiration.",
            security_relevance="high",
            common_vulnerabilities=["Nonce replay attack (missing or weak nonce validation)", "Audience confusion (aud claim not validated)", "ID token acceptance from wrong issuer", "Missing signature verification on ID token", "Expired ID token acceptance", "Sub claim manipulation"],
            investigation_priority=95,
            tags=["id-token", "jwt", "claims", "validation"],
        ),
        TechnologyComponentProfile(
            name="Nonce Mechanism",
            description="A random value sent with the authentication request to prevent replay attacks. Absent or weakly validated nonce enables token replay.",
            security_relevance="high",
            common_vulnerabilities=["Nonce replay via missing nonce validation", "Weak/guessable nonce generation", "Nonce reuse across multiple auth requests", "Nonce lifetime bypass", "Nonce removal via acr_values manipulation"],
            investigation_priority=95,
            tags=["nonce", "replay", "csrf"],
        ),
        TechnologyComponentProfile(
            name="acr_values / Authentication Context",
            description="Authentication Context Class Reference specifies the authentication method strength. Manipulation can weaken the authentication requirements.",
            security_relevance="high",
            common_vulnerabilities=["acr_values manipulation to downgrade auth strength", "acr_values injection with custom values", "Missing acr validation allowing weak auth for sensitive operations", "acr_values bypass via parameter removal", "Authentication context confusion between different flows"],
            investigation_priority=85,
            tags=["acr-values", "auth-context", "downgrade"],
        ),
        TechnologyComponentProfile(
            name="Token Endpoint / Code Exchange",
            description="OIDC uses OAuth2 token endpoint to exchange codes for tokens. Code injection and token interception risks.",
            security_relevance="high",
            common_vulnerabilities=["Authorization code injection", "Bearer token interception via redirect URI manipulation", "ID token in URL fragment exposure", "Access token / ID token confusion", "Missing token binding"],
            investigation_priority=90,
            tags=["token-exchange", "code", "injection", "bearer-token"],
        ),
        TechnologyComponentProfile(
            name="Signed vs Encrypted Tokens",
            description="OIDC supports signed (JWS) and encrypted (JWE) tokens. Hybrid attacks exploit weaknesses in combined signing and encryption.",
            security_relevance="high",
            common_vulnerabilities=["Signed-then-encrypted token parsing confusion", "Encrypted-then-signed signature stripping", "JWE algorithm confusion on nested tokens", "Missing integrity protection on encrypted-only tokens", "CBC padding oracle on JWE tokens", "Key confusion between signing and encryption keys"],
            investigation_priority=85,
            tags=["jws", "jwe", "encryption", "signing", "hybrid"],
        ),
        TechnologyComponentProfile(
            name="UserInfo Endpoint",
            description="OIDC endpoint returning identity claims for a valid access token. Missing audience validation enables cross-client data access.",
            security_relevance="high",
            common_vulnerabilities=["UserInfo endpoint without access token validation", "Reused access token across clients for data access", "Excessive claims in UserInfo response", "UserInfo endpoint enumeration"],
            investigation_priority=80,
            tags=["userinfo", "claims", "data-access"],
        ),
        TechnologyComponentProfile(
            name="Discovery / Metadata",
            description="OIDC discovery document at /.well-known/openid-configuration exposes provider metadata. Manipulation of metadata leads to downgrade attacks.",
            security_relevance="medium",
            common_vulnerabilities=["Discovery document manipulation via SSRF", "Downgrade attack via metadata injection", "Unvalidated discovery document source", "Missing certs endpoint authentication"],
            investigation_priority=75,
            tags=["discovery", "metadata", "configuration"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="OIDC Authorization Endpoint",
                description="OIDC authentication request endpoint (extends OAuth2 authorize)",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/oauth/authorize",
                parameters=["client_id", "redirect_uri", "response_type", "scope", "state", "nonce", "acr_values", "claims", "prompt", "max_age", "ui_locales"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.CSRF.value, BugClass.OPEN_REDIRECT.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="OIDC Token Endpoint",
                description="OIDC token endpoint returning ID token and access token",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/oauth/token",
                parameters=["grant_type", "code", "redirect_uri", "client_id", "client_secret", "code_verifier"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.BROKEN_AUTH.value, BugClass.BUSINESS_LOGIC.value],
            ),
            AttackSurfaceEntry(
                name="UserInfo Endpoint",
                description="OIDC endpoint returning identity claims for valid access token",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/oauth/userinfo",
                parameters=["access_token"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Discovery Endpoint",
                description="OIDC provider metadata and configuration",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/.well-known/openid-configuration",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/.well-known/openid-configuration", "/.well-known/oauth-authorization-server", "/oauth/authorize", "/oauth/token", "/oauth/userinfo", "/oauth/introspect", "/oauth/revoke", "/oauth/end_session", "/oauth/jwks"],
        parameters=["client_id", "redirect_uri", "response_type", "response_mode", "scope", "state", "nonce", "acr_values", "claims", "prompt", "max_age", "id_token_hint", "login_hint", "ui_locales", "code", "code_verifier", "grant_type", "client_secret", "refresh_token"],
        authentication=["Client authentication (client_secret_basic)", "Client authentication (client_secret_post)", "Client authentication (private_key_jwt)", "Public client (PKCE)", "Bearer token"],
        authorization=["OIDC scopes (openid, profile, email, address, phone)", "Custom claims-based access", "acr_values-based step-up auth"],
        storage=["ID token store", "Session store", "Refresh token store", "Authorization code store"],
        background_jobs=["Token cleanup", "Session expiry management"],
        queues=[],
        caches=["JWKS cache", "Session cache", "Discovery document cache"],
        admin_interfaces=["/admin/oidc/clients", "/admin/oidc/sessions", "/admin/oidc/tokens"],
        internal_apis=["/internal/oidc/verify", "/internal/oidc/userinfo"],
        external_apis=["Google Identity Platform", "Microsoft Entra ID", "Auth0", "Okta", "Keycloak", "Ping Identity", "ForgeRock", "AWS Cognito"],
        trust_boundaries=[
            TrustBoundary(name="Client-to-OP", description="Client communicates with OpenID Provider", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="Browser-to-OP", description="User's browser authenticates at the OP", direction="inbound", sensitivity="high"),
            TrustBoundary(name="OP-to-Resource-Server", description="OP issues tokens for resource server", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Nonce replay attack via missing or skipped nonce validation",
            "acr_values manipulation to downgrade authentication strength",
            "Audience confusion via missing aud claim validation on ID token",
            "Bearer token interception via redirect URI manipulation",
            "Signed vs encrypted hybrid token attacks (JWS/JWE confusion)",
            "ID token signature verification bypass",
            "Missing iss (issuer) validation allowing token injection from rogue OP",
            "Access token reused across different audiences",
            "Authorization code injection at token endpoint",
            "CBC padding oracle attack on JWE encrypted tokens",
            "UserInfo endpoint without proper access token validation",
            "Session management bypass via id_token_hint injection",
        ],
        investigation_areas=[
            "Test nonce replay by reusing a captured ID token",
            "Manipulate acr_values to request weaker authentication",
            "Check ID token aud claim validation against client_id",
            "Test bearer token interception by manipulating redirect_uri",
            "Parse JWE/JWS nested tokens for algorithm confusion",
            "Strip signature from ID token and test acceptance",
            "Swap ID token issuer and test if validated",
            "Reuse access token from one client against another's UserInfo",
            "Intercept and replay authorization code at token endpoint",
            "Test CBC padding oracle on JWE encrypted tokens",
            "Call UserInfo endpoint without access token",
            "Test id_token_hint manipulation for session modification",
        ],
        tags=["oidc", "openid", "authentication", "identity", "sso"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "content-type": "application/json",
        },
        cookies=["oidc_state", "oidc_session", "nonce", "auth_session", "__session"],
        js_indicators=["openid", "oidc", "userManager", "UserManager", "OidcClient", "auth0", "okta", "keycloak", "msal", "passport.authenticate", "openid-client"],
        file_indicators=["oidc-client.js", "oidc-client.ts", "auth_config.js", "auth.config.js", "msal.js", "keycloak.json", "keycloak.js", "angular-auth-oidc-client.js", "oidc-provider.js"],
        directory_indicators=["/.well-known/", "/oauth/", "/oidc/", "/auth/", "/.well-known/"],
        server_signatures=["openid", "oidc", "auth0", "okta", "keycloak", "cognito", "azure-ad", "identity-server"],
        error_page_signatures=["invalid_nonce", "invalid_id_token", "id_token validation failed", "invalid audience", "invalid issuer", "OpenIDConnectError", "acr_values not supported", "jose", "JWT validation failed", "oidc"],
        default_paths=["/.well-known/openid-configuration", "/.well-known/oauth-authorization-server", "/oauth/authorize", "/oauth/token", "/oauth/userinfo", "/oauth/jwks", "/oauth/introspect", "/oauth/revoke", "/oauth/end_session", "/.well-known/jwks.json"],
        default_files=["oidc-client.js", "auth_config.js", "auth.config.js", "keycloak.json", "msal.js", ".env", "openid-configuration.json", "jwks.json"],
        metadata_patterns={"openid-configuration": "pattern: .*/\\.[0-9]+\\.[0-9]+.*"},
        tags=["fingerprint", "oidc", "openid", "authentication"],
    ),
    recon=ReconProfile(
        directories_to_check=["/.well-known/", "/oauth/", "/oidc/", "/auth/", "/.well-known/"],
        files_to_check=["oidc-client.js", "auth_config.js", "auth.config.js", "keycloak.json", "msal.js", ".env", "jwks.json"],
        endpoints_to_scan=["/.well-known/openid-configuration", "/.well-known/oauth-authorization-server", "/.well-known/jwks.json", "/oauth/authorize", "/oauth/token", "/oauth/userinfo", "/oauth/jwks", "/oauth/introspect", "/oauth/end_session"],
        version_detection_paths=["/.well-known/openid-configuration", "/.well-known/oauth-authorization-server"],
        debug_paths_to_check=["/oauth/debug", "/oauth/token?debug=true", "/oauth/authorize?debug=true"],
        admin_paths_to_check=["/admin/oidc", "/admin/oidc/clients", "/admin/oidc/sessions", "/admin/oidc/tokens"],
        tags=["recon", "oidc", "openid", "authentication"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Nonce replay attack via missing or weak nonce validation",
            impact="Replay of captured ID tokens to impersonate users",
            attack_scenario="Capture a valid ID token with its nonce, then replay it in a new authentication session that skips or weakly validates the nonce",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="acr_values manipulation downgrades authentication strength",
            impact="Weak authentication accepted for sensitive operations requiring MFA or higher assurance",
            attack_scenario="Change acr_values from 'phr' (phishing-resistant) to 'urn:mace:incommon:iap:silver' or remove entirely to bypass MFA requirement",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Audience confusion via missing aud claim validation",
            impact="ID token issued for one application accepted by another, enabling cross-client impersonation",
            attack_scenario="Present ID token with aud set to a different client_id; the victim application accepts it without verifying the audience",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Bearer token interception via redirect URI manipulation",
            impact="Access token theft for impersonation and API access",
            attack_scenario="Register a client with a malicious redirect URI or exploit path traversal in redirect URI validation to intercept the authorization code or token",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Signed vs encrypted hybrid token attack (JWS/JWE confusion)",
            impact="Bypass of integrity protection allowing token forgery or claim manipulation",
            attack_scenario="If provider supports both signed-only and signed+encrypted tokens, strip the signature from an encrypted token or confuse the parsing to accept unsigned claims",
            complexity="high",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Missing iss (issuer) validation allows token injection from rogue provider",
            impact="Authentication bypass by injecting tokens from an attacker-controlled OpenID Provider",
            attack_scenario="Set up a rogue OIDC provider, issue ID tokens for victim's email, present them to application that doesn't validate the iss claim",
            complexity="high",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="oauth",
            relationship_type=KnowledgeRelationshipType.DEPENDS_ON,
            description="OIDC is built on top of OAuth 2.0",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="jwt",
            relationship_type=KnowledgeRelationshipType.IMPLEMENTS,
            description="OIDC uses JWTs as ID tokens",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="saml",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="OIDC competes with SAML for SSO and identity federation",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="rest",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="OIDC secures REST API access via access tokens",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="graphql",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="OIDC secures GraphQL API access via access tokens",
            confidence="medium",
        ),
    ],
    dependencies=[],
    related_packs=["oauth", "jwt", "saml", "rest", "graphql"],
    workflow=[
        "1. Discover OIDC provider configuration via /.well-known/openid-configuration",
        "2. Identify supported response types, scopes, claims, and acr_values",
        "3. Capture ID token and validate nonce handling/replay protection",
        "4. Test acr_values manipulation to weaken authentication",
        "5. Validate ID token aud, iss, exp, and signature verification",
        "6. Swap aud claim to test audience confusion",
        "7. Test bearer token interception through redirect URI fuzzing",
        "8. Analyze hybrid flow tokens for JWS/JWE confusion attacks",
        "9. Test UserInfo endpoint with stolen or invalid access tokens",
        "10. Attempt authorization code injection at token endpoint",
        "11. Test session management via id_token_hint and end_session endpoint",
        "12. Check for CBC padding oracle in JWE encrypted tokens",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="OIDC-01",
            category="Authentication",
            description="Test nonce replay by reusing an ID token in a new authorization request",
            expected_result="Server must validate nonce and reject replayed ID tokens",
            tools=["custom scripts", "curl", "Burp Suite"],
            references=["https://openid.net/specs/openid-connect-core-1_0.html#NonceNotes"],
        ),
        ManualTestChecklistItem(
            step_id="OIDC-02",
            category="Authentication",
            description="Manipulate acr_values to downgrade authentication strength",
            expected_result="Server should enforce minimum acr requirements for sensitive scopes",
            tools=["curl", "custom scripts"],
            references=["https://openid.net/specs/openid-connect-core-1_0.html#acrSemantics"],
        ),
        ManualTestChecklistItem(
            step_id="OIDC-03",
            category="Authorization",
            description="Test audience confusion by modifying aud claim in ID token",
            expected_result="Server must validate that aud matches the client_id and reject mismatches",
            tools=["jwt_tool", "custom scripts", "curl"],
            references=["https://openid.net/specs/openid-connect-core-1_0.html#IDToken"],
        ),
        ManualTestChecklistItem(
            step_id="OIDC-04",
            category="Information Disclosure",
            description="Test redirect URI manipulation for bearer token interception",
            expected_result="Only registered redirect URIs should be accepted, no path traversal allowed",
            tools=["curl", "Burp Suite Intruder"],
            references=["https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest"],
        ),
        ManualTestChecklistItem(
            step_id="OIDC-05",
            category="Cryptography",
            description="Test hybrid signed+encrypted token for JWS/JWE parsing confusion",
            expected_result="Token parsing must correctly handle nested JWS and JWE structures",
            tools=["custom scripts", "jose libraries"],
            references=["https://datatracker.ietf.org/doc/html/rfc7516", "https://datatracker.ietf.org/doc/html/rfc7515"],
        ),
        ManualTestChecklistItem(
            step_id="OIDC-06",
            category="Authentication",
            description="Test issuer validation by swapping ID token iss claim",
            expected_result="Server must validate iss against trusted issuers list",
            tools=["jwt_tool", "custom scripts"],
            references=["https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation"],
        ),
        ManualTestChecklistItem(
            step_id="OIDC-07",
            category="Information Disclosure",
            description="Test UserInfo endpoint with invalid or missing access token",
            expected_result="UserInfo endpoint must require valid access token",
            tools=["curl"],
            references=["https://openid.net/specs/openid-connect-core-1_0.html#UserInfo"],
        ),
        ManualTestChecklistItem(
            step_id="OIDC-08",
            category="Authorization",
            description="Test authorization code injection at token endpoint",
            expected_result="Token endpoint must validate code binding to client_id and redirect_uri",
            tools=["curl", "custom scripts"],
            references=["https://openid.net/specs/openid-connect-core-1_0.html#TokenEndpoint"],
        ),
    ],
    references=[
        {"title": "OpenID Connect Core 1.0", "url": "https://openid.net/specs/openid-connect-core-1_0.html"},
        {"title": "OpenID Connect Discovery 1.0", "url": "https://openid.net/specs/openid-connect-discovery-1_0.html"},
        {"title": "OAuth 2.0 for Native Apps (RFC 8252)", "url": "https://datatracker.ietf.org/doc/html/rfc8252"},
        {"title": "OAuth 2.0 Security Best Current Practice", "url": "https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics"},
        {"title": "JWT & JOSE Guide", "url": "https://auth0.com/docs/secure/tokens/json-web-tokens"},
        {"title": "PortSwigger OAuth/OIDC Attacks", "url": "https://portswigger.net/web-security/oauth"},
    ],
    cwe_ids=["CWE-294", "CWE-287", "CWE-290", "CWE-345", "CWE-310", "CWE-326", "CWE-200", "CWE-601", "CWE-306", "CWE-862", "CWE-270", "CWE-523", "CWE-311"],
    cve_ids=["CVE-2023-34092", "CVE-2023-29160", "CVE-2022-2880", "CVE-2022-23529", "CVE-2021-21318", "CVE-2020-15250", "CVE-2019-10074", "CVE-2018-0489"],
    tags=["oidc", "openid", "authentication", "identity", "sso", "cross-cutting"],
)
