"""REST knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="rest",
    version="1.0.0",
    category=KnowledgePackCategory.API,
    description="REST API: HTTP method overriding, mass assignment, lack of rate limiting, pagination-based data leaks, HATEOAS link manipulation, content negotiation bypass.",
    technology=TechnologyProfile(
        name="REST API",
        vendor="",
        language="",
        runtime="",
        description="REST (Representational State Transfer) is an architectural style for designing networked applications. RESTful APIs use HTTP methods (GET, POST, PUT, PATCH, DELETE) to perform CRUD operations on resources identified by URLs.",
        common_aliases=["rest", "restful", "rest-api", "restful-api"],
        dependencies=[],
        common_integrations=["OpenAPI/Swagger", "JSON:API", "OData", "HAL", "HATEOAS", "Postman", "Insomnia", "API Gateway", "Rate Limiter"],
        architecture_description="Stateless client-server architecture where resources are identified by URIs and manipulated through HTTP methods. Responses are typically JSON/XML with hypermedia links for navigation.",
        request_lifecycle="HTTP request -> API Gateway/Load Balancer -> Web server -> Router -> Controller -> Service -> Data access -> Response serialization -> HTTP response",
        documentation_url="https://restfulapi.net/",
        tags=["rest", "api", "http", "crud"],
    ),
    components=[
        TechnologyComponentProfile(
            name="HTTP Method Handling",
            description="REST APIs map CRUD operations to HTTP methods. Improper method handling can lead to method overriding and bypass attacks.",
            security_relevance="high",
            common_vulnerabilities=["HTTP method overriding via X-HTTP-Method-Override header", "Method tunneling via POST", "Verb tampering leading to auth bypass", "Unsupported method handling crash", "Arbitrary method execution on constrained endpoints"],
            investigation_priority=90,
            tags=["http-methods", "verb-tampering", "override"],
        ),
        TechnologyComponentProfile(
            name="Request Body / Payload Handling",
            description="JSON/XML deserialization of request bodies. Mass assignment allows setting properties not intended for client modification.",
            security_relevance="high",
            common_vulnerabilities=["Mass assignment via extra JSON fields", "Object injection via deserialization", "XML external entity injection", "Schema validation bypass using type confusion", "Nested object manipulation"],
            investigation_priority=90,
            tags=["mass-assignment", "deserialization", "json", "xml"],
        ),
        TechnologyComponentProfile(
            name="Rate Limiting",
            description="Mechanisms to limit API request frequency. Absence allows brute-force, scraping, and DoS attacks.",
            security_relevance="high",
            common_vulnerabilities=["Lack of rate limiting on authentication endpoints", "Rate limiting bypass via IP rotation", "Rate limiting bypass via header manipulation", "Undocumented unauthenticated endpoints without rate limits", "Rate limit resets via session manipulation"],
            investigation_priority=85,
            tags=["rate-limiting", "brute-force", "dos"],
        ),
        TechnologyComponentProfile(
            name="Pagination System",
            description="Offset/limit or cursor-based pagination for listing resources. Flawed pagination can leak data across boundaries.",
            security_relevance="medium",
            common_vulnerabilities=["Pagination-based data leaks via large offset", "IDOR via page/cursor enumeration", "Cursor manipulation to access unauthorized data", "Missing authorization on paginated endpoints", "Total count disclosure in pagination metadata"],
            investigation_priority=80,
            tags=["pagination", "data-leak", "enumeration"],
        ),
        TechnologyComponentProfile(
            name="HATEOAS / Hypermedia Links",
            description="Hypermedia links in API responses guide client navigation. Manipulated links can lead to unauthorized actions.",
            security_relevance="medium",
            common_vulnerabilities=["HATEOAS link manipulation attacks", "Undiscovered endpoints via link enumeration", "Link injection leading to open redirect", "Templated link parameter injection", "Missing validation on link targets"],
            investigation_priority=70,
            tags=["hateoas", "hypermedia", "links"],
        ),
        TechnologyComponentProfile(
            name="Content Negotiation",
            description="Server-side content type negotiation via Accept, Content-Type, and similar headers. Inconsistent handling can bypass security controls or reveal extra data.",
            security_relevance="medium",
            common_vulnerabilities=["Content negotiation bypass via Accept header", "JSONP endpoint abuse via callback parameter", "XML content-type enabling XXE", "Serialization format confusion", "Deserialization via content type switching"],
            investigation_priority=75,
            tags=["content-negotiation", "accept-header", "serialization"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="API Endpoint",
                description="REST resources identified by URL paths manipulated via HTTP methods",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/api/{resource}",
                parameters=["id", "page", "limit", "sort", "filter", "fields", "include"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.BROKEN_AUTH.value, BugClass.BUSINESS_LOGIC.value, BugClass.IDOR.value, BugClass.RATE_LIMIT_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="API Documentation",
                description="OpenAPI/Swagger docs endpoint",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/api/docs",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Authentication Endpoint",
                description="Login, token, and auth-related endpoints",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/api/auth/*",
                parameters=["username", "password", "token", "grant_type", "client_id", "client_secret"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.BROKEN_AUTH.value, BugClass.RATE_LIMIT_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/api/*", "/api/v1/*", "/api/v2/*", "/api/rest/*", "/swagger.json", "/api-docs", "/openapi.json", "/docs", "/api/auth/*", "/api/login", "/api/register"],
        parameters=["id", "page", "limit", "offset", "cursor", "sort", "order", "filter", "search", "fields", "include", "expand", "embed"],
        authentication=["JWT Bearer token", "API key in header", "Basic auth", "Session cookie", "OAuth2 token", "Custom header auth"],
        authorization=["Role-based access control", "Attribute-based access control", "Scope-based authorization", "Middleware guards", "Policy-based authorization"],
        storage=["Relational databases", "Document stores", "Object storage", "Key-value stores"],
        background_jobs=["Async task processors", "Webhook dispatchers", "Report generators"],
        queues=["Message queues", "Task queues", "Event buses"],
        caches=["API response cache", "Redis", "CDN cache", "ETag/Last-Modified"],
        admin_interfaces=["/admin", "/admin/*", "/api/admin", "/dashboard", "/admin/api"],
        internal_apis=["/internal/*", "/api/internal/*", "/admin/api/*", "/_internal/*"],
        external_apis=["Payment gateways", "Email services", "SMS providers", "Maps APIs", "Social login"],
        trust_boundaries=[
            TrustBoundary(name="Client-to-API", description="Client sends HTTP requests to the API", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="API-to-Database", description="API queries database for resource data", direction="outbound", sensitivity="high"),
            TrustBoundary(name="API-to-External-Service", description="API calls external third-party services", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "HTTP method overriding allowing auth bypass",
            "Mass assignment via extra JSON request body fields",
            "Lack of rate limiting on auth and data endpoints",
            "Pagination-based data leaks via offset/cursor manipulation",
            "HATEOAS link manipulation and injection",
            "Content negotiation bypass via Accept header switching",
            "Verb tampering to access restricted resources",
            "Inconsistent authorization across CRUD operations",
            "OpenAPI/Swagger exposure in production",
            "Undocumented debug/admin endpoints",
            "ETag/If-Modified-Since caching manipulation",
            "API versioning allowing access to deprecated insecure endpoints",
        ],
        investigation_areas=[
            "Test HTTP method overriding via X-HTTP-Method-Override header",
            "Send extra JSON fields to test for mass assignment",
            "Check rate limiting headers and test brute-force protection",
            "Manipulate offset/cursor beyond data range for data leaks",
            "Analyze HATEOAS links for manipulation possibilities",
            "Switch Accept headers between JSON, XML, and XHTML",
            "Test verb tampering (GET vs POST vs PATCH vs DELETE)",
            "Verify authorization consistency across all CRUD operations",
            "Check /swagger.json or /openapi.json accessibility",
            "Fuzz for undocumented endpoints (/admin, /debug, /internal)",
            "Test ETag/If-None-Match caching behavior",
            "Check older API versions for known vulnerabilities",
        ],
        tags=["rest", "api", "http"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "content-type": "application/json",
            "x-powered-by": "",
            "access-control-allow-origin": "",
        },
        cookies=["sessionid", "connect.sid", "PHPSESSID", "JSESSIONID", "api-key", "access_token", "refresh_token"],
        js_indicators=["api", "apiClient", "axios.get", "fetch(", "$.ajax", "api/v1", "apiUrl", "baseUrl", "endpoint"],
        file_indicators=["swagger.json", "openapi.json", "api-docs.json", ".env", "config/api.js", "routes/", "controllers/", "middleware/auth.js"],
        directory_indicators=["/api/", "/api/v1/", "/api/v2/", "/swagger/", "/docs/", "/routes/", "/controllers/", "/middleware/"],
        server_signatures=["express", "django", "flask", "spring", "asp.net", "nginx", "apache", "gunicorn", "uvicorn", "fastapi"],
        error_page_signatures=["Validation failed", "Bad Request", "404 Not Found", "405 Method Not Allowed", "500 Internal Server Error", "401 Unauthorized", "403 Forbidden", "422 Unprocessable Entity"],
        default_paths=["/api", "/api/v1", "/api/v2", "/swagger.json", "/openapi.json", "/api-docs", "/docs", "/health", "/status", "/metrics", "/"],
        default_files=["swagger.json", "openapi.json", ".env.example", "docker-compose.yml", "Dockerfile", "README.md", "requirements.txt", "package.json"],
        metadata_patterns={"openapi": "pattern: [0-9]+\\.[0-9]+\\.[0-9]+", "api-version": "pattern: v[0-9]+"},
        tags=["fingerprint", "rest", "api"],
    ),
    recon=ReconProfile(
        directories_to_check=["/api/", "/api/v1/", "/api/v2/", "/swagger/", "/docs/", "/admin/", "/health/", "/metrics/"],
        files_to_check=["swagger.json", "openapi.json", "api-docs.json", ".env", "docker-compose.yml", "Dockerfile", "package.json", "requirements.txt", "Procfile"],
        endpoints_to_scan=["/api", "/api/v1", "/api/v2", "/swagger.json", "/openapi.json", "/api-docs", "/docs", "/health", "/metrics", "/status"],
        version_detection_paths=["/api/version", "/version", "/api/v1/status", "/api/v2/status"],
        debug_paths_to_check=["/debug", "/__debug__", "/api/debug", "/_debug", "/api/_debug", "/dev", "/api/dev"],
        admin_paths_to_check=["/admin", "/admin/*", "/api/admin", "/dashboard", "/api/dashboard", "/admin/api"],
        tags=["recon", "rest", "api"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="HTTP method overriding allows bypassing method-based access controls",
            impact="Authentication and authorization bypass by switching HTTP methods",
            attack_scenario="Send GET to a POST-only endpoint with X-HTTP-Method-Override: POST to access restricted functionality",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Mass assignment via extra JSON fields allows manipulating unexposed properties",
            impact="Privilege escalation, data corruption, unauthorized state changes",
            attack_scenario="Add fields like 'is_admin': true, 'role': 'admin' to a PATCH request on /api/users",
            complexity="low",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="Lack of rate limiting enables brute-force credential attacks",
            impact="Account takeover via password brute-force, API key enumeration",
            attack_scenario="Send thousands of login requests with different passwords to enumerate valid credentials",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Pagination offset manipulation leaks records beyond authorized scope",
            impact="Unauthorized data access across tenant boundaries, data scraping",
            attack_scenario="Set large offset or manipulate cursor to access records belonging to other users",
            complexity="low",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="HATEOAS link manipulation enables unintended state transitions",
            impact="Unauthorized resource access, privilege escalation via link discovery",
            attack_scenario="Modify href values in HATEOAS links to access resources outside authorized scope",
            complexity="medium",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="Content negotiation bypass via Accept header switching enables XXE or data leakage",
            impact="XML External Entity injection, sensitive data exposure via alternative serialization formats",
            attack_scenario="Switch Accept header to application/xml and inject XXE payload in the request",
            complexity="medium",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="graphql",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="REST competes with GraphQL as an API paradigm",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="jwt",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="REST APIs commonly use JWT for authentication",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="oauth",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="REST APIs use OAuth2 for delegated authorization",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="oauth",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="REST APIs integrate with OAuth2 providers for SSO",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="saml",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="Enterprise REST APIs may use SAML for SSO",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="oidc",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="REST APIs can use OIDC for identity layer on OAuth2",
            confidence="medium",
        ),
    ],
    dependencies=[],
    related_packs=["graphql", "jwt", "oauth", "saml", "oidc"],
    workflow=[
        "1. Discover API endpoints via docs, JS files, or common paths",
        "2. Test HTTP method overriding with X-HTTP-Method-Override header",
        "3. Send extra JSON body fields to test mass assignment",
        "4. Check rate limiting headers and attempt brute-force",
        "5. Manipulate pagination parameters to leak data",
        "6. Analyze response hypermedia links for manipulation",
        "7. Switch Accept/Content-Type headers for content negotiation bypass",
        "8. Test verb tampering across all discovered endpoints",
        "9. Verify consistent authorization across GET/POST/PUT/PATCH/DELETE",
        "10. Check for OpenAPI/Swagger docs exposure",
        "11. Fuzz for internal/debug/admin endpoints",
        "12. Explore older API versions for deprecated vulnerable functionality",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="REST-01",
            category="Authentication Bypass",
            description="Test HTTP method overriding via X-HTTP-Method-Override, X-HTTP-Method, X-Method-Override headers",
            expected_result="Server should reject or ignore method override headers",
            tools=["curl", "Burp Suite", "custom scripts"],
            references=["https://owasp.org/www-community/attacks/HTTP_Method_Override"],
        ),
        ManualTestChecklistItem(
            step_id="REST-02",
            category="Mass Assignment",
            description="Send extra JSON fields in POST/PUT/PATCH to test mass assignment",
            expected_result="Unexpected fields should be ignored or rejected",
            tools=["curl", "Burp Suite"],
            references=["https://cheatsheetseries.owasp.org/cheatsheets/Mass_Assignment_Cheat_Sheet.html"],
        ),
        ManualTestChecklistItem(
            step_id="REST-03",
            category="Rate Limiting",
            description="Check rate limiting headers (X-RateLimit-*) and bypass attempts",
            expected_result="Rate limiting should be enforced on auth and data endpoints",
            tools=["curl", "custom scripts", "Burp Suite Intruder"],
            references=["https://cheatsheetseries.owasp.org/cheatsheets/Denial_of_Service_Cheat_Sheet.html"],
        ),
        ManualTestChecklistItem(
            step_id="REST-04",
            category="Data Leakage",
            description="Manipulate pagination offset/cursor far beyond data range",
            expected_result="Should not expose records outside authorized scope",
            tools=["curl", "custom scripts"],
            references=["https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/"],
        ),
        ManualTestChecklistItem(
            step_id="REST-05",
            category="Content Negotiation",
            description="Switch Accept header between JSON, XML, XHTML, and text/plain",
            expected_result="Responses should be consistent and not leak data via alternate formats",
            tools=["curl"],
            references=["https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation"],
        ),
        ManualTestChecklistItem(
            step_id="REST-06",
            category="Information Disclosure",
            description="Check for OpenAPI/Swagger documentation endpoints",
            expected_result="API documentation should not be accessible without authentication in production",
            tools=["curl", "browser"],
            references=["https://swagger.io/docs/"],
        ),
        ManualTestChecklistItem(
            step_id="REST-07",
            category="Authorization",
            description="Test verb tampering: use GET on POST-only endpoints and vice versa",
            expected_result="Authorization should be consistent regardless of HTTP method",
            tools=["curl"],
            references=["https://owasp.org/www-community/attacks/HTTP_Verb_Tampering"],
        ),
    ],
    references=[
        {"title": "REST API Tutorial", "url": "https://restfulapi.net/"},
        {"title": "OWASP REST Security Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html"},
        {"title": "OWASP API Security Top 10", "url": "https://owasp.org/www-project-api-security/"},
        {"title": "Microsoft REST API Guidelines", "url": "https://github.com/microsoft/api-guidelines"},
        {"title": "JSON API Specification", "url": "https://jsonapi.org/"},
    ],
    cwe_ids=["CWE-287", "CWE-915", "CWE-770", "CWE-200", "CWE-601", "CWE-611", "CWE-862", "CWE-639", "CWE-345", "CWE-352"],
    cve_ids=["CVE-2023-29489", "CVE-2022-35969", "CVE-2022-38197", "CVE-2021-26084", "CVE-2020-9484"],
    tags=["rest", "api", "http", "crud", "cross-cutting"],
)
