"""SAML knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="saml",
    version="1.0.0",
    category=KnowledgePackCategory.AUTHENTICATION,
    description="SAML: XML signature wrapping, Assertion injection, response tampering, issuer spoofing, missing audience restriction, Replay attack (missing NotOnOrAfter).",
    technology=TechnologyProfile(
        name="SAML (Security Assertion Markup Language)",
        vendor="OASIS",
        language="XML",
        runtime="",
        description="SAML (Security Assertion Markup Language) is an XML-based framework for exchanging authentication and authorization data between parties, particularly between an identity provider (IdP) and a service provider (SP).",
        common_aliases=["saml", "saml2", "saml-2.0", "saml-assertion"],
        dependencies=["XML Digital Signature", "XML Encryption"],
        common_integrations=["Okta", "Azure AD", "AWS IAM", "Salesforce", "OneLogin", "Ping Identity", "Keycloak", "ADFS", "ForgeRock", "Shibboleth", "SimpleSAMLphp"],
        architecture_description="SAML defines three roles: principal (user), identity provider (IdP), and service provider (SP). The IdP authenticates the user and issues a SAML assertion, which the SP consumes to grant access. Assertions are XML documents signed with XML Signature.",
        request_lifecycle="User attempts to access SP resource -> SP generates AuthnRequest -> User redirected to IdP -> IdP authenticates user -> IdP generates SAML Response (XML assertion) -> User POSTs assertion to SP ACS endpoint -> SP validates signature and conditions -> Access granted",
        documentation_url="https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=security",
        tags=["saml", "saml2", "authentication", "sso", "xml"],
    ),
    components=[
        TechnologyComponentProfile(
            name="SAML Assertion",
            description="XML document containing authentication and attribute statements. Contains conditions (audience, validity), subject, and attribute statements.",
            security_relevance="high",
            common_vulnerabilities=["Assertion injection via XML manipulation", "Response tampering via unsigned or weakly signed assertions", "Issuer spoofing via manipulated Issuer element", "Missing audience restriction allowing cross-SP access", "Weak subject confirmation method"],
            investigation_priority=95,
            tags=["assertion", "xml", "authentication-statement"],
        ),
        TechnologyComponentProfile(
            name="XML Signature Wrapping",
            description="SAML assertions are signed using XML Signature (XMLDSig). Signature wrapping exploits the discrepancy between what the XML signature covers and what the application processes.",
            security_relevance="high",
            common_vulnerabilities=["XML signature wrapping attack by injecting duplicate elements", "Signature exclusion via XPath manipulation", "Reference URI manipulation to bypass signature coverage", "KeyInfo element injection for key confusion", "Detached signature confusion"],
            investigation_priority=95,
            tags=["xml-signature", "signature-wrapping", "xmldsig", "wrapping"],
        ),
        TechnologyComponentProfile(
            name="SAML Response / Protocol",
            description="The SAML Response XML document containing the assertion. Protocol-level vulnerabilities enable injection and replay.",
            security_relevance="high",
            common_vulnerabilities=["Response tampering by modifying InResponseTo attribute", "Replay attack via missing or weak NotOnOrAfter / NotBefore conditions", "Destination attribute validation bypass", "XML external entity injection in SAML response", "XSLT transformation injection"],
            investigation_priority=95,
            tags=["response", "protocol", "replay", "tampering"],
        ),
        TechnologyComponentProfile(
            name="Issuer Element",
            description="XML element identifying the issuer of the SAML assertion. Spoofing allows impersonation of trusted IdPs.",
            security_relevance="high",
            common_vulnerabilities=["Issuer spoofing via unchecked Issuer element", "Issuer confusion when multiple IdPs are supported", "Issuer element injection via XML manipulation", "Missing issuer validation allowing token from untrusted IdP"],
            investigation_priority=90,
            tags=["issuer", "spoofing", "trust"],
        ),
        TechnologyComponentProfile(
            name="Audience Restriction",
            description="SAML conditions element that restricts which SP can consume the assertion. Missing restrictions allow cross-application access.",
            security_relevance="high",
            common_vulnerabilities=["Missing AudienceRestriction condition", "Wildcard audience acceptance", "Audience value manipulation", "Weak audience validation (prefix or substring match)", "Cross-application assertion reuse"],
            investigation_priority=90,
            tags=["audience", "restriction", "cross-sp"],
        ),
        TechnologyComponentProfile(
            name="Conditions / Assertion Validity",
            description="Time-based conditions (NotBefore, NotOnOrAfter) that control assertion validity. Missing or weak time constraints enable replay.",
            security_relevance="high",
            common_vulnerabilities=["Missing NotOnOrAfter allowing infinite assertion validity", "Large time skew (NotBefore long in past)", "Clock skew exploitation between IdP and SP", "Conditions element removal via XML manipulation", "OneTimeUse condition bypass"],
            investigation_priority=90,
            tags=["conditions", "validity", "replay", "time-based"],
        ),
        TechnologyComponentProfile(
            name="XML Parsing / Processing",
            description="XML parser behavior when processing SAML documents. XXE, XSLT, and entity expansion vulnerabilities.",
            security_relevance="high",
            common_vulnerabilities=["XML External Entity (XXE) injection in SAML documents", "XML entity expansion (billion laughs) DoS", "XSLT transformation injection", "DTD-based attacks", "Namespace confusion attacks", "Coercive parsing attacks"],
            investigation_priority=85,
            tags=["xml-parsing", "xxe", "entity-expansion", "xslt"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Assertion Consumer Service (ACS)",
                description="Endpoint where SP receives SAML responses from the user's browser via HTTP POST",
                protocol="HTTP/HTTPS",
                method="POST",
                path="/saml/acs",
                parameters=["SAMLResponse", "RelayState"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.XXE.value, BugClass.BUSINESS_LOGIC.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="SAML Login / SSO Initiation",
                description="Endpoint initiating SAML authentication request",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/saml/login",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.OPEN_REDIRECT.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Metadata Endpoint",
                description="SP or IdP metadata XML endpoint",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/saml/metadata",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Single Logout (SLO) Endpoint",
                description="SAML single logout endpoint",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/saml/slo",
                parameters=["SAMLRequest", "SAMLResponse", "RelayState"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.BUSINESS_LOGIC.value],
            ),
        ],
        endpoints=["/saml/acs", "/saml/login", "/saml/metadata", "/saml/slo", "/saml/sso", "/saml/sp/metadata", "/saml/idp/metadata", "/auth/saml", "/api/auth/saml"],
        parameters=["SAMLResponse", "SAMLRequest", "RelayState", "SigAlg", "Signature", "encoding"],
        authentication=["SAML assertion via HTTP POST binding", "SAML artifact via HTTP redirect binding", "SAML attribute statements for authorization"],
        authorization=["SAML attribute statements", "SAML authorization decision statements", "Role/group attributes"],
        storage=["SAML session store", "Assertion cache", "Artifact resolution store"],
        background_jobs=["Session cleanup", "Metadata refresh"],
        queues=[],
        caches=["Metadata cache", "IdP public key cache"],
        admin_interfaces=["/admin/saml", "/admin/saml/metadata", "/admin/saml/certificates"],
        internal_apis=["/internal/saml/validate", "/internal/saml/resolve_artifact"],
        external_apis=["Okta", "Azure AD", "AWS IAM", "Salesforce", "OneLogin", "Ping Identity", "Keycloak", "ADFS", "Shibboleth"],
        trust_boundaries=[
            TrustBoundary(name="Browser-to-SP", description="User's browser POSTs SAML response to SP ACS", direction="inbound", sensitivity="high"),
            TrustBoundary(name="SP-to-IdP", description="SP communicates with IdP for artifact resolution", direction="outbound", sensitivity="high"),
            TrustBoundary(name="SP-to-Metadata-Source", description="SP fetches IdP metadata", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "XML signature wrapping allowing assertion forgery",
            "Assertion injection via duplicate element insertion",
            "Response tampering via unsigned assertion modification",
            "Issuer spoofing via Issuer element manipulation",
            "Missing audience restriction enabling cross-SP assertion reuse",
            "Replay attack via missing NotOnOrAfter condition",
            "XXE injection in SAML XML documents",
            "Missing Destination attribute validation on Response",
            "Weak or missing SubjectConfirmation validation",
            "XML entity expansion (DoS) via SAML document",
            "Clock skew exploitation between IdP and SP",
            "SAML metadata poisoning via fake metadata injection",
        ],
        investigation_areas=[
            "Test XML signature wrapping by inserting duplicate assertions",
            "Inject additional Assertion elements into SAML Response",
            "Modify unsigned assertions in SAML response",
            "Spoof Issuer element with trusted IdP name but attacker-controlled assertion",
            "Remove or modify AudienceRestriction to reuse assertion on different SP",
            "Replay SAML response after NotOnOrAfter timestamp",
            "Inject XXE payload in SAML Response XML",
            "Modify Destination attribute in Response",
            "Remove or weaken SubjectConfirmation element",
            "Test billion laughs XML entity expansion DoS",
            "Exploit clock skew by sending future-dated assertions",
            "Modify SP metadata to accept attacker-controlled IdP",
        ],
        tags=["saml", "saml2", "authentication", "sso", "xml"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "content-type": "text/xml",
        },
        cookies=["saml_session", "saml", "auth_session", "relay_state"],
        js_indicators=["saml", "SAML", "SAMLResponse", "SAMLRequest", "RelayState", "okta", "onelogin", "adfs", "samlify", "saml2"],
        file_indicators=["saml.js", "saml.py", "saml_config.js", "saml.php", "metadata.xml", "saml20-idp-remote.php", "saml20-sp-remote.php", "adfs_metadata.xml", "okta_cert.pem", "sp.key", "sp.crt", "idp.key", "idp.crt"],
        directory_indicators=["/saml/", "/auth/saml/", "/metadata/", "/simplesaml/", "/Shibboleth.sso/"],
        server_signatures=["saml", "shibboleth", "simplesamlphp", "pingsso", "okta", "onelogin", "adfs", "keycloak"],
        error_page_signatures=["SAML Response validation failed", "Invalid SAML Response", "Invalid assertion", "authn failed", "audience mismatch", "issuer mismatch", "NotOnOrAfter", "NotBefore", "SAML validation error", "SAML2", "saml:Assertion"],
        default_paths=["/saml/acs", "/saml/login", "/saml/metadata", "/saml/slo", "/simplesaml/", "/Shibboleth.sso/SAML2/POST", "/Shibboleth.sso/Login", "/Shibboleth.sso/Metadata"],
        default_files=["metadata.xml", "saml20-idp-remote.php", "saml20-sp-remote.php", "sp.key", "sp.crt", "idp.key", "idp.crt", "saml_config.js", "okta_cert.pem"],
        metadata_patterns={"saml-metadata": "pattern: urn:oasis:names:tc:SAML:2\\.0:metadata"},
        tags=["fingerprint", "saml", "saml2", "authentication"],
    ),
    recon=ReconProfile(
        directories_to_check=["/saml/", "/auth/saml/", "/metadata/", "/simplesaml/", "/Shibboleth.sso/"],
        files_to_check=["metadata.xml", "saml20-idp-remote.php", "saml20-sp-remote.php", "sp.key", "sp.crt", "idp.key", "idp.crt", "saml_config.js", "okta_cert.pem"],
        endpoints_to_scan=["/saml/acs", "/saml/login", "/saml/metadata", "/saml/slo", "/simplesaml/", "/Shibboleth.sso/SAML2/POST", "/Shibboleth.sso/Login", "/Shibboleth.sso/Metadata"],
        version_detection_paths=["/saml/metadata", "/Shibboleth.sso/Metadata"],
        debug_paths_to_check=["/saml/debug", "/simplesaml/module.php/saml/debug", "/Shibboleth.sso/"],
        admin_paths_to_check=["/admin/saml", "/admin/saml/metadata", "/admin/saml/certificates", "/simplesaml/admin/"],
        tags=["recon", "saml", "saml2", "authentication"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="XML signature wrapping allows forging assertions while bypassing signature validation",
            impact="Complete authentication bypass, arbitrary user impersonation, privilege escalation",
            attack_scenario="Insert a duplicate Assertion element outside the signed portion while keeping the original valid assertion signed; SP processes the injected unsigned assertion",
            complexity="high",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Assertion injection via duplicate element insertion in SAML Response",
            impact="Forged authentication and authorization data",
            attack_scenario="Intercept the SAML Response, inject an additional Assertion element with attacker-controlled attributes and subject",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Response tampering via modifying unsigned or weakly protected assertions",
            impact="Modification of user identity, attributes, or authorization level",
            attack_scenario="Modify SAML attribute values (e.g., role, email, group membership) when the assertion is unsigned or uses weak signing",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Issuer spoofing by manipulating the Issuer element in the SAML response",
            impact="Assertion accepted from untrusted or malicious identity provider",
            attack_scenario="Change the Issuer element to a trusted IdP entity ID while the assertion comes from an attacker-controlled source",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Missing audience restriction allows SAML assertion reuse across different service providers",
            impact="Unauthorized access to multiple services using a single assertion",
            attack_scenario="Remove or modify the AudienceRestriction condition and present the assertion to a different SP endpoint",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Replay attack via missing NotOnOrAfter condition allows indefinite assertion reuse",
            impact="Perpetual access using captured assertion, session hijacking",
            attack_scenario="Capture a valid SAML response, remove the NotOnOrAfter condition, and repeatedly submit it over time",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="XXE injection in SAML XML documents allows file disclosure and SSRF",
            impact="Server-side file disclosure, internal network scanning, denial of service",
            attack_scenario="Inject XML External Entity payload in SAML Response to read /etc/passwd or perform SSRF to internal services",
            complexity="medium",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="oauth",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="SAML competes with OAuth2 for SSO and authorization",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="oidc",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="SAML competes with OIDC as an identity federation protocol",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="jwt",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="SAML assertions compete with JWT as token formats",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="rest",
            relationship_type=KnowledgeRelationshipType.AUTHENTICATES_WITH,
            description="SAML can authenticate REST API requests via bearer assertions",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="rest",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="SAML integrates with REST APIs for enterprise SSO",
            confidence="high",
        ),
    ],
    dependencies=[],
    related_packs=["oauth", "oidc", "jwt", "rest", "graphql"],
    workflow=[
        "1. Discover SAML endpoints (/saml/acs, /saml/login, /saml/metadata)",
        "2. Fetch SP/IdP metadata XML from /saml/metadata",
        "3. Capture a valid SAMLResponse from the ACS endpoint",
        "4. Test XML signature wrapping by inserting duplicate elements",
        "5. Inject additional Assertion elements into the response",
        "6. Modify attribute statements (role, email, uid) in the assertion",
        "7. Spoof the Issuer element to a different trusted IdP",
        "8. Remove or modify AudienceRestriction for cross-SP use",
        "9. Remove NotOnOrAfter condition for replay attack",
        "10. Test XXE injection in SAML XML documents",
        "11. Modify Destination attribute in the Response",
        "12. Modify SubjectConfirmation method or data",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="SAML-01",
            category="XML Signature",
            description="Test XML signature wrapping by inserting a duplicate Assertion outside the signature",
            expected_result="SP must reject assertions not covered by the XML signature",
            tools=["Burp Suite", "custom scripts", "saml_toolkit", "SAML Raider"],
            references=["https://www.usenix.org/conference/usenixsecurity12/technical-sessions/presentation/somorovsky"],
        ),
        ManualTestChecklistItem(
            step_id="SAML-02",
            category="Injection",
            description="Inject additional Assertion elements with forged user attributes",
            expected_result="SP should only process properly signed assertions",
            tools=["Burp Suite", "SAML Raider", "custom scripts"],
            references=["https://owasp.org/www-community/attacks/SAML_Security_Cheat_Sheet"],
        ),
        ManualTestChecklistItem(
            step_id="SAML-03",
            category="Authorization",
            description="Modify attribute values (role, permission, group) in the assertion",
            expected_result="SP must validate assertion signature and not accept tampered attributes",
            tools=["Burp Suite", "SAML Raider", "custom scripts"],
            references=["https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf"],
        ),
        ManualTestChecklistItem(
            step_id="SAML-04",
            category="Authentication",
            description="Spoof Issuer element with a trusted IdP entity ID",
            expected_result="SP must validate Issuer against trusted IdP list AND validate signature with the correct IdP key",
            tools=["Burp Suite", "SAML Raider"],
            references=["https://sso.rocks/"],
        ),
        ManualTestChecklistItem(
            step_id="SAML-05",
            category="Authorization",
            description="Remove AudienceRestriction or modify to a different SP entity ID",
            expected_result="SP must reject assertions with non-matching audience",
            tools=["Burp Suite", "SAML Raider", "custom scripts"],
            references=["https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf"],
        ),
        ManualTestChecklistItem(
            step_id="SAML-06",
            category="Replay",
            description="Remove NotOnOrAfter condition and replay the SAML response",
            expected_result="SP must enforce time-based conditions (NotBefore, NotOnOrAfter)",
            tools=["Burp Suite", "SAML Raider", "curl"],
            references=["https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf"],
        ),
        ManualTestChecklistItem(
            step_id="SAML-07",
            category="XXE",
            description="Test XML External Entity injection in SAMLResponse XML",
            expected_result="XML parser must be configured to disable external entity resolution",
            tools=["curl", "custom scripts"],
            references=["https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html"],
        ),
        ManualTestChecklistItem(
            step_id="SAML-08",
            category="Authentication",
            description="Test SubjectConfirmation method manipulation (bearer vs holder-of-key)",
            expected_result="SP must enforce SubjectConfirmation requirements",
            tools=["Burp Suite", "SAML Raider"],
            references=["https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf"],
        ),
    ],
    references=[
        {"title": "SAML 2.0 Core Specification", "url": "https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf"},
        {"title": "SAML 2.0 Technical Overview", "url": "https://www.oasis-open.org/committees/download.php/27819/sstc-saml-tech-overview-2.0-cd-02.pdf"},
        {"title": "OWASP SAML Security Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/SAML_Security_Cheat_Sheet.html"},
        {"title": "XML Signature Wrapping Attacks", "url": "https://www.usenix.org/conference/usenixsecurity12/technical-sessions/presentation/somorovsky"},
        {"title": "SAML Raider (Burp Suite Extension)", "url": "https://github.com/SAMLRaider/SAMLRaider"},
        {"title": "Hacking SAML: A Developer's Guide", "url": "https://sso.rocks/"},
    ],
    cwe_ids=["CWE-287", "CWE-290", "CWE-345", "CWE-347", "CWE-302", "CWE-20", "CWE-611", "CWE-613", "CWE-829", "CWE-863", "CWE-16", "CWE-106", "CWE-611"],
    cve_ids=["CVE-2023-43641", "CVE-2022-24899", "CVE-2022-23514", "CVE-2021-21300", "CVE-2020-5408", "CVE-2019-3789", "CVE-2018-0489", "CVE-2017-11429", "CVE-2017-5636"],
    tags=["saml", "saml2", "authentication", "sso", "xml", "cross-cutting"],
)
