"""AWS knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="aws",
    version="1.0.0",
    category=KnowledgePackCategory.CLOUD,
    description="Amazon Web Services — EC2 metadata service SSRF, S3 bucket enumeration and public access, IAM privilege escalation, Lambda function injection, API Gateway misconfiguration, CloudFront exposure, Cognito misconfiguration, CloudFormation template leakage, EBS snapshot exposure, RDS public access, and CloudTrail logging bypass.",
    technology=TechnologyProfile(
        name="Amazon Web Services",
        vendor="Amazon",
        language="",
        runtime="AWS Global Infrastructure",
        description="Amazon Web Services (AWS) is the world's most comprehensive and broadly adopted cloud platform, offering over 200 fully featured services from data centers globally. Includes compute (EC2, Lambda), storage (S3, EBS, EFS), database (RDS, DynamoDB), networking (VPC, API Gateway, CloudFront), and security (IAM, Cognito, WAF).",
        common_aliases=["aws", "amazon web services", "ec2", "s3", "lambda"],
        dependencies=["AWS SDK", "AWS CLI", "Terraform", "CloudFormation", "Kubernetes (EKS)"],
        common_integrations=["S3", "EC2", "Lambda", "IAM", "API Gateway", "CloudFront", "RDS", "DynamoDB", "Cognito", "CloudTrail", "CloudWatch", "Route53", "SQS", "SNS", "Kinesis", "Step Functions"],
        architecture_description="Global infrastructure of Regions and Availability Zones. Each AZ has one or more data centers. Services are accessed via API endpoints (global or regional). IAM provides centralized access control across all services. VPC provides network isolation.",
        request_lifecycle="Client -> AWS API Endpoint (auth via SigV4/IAM) -> Service-specific processing -> Response signed by AWS",
        documentation_url="https://docs.aws.amazon.com/",
        tags=["cloud", "aws", "amazon", "iaas", "paas", "faas"],
    ),
    components=[
        TechnologyComponentProfile(
            name="EC2 Metadata Service",
            description="HTTP endpoint at 169.254.169.254 providing instance metadata including IAM credentials, user data, and network configuration. Primary SSRF target.",
            security_relevance="high",
            common_vulnerabilities=["SSRF exploitation to access metadata service", "IMDSv1 (no session-based auth) allowing credential theft", "User data extraction containing secrets and scripts", "IAM role credential theft from metadata"],
            investigation_priority=95,
            tags=["ec2", "metadata", "ssrf", "imds", "credentials"],
        ),
        TechnologyComponentProfile(
            name="S3 (Simple Storage Service)",
            description="Object storage service with bucket-level and object-level access policies. Public buckets, misconfigured bucket policies, and unauthenticated access.",
            security_relevance="high",
            common_vulnerabilities=["Publicly readable S3 buckets", "Bucket listing enabled without auth", "Bucket policy misconfiguration allowing write access", "S3 ACL misconfiguration", "S3 object versioning exposing deleted data", "S3 bucket takeover via DNS"],
            investigation_priority=95,
            tags=["s3", "storage", "bucket", "public-access", "data-leak"],
        ),
        TechnologyComponentProfile(
            name="IAM (Identity and Access Management)",
            description="Centralized access control for all AWS services. Users, groups, roles, and policies define permissions. Misconfiguration leads to privilege escalation.",
            security_relevance="high",
            common_vulnerabilities=["Overly permissive IAM policies (Action: *)", "PassRole to EC2 allowing privilege escalation", "IAM user with full admin access", "Cross-account trust misconfiguration", "Unused IAM credentials and access keys", "AssumeRole privilege escalation"],
            investigation_priority=95,
            tags=["iam", "auth", "authorization", "roles", "policies"],
        ),
        TechnologyComponentProfile(
            name="Lambda",
            description="Serverless compute service running functions in response to events. Function code, environment variables, and IAM execution role.",
            security_relevance="high",
            common_vulnerabilities=["Event injection into Lambda functions", "Environment variable leakage (DB creds, API keys)", "Overly permissive Lambda execution role", "Lambda function URL exposed without auth", "Third-party library dependency vulnerabilities", "Code injection via unsanitized event input"],
            investigation_priority=90,
            tags=["lambda", "serverless", "faas", "injection", "env"],
        ),
        TechnologyComponentProfile(
            name="API Gateway",
            description="Managed API service for creating RESTful and WebSocket APIs. Exposed endpoints, auth bypass, and Lambda integration issues.",
            security_relevance="high",
            common_vulnerabilities=["API Gateway exposed to the internet without auth", "Missing resource policy restricting access", "API key in URL/query string", "Lambda authorizer misconfiguration", "WAF not attached allowing OWASP top 10 attacks", "Excessive API endpoint exposure (wildcard paths)"],
            investigation_priority=90,
            tags=["api-gateway", "api", "rest", "websocket", "exposure"],
        ),
        TechnologyComponentProfile(
            name="Cognito",
            description="Identity platform for web and mobile apps. User pools, identity pools, and federated identities.",
            security_relevance="medium",
            common_vulnerabilities=["Cognito user pool exposed without auth", "Weak password policies in user pool", "Unverified email/phone signup enabled", "Identity pool with unauthenticated access", "AWS credentials leaked via Cognito identity pool ID"],
            investigation_priority=85,
            tags=["cognito", "identity", "auth", "user-pool"],
        ),
        TechnologyComponentProfile(
            name="CloudFront",
            description="Content delivery network (CDN) service. Origin exposure, misconfigured security policies, and WAF bypass.",
            security_relevance="medium",
            common_vulnerabilities=["CloudFront origin exposure (direct S3/EC2 access bypassing CDN)", "Missing WAF (Web ACL) on distribution", "Geographic restriction bypass", "Invalidation of CloudFront logs", "Custom SSL/TLS certificate misconfiguration", "CloudFront function injection"],
            investigation_priority=80,
            tags=["cloudfront", "cdn", "waf", "edge"],
        ),
        TechnologyComponentProfile(
            name="RDS (Relational Database Service)",
            description="Managed database service supporting PostgreSQL, MySQL, MariaDB, Oracle, SQL Server, and Aurora. Public access and weak credentials.",
            security_relevance="high",
            common_vulnerabilities=["RDS instance publicly accessible", "Default or weak master credentials", "RDS snapshot shared publicly", "Automated backup exposure", "SSL/TLS not enforced for connections", "RDS proxy misconfiguration"],
            investigation_priority=85,
            tags=["rds", "database", "public", "snapshot"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="EC2 Instance Metadata Service",
                description="SSRF target at http://169.254.169.254/latest/meta-data/",
                protocol="HTTP",
                method="GET",
                path="http://169.254.169.254/latest/meta-data/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.SSRF.value, BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="S3 Bucket",
                description="S3 bucket potentially allowing public listing or object access",
                protocol="HTTPS",
                method="GET",
                path="https://{bucket}.s3.amazonaws.com/",
                parameters=["prefix", "delimiter", "max-keys"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="AWS API Endpoint",
                description="AWS service API endpoints for various services",
                protocol="HTTPS",
                method="ANY",
                path="https://{service}.{region}.amazonaws.com/",
                parameters=["Action", "Version", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Signature"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.PRIVILEGE_ESCALATION.value],
            ),
            AttackSurfaceEntry(
                name="Lambda Function URL",
                description="Lambda function URL endpoint potentially exposed without auth",
                protocol="HTTPS",
                method="ANY",
                path="https://{url-id}.lambda-url.{region}.on.aws/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.RCE.value, BugClass.INFO_DISCLOSURE.value, BugClass.COMMAND_INJECTION.value],
            ),
            AttackSurfaceEntry(
                name="API Gateway Endpoint",
                description="REST/WebSocket API endpoint exposed via API Gateway",
                protocol="HTTPS",
                method="ANY",
                path="https://{api-id}.execute-api.{region}.amazonaws.com/{stage}/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.COMMAND_INJECTION.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Cognito User Pool",
                description="Cognito hosted UI and API endpoints for authentication",
                protocol="HTTPS",
                method="ANY",
                path="https://{domain}.auth.{region}.amazoncognito.com/",
                parameters=["client_id", "redirect_uri", "response_type", "scope"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="CloudFront Distribution",
                description="CloudFront CDN distribution with potential origin exposure",
                protocol="HTTPS",
                method="ANY",
                path="https://{distribution}.cloudfront.net/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
        ],
        endpoints=["http://169.254.169.254/latest/meta-data/iam/security-credentials/", "https://{bucket}.s3.amazonaws.com/", "https://{bucket}.s3.{region}.amazonaws.com/", "https://{api-id}.execute-api.{region}.amazonaws.com/{stage}/", "https://{url-id}.lambda-url.{region}.on.aws/", "https://sts.amazonaws.com", "https://iam.amazonaws.com", "https://s3.amazonaws.com"],
        parameters=["Action", "Version", "X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-SignedHeaders", "X-Amz-Signature", "AWSAccessKeyId", "Signature", "Expires", "prefix", "delimiter", "max-keys", "marker"],
        authentication=["IAM user access keys (access key ID + secret access key)", "IAM role (temporary credentials via STS AssumeRole)", "Cognito user pool tokens (ID token, access token, refresh token)", "S3 pre-signed URLs", "CloudFront signed URLs/Cookies", "API Gateway API keys", "IAM roles for EC2 (instance profile)", "SAML/SSO federation", "Web identity federation (Cognito Identity Pools)"],
        authorization=["IAM policies (identity-based and resource-based)", "S3 bucket policies and ACLs", "SQS queue policies", "SNS topic policies", "KMS key policies", "Lambda resource-based policies", "API Gateway resource policies", "VPC endpoint policies"],
        storage=["S3", "EBS (Elastic Block Store)", "EFS (Elastic File System)", "Glacier/Glacier Deep Archive", "RDS (Relational Database Service)", "DynamoDB", "ElastiCache", "SQS (Simple Queue Service)", "SNS (Simple Notification Service)"],
        background_jobs=["AWS Lambda (async invocation)", "SQS message processing", "SNS topic delivery", "CloudWatch Events/EventBridge rules", "Step Functions state machines", "EC2 Auto Scaling", "AWS Batch jobs", "Glue ETL jobs"],
        queues=["SQS (Standard and FIFO queues)", "SNS (pub/sub messaging)", "Kinesis Data Streams", "EventBridge event bus", "MQ (ActiveMQ/RabbitMQ)"],
        caches=["ElastiCache (Redis/Memcached)", "CloudFront edge cache", "DAX (DynamoDB Accelerator)", "Global Accelerator"],
        admin_interfaces=["AWS Management Console", "AWS CLI", "AWS SDKs (boto3, aws-sdk)", "AWS CloudShell", "AWS Systems Manager", "AWS Config", "CloudFormation console", "Terraform (via AWS provider)"],
        internal_apis=["EC2 metadata service (169.254.169.254)", "VPC DNS resolver (169.254.169.253)", "S3 gateway endpoints", "VPC endpoints for various services", "ECS task metadata endpoint"],
        external_apis=["AWS service public endpoints", "S3 REST API", "CloudFront API", "API Gateway", "Lambda URL", "AppSync GraphQL", "Pinpoint"],
        cloud_resources=["EC2 instances", "S3 buckets", "Lambda functions", "API Gateway APIs", "RDS instances", "DynamoDB tables", "IAM roles/users/policies", "CloudFront distributions", "Cognito user/identity pools", "VPCs and subnets", "Security groups", "EBS volumes", "ELB/ALB/NLB", "Route53 hosted zones"],
        trust_boundaries=[
            TrustBoundary(name="Internet-to-AWS-Service", description="External users accessing AWS services (S3, API GW, CloudFront)", direction="inbound", sensitivity="high"),
            TrustBoundary(name="EC2-to-Metadata", description="EC2 instance requests to metadata service for IAM credentials", direction="outbound", sensitivity="critical"),
            TrustBoundary(name="Cross-Service-IAM", description="AWS services assuming IAM roles to access other services", direction="bidirectional", sensitivity="high"),
            TrustBoundary(name="VPC-to-Internet", description="VPC resources accessing internet via NAT/IGW", direction="outbound", sensitivity="medium"),
        ],
        attack_surface_areas=[
            "EC2 metadata service accessible via SSRF allows IAM credential theft",
            "S3 buckets with public read/write ACLs or bucket policies",
            "IAM policies with wildcard actions (*) or resources (*)",
            "Lambda functions with overly permissive execution roles",
            "API Gateway endpoints without auth or WAF protection",
            "Cognito user pools with unauthenticated signup or weak password policy",
            "CloudFront distributions exposing origin servers directly",
            "RDS instances publicly accessible from 0.0.0.0/0",
            "S3 bucket takeover via DNS (missing bucket) allowing phishing",
            "CloudFormation templates exposing secrets in parameters/outputs",
            "EBS snapshots shared publicly or with external accounts",
            "SQS queues with public policy allowing anyone to send/receive messages",
            "ElastiCache clusters without auth token or encryption in transit",
            "Lambda function URLs without IAM auth",
        ],
        investigation_areas=[
            "Check for SSRF opportunities to reach 169.254.169.254",
            "Enumerate S3 buckets for public access or leakage",
            "Review IAM policies for privilege escalation paths",
            "Check Lambda function environment variables for secrets",
            "Test API Gateway endpoints for auth bypass and injection",
            "Inspect Cognito configuration for auth bypass",
            "Check CloudFront for origin exposure and WAF bypass",
            "Scan for publicly accessible RDS instances",
            "Search for exposed CloudFormation outputs containing secrets",
            "Check for public EBS snapshots containing sensitive data",
            "Test SQS/SNS for public access policies",
            "Look for exposed AWS access keys in public repos and logs",
        ],
        tags=["aws", "cloud", "ec2", "s3", "lambda", "iam", "api-gateway"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "AmazonS3",
            "x-amz-request-id": "",
            "x-amz-id-2": "",
            "x-amz-bucket-region": "",
            "x-amz-cf-id": "",
            "via": "1.1 amazon",
        },
        cookies=["aws-appsync-"],
        js_indicators=["AWS.config", "new AWS.", "AWS_SDK", "amazonaws.com", "s3.amazonaws.com", "cognito-idp"],
        file_indicators=["credentials", "config", ".aws/credentials", ".aws/config", "boto3", "aws-sdk", "~/.aws/", "credentials.json", "aws_key", "aws_secret", "access_key", "secret_key"],
        directory_indicators=[".aws/"],
        server_signatures=["AmazonS3", "CloudFront", "awselb/", "Amazon CloudFront"],
        error_page_signatures=["AccessDenied", "AccessDeniedException", "NoSuchBucket", "InvalidAccessKeyId", "SignatureDoesNotMatch", "AllAccessDisabled", "NoSuchKey", "Not Found", "AuthorizationHeaderMalformed"],
        default_paths=["/", "/?prefix=&delimiter=/", "/?acl", "/?policy", "/?location", "/?versioning", "/?logging", "/?tagging", "/?cors", "/?lifecycle"],
        default_files=[".aws/credentials", ".aws/config", "credentials.json", "access_key", "secret_key", "aws_key.txt", "terraform.tfstate", "terraform.tfvars", "serverless.yml", "samconfig.toml"],
        metadata_patterns={"x-amz-request-id": "\\w+", "x-amz-id-2": ".+", "AccessDenied": "AccessDenied"},
        tags=["fingerprint", "aws", "cloud"],
    ),
    recon=ReconProfile(
        directories_to_check=["/.aws/", "/.aws/credentials", "/.aws/config", "/backup/", "/credentials/", "/keys/", "/secrets/"],
        files_to_check=[".aws/credentials", ".aws/config", "credentials.json", "aws_key.txt", "secret_key.txt", "terraform.tfstate", "terraform.tfvars", "serverless.yml", "samconfig.toml", "Dockerfile", "docker-compose.yml", ".env", ".git/config"],
        endpoints_to_scan=["https://{bucket}.s3.amazonaws.com/", "https://{bucket}.s3.{region}.amazonaws.com/", "https://{api-id}.execute-api.{region}.amazonaws.com/", "https://{url-id}.lambda-url.{region}.on.aws/", "http://169.254.169.254/latest/meta-data/", "https://sts.amazonaws.com"],
        subdomains_to_check=["s3.amazonaws.com", "cloudfront.net", "execute-api.{region}.amazonaws.com", "elb.amazonaws.com", "amazonaws.com"],
        dns_records_to_check=["CNAME", "TXT", "MX", "NS"],
        port_scan_targets=[443, 80, 5432, 3306, 6379, 11211, 27017, 5000, 9000],
        version_detection_paths=["/", "/?location", "/?versioning"],
        debug_paths_to_check=["/debug/", "/health", "/healthz", "/info", "/status"],
        admin_paths_to_check=["/console/", "/admin/", "/aws/", "/cloud/", "/management/", "/dashboard/"],
        tags=["recon", "aws", "cloud", "s3", "ec2"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="SSRF vulnerability allowing access to EC2 metadata service at 169.254.169.254 to steal IAM role credentials",
            impact="Complete AWS account compromise — stolen IAM credentials can access any service the role permits, potentially including S3, RDS, Lambda, and IAM itself",
            attack_scenario="Trigger SSRF via vulnerable parameter (url, file, redirect) pointing to http://169.254.169.254/latest/meta-data/iam/security-credentials/{role}; extract AccessKeyId, SecretAccessKey, Token; configure AWS CLI with stolen creds",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="S3 bucket with public listing enabled exposing all object keys and potentially sensitive data",
            impact="Data leakage of all bucket contents — configs, backups, user data, database dumps, and credentials",
            attack_scenario="Enumerate bucket via https://bucket.s3.amazonaws.com/?prefix=; list all objects; download interesting files; look for data, configs, credentials, and backups",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="IAM privilege escalation via PassRole where an EC2 instance can be launched with an existing admin role",
            impact="Privilege escalation from limited IAM user to full admin access via launching an EC2 instance with a privileged IAM role",
            attack_scenario="IAM user with ec2:RunInstances and iam:PassRole on an admin role launches EC2 with that role; SSRF metadata or instance shell extracts admin credentials",
            complexity="medium",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="Lambda function environment variables containing database credentials, API keys, or other secrets",
            impact="Credential theft leading to database access, third-party API access, or further AWS service compromise",
            attack_scenario="Get Lambda function configuration via ListFunctions/GetFunctionConfiguration or via exposed Lambda URL; extract environment variables; use creds to access RDS or external services",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="API Gateway endpoint without IAM auth or API key exposing backend Lambda or HTTP integration directly",
            impact="Unauthenticated access to backend APIs, data exfiltration, injection attacks, and business logic abuse",
            attack_scenario="Discover API Gateway URL via JS files, source maps, or API enumeration; call endpoint directly; test for injection, IDOR, and data exposure",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Cognito identity pool allowing unauthenticated AWS credential retrieval via GetId/GetCredentialsForIdentity",
            impact="Anonymous users obtain AWS credentials with the permissions of the unauthenticated IAM role",
            attack_scenario="Call cognito-identity GetId with IdentityPoolId; call GetCredentialsForIdentity; use returned AWS creds to access S3, DynamoDB, or other services",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="azure",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="AWS and Azure are competing cloud platforms",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="gcp",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="AWS and GCP are competing cloud platforms",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="kubernetes",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="AWS integrates with Kubernetes via EKS",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="AWS provides ECR and ECS for Docker container management",
            confidence="high",
        ),
    ],
    dependencies=["AWS CLI", "AWS SDK", "boto3", "Terraform AWS provider"],
    related_packs=["azure", "gcp", "cloudflare", "kubernetes", "docker"],
    workflow=[
        "1. Enumerate subdomains and API endpoints for AWS services (S3, API GW, CloudFront, Lambda URLs)",
        "2. Check for SSRF in application parameters, headers, and file uploads targeting 169.254.169.254",
        "3. Enumerate S3 buckets via bucket name guessing and permutation",
        "4. Check S3 buckets for public listing, read, and write access",
        "5. Review exposed JS files for API Gateway URLs, Cognito pool IDs, and AWS access keys",
        "6. Check API Gateway endpoints for authentication and authorization bypass",
        "7. Test Lambda function URLs for injection and env var leakage",
        "8. Check Cognito user pools for unauthenticated signup and auth bypass",
        "9. Review IAM policies if credentials obtained for privilege escalation paths",
        "10. Check for publicly accessible RDS instances and EBS snapshots",
        "11. Look for CloudFormation stack outputs and parameter store secrets",
        "12. Check CloudFront for origin exposure and WAF misconfiguration",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="AWS-01",
            category="SSRF via Metadata Service",
            description="Test SSRF to access EC2 metadata service at 169.254.169.254/latest/meta-data/",
            expected_result="Metadata service should not be accessible via SSRF — network filtering or IMDSv2 required",
            tools=["curl", "Burp Suite", "ffuf", "ssrf-tool"],
            references=["https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html"],
        ),
        ManualTestChecklistItem(
            step_id="AWS-02",
            category="S3 Bucket Enumeration",
            description="Enumerate S3 buckets and check for public access",
            expected_result="S3 buckets should not allow public listing or public read/write access",
            tools=["aws-cli", "s3scanner", "cloud_enum", "grayhatwarfare"],
            references=["https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html"],
        ),
        ManualTestChecklistItem(
            step_id="AWS-03",
            category="IAM Privilege Escalation",
            description="Review IAM policies for privilege escalation paths",
            expected_result="IAM policies should follow least privilege — no wildcard actions on sensitive services",
            tools=["aws-cli", "pmapper", "ScoutSuite", "prowler"],
            references=["https://rhinosecuritylabs.com/aws/aws-privilege-escalation-methods-mitigation/"],
        ),
        ManualTestChecklistItem(
            step_id="AWS-04",
            category="Lambda Function Review",
            description="Review Lambda functions for secrets in env vars and overprivileged roles",
            expected_result="Lambda functions should not store secrets in env vars and should have least-privilege execution roles",
            tools=["aws-cli", "ScoutSuite", "prowler"],
            references=["https://docs.aws.amazon.com/lambda/latest/dg/security-best-practices.html"],
        ),
        ManualTestChecklistItem(
            step_id="AWS-05",
            category="API Gateway Security",
            description="Test API Gateway endpoints for auth bypass, injection, and data exposure",
            expected_result="API endpoints should require authentication and validate input",
            tools=["curl", "Burp Suite", "Postman", "nuclei"],
            references=["https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-to-api.html"],
        ),
        ManualTestChecklistItem(
            step_id="AWS-06",
            category="Cognito Misconfiguration",
            description="Check Cognito pools for unauthenticated signup, weak policies, and credential leakage",
            expected_result="Cognito should require verification, enforce strong passwords, and not allow unauthorized access",
            tools=["aws-cli", "cognito-scanner"],
            references=["https://docs.aws.amazon.com/cognito/latest/developerguide/security-best-practices.html"],
        ),
        ManualTestChecklistItem(
            step_id="AWS-07",
            category="CloudTrail & Logging",
            description="Verify CloudTrail is enabled across all regions and logging is not tampered with",
            expected_result="CloudTrail should be enabled in all regions with log file validation enabled",
            tools=["aws-cli", "prowler", "ScoutSuite"],
            references=["https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html"],
        ),
        ManualTestChecklistItem(
            step_id="AWS-08",
            category="Public RDS & EBS Snapshots",
            description="Check for RDS instances publicly accessible and EBS snapshots shared publicly",
            expected_result="RDS should not be public, EBS snapshots should not be shared externally",
            tools=["aws-cli", "prowler", "cloudsploit"],
            references=["https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ConnectToInstance.html"],
        ),
    ],
    references=[
        {"title": "AWS Security Documentation", "url": "https://docs.aws.amazon.com/security/"},
        {"title": "AWS Well-Architected Framework - Security Pillar", "url": "https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/"},
        {"title": "HackTricks - AWS Pentesting", "url": "https://book.hacktricks.xyz/cloud-security/aws-pentesting"},
        {"title": "Rhino Security Labs - AWS Privilege Escalation", "url": "https://rhinosecuritylabs.com/aws/aws-privilege-escalation-methods-mitigation/"},
        {"title": "Prowler - AWS Security Tool", "url": "https://github.com/prowler-cloud/prowler"},
        {"title": "ScoutSuite", "url": "https://github.com/nccgroup/ScoutSuite"},
        {"title": "AWS CLI", "url": "https://aws.amazon.com/cli/"},
    ],
    cwe_ids=["CWE-918", "CWE-200", "CWE-269", "CWE-862", "CWE-732", "CWE-522", "CWE-284", "CWE-306", "CWE-668"],
    cve_ids=["CVE-2023-34051", "CVE-2022-3466", "CVE-2022-22965", "CVE-2022-22963", "CVE-2021-44228", "CVE-2020-5902"],
    tags=["aws", "cloud", "amazon", "ec2", "s3", "lambda", "iam", "api-gateway", "cognito", "cloudfront"],
)
