"""Azure knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="azure",
    version="1.0.0",
    category=KnowledgePackCategory.CLOUD,
    description="Microsoft Azure — Azure VM metadata service SSRF, Blob storage container enumeration, IAM / RBAC misconfiguration, API Management exposure, Azure Functions injection, Key Vault secret access, App Service authentication bypass, Logic Apps misconfiguration, and Azure AD token manipulation.",
    technology=TechnologyProfile(
        name="Microsoft Azure",
        vendor="Microsoft",
        language="",
        runtime="Azure Global Infrastructure",
        description="Microsoft Azure is a cloud computing platform offering infrastructure (VMs, storage), platform (App Service, Functions), and software services (Office 365, Dynamics 365) across global regions. Supports hybrid cloud with Azure Arc and integrates deeply with Microsoft ecosystem including Active Directory, Visual Studio, and GitHub.",
        common_aliases=["azure", "microsoft azure", "windows azure", "az"],
        dependencies=["Azure CLI", "Azure PowerShell", "Terraform", "Bicep", "ARM templates", "Kubernetes (AKS)"],
        common_integrations=["Azure AD / Entra ID", "Blob Storage", "Azure Functions", "App Service", "SQL Database", "Cosmos DB", "Key Vault", "API Management", "Logic Apps", "Service Bus", "Event Grid", "Azure DevOps", "Application Insights", "Azure Kubernetes Service (AKS)"],
        architecture_description="Global infrastructure with regions, availability zones, and paired regions. Subscription -> Resource Group -> Resource hierarchy. Azure AD provides identity and access management. ExpressRoute and VPN provide hybrid connectivity.",
        request_lifecycle="Client -> Azure Resource Manager/Service API (auth via Azure AD OAuth2) -> Service-specific endpoint -> Response",
        documentation_url="https://docs.microsoft.com/azure/",
        tags=["cloud", "azure", "microsoft", "iaas", "paas", "faas"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Azure VM Metadata Service",
            description="HTTP endpoint at 169.254.169.254 on Azure VMs providing instance metadata, managed identity tokens, and custom data. Primary SSRF target in Azure environments.",
            security_relevance="high",
            common_vulnerabilities=["SSRF exploitation fetching managed identity access tokens", "Instance metadata exposure (VM name, resource group, subscription ID)", "Custom data / user data extraction containing deployment scripts and secrets", "Managed identity token theft for lateral movement"],
            investigation_priority=95,
            tags=["metadata", "ssrf", "vm", "imds", "managed-identity"],
        ),
        TechnologyComponentProfile(
            name="Azure Blob Storage",
            description="Object storage service for unstructured data. Containers (blob containers), storage accounts, and access tiers (hot, cool, archive). Public containers and misconfigured access.",
            security_relevance="high",
            common_vulnerabilities=["Publicly accessible blob containers (anonymous access)", "Container listing enabled for anonymous users", "Storage account with firewall disabled", "Shared Access Signature (SAS) tokens in URLs with excessive permissions", "Soft-deleted blobs still recoverable exposing old data", "Storage account key leakage"],
            investigation_priority=95,
            tags=["blob", "storage", "container", "public-access", "sas"],
        ),
        TechnologyComponentProfile(
            name="Azure RBAC / IAM",
            description="Role-based access control for Azure resources. Built-in and custom roles assigned at management group, subscription, resource group, or resource scope.",
            security_relevance="high",
            common_vulnerabilities=["Overly permissive RBAC roles (Contributor, Owner)", "Privileged role assignments to service principals", "Custom roles with wildcard actions (*)", "Managed identity with excessive permissions", "Privilege escalation via RBAC role assignment"],
            investigation_priority=95,
            tags=["rbac", "iam", "roles", "permissions", "authorization"],
        ),
        TechnologyComponentProfile(
            name="Azure Functions",
            description="Serverless compute service for event-driven applications. Function code, app settings (env vars), and managed identity.",
            security_relevance="high",
            common_vulnerabilities=["Function app secrets in app settings / environment variables", "Function endpoints exposed without authentication", "Managed identity with excessive RBAC permissions", "Code injection via HTTP trigger input parameters", "Unsecured function app slots with outdated code"],
            investigation_priority=90,
            tags=["functions", "serverless", "faas", "injection", "app-settings"],
        ),
        TechnologyComponentProfile(
            name="API Management (APIM)",
            description="Managed API gateway for publishing, securing, and analyzing APIs. Subscription keys, OAuth2, and policy-based access control.",
            security_relevance="high",
            common_vulnerabilities=["API Management developer portal exposed publicly", "Subscription keys hardcoded in client applications", "APIM policy misconfiguration allowing backend bypass", "Missing rate limiting or throttling policies", "Backend API exposed via direct URL bypassing APIM"],
            investigation_priority=85,
            tags=["apim", "api-management", "api-gateway", "subscription"],
        ),
        TechnologyComponentProfile(
            name="Key Vault",
            description="Managed service for storing and accessing secrets, keys, and certificates. Access policies and soft-delete protection.",
            security_relevance="high",
            common_vulnerabilities=["Key Vault accessible from public internet without firewall", "Overly permissive Key Vault access policies", "Managed identity with access to Key Vault allowing secret theft", "Soft-delete enabled allowing recovery of deleted secrets", "Key Vault DNS name enumeration"],
            investigation_priority=95,
            tags=["key-vault", "secrets", "certificates", "keys", "encryption"],
        ),
        TechnologyComponentProfile(
            name="Azure App Service",
            description="PaaS offering for web applications, REST APIs, and mobile backends. Auto-scaling, deployment slots, and integrated authentication.",
            security_relevance="high",
            common_vulnerabilities=["App Service authentication / EasyAuth bypass", "App settings containing database connection strings and API keys", "Kudu / SCM site exposed without strong auth", "Deployment slot swapping exposes staging environment", "FTPS endpoint with weak credentials", "App Service managed identity credential abuse"],
            investigation_priority=90,
            tags=["app-service", "web-app", "paas", "auth", "kudu"],
        ),
        TechnologyComponentProfile(
            name="Azure AD / Entra ID",
            description="Identity and access management service providing authentication and authorization for Azure, Microsoft 365, and third-party applications.",
            security_relevance="high",
            common_vulnerabilities=["OAuth2 implicit grant flow with token leakage", "Azure AD application with excessive delegated permissions", "Service principal with overprivileged directory roles", "Multi-factor authentication not enforced for admins", "Application registration consent phishing", "Azure AD token reuse across tenants"],
            investigation_priority=90,
            tags=["aad", "entra-id", "identity", "oauth2", "saml"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Azure VM Metadata Service",
                description="SSRF target at http://169.254.169.254/metadata/instance",
                protocol="HTTP",
                method="GET",
                path="http://169.254.169.254/metadata/instance?api-version=2021-02-01",
                parameters=["api-version", "format"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.SSRF.value, BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Azure Blob Container",
                description="Blob storage container potentially allowing anonymous access",
                protocol="HTTPS",
                method="GET",
                path="https://{account}.blob.core.windows.net/{container}/",
                parameters=["restype", "comp", "timeout", "sv", "se", "sr", "sp", "sig"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Azure Function HTTP Trigger",
                description="Azure Function HTTP endpoint potentially exposed without auth",
                protocol="HTTPS",
                method="ANY",
                path="https://{app}.azurewebsites.net/api/{function}",
                parameters=["code", "clientId"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.COMMAND_INJECTION.value, BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Azure App Service",
                description="Azure App Service web app with potential EasyAuth bypass",
                protocol="HTTPS",
                method="ANY",
                path="https://{app}.azurewebsites.net/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value, BugClass.COMMAND_INJECTION.value],
            ),
            AttackSurfaceEntry(
                name="Azure API Management",
                description="API Management gateway and developer portal",
                protocol="HTTPS",
                method="ANY",
                path="https://{service}.azure-api.net/{api}/{operation}",
                parameters=["subscription-key", "api-version"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Azure Key Vault",
                description="Key Vault REST API for managing secrets, keys, and certificates",
                protocol="HTTPS",
                method="ANY",
                path="https://{vault}.vault.azure.net/{object-type}/{object-name}",
                parameters=["api-version"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Kudu / SCM Site",
                description="App Service Kudu console for debugging and management",
                protocol="HTTPS",
                method="ANY",
                path="https://{app}.scm.azurewebsites.net/",
                parameters=[],
                authentication_required=True,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.RCE.value, BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["http://169.254.169.254/metadata/instance?api-version=2021-02-01", "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/", "https://{account}.blob.core.windows.net/", "https://{account}.blob.core.windows.net/{container}?restype=container&comp=list", "https://{app}.azurewebsites.net/", "https://{app}.scm.azurewebsites.net/", "https://{service}.azure-api.net/", "https://{vault}.vault.azure.net/", "https://management.azure.com/", "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token"],
        parameters=["api-version", "$filter", "$top", "$skip", "resource", "client_id", "client_secret", "scope", "redirect_uri", "response_type", "grant_type", "code", "sv", "se", "sr", "sp", "sig", "restype", "comp"],
        authentication=["Azure AD OAuth2 (authorization code, client credentials, device code, implicit)", "Azure AD managed identity (system-assigned and user-assigned)", "SAS tokens (Shared Access Signatures — service, account, user delegation)", "Storage account keys (primary/secondary)", "API Management subscription keys", "App Service authentication (EasyAuth)", "Azure AD B2C", "Azure AD application credentials (client secret, certificate)"],
        authorization=["Azure RBAC (Owner, Contributor, Reader, custom roles)", "Azure AD roles (Global Administrator, Application Administrator, etc.)", "Key Vault access policies", "Azure Policy", "Managed identity RBAC assignments", "Logic App access control (IAM)", "API Management policy-based authorization"],
        storage=["Azure Blob Storage", "Azure Disk Storage", "Azure Files", "Azure NetApp Files", "Cosmos DB", "SQL Database / Managed Instance", "Azure Cache for Redis", "Service Bus", "Event Hubs", "Data Lake Storage Gen2"],
        background_jobs=["Azure Functions (event-driven)", "Logic Apps (workflows)", "WebJobs", "Azure Batch", "Azure Automation runbooks", "Durable Functions", "Event Grid event processing"],
        queues=["Azure Queue Storage", "Service Bus queues and topics", "Event Hubs", "Event Grid"],
        caches=["Azure Cache for Redis", "CDN (Azure Front Door / CDN Profiles)", "Cosmos DB built-in caching"],
        admin_interfaces=["Azure Portal (portal.azure.com)", "Azure CLI", "Azure PowerShell", "Azure Cloud Shell", "Azure DevOps", "Kudu / SCM console", "Azure Resource Explorer"],
        internal_apis=["Azure Instance Metadata Service (169.254.169.254)", "Azure DNS (168.63.129.16)", "Azure Wire Server", "Kudu / SCM site", "App Service file system"],
        external_apis=["Azure Resource Manager (management.azure.com)", "Azure AD Graph / Microsoft Graph", "Blob Storage REST API", "Azure SQL Database", "Cosmos DB account endpoints", "Service Bus REST API", "Event Grid REST API"],
        cloud_resources=["Virtual Machines", "Blob Storage accounts", "Azure Functions", "App Services", "API Management instances", "Key Vaults", "SQL Databases / Managed Instances", "Cosmos DB accounts", "Logic Apps", "Azure Kubernetes Service clusters", "Virtual Networks", "Network Security Groups", "Load Balancers", "Application Gateways", "Azure Firewall"],
        trust_boundaries=[
            TrustBoundary(name="Internet-to-Azure-Service", description="External users accessing Azure services (App Service, API Management, Blob)", direction="inbound", sensitivity="high"),
            TrustBoundary(name="VM-to-Metadata", description="Azure VM requests metadata service for managed identity tokens", direction="outbound", sensitivity="critical"),
            TrustBoundary(name="Azure-AD-Token", description="Applications exchanging auth codes for tokens via Azure AD", direction="external", sensitivity="high"),
            TrustBoundary(name="Cross-Tenant-Access", description="Azure AD B2B and multi-tenant app access across tenants", direction="bidirectional", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Azure VM metadata service accessible via SSRF allowing managed identity token theft",
            "Blob storage containers with anonymous read access exposing data",
            "SAS tokens with excessive permissions (read, write, delete) leaked in URLs or source code",
            "Azure Functions with overprivileged managed identity RBAC assignments",
            "App Service EasyAuth bypass allowing unauthenticated access to protected endpoints",
            "Key Vault accessible from public internet without firewall restrictions",
            "API Management developer portal exposed without authentication",
            "Kudu / SCM site exposed without strong password or Entra ID integration",
            "RBAC custom roles with wildcard permissions allowing privilege escalation",
            "Logic Apps with HTTP triggers exposed without auth",
            "Managed identity credentials accessible via SSRF in Functions or App Services",
            "Azure AD app registrations with excessive delegated permissions and no admin consent",
        ],
        investigation_areas=[
            "Check for SSRF to Azure metadata service at 169.254.169.254",
            "Enumerate Azure Blob storage containers for anonymous access",
            "Review RBAC role assignments for overprivileged principals",
            "Check Azure Function app settings for secrets",
            "Test App Service authentication and Kudu console access",
            "Check Key Vault firewall and access policies",
            "Review API Management configuration for auth bypass",
            "Test Logic Apps HTTP triggers for unauthenticated access",
            "Look for SAS tokens in URLs, source code, and logs",
            "Enumerate Azure AD applications for misconfigured permissions",
            "Check for exposed Azure DevOps variables and service connections",
            "Review Network Security Group rules for overly permissive access",
        ],
        tags=["azure", "cloud", "microsoft", "blob", "functions", "app-service"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "Microsoft-IIS",
            "x-ms-request-id": "",
            "x-ms-version": "",
            "x-ms-blob-type": "",
            "x-ms-lease-status": "",
            "x-ms-client-request-id": "",
            "x-powered-by": "ASP.NET",
        },
        cookies=["AppServiceAuthSession", "AppServiceSession", "ARRAffinity", "ARRAffinitySameSite", "x-ms-"],
        js_indicators=["@azure/", "azure-storage", "azure-blob", "AzureFunction", "DefaultAzureCredential", "InteractiveBrowserCredential", "azureServiceBus", "azureEventHub", "azureStorage", "msal", "@azure/msal"],
        file_indicators=["az", "azure", "azure_config", "azure_credentials", ".azure/", "credentials.azure", "azuredeploy.json", "main.bicep", "azure-pipelines.yml", "local.settings.json", "host.json", "proxies.json"],
        directory_indicators=[".azure/", "azuredeploy/", "arm-templates/"],
        server_signatures=["Microsoft-IIS", "AzureBlob", "AzureFunctions", "Azure", "Kestrel"],
        error_page_signatures=["AuthenticationFailed", "AuthorizationFailed", "BlobNotFound", "ResourceNotFound", "ContainerNotFound", "StorageAccountNotFound", "InvalidAuthenticationInfo", "AuthenticationErrorDetail", "AccessDenied", "NotFound", "Forbidden"],
        default_paths=["/", "/.auth/me", "/.auth/login", "/admin/", "/api/", "/scm/", "/api/functions", "/api/status", "/debug/", "/runtime/webhooks/durabletask/"],
        default_files=["local.settings.json", "host.json", "proxies.json", "azuredeploy.json", "main.bicep", ".azure/config", "azure-pipelines.yml", "Dockerfile", "appsettings.json", "appsettings.Development.json", "connectionstrings.xml"],
        metadata_patterns={"x-ms-request-id": "\\w+", "x-ms-version": "\\d{4}-\\d{2}-\\d{2}", "AuthenticationFailed": "AuthenticationFailed"},
        tags=["fingerprint", "azure", "cloud"],
    ),
    recon=ReconProfile(
        directories_to_check=["/.azure/", "/azuredeploy/", "/arm-templates/", "/credentials/", "/appsettings/", "/azure/"],
        files_to_check=["local.settings.json", "host.json", "proxies.json", "azuredeploy.json", "main.bicep", ".azure/config", "azure-pipelines.yml", "appsettings.json", "connectionstrings.xml", "credentials.azure", "Dockerfile", ".env", "terraform.tfvars"],
        endpoints_to_scan=["https://{vault}.vault.azure.net/", "https://{account}.blob.core.windows.net/", "https://{app}.azurewebsites.net/", "https://{app}.scm.azurewebsites.net/", "https://{service}.azure-api.net/", "https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration", "https://management.azure.com/"],
        subdomains_to_check=["blob.core.windows.net", "azurewebsites.net", "azure-api.net", "vault.azure.net", "azureedge.net", "trafficmanager.net", "cloudapp.net", "file.core.windows.net", "queue.core.windows.net", "table.core.windows.net"],
        dns_records_to_check=["CNAME", "TXT", "MX", "NS", "SOA"],
        port_scan_targets=[443, 80, 1433, 3306, 5432, 6379, 11211, 27017, 5000, 9000, 2222],
        version_detection_paths=["/v2.0/.well-known/openid-configuration", "/", "/.auth/me"],
        debug_paths_to_check=["/debug/", "/debug/pprof/", "/api/functions", "/admin/host/status", "/runtime/webhooks/"],
        admin_paths_to_check=["/admin/", "/scm/", "/api/", "/console/", "/dashboard/", "/management/", "/portal/"],
        tags=["recon", "azure", "cloud", "blob", "functions"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="SSRF to Azure metadata service allowing theft of managed identity access tokens",
            impact="Complete compromise of the managed identity — access to any Azure resource the identity has RBAC permissions on, including Key Vault, Storage, and SQL Database",
            attack_scenario="Trigger SSRF via vulnerable parameter pointing to http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://vault.azure.net; parse JSON response for access_token; use token to access Key Vault secrets",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Azure Blob container with anonymous read access exposing all stored data including backups, configs, and user data",
            impact="Data leakage of all blob contents — potential exposure of PII, credentials, database dumps, and application configuration",
            attack_scenario="List blob container via https://account.blob.core.windows.net/container?restype=container&comp=list; download all blobs; analyze for sensitive data including connection strings, API keys, and PII",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="SAS token with excessive permissions (read, write, delete, list) leaked in GitHub, client-side code, or URL parameters",
            impact="Unauthorized access to storage account — data theft, data deletion, and potential malware upload via write access",
            attack_scenario="Extract SAS token from JavaScript file, URL query string, or public repository; decode token parameters to determine scope and expiry; use token to list, read, write, or delete blobs",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Azure Functions with app settings containing database connection strings, storage account keys, or API secrets in plaintext",
            impact="Credential theft leading to database access, storage account compromise, or third-party API access",
            attack_scenario="List function apps and read app settings via Azure portal, CLI, or exposed Function admin endpoint; extract connection strings and API keys; use credentials to access SQL Database, Storage, or external services",
            complexity="medium",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="Kudu / SCM console exposed without strong authentication allowing file upload, process execution, and site management",
            impact="Remote code execution on App Service — full control over the web application, environment variables, and connected resources",
            attack_scenario="Access https://app.scm.azurewebsites.net/; if basic auth is weak or default creds work, upload webshell or execute commands via Kudu API /api/command",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Key Vault accessible from public internet without firewall or with overly permissive access policies allowing secret extraction",
            impact="Theft of all secrets, keys, and certificates stored in Key Vault — including database passwords, API keys, and TLS certificates",
            attack_scenario="Enumerate Key Vault DNS name; if firewall is disabled, authenticate with a compromised service principal and list/list all secrets via Key Vault REST API",
            complexity="medium",
            requires_authentication=True,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="aws",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="Azure and AWS are competing cloud platforms",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="gcp",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="Azure and GCP are competing cloud platforms",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="kubernetes",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Azure integrates with Kubernetes via AKS",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Azure provides ACR for Docker container registry and AKS/App Service for container hosting",
            confidence="high",
        ),
    ],
    dependencies=["Azure CLI", "Azure PowerShell", "Azure SDK (az-*)", "Terraform Azure provider", "Bicep"],
    related_packs=["aws", "gcp", "cloudflare", "kubernetes", "docker"],
    workflow=[
        "1. Enumerate Azure subdomains (blob.core.windows.net, azurewebsites.net, azure-api.net, vault.azure.net)",
        "2. Check for SSRF targeting Azure metadata service endpoints",
        "3. Enumerate Blob storage containers for anonymous read/list access",
        "4. Look for SAS tokens in JavaScript files, URLs, and source code repos",
        "5. Check Azure Functions HTTP endpoints for auth bypass and injection",
        "6. Test App Service endpoints and Kudu/SCM console access",
        "7. Enumerate Key Vault DNS names and check firewall/access policy configuration",
        "8. Review API Management instances for exposed developer portal and endpoints",
        "9. Check Logic Apps HTTP triggers for unauthenticated invocation",
        "10. Analyze Azure AD app registrations for overprivileged permissions",
        "11. Look for Azure DevOps exposed variables and service connections",
        "12. Check Network Security Group rules and Azure Firewall configuration",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="AZURE-01",
            category="SSRF via Metadata Service",
            description="Test SSRF to access Azure metadata service at 169.254.169.254/metadata/instance and managed identity token endpoint",
            expected_result="Metadata service should not be accessible via SSRF — network filtering, firewall, or header requirement (Metadata:true) must be enforced",
            tools=["curl", "Burp Suite", "ffuf", "ssrf-tool"],
            references=["https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service"],
        ),
        ManualTestChecklistItem(
            step_id="AZURE-02",
            category="Blob Storage Enumeration",
            description="Enumerate Azure Blob containers and check for anonymous access",
            expected_result="No anonymous read/list access to blob containers; storage firewall should be enabled",
            tools=["az-cli", "Microsoft Azure Storage Explorer", "cloud_enum", "MicroBurst"],
            references=["https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure"],
        ),
        ManualTestChecklistItem(
            step_id="AZURE-03",
            category="Key Vault Exposure",
            description="Check Key Vault firewall and access policies for public exposure and overprivileged access",
            expected_result="Key Vault should have firewall enabled and follow least privilege for access policies",
            tools=["az-cli", "PowerShell"],
            references=["https://docs.microsoft.com/en-us/azure/key-vault/general/network-security"],
        ),
        ManualTestChecklistItem(
            step_id="AZURE-04",
            category="App Service / Kudu Security",
            description="Check App Service authentication configuration and Kudu console access",
            expected_result="App Service should enforce authentication; Kudu should require Entra ID or strong credentials",
            tools=["curl", "browser", "az-cli"],
            references=["https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization"],
        ),
        ManualTestChecklistItem(
            step_id="AZURE-05",
            category="Managed Identity Review",
            description="Review managed identity RBAC assignments for overprivileged access",
            expected_result="Managed identities should follow least privilege principle",
            tools=["az-cli", "PowerShell", "Azure Portal"],
            references=["https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview"],
        ),
        ManualTestChecklistItem(
            step_id="AZURE-06",
            category="Azure AD / Entra ID Review",
            description="Review Azure AD app registrations for excessive permissions, weak auth, and consent phishing",
            expected_result="App registrations should have minimal required permissions with admin consent",
            tools=["az-cli", "Microsoft Graph Explorer", "Azure Portal"],
            references=["https://docs.microsoft.com/en-us/azure/active-directory/develop/security-best-practices-for-app-registration"],
        ),
        ManualTestChecklistItem(
            step_id="AZURE-07",
            category="Logic Apps Exposure",
            description="Test Logic Apps HTTP triggers for unauthenticated access and injection",
            expected_result="Logic Apps HTTP triggers should use Azure AD auth or shared access signatures",
            tools=["curl", "Postman", "Burp Suite"],
            references=["https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-securing-a-logic-app"],
        ),
        ManualTestChecklistItem(
            step_id="AZURE-08",
            category="RBAC Misconfiguration",
            description="Review Azure RBAC role assignments for overprivileged users and service principals",
            expected_result="No subscription-wide Owner/Contributor assignments to non-admin principals",
            tools=["az-cli", "PowerShell", "Azure Portal", "BloodHound for Azure"],
            references=["https://docs.microsoft.com/en-us/azure/role-based-access-control/best-practices"],
        ),
    ],
    references=[
        {"title": "Azure Security Documentation", "url": "https://docs.microsoft.com/en-us/azure/security/"},
        {"title": "Azure Security Benchmark", "url": "https://docs.microsoft.com/en-us/security/benchmark/azure/"},
        {"title": "HackTricks - Azure Pentesting", "url": "https://book.hacktricks.xyz/cloud-security/azure-pentesting"},
        {"title": "MicroBurst - Azure Security Tool", "url": "https://github.com/NetSPI/MicroBurst"},
        {"title": "Azure AD Attack and Defense", "url": "https://github.com/Cloud-Architekt/AzureAD-Attack-Defense"},
        {"title": "Microsoft Azure CLI", "url": "https://docs.microsoft.com/en-us/cli/azure/"},
        {"title": "Azure Pentesting Methodology", "url": "https://github.com/rootsec1/Azure-Pentesting-Methodology"},
    ],
    cwe_ids=["CWE-918", "CWE-200", "CWE-269", "CWE-862", "CWE-732", "CWE-522", "CWE-284", "CWE-306", "CWE-668", "CWE-798"],
    cve_ids=["CVE-2023-36419", "CVE-2022-30181", "CVE-2022-26923", "CVE-2021-42306", "CVE-2021-33759", "CVE-2020-17049"],
    tags=["azure", "cloud", "microsoft", "blob", "functions", "key-vault", "app-service", "rbac", "aad"],
)
