"""Cloudflare knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="cloudflare",
    version="1.0.0",
    category=KnowledgePackCategory.CLOUD,
    description="Cloudflare — WAF bypass techniques (rule ID enumeration, content type confusion, HTTP method override), CDN origin IP discovery (Censys, Shodan, Favicon hash, MX/SPF records), DDoS protection bypass, DNS zone misconfiguration exposed via SOA/NS records, Cloudflare Workers serverless injection, Argo Tunnel exposure, API Shield misconfiguration, SSL/TLS termination bypass, and bot management evasion.",
    technology=TechnologyProfile(
        name="Cloudflare",
        vendor="Cloudflare Inc.",
        language="",
        runtime="Cloudflare Edge Network (330+ cities globally)",
        description="Cloudflare is a cloud connectivity platform offering CDN, DDoS protection, WAF, DNS, serverless computing (Workers), API management (API Shield), bot management, SSL/TLS termination, and network security services. Operates one of the world's largest edge networks, proxying traffic for millions of internet properties.",
        common_aliases=["cloudflare", "cf", "cloudflare cdn", "cloudflare waf"],
        dependencies=["Cloudflare DNS", "Cloudflare SSL/TLS", "Cloudflare WAF", "Cloudflare Workers"],
        common_integrations=["Cloudflare CDN", "Cloudflare WAF / Firewall Rules", "Cloudflare DNS", "Cloudflare Workers", "Cloudflare Pages", "Cloudflare R2 (object storage)", "Cloudflare D1 (edge database)", "Cloudflare KV (key-value store)", "Cloudflare Queues", "Cloudflare Stream", "Cloudflare Images", "Cloudflare Zero Trust / Access", "Cloudflare API Shield", "Cloudflare Bot Management", "Cloudflare Argo / Smart Routing"],
        architecture_description="Edge network spanning 330+ cities. DNS proxied through Cloudflare (orange-clouded) hides real origin IP. HTTP requests are terminated at the edge, inspected by WAF rules, cached, or forwarded to origin. SSL/TLS can be full (strict), flexible, or off.",
        request_lifecycle="Client -> Cloudflare Edge (WAF inspection, DDoS filtering, caching, bot detection) -> Origin server (if not cached or bypassed) -> Response back through Cloudflare edge",
        documentation_url="https://developers.cloudflare.com/",
        tags=["cloud", "cdn", "waf", "dns", "security", "edge-computing"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Cloudflare WAF",
            description="Web Application Firewall protecting against OWASP Top 10 and known attacks. Managed and custom rule sets, rate limiting, and bot management.",
            security_relevance="high",
            common_vulnerabilities=["WAF bypass via content-type confusion", "WAF rule ID enumeration to determine blocked/not blocked patterns", "HTTP method override (X-HTTP-Method-Override) bypass", "WAF bypass via encoding differences (URL, Unicode, double encoding)", "WAF bypass via HTTP parameter pollution", "Known CVE-based WAF bypass techniques"],
            investigation_priority=95,
            tags=["waf", "firewall-rules", "bypass", "inspection", "rate-limit"],
        ),
        TechnologyComponentProfile(
            name="Cloudflare CDN / Proxy",
            description="Content delivery network and reverse proxy. DDoS protection, caching, SSL termination, and origin IP concealment.",
            security_relevance="high",
            common_vulnerabilities=["Origin server IP discovery via Shodan/Censys", "Favicon hash reverse-search", "MX/SPF/DMARC DNS records revealing origin IP", "Historical DNS records (SecurityTrails, VirusTotal)", "Cloudflare-Origins-IP header leakage", "Direct-to-origin access bypassing Cloudflare"],
            investigation_priority=95,
            tags=["cdn", "origin-ip", "proxy", "caching", "ddos"],
        ),
        TechnologyComponentProfile(
            name="Cloudflare Workers",
            description="Serverless edge computing platform running JavaScript/WASM at Cloudflare edge. Code, secrets, and environment variables.",
            security_relevance="high",
            common_vulnerabilities=["Workers secrets exposed via environment variables", "Workers route misconfiguration exposing internal logic", "Unvalidated fetch() calls in Workers enabling SSRF", "CORS misconfiguration in Workers responses", "Workers with excessive execution time causing resource exhaustion", "Workers subrequest hijacking"],
            investigation_priority=85,
            tags=["workers", "serverless", "edge-computing", "js", "wasm"],
        ),
        TechnologyComponentProfile(
            name="Cloudflare DNS",
            description="Authoritative DNS service with DNSSEC, CNAME flattening, and proxied DNS records. Zone transfers, subdomain enumeration, and DNS record exposure.",
            security_relevance="high",
            common_vulnerabilities=["DNS zone transfer (AXFR) if enabled", "Subdomain enumeration via DNS records", "Proxied (orange cloud) vs DNS-only (gray cloud) leakage", "DNS record TTL data exfiltration", "CNAME records revealing internal hostnames", "TXT records with sensitive data (SPF verification info)"],
            investigation_priority=90,
            tags=["dns", "zone", "records", "subdomains", "axfr"],
        ),
        TechnologyComponentProfile(
            name="Cloudflare SSL/TLS",
            description="SSL/TLS termination at the edge. Flexible, Full, Full (strict), and Off modes. Certificate management and origin CA certificates.",
            security_relevance="high",
            common_vulnerabilities=["Flexible SSL mode allows downgrade to HTTP between CF and origin", "Origin CA certificate leakage exposing encryption configuration", "Mixed content issues with flexible SSL", "SSL passthrough bypassing Cloudflare inspection", "Outdated TLS version support on edge"],
            investigation_priority=80,
            tags=["ssl", "tls", "encryption", "certificate", "https"],
        ),
        TechnologyComponentProfile(
            name="Cloudflare Access / Zero Trust",
            description="Zero Trust authentication proxy securing applications behind Cloudflare. Identity-based access policies, JWT validation, and session management.",
            security_relevance="high",
            common_vulnerabilities=["Access policy misconfiguration allowing bypass", "JWT token leakage or reuse", "Access application with insufficient identity provider restrictions", "Service token with excessive permissions", "Access session hijacking via misconfigured session duration"],
            investigation_priority=85,
            tags=["zero-trust", "access", "auth", "jwt", "identity"],
        ),
        TechnologyComponentProfile(
            name="API Shield",
            description="API security solution with mTLS, schema validation, rate limiting, and abuse detection.",
            security_relevance="high",
            common_vulnerabilities=["API endpoints without mTLS enforcement", "Schema validation disabled allowing injection", "API Shield not configured for all endpoints", "Mutual TLS certificate pinning weaknesses", "API abuse detection thresholds too high"],
            investigation_priority=80,
            tags=["api-shield", "api", "mtls", "schema-validation"],
        ),
        TechnologyComponentProfile(
            name="Cloudflare Argo / Smart Routing",
            description="Intelligent routing optimizing origin traffic. Argo Tunnel creates encrypted tunnels without public origin IP.",
            security_relevance="medium",
            common_vulnerabilities=["Argo Tunnel exposes local services to internet", "Tunnel authentication token leakage", "Argo Smart Routing bypassing geographic restrictions", "Argo tunnel endpoint discovery"],
            investigation_priority=70,
            tags=["argo", "tunnel", "routing", "smart-routing"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Origin Server Direct Access",
                description="Target origin server directly bypassing Cloudflare WAF/CDN",
                protocol="HTTPS/HTTP",
                method="ANY",
                path="https://{origin-ip}/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value, BugClass.COMMAND_INJECTION.value],
            ),
            AttackSurfaceEntry(
                name="Cloudflare Workers Endpoint",
                description="Workers.dev subdomain or custom domain Workers route",
                protocol="HTTPS",
                method="ANY",
                path="https://{subdomain}.workers.dev/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.SSRF.value, BugClass.COMMAND_INJECTION.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Cloudflare DNS Zone",
                description="DNS zone providing records about target infrastructure",
                protocol="DNS/HTTPS",
                method="GET",
                path="dns://{ns}.cloudflare.com/",
                parameters=["type", "name"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Argo Tunnel",
                description="Argo Tunnel endpoint exposing local services via Cloudflare",
                protocol="HTTPS",
                method="ANY",
                path="https://{tunnel-id}.cfargotunnel.com/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Cloudflare Pages",
                description="Cloudflare Pages site potentially with secret env vars",
                protocol="HTTPS",
                method="ANY",
                path="https://{project}.pages.dev/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.COMMAND_INJECTION.value],
            ),
            AttackSurfaceEntry(
                name="Cloudflare R2 Bucket",
                description="R2 object storage bucket potentially with public access",
                protocol="HTTPS",
                method="ANY",
                path="https://{bucket}.r2.cloudflarestorage.com/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
        ],
        endpoints=["https://{target}/cdn-cgi/trace", "https://{target}/cdn-cgi/scripts/", "https://{target}/cdn-cgi/rum", "https://{target} (directly)", "https://{subdomain}.workers.dev/", "https://{project}.pages.dev/", "https://{tunnel-id}.cfargotunnel.com/", "https://{bucket}.r2.cloudflarestorage.com/"],
        parameters=["__cf_chl_tk", "__cf_chl_captcha_tk", "cf_chl_opt", "_cf_", "cf_clearance"],
        authentication=["Cloudflare API Token (global or scoped)", "Cloudflare API Key (global)", "Cloudflare Origin CA Certificate", "Cloudflare Access JWT tokens", "Cloudflare Workers API key (account-level)", "Cloudflare Pages deploy token", "Argo Tunnel token (cert.pem / tunnel.json)"],
        authorization=["Cloudflare API Token permissions (zone:dns:read, zone:firewall:write, etc.)", "Cloudflare Access policies (Zero Trust)", "Workers API route permissions", "Cloudflare Teams / Gateway policies"],
        storage=["Cloudflare R2 (object storage)", "Cloudflare KV (key-value)", "Cloudflare D1 (SQLite edge database)", "Cloudflare Images", "Cloudflare Stream (video storage)", "Cloudflare Cache (CDN edge cache)"],
        background_jobs=["Cloudflare Workers (Cron Triggers / scheduled events)", "Cloudflare Queues (async message processing)", "Cloudflare Pages builds", "Cloudflare Logpush (log delivery)"],
        queues=["Cloudflare Queues", "Cloudflare Workers (via fetch events streaming)"],
        caches=["Cloudflare CDN edge cache (Argo Smart Routing)", "Cloudflare Workers Cache API (KV)"],
        admin_interfaces=["Cloudflare Dashboard (dash.cloudflare.com)", "Cloudflare API", "Cloudflare Wrangler CLI (Workers)", "Cloudflare Terraform provider"],
        internal_apis=["Cloudflare API (api.cloudflare.com)", "Cloudflare GraphQL Analytics API"],
        external_apis=["Cloudflare API", "Cloudflare Workers API", "Cloudflare Pages API", "Cloudflare R2 S3-compatible API"],
        cloud_resources=["DNS zones", "WAF / firewall rules", "Workers scripts", "Pages projects", "R2 buckets", "D1 databases", "KV namespaces", "Queues", "API Shield configurations", "Zero Trust / Access policies", "Load balancers", "Argo tunnels"],
        trust_boundaries=[
            TrustBoundary(name="Client-to-Cloudflare", description="End users connect to Cloudflare edge, not origin directly", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="Cloudflare-to-Origin", description="Cloudflare edge forwards traffic to origin server (encrypted or not)", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Workers-to-External", description="Cloudflare Workers making outbound fetch() calls to external services", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Argo-Tunnel", description="Argo Tunnel creating encrypted tunnel from origin to Cloudflare edge", direction="bidirectional", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Origin server IP discovered bypassing Cloudflare WAF/CDN protection entirely",
            "WAF bypass via HTTP method override, content-type confusion, or double encoding",
            "Direct-to-IP scanning bypassing all Cloudflare security layers",
            "Workers endpoints with unvalidated fetch() calls enabling SSRF to internal services",
            "DNS records exposing origin IP via MX, SPF, TXT, or historical DNS lookups",
            "Argo Tunnel authentication token leakage exposing local services",
            "R2 buckets with public access policies exposing stored data",
            "Cloudflare Pages secret env vars exposed via build output or worker bindings",
            "Zone transfer (AXFR) enabled allowing complete DNS record exfiltration",
            "API endpoints not behind API Shield or Access authentication",
            "SSL mode set to Flexible allowing plaintext HTTP between CF and origin",
            "Cloudflare Access bypass via misconfigured exclude/include rules",
        ],
        investigation_areas=[
            "Discover origin IP via Shodan/Censys, favicon hash, MX records, and certificate transparency logs",
            "Test WAF bypass techniques (HTTP method override, content-type, encoding, parameter pollution)",
            "Check for direct-to-origin access by scanning discovered origin IPs",
            "Enumerate Cloudflare Workers subdomains (workers.dev)",
            "Look for Argo Tunnel endpoints (cfargotunnel.com) and test their auth",
            "Check Cloudflare DNS records via passive DNS and zone transfer attempts",
            "Search for Cloudflare API tokens and Workers secrets in public repos",
            "Test Cloudflare Access-protected pages for bypass techniques",
            "Enumerate R2 buckets for public access",
            "Check cdn-cgi endpoints for debugging info exposure (/cdn-cgi/trace)",
            "Analyze Cloudflare WAF behavior by probing with attack patterns",
            "Review SSL/TLS configuration by testing https and http origin direct access",
        ],
        tags=["cloudflare", "cdn", "waf", "dns", "workers", "edge"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "cloudflare",
            "CF-RAY": "",
            "cf-request-id": "",
            "x-amz-cf-id": "",
            "x-content-type-options": "nosniff",
            "x-frame-options": "SAMEORIGIN",
            "Expect-CT": "",
            "Report-To": "",
        },
        cookies=["__cfduid", "__cf_bm", "cf_clearance", "__cf_chl_f_tk", "__cf_chl_opt", "__cf_chl_root"],
        js_indicators=["Cloudflare", "cf-", "turnstile", "cf_chl_opt", "cloudflare.com/cdn-cgi/", "cf_challenge"],
        file_indicators=["wrangler.toml", "workers.toml", "cloudflare.toml", "_worker.js", "worker.js", ".cloudflare/", "cf-api-token", "cloudflare_api"],
        directory_indicators=["/cdn-cgi/", "/.cloudflare/"],
        server_signatures=["cloudflare", "cloudflare-nginx", "Cloudflare", "cloudflare-worker"],
        error_page_signatures=["cloudflare", "Cloudflare", "Error 1000 (DNS points to prohibited IP)", "Error 1001 (DNS resolution error)", "Error 1002 (DNS points to local or disallowed IP)", "Error 1003 (Access Denied)", "Error 1010 (Access Denied - Bad IP)", "Error 1011 (Access Denied - Hotlinking)", "Error 1012 (Access Denied - Malicious Request)", "Error 1015 (Rate Limited)", "Error 1020 (Access Denied)", "Error 1025 (Please enable JavaScript)", "Error 1033 (Argo Tunnel error)", "error code: 1020", "Attention Required! | Cloudflare"],
        default_paths=["/cdn-cgi/trace", "/cdn-cgi/scripts/", "/cdn-cgi/rum", "/cdn-cgi/challenge-platform/", "/.well-known/cloudflare/", "/favicon.ico"],
        default_files=["wrangler.toml", "workers.toml", "_worker.js", "worker.js", "route.yaml", "pages.toml", "functions/", ".env (Workers)", "cloudflare_api.txt"],
        metadata_patterns={"CF-RAY": "\\w+-\\w+", "cloudflare": "cloudflare", "error code": "\\d{4}"},
        tags=["fingerprint", "cloudflare", "cdn", "waf"],
    ),
    recon=ReconProfile(
        directories_to_check=["/cdn-cgi/", "/.cloudflare/", "/workers/", "/pages/", "/.well-known/cloudflare/", "/favicon.ico"],
        files_to_check=["wrangler.toml", "workers.toml", "_worker.js", "worker.js", "route.yaml", "pages.toml", ".env", "cloudflare.toml", "Dockerfile", "build/", "functions/"],
        endpoints_to_scan=["https://{target}/cdn-cgi/trace", "https://{target}/cdn-cgi/scripts/", "https://{target} (direct via IP)", "https://{subdomain}.workers.dev/", "https://{project}.pages.dev/", "https://{tunnel-id}.cfargotunnel.com/"],
        subdomains_to_check=["workers.dev", "pages.dev", "cfargotunnel.com", "r2.cloudflarestorage.com", "cloudflare.com"],
        dns_records_to_check=["A", "AAAA", "CNAME", "MX", "TXT", "NS", "SOA", "SPF"],
        port_scan_targets=[443, 80, 2052, 2053, 2082, 2083, 2086, 2087, 2095, 2096, 8080, 8443, 8880],
        version_detection_paths=["/cdn-cgi/trace", "/cdn-cgi/scripts/", "/favicon.ico"],
        debug_paths_to_check=["/cdn-cgi/trace", "/cdn-cgi/scripts/", "/cdn-cgi/rum", "/cdn-cgi/challenge-platform/", "/debug/"],
        admin_paths_to_check=["/admin/", "/.cloudflare/", "/__workers/", "/dashboard/", "/management/"],
        tags=["recon", "cloudflare", "cdn", "waf", "dns"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Origin IP discovered via Shodan, Censys, or DNS historical records bypasses Cloudflare WAF/CDN entirely",
            impact="Complete bypass of Cloudflare security — direct access to origin server without WAF, DDoS protection, rate limiting, or bot management",
            attack_scenario="Find origin IP via Shodan search for target domain; review certificate transparency logs; check favicon hash against Shodan; scan MX records for mail server IPs in same range; directly access origin IP on port 443/80",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="WAF bypass via HTTP method override (X-HTTP-Method-Override header) to perform POST operations via GET bypassing WAF rules",
            impact="WAF rules that only inspect specific HTTP methods can be completely bypassed — enabling SQLi, XSS, and other injection attacks",
            attack_scenario="Send request with X-HTTP-Method-Override header: POST; WAF sees a GET request (potentially un-inspected) but origin processes it as POST; test with SQLi payloads in POST body while using GET method",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Cloudflare Workers fetch() calls without URL validation allowing SSRF to internal services (metadata services, internal APIs)",
            impact="SSRF from Workers to internal cloud metadata services (169.254.169.254) or internal APIs — credential theft and lateral movement",
            attack_scenario="Find Workers endpoint; identify input parameter passed to fetch(); provide http://169.254.169.254/latest/meta-data/ or internal API URL; read response for credentials or sensitive data",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Cloudflare Argo Tunnel token leakage exposing locally served applications that were meant to be private",
            impact="Unauthorized access to internal applications — developer tools, admin panels, staging environments, and internal APIs exposed via tunnel",
            attack_scenario="Find Argo Tunnel endpoint via subdomain scan of cfargotunnel.com; access https://{tunnel-id}.cfargotunnel.com/; if no additional auth, access internal applications directly",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Cloudflare Access policy misconfiguration allowing bypass via path exclusion or JWT manipulation",
            impact="Unauthorized access to protected applications — admin panels, internal dashboards, and API endpoints behind Cloudflare Access",
            attack_scenario="Identify Access-protected URL; manipulate JWT tokens; test path exclusions that don't require auth; try to access /.well-known/ or /cdn-cgi/ path bypasses",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="SSL/TLS mode set to Flexible allowing plaintext HTTP communication between Cloudflare edge and origin server",
            impact="Man-in-the-middle attack on traffic between Cloudflare and origin — interception of sensitive data, credentials, and API tokens in transit",
            attack_scenario="If positioned between Cloudflare and origin (e.g., same network, compromised router), capture HTTP traffic; extract session tokens, API keys, and form submissions in plaintext",
            complexity="high",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="aws",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Cloudflare often fronts AWS-hosted applications (EC2, S3, ALB)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="azure",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Cloudflare often fronts Azure-hosted applications (App Service, Azure Front Door alternative)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="gcp",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Cloudflare often fronts GCP-hosted applications (Cloud Run, GKE, App Engine)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="nginx",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Cloudflare compatible with Nginx origin servers (real-ip module for CF-Connecting-IP)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="kubernetes",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Cloudflare Ingress Controller for Kubernetes integrated with Cloudflare WAF/CDN",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Cloudflare can front Docker-deployed applications on any cloud or on-premise",
            confidence="high",
        ),
    ],
    dependencies=["Cloudflare DNS", "Cloudflare WAF (Web Application Firewall)", "Cloudflare Workers (optional)"],
    related_packs=["aws", "azure", "gcp", "nginx", "kubernetes"],
    workflow=[
        "1. Check if site uses Cloudflare (HTTP headers, DNS records, cdn-cgi path)",
        "2. Discover origin IP via Shodan, Censys, favicon hash, MX records, historical DNS",
        "3. Test direct-to-origin access bypassing Cloudflare",
        "4. Analyze WAF behavior by sending common attack patterns and observing responses",
        "5. Attempt WAF bypass techniques (method override, content-type, encoding, PP)",
        "6. Enumerate Workers subdomains and test for SSRF via fetch()",
        "7. Look for Argo Tunnel endpoints on cfargotunnel.com",
        "8. Check for exposed .env, wrangler.toml, and Workers secrets in repos",
        "9. Enumerate Cloudflare DNS records via zone transfer and passive DNS",
        "10. Test Cloudflare Access-protected pages for auth bypass",
        "11. Review SSL/TLS configuration (Flexible vs Full Strict)",
        "12. Check R2 bucket and Pages project exposure",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="CF-01",
            category="Origin IP Discovery",
            description="Discover true origin server IP bypassing Cloudflare and test direct access",
            expected_result="Origin IP should not be discoverable and Cloudflare should be the only entry point",
            tools=["Shodan", "Censys", "favirecon", "dnsdumpster", "SecurityTrails", "certspotter"],
            references=["https://community.cloudflare.com/t/best-practices-to-prevent-origin-ip-exposure/"],
        ),
        ManualTestChecklistItem(
            step_id="CF-02",
            category="WAF Bypass Testing",
            description="Test WAF bypass techniques including HTTP method override, content-type switching, encoding, and parameter pollution",
            expected_result="WAF rules should block malicious requests regardless of encoding or method obfuscation",
            tools=["Burp Suite", "curl", "wafw00f", "sqlmap (--tamper options)", "bypass-403"],
            references=["https://developers.cloudflare.com/waf/"],
        ),
        ManualTestChecklistItem(
            step_id="CF-03",
            category="DNS Zone Review",
            description="Check DNS zone configuration for unintended information disclosure and zone transfer",
            expected_result="Zone transfers should be disabled, DNS records should not reveal origin IP or internal hostnames",
            tools=["dig", "nslookup", "dnsrecon", "dnsenum"],
            references=["https://developers.cloudflare.com/dns/"],
        ),
        ManualTestChecklistItem(
            step_id="CF-04",
            category="SSL/TLS Mode Check",
            description="Verify SSL/TLS configuration is Full (strict) to prevent MiTM between CF and origin",
            expected_result="SSL/TLS mode should be Full (strict) or higher, never Flexible",
            tools=["curl", "OpenSSL s_client", "SSL Labs"],
            references=["https://developers.cloudflare.com/ssl/origin-configuration/ssl-modes/"],
        ),
        ManualTestChecklistItem(
            step_id="CF-05",
            category="Workers SSRF",
            description="Test Cloudflare Workers endpoints for SSRF via unvalidated fetch() calls",
            expected_result="Workers should not make requests to user-supplied URLs without strict validation",
            tools=["curl", "Burp Suite", "custom scripts"],
            references=["https://developers.cloudflare.com/workers/configuration/security/"],
        ),
        ManualTestChecklistItem(
            step_id="CF-06",
            category="Access Policy Review",
            description="Test Cloudflare Access-protected applications for policy bypass",
            expected_result="Access policies should correctly block unauthorized requests across all paths",
            tools=["curl", "browser", "jwt_tool"],
            references=["https://developers.cloudflare.com/cloudflare-one/policies/access/"],
        ),
        ManualTestChecklistItem(
            step_id="CF-07",
            category="Argo Tunnel Exposure",
            description="Check for exposed Argo Tunnel endpoints without additional authentication",
            expected_result="Argo Tunnel endpoints should have additional Cloudflare Access or origin authentication",
            tools=["curl", "subdomain enumeration"],
            references=["https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/"],
        ),
        ManualTestChecklistItem(
            step_id="CF-08",
            category="API Shield Review",
            description="Verify API Shield configuration for mTLS, schema validation, and rate limiting",
            expected_result="API endpoints should enforce mTLS and schema validation",
            tools=["curl", "Postman", "custom scripts"],
            references=["https://developers.cloudflare.com/api-shield/"],
        ),
    ],
    references=[
        {"title": "Cloudflare Security Documentation", "url": "https://developers.cloudflare.com/fundamentals/security/"},
        {"title": "Cloudflare WAF Documentation", "url": "https://developers.cloudflare.com/waf/"},
        {"title": "HackTricks - Cloudflare Pentesting", "url": "https://book.hacktricks.xyz/cloud-security/cloudflare-pentesting"},
        {"title": "Cloudflare Bypass Techniques", "url": "https://www.cloudflare.com/ips/"},
        {"title": "Cloudflare Workers Security", "url": "https://developers.cloudflare.com/workers/configuration/security/"},
        {"title": "Cloudflare API Documentation", "url": "https://api.cloudflare.com/"},
        {"title": "Cloudflare WAF Bypass Techniques", "url": "https://github.com/0xInfection/Awesome-WAF#bypass-techniques"},
    ],
    cwe_ids=["CWE-918", "CWE-200", "CWE-862", "CWE-306", "CWE-693", "CWE-200", "CWE-319", "CWE-732"],
    cve_ids=["CVE-2023-33934", "CVE-2022-23694", "CVE-2021-38147", "CVE-2020-15950", "CVE-2020-10124"],
    tags=["cloudflare", "cdn", "waf", "dns", "workers", "ssl", "access", "argo"],
)
