"""GCP knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="gcp",
    version="1.0.0",
    category=KnowledgePackCategory.CLOUD,
    description="Google Cloud Platform — Compute Engine metadata service SSRF, Cloud Storage bucket enumeration, IAM misconfiguration, Cloud Functions injection, Cloud Run exposure, API Gateway bypass, Firestore/Firebase misconfiguration, Secret Manager access, and KMS key exposure.",
    technology=TechnologyProfile(
        name="Google Cloud Platform",
        vendor="Google",
        language="",
        runtime="GCP Global Infrastructure",
        description="Google Cloud Platform is a suite of cloud computing services running on the same infrastructure that Google uses internally. Offers compute (Compute Engine, GKE, Cloud Run, Cloud Functions), storage (Cloud Storage, Filestore), database (Firestore, BigQuery, Cloud SQL, Spanner), networking (VPC, Cloud CDN, Cloud Load Balancing), and security (IAM, Cloud KMS, Secret Manager, Cloud Armor).",
        common_aliases=["gcp", "google cloud", "gcloud", "google cloud platform", "g suite"],
        dependencies=["gcloud CLI", "Google Cloud SDK", "Terraform", "Deployment Manager", "Kubernetes (GKE)"],
        common_integrations=["Compute Engine", "Cloud Storage", "Cloud Functions", "Cloud Run", "GKE", "Cloud SQL", "Firestore", "BigQuery", "Cloud IAM", "Secret Manager", "Cloud KMS", "Cloud Endpoints", "Apigee", "Cloud Armor", "Cloud CDN", "Cloud Scheduler", "Cloud Tasks", "Pub/Sub"],
        architecture_description="Global infrastructure organized into regions, zones, and multi-regions. Hierarchical resource hierarchy: Organization -> Folder -> Project -> Resources. IAM policies are inherited through the hierarchy. VPC networks provide global, scalable networking.",
        request_lifecycle="Client -> GCP API endpoint (auth via OAuth2 access token / service account key) -> Service-specific processing -> Response",
        documentation_url="https://cloud.google.com/docs",
        tags=["cloud", "gcp", "google", "iaas", "paas", "faas"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Compute Engine Metadata Service",
            description="HTTP endpoint at 169.254.169.254 providing instance metadata and service account access tokens for GCE instances. Primary SSRF target in GCP.",
            security_relevance="high",
            common_vulnerabilities=["SSRF to metadata service for OAuth2 access token theft", "Metadata service accessible from container (GKE) workloads", "Custom metadata values containing secrets", "Project and instance metadata enumeration", "Kubernetes service account tokens via metadata"],
            investigation_priority=95,
            tags=["compute-engine", "metadata", "ssrf", "gce", "service-account"],
        ),
        TechnologyComponentProfile(
            name="Cloud Storage (GCS)",
            description="Object storage service with uniform and fine-grained access control. Public buckets, signed URLs, and object versioning.",
            security_relevance="high",
            common_vulnerabilities=["Publicly accessible Cloud Storage buckets", "Bucket policy with allUsers/allAuthenticatedUsers access", "Signed URLs with excessive time window and permissions", "Object versioning exposing deleted data", "Bucket with no public access prevention enforced", "Uniform bucket-level access not enabled"],
            investigation_priority=95,
            tags=["cloud-storage", "gcs", "bucket", "public-access", "data-leak"],
        ),
        TechnologyComponentProfile(
            name="Cloud IAM",
            description="Unified access control for all GCP resources. Roles (basic, predefined, custom), service accounts, and policies.",
            security_relevance="high",
            common_vulnerabilities=["Service account with overly broad IAM roles (roles/owner, roles/editor)", "Custom IAM roles with wildcard permissions", "Service account key leakage (JSON key files)", "Workload identity federation misconfiguration", "Cross-project service account impersonation", "IAM policy with allAuthenticatedUsers bindings"],
            investigation_priority=95,
            tags=["iam", "roles", "service-account", "permissions", "authorization"],
        ),
        TechnologyComponentProfile(
            name="Cloud Functions",
            description="Serverless compute service for event-driven and HTTP-triggered functions. Function source code, environment variables, and service account.",
            security_relevance="high",
            common_vulnerabilities=["Cloud Functions HTTP trigger without authentication", "Environment variable exposure (secrets, API keys, DB creds)", "Overprivileged Cloud Functions service account", "Code injection via HTTP or event payload", "Unsecured function dependencies with known CVEs"],
            investigation_priority=90,
            tags=["cloud-functions", "serverless", "faas", "injection", "env"],
        ),
        TechnologyComponentProfile(
            name="Cloud Run",
            description="Managed compute platform for stateless containers. Container image, environment variables, and service account.",
            security_relevance="high",
            common_vulnerabilities=["Cloud Run service without IAM auth (allUsers invocation)", "Environment variable secrets in plaintext", "Overprivileged Cloud Run service account permissions", "Container image with vulnerabilities from Artifact Registry", "Cloud Run revision exposure (older vulnerable revisions accessible)"],
            investigation_priority=90,
            tags=["cloud-run", "serverless", "containers", "knative", "auth"],
        ),
        TechnologyComponentProfile(
            name="Secret Manager",
            description="Managed service for storing API keys, passwords, certificates, and other sensitive data.",
            security_relevance="high",
            common_vulnerabilities=["Overly permissive IAM on Secret Manager (secretmanager.secretAccessor)", "Secrets with no version destruction", "Secrets exposed via Cloud Functions env vars", "Secret Manager audit logging disabled"],
            investigation_priority=90,
            tags=["secret-manager", "secrets", "credentials", "encryption"],
        ),
        TechnologyComponentProfile(
            name="Firestore / Firebase",
            description="NoSQL document database with real-time capabilities. Security rules, Firebase Auth, and Firestore indexes.",
            security_relevance="high",
            common_vulnerabilities=["Firebase Realtime Database with read/write open to all", "Firestore security rules allowing public read/write", "Firebase API keys exposed in mobile apps or web clients", "Firebase Auth misconfiguration allowing account takeover", "Firestore with no data validation"],
            investigation_priority=90,
            tags=["firestore", "firebase", "nosql", "database", "security-rules"],
        ),
        TechnologyComponentProfile(
            name="Cloud SQL",
            description="Managed relational database service for PostgreSQL, MySQL, and SQL Server. Public IP, SSL enforcement, and IAM authentication.",
            security_relevance="high",
            common_vulnerabilities=["Cloud SQL instance with public IP authorized via 0.0.0.0/0", "SSL/TLS not enforced for connections", "Default or weak database passwords", "Cloud SQL proxy not used forcing direct connection", "Automated backup exposure via export to public bucket"],
            investigation_priority=85,
            tags=["cloud-sql", "database", "postgresql", "mysql", "public"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="GCE Metadata Service",
                description="SSRF target at http://169.254.169.254/computeMetadata/v1/",
                protocol="HTTP",
                method="GET",
                path="http://169.254.169.254/computeMetadata/v1/",
                parameters=["recursive", "alt"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.SSRF.value, BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Cloud Storage Bucket",
                description="GCS bucket potentially allowing public listing or access",
                protocol="HTTPS",
                method="GET",
                path="https://{bucket}.storage.googleapis.com/",
                parameters=["prefix", "delimiter", "maxResults", "versions", "projection"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Cloud Function HTTP Trigger",
                description="Cloud Functions HTTP endpoint potentially exposed without auth",
                protocol="HTTPS",
                method="ANY",
                path="https://{region}-{project}.cloudfunctions.net/{function}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.COMMAND_INJECTION.value, BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Cloud Run Service",
                description="Cloud Run service potentially accessible without authentication",
                protocol="HTTPS",
                method="ANY",
                path="https://{service}-{hash}-{region}-a.run.app/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.COMMAND_INJECTION.value, BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Firebase Realtime Database",
                description="Firebase Realtime Database with potentially open read/write rules",
                protocol="HTTPS",
                method="ANY",
                path="https://{project}.firebaseio.com/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Firestore Database",
                description="Firestore database with potentially open security rules",
                protocol="HTTPS",
                method="ANY",
                path="https://firestore.googleapis.com/v1/projects/{project}/databases/(default)/documents/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="GCP API Endpoint",
                description="GCP REST API endpoints for various services",
                protocol="HTTPS",
                method="ANY",
                path="https://{service}.googleapis.com/{version}/{resource}",
                parameters=["key", "access_token", "oauth_token", "fields", "quotaUser", "prettyPrint"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token", "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/identity?audience=https://example.com", "https://{bucket}.storage.googleapis.com/", "https://{bucket}.storage.googleapis.com/?prefix=&delimiter=/", "https://{region}-{project}.cloudfunctions.net/", "https://{service}-{hash}-{region}-a.run.app/", "https://{project}.firebaseio.com/.json", "https://firestore.googleapis.com/v1/projects/{project}/databases/(default)/documents/", "https://secretmanager.googleapis.com/v1/projects/{project}/secrets", "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/{sa}:generateAccessToken"],
        parameters=["key", "access_token", "oauth_token", "bearer_token", "fields", "prettyPrint", "quotaUser", "alt", "oauth_provider", "recursive", "prefix", "delimiter", "maxResults", "versions", "projection"],
        authentication=["GCP OAuth2 (access token, refresh token, ID token)", "Service account keys (JSON key file — client_email, private_key)", "GCP IAM roles (user, service account, group, domain)", "Firebase Authentication (email/password, Google, Facebook, Apple, anonymous)", "Workload Identity Federation (AWS, Azure, OIDC provider)", "API keys for GCP APIs (limited scoping)"],
        authorization=["GCP IAM roles (basic: owner/editor/viewer, predefined service-specific roles, custom roles)", "Cloud Storage IAM & ACLs", "Firestore / Firebase security rules", "VPC firewall rules", "Cloud Armor security policies", "Organization policies", "IAM Conditions and deny policies"],
        storage=["Cloud Storage (GCS)", "Persistent Disk (SSD/HDD)", "Filestore", "Cloud SQL", "Firestore", "BigQuery", "Spanner", "Memorystore (Redis, Memcached)"],
        background_jobs=["Cloud Functions (event-driven by Pub/Sub, Storage, Firestore)", "Cloud Scheduler (cron jobs)", "Cloud Tasks (task queues)", "Workflows (workflow orchestration)", "Composer / Airflow", "BigQuery scheduled queries", "Cloud Build triggers"],
        queues=["Pub/Sub", "Cloud Tasks", "Cloud Scheduler", "Eventarc"],
        caches=["Memorystore (Redis, Memcached)", "Cloud CDN", "Cloud Load Balancing cache"],
        admin_interfaces=["Google Cloud Console (console.cloud.google.com)", "gcloud CLI", "Google Cloud SDK", "Cloud Shell", "Cloud Code (IDE extensions)"],
        internal_apis=["GCE metadata service (169.254.169.254)", "GKE metadata concealment", "Cloud DNS (169.254.169.254)", "GCE internal DNS", "VPC internal APIs"],
        external_apis=["Google APIs (googleapis.com)", "Firebase APIs (firebaseio.com)", "Cloud Functions URLs (cloudfunctions.net)", "Cloud Run URLs (run.app)", "App Engine URLs (appspot.com)", "Cloud Endpoints", "Apigee API management"],
        cloud_resources=["Compute Engine VMs", "Cloud Storage buckets", "Cloud Functions", "Cloud Run services", "GKE clusters", "Cloud SQL instances", "Firestore databases", "BigQuery datasets", "Secret Manager secrets", "Cloud KMS key rings", "VPC networks", "Cloud Router / Cloud NAT"],
        trust_boundaries=[
            TrustBoundary(name="Internet-to-GCP-Service", description="External users accessing GCP services (Cloud Functions, Cloud Run, GCS)", direction="inbound", sensitivity="high"),
            TrustBoundary(name="VM-to-Metadata", description="GCE instance requests to metadata service for OAuth2 tokens", direction="outbound", sensitivity="critical"),
            TrustBoundary(name="GKE-Workload-to-Metadata", description="GKE pod requests metadata service (unless metadata concealment is on)", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Service-Account-Impersonation", description="Service accounts generating tokens for other service accounts via IAM Credentials API", direction="bidirectional", sensitivity="high"),
        ],
        attack_surface_areas=[
            "GCE metadata service accessible via SSRF allowing OAuth2 access token theft",
            "Cloud Storage buckets with public access (allUsers/allAuthenticatedUsers)",
            "Cloud Functions / Cloud Run with allUsers invocation (no IAM auth required)",
            "Service account keys leaked in source code, Docker images, or config files",
            "IAM custom roles with wildcard permissions allowing privilege escalation",
            "Firebase RTDB / Firestore with open security rules allowing data read/write",
            "Secret Manager secrets with overprivileged IAM bindings",
            "Cloud SQL instances with public IP and 0.0.0.0/0 authorized networks",
            "App Engine versions exposed publicly with no auth",
            "GKE clusters with legacy ABAC or overly permissive RBAC",
            "Cloud KMS key rings with public IAM bindings",
            "Cloud Build logs and artifacts exposing service account tokens",
        ],
        investigation_areas=[
            "Check for SSRF to GCE metadata service at 169.254.169.254",
            "Enumerate Cloud Storage buckets for public access",
            "Test Cloud Functions endpoints for no-auth invocation and injection",
            "Check Cloud Run services for allUsers IAM policy",
            "Look for Firebase databases with open security rules",
            "Search for service account JSON keys in repos, images, and configs",
            "Review IAM policies for overprivileged service accounts",
            "Check Secret Manager IAM bindings and secret versions",
            "Test Cloud SQL for public access and weak credentials",
            "Enumerate App Engine services and versions",
            "Review KMS key rings for public IAM bindings",
            "Check GKE cluster RBAC and metadata concealment configuration",
        ],
        tags=["gcp", "cloud", "google", "cloud-storage", "cloud-functions", "iam"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "Google Frontend",
            "X-GUploader-UploadID": "",
            "X-Goog-Request-Reason": "",
            "X-Goog-Meta-": "",
            "X-Cloud-Trace-Context": "",
        },
        cookies=["X-Goog-AuthUser", "X-Goog-PageId", "G_AUTHUSER_", "SAPISID", "APISID", "SSID", "HSID", "NID"],
        js_indicators=["@google-cloud/", "firebase", "firebase.initializeApp", "gapi.client", "gapi.auth2", "googleapis", "gcloud", "google-cloud", "firebaseio.com", "storage.googleapis.com", "cloudfunctions.net", "run.app"],
        file_indicators=["gcloud", "google_cloud", "credentials.json", "service-account.json", "serviceaccount.json", "key.json", "*.json (service account key)", "application_default_credentials.json", ".gcloud/", "config.json (firebase)", "google-services.json", "GoogleService-Info.plist"],
        directory_indicators=[".gcloud/", ".config/gcloud/"],
        server_signatures=["Google Frontend", "GUpload", "gws", "Google Cloud", "ESF (Extended Service Framework)"],
        error_page_signatures=["AccessDenied", "NotAuthorized", "ProjectNotActivated", "BucketNotFound", "ServiceUnavailable", "Forbidden", "Not Found", "The project is not found", "Your application has authenticated using end user credentials"],
        default_paths=["/", "/.json (Firebase)", "/computeMetadata/v1/", "/v1/projects/", "/v1/secrets/", "/v1/functions/", "/v1/services/", "/v1/instances/", "/v1/databases/"],
        default_files=["credentials.json", "service-account.json", "key.json", "google-services.json", "GoogleService-Info.plist", "firebase-config.js", ".gcloud/config", "application_default_credentials.json", "terraform.tfstate", "terraform.tfvars", "main.tf", "deployment.yaml"],
        metadata_patterns={"X-GUploader-UploadID": ".+", "x-goog-": ".+", "Google": "Frontend"},
        tags=["fingerprint", "gcp", "google-cloud"],
    ),
    recon=ReconProfile(
        directories_to_check=["/.gcloud/", "/.config/gcloud/", "/credentials/", "/keys/", "/secrets/", "/firebase/", "/deployment/"],
        files_to_check=["credentials.json", "service-account.json", "key.json", "google-services.json", "GoogleService-Info.plist", "firebase-config.js", "application_default_credentials.json", "terraform.tfstate", "main.tf", "deployment.yaml", "Dockerfile", ".env", "cloudbuild.yaml", "app.yaml", "requirements.txt", "package.json"],
        endpoints_to_scan=["https://{bucket}.storage.googleapis.com/", "https://{project}.firebaseio.com/.json", "https://{region}-{project}.cloudfunctions.net/", "https://{service}-{hash}-{region}-a.run.app/", "https://secretmanager.googleapis.com/v1/projects/{project}/secrets", "http://169.254.169.254/computeMetadata/v1/", "https://oauth2.googleapis.com/token"],
        subdomains_to_check=["storage.googleapis.com", "cloudfunctions.net", "run.app", "firebaseio.com", "firestore.googleapis.com", "appspot.com", "googleapis.com", "cloud.google.com"],
        dns_records_to_check=["CNAME", "TXT", "MX", "NS", "SOA"],
        port_scan_targets=[443, 80, 3306, 5432, 6379, 11211, 27017, 5000, 8080, 9000],
        version_detection_paths=["/", "/?key={dummy}", "/v1/projects/"],
        debug_paths_to_check=["/debug/", "/_debug/", "/debug-info", "/health", "/info", "/status"],
        admin_paths_to_check=["/admin/", "/console/", "/gcp/", "/cloud/", "/management/", "/_admin/"],
        tags=["recon", "gcp", "google-cloud", "storage", "functions"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="SSRF to GCE metadata service allowing theft of OAuth2 access tokens for the instance's default service account",
            impact="Complete project compromise — stolen access tokens can access any GCP resource the service account has IAM permissions for, including Cloud Storage, Secret Manager, Cloud SQL, and Cloud KMS",
            attack_scenario="Trigger SSRF via vulnerable parameter to http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token with Metadata-Flavor: Google header; parse JSON response for access_token; use with gcloud --access-token=... to call GCP APIs",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Cloud Storage bucket with allUsers or allAuthenticatedUsers IAM binding allowing public read/list access",
            impact="Data leakage of all stored objects — potential exposure of PII, backups, configs, database dumps, and credentials",
            attack_scenario="List bucket via https://bucket.storage.googleapis.com/?prefix=; download all objects; analyze for sensitive data; check versioning for deleted object recovery",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Cloud Functions / Cloud Run with IAM policy allowing allUsers invocation, exposing the endpoint to the entire internet without auth",
            impact="Unauthenticated access to serverless application logic — data exfiltration, injection attacks, business logic abuse, and resource hijacking",
            attack_scenario="Discover Cloud Functions URL via OpenAPI spec, JS file, or subdomain scan; call function endpoint directly; test for injection (SQL, NoSQL, command) and data exposure via error messages and responses",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Service account JSON key file leaked in source code repository, Docker image layer, or exposed deployment artifact",
            impact="Full GCP project compromise — the leaked key allows authentication as that service account with all its IAM permissions",
            attack_scenario="Find credentials.json or key.json in public repo, Docker image, or exposed /credentials/ directory; configure GOOGLE_APPLICATION_CREDENTIALS; use gcloud to enumerate and access all resources the SA has access to",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Firebase Realtime Database or Firestore with security rules allowing public read and write access to all data",
            impact="Complete data loss and exposure — all user data, application state, and configuration can be read, modified, or deleted by anyone",
            attack_scenario="Determine Firebase project ID from client app; access https://project.firebaseio.com/.json to get entire RTDB dump; for Firestore, access via REST API at /documents/ path; write malicious data, delete collections",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="IAM custom role with wildcard permissions (roles/*) or overly broad service account permissions allowing privilege escalation",
            impact="Privilege escalation from limited access to full project admin — attacker can create, modify, and delete any resource",
            attack_scenario="With compromised service account, enumerate IAM policy; if SA has iam.roles.update or iam.serviceAccounts.getAccessToken, escalate by granting additional permissions or generating tokens for more privileged SAs",
            complexity="medium",
            requires_authentication=True,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="aws",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="GCP and AWS are competing cloud platforms",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="azure",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="GCP and Azure are competing cloud platforms",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="kubernetes",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="GCP integrates with Kubernetes via GKE",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="GCP provides Artifact Registry for container storage and GKE/Cloud Run for container hosting",
            confidence="high",
        ),
    ],
    dependencies=["gcloud CLI", "Google Cloud SDK", "Terraform GCP provider", "Deployment Manager"],
    related_packs=["aws", "azure", "cloudflare", "kubernetes", "docker"],
    workflow=[
        "1. Enumerate GCP subdomains (storage.googleapis.com, cloudfunctions.net, run.app, firebaseio.com, appspot.com)",
        "2. Check for SSRF to GCE metadata service targeting OAuth2 token endpoint",
        "3. Enumerate Cloud Storage buckets for public listing and access",
        "4. Test Cloud Functions HTTP endpoints for unauthorized invocation",
        "5. Check Cloud Run services for allUsers IAM policy",
        "6. Look for Firebase databases with open security rules",
        "7. Search for service account JSON keys in repos, images, and publicly exposed files",
        "8. Review IAM policies for overprivileged roles and wildcard permissions",
        "9. Check Secret Manager secrets and their IAM bindings",
        "10. Test Cloud SQL instances for public IP and weak authorized networks",
        "11. Enumerate App Engine services and versions for exposure",
        "12. Review GKE cluster RBAC and metadata concealment settings",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="GCP-01",
            category="SSRF via Metadata Service",
            description="Test SSRF to access GCE metadata service at 169.254.169.254/computeMetadata/v1/",
            expected_result="Metadata service should not be accessible via SSRF — network filtering or metadata concealment should be in place",
            tools=["curl", "Burp Suite", "ffuf", "ssrf-tool"],
            references=["https://cloud.google.com/compute/docs/storing-retrieving-metadata"],
        ),
        ManualTestChecklistItem(
            step_id="GCP-02",
            category="Cloud Storage Enumeration",
            description="Enumerate Cloud Storage buckets and check for public access",
            expected_result="No public read/list access to Cloud Storage buckets; public access prevention should be enabled",
            tools=["gcloud", "gsutil", "cloud_enum", "bucket-stream"],
            references=["https://cloud.google.com/storage/docs/access-control/making-data-public"],
        ),
        ManualTestChecklistItem(
            step_id="GCP-03",
            category="Cloud Functions Auth Bypass",
            description="Check Cloud Functions for allUsers IAM policy allowing unauthenticated invocation",
            expected_result="Cloud Functions should require IAM authentication unless explicitly designed as public",
            tools=["curl", "gcloud", "nuclei"],
            references=["https://cloud.google.com/functions/docs/securing/managing-access-iam"],
        ),
        ManualTestChecklistItem(
            step_id="GCP-04",
            category="Service Account Key Exposure",
            description="Search for leaked service account JSON keys in source code, Docker images, and public storage",
            expected_result="Service account keys should not be committed to source code or exposed in public repositories",
            tools=["git-secrets", "truffleHog", "gitleaks", "Google Dorks"],
            references=["https://cloud.google.com/iam/docs/creating-managing-service-account-keys"],
        ),
        ManualTestChecklistItem(
            step_id="GCP-05",
            category="Firebase Security Rules",
            description="Test Firebase Realtime Database and Firestore for open security rules",
            expected_result="Firebase security rules should restrict read/write access to authenticated users only",
            tools=["curl", "firebase-tools", "Firebase Scanner"],
            references=["https://firebase.google.com/docs/rules"],
        ),
        ManualTestChecklistItem(
            step_id="GCP-06",
            category="IAM Policy Review",
            description="Review IAM policies for overprivileged service accounts and wildcard permissions",
            expected_result="IAM roles should follow least privilege with no wildcard permissions on service accounts",
            tools=["gcloud", "policy-analyzer", "terraform-validator"],
            references=["https://cloud.google.com/iam/docs/understanding-roles"],
        ),
        ManualTestChecklistItem(
            step_id="GCP-07",
            category="Secret Manager Access",
            description="Check Secret Manager IAM bindings for overprivileged access to secrets",
            expected_result="Only authorized principals should have secretmanager.secretAccessor permission",
            tools=["gcloud", "policy-analyzer"],
            references=["https://cloud.google.com/secret-manager/docs/access-control"],
        ),
        ManualTestChecklistItem(
            step_id="GCP-08",
            category="Cloud SQL Public Access",
            description="Check Cloud SQL instances for public IP and 0.0.0.0/0 authorized networks",
            expected_result="Cloud SQL instances should use private IP or restrict authorized networks to specific IPs",
            tools=["gcloud", "nmap", "psql / mysql client"],
            references=["https://cloud.google.com/sql/docs/mysql/configure-ip"],
        ),
    ],
    references=[
        {"title": "GCP Security Documentation", "url": "https://cloud.google.com/security"},
        {"title": "Google Cloud Security Foundations Guide", "url": "https://cloud.google.com/security/foundations"},
        {"title": "HackTricks - GCP Pentesting", "url": "https://book.hacktricks.xyz/cloud-security/gcp-pentesting"},
        {"title": "Rhino Security Labs - GCP Privilege Escalation", "url": "https://rhinosecuritylabs.com/gcp/privilege-escalation-google-cloud-platform-part-1/"},
        {"title": "gcp_scanner", "url": "https://github.com/google/gcp_scanner"},
        {"title": "Cloudsploit", "url": "https://github.com/nccgroup/ScoutSuite"},
        {"title": "GCP CLI", "url": "https://cloud.google.com/sdk/gcloud"},
    ],
    cwe_ids=["CWE-918", "CWE-200", "CWE-269", "CWE-862", "CWE-732", "CWE-522", "CWE-284", "CWE-306", "CWE-668", "CWE-798"],
    cve_ids=["CVE-2023-44487", "CVE-2022-35681", "CVE-2022-21436", "CVE-2021-22555", "CVE-2021-20268", "CVE-2020-14386"],
    tags=["gcp", "cloud", "google", "cloud-storage", "cloud-functions", "firebase", "iam", "cloud-run", "secret-manager"],
)
