"""Apache HTTP Server knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="apache",
    version="1.0.0",
    category=KnowledgePackCategory.WEBSERVER,
    description="Apache HTTP Server — directory listing, .htaccess bypass and misconfiguration, server-status and server-info exposure, mod_status information leak, CGI-BIN execution, server tokens disclosure, HTTP request smuggling, mod_rewrite open redirect.",
    technology=TechnologyProfile(
        name="Apache HTTP Server",
        vendor="Apache Software Foundation",
        language="C",
        runtime="Apache (prefork/worker/event MPM)",
        description="Apache HTTP Server is the world's most widely used web server, known for its modular architecture, extensive module ecosystem, and flexibility. Supports dynamic modules, virtual hosts, .htaccess per-directory configuration, and multiple MPMs.",
        common_aliases=["apache", "apache2", "httpd", "apache-httpd"],
        dependencies=["Linux/Unix/Windows", "APR (Apache Portable Runtime)", "PCRE", "OpenSSL"],
        common_integrations=["mod_php", "mod_perl", "mod_python", "mod_wsgi", "mod_jk", "mod_proxy", "mod_security", "OpenSSL", "Tomcat (mod_jk/mod_proxy_ajp)"],
        architecture_description="Modular, multi-processing architecture supporting prefork (process-based), worker (hybrid), and event (async) MPMs. Each request is handled by a worker thread/process within a virtual host context.",
        request_lifecycle="Client -> TCP connection -> MPM worker -> Virtual host matching -> .htaccess processing -> URL rewriting -> Module chain -> Response generation -> Logging",
        documentation_url="https://httpd.apache.org/docs/",
        tags=["webserver", "httpd", "c", "modular", "virtual-hosts"],
    ),
    components=[
        TechnologyComponentProfile(
            name="mod_status",
            description="Server status page showing server health, active connections, request rate, and worker status. Can leak internal server information.",
            security_relevance="high",
            common_vulnerabilities=["Information disclosure via /server-status", "Connection pool enumeration", "Request rate exposure", "Worker process information leak"],
            investigation_priority=90,
            tags=["status", "information-disclosure", "monitoring"],
        ),
        TechnologyComponentProfile(
            name="mod_info",
            description="Server configuration information page exposing all loaded modules and their settings. Severely leaks server internals.",
            security_relevance="high",
            common_vulnerabilities=["Full configuration disclosure via /server-info", "Module version exposure", "Directory path leaks", "Loaded extension enumeration"],
            investigation_priority=95,
            tags=["info", "configuration-disclosure", "information-disclosure"],
        ),
        TechnologyComponentProfile(
            name="mod_rewrite",
            description="URL rewriting engine based on server/config/virtual-host-level rules. Open redirect, regex bypass, SSRF via proxy rewrites.",
            security_relevance="high",
            common_vulnerabilities=["Open redirect via $1 backreferences", "Rewrite rule bypass", "SSRF via proxy flag [P]", "Regex injection"],
            investigation_priority=85,
            tags=["rewrite", "redirect", "regex", "proxy"],
        ),
        TechnologyComponentProfile(
            name=".htaccess / AllowOverride",
            description="Per-directory configuration files override server-level settings. Misconfiguration can disable auth, expose files, or enable CGI execution.",
            security_relevance="high",
            common_vulnerabilities=[".htaccess bypass via AllowOverride misconfig", ".htaccess file disclosure", "Auth bypass via .htaccess override", "CGI execution via AddHandler/AddType"],
            investigation_priority=90,
            tags=["htaccess", "configuration", "auth", "override"],
        ),
        TechnologyComponentProfile(
            name="mod_proxy / mod_proxy_http",
            description="Forward and reverse proxy capabilities. SSRF, internal network scanning, open proxy abuse.",
            security_relevance="high",
            common_vulnerabilities=["SSRF via ProxyPass/ProxyPassReverse", "Open proxy configuration", "Internal network scanning", "HTTP CONNECT tunneling abuse"],
            investigation_priority=95,
            tags=["proxy", "ssrf", "reverse-proxy", "forward-proxy"],
        ),
        TechnologyComponentProfile(
            name="CGI-BIN",
            description="Legacy CGI script execution directory. Remote code execution via vulnerable scripts, shell injection, source code disclosure.",
            security_relevance="high",
            common_vulnerabilities=["Shell injection in CGI scripts", "Source code disclosure via .pl/.cgi files", "Arbitrary command execution", "Directory listing of /cgi-bin/"],
            investigation_priority=90,
            tags=["cgi", "rce", "legacy", "execution"],
        ),
        TechnologyComponentProfile(
            name="mod_userdir",
            description="User directory mapping (~user) allowing access to user home directories. Sensitive file disclosure, directory traversal.",
            security_relevance="medium",
            common_vulnerabilities=["User enumeration via ~username paths", "Sensitive file disclosure from home directories", "Directory traversal via ~user/public_html"],
            investigation_priority=75,
            tags=["userdir", "user-enumeration", "disclosure"],
        ),
        TechnologyComponentProfile(
            name="mod_autoindex",
            description="Automatic directory index generation when no index file exists. Directory listing of all served directories.",
            security_relevance="high",
            common_vulnerabilities=["Directory listing on /, /uploads/, /backup/, /logs/", "Recursive directory listing", "Index file name disclosure (index.html, default.htm)"],
            investigation_priority=85,
            tags=["autoindex", "directory-listing", "enumerations"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Server Status",
                description="Apache mod_status page showing real-time server health and connection info",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/server-status",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Server Info",
                description="Apache mod_info page exposing full server configuration and loaded modules",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/server-info",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="CGI-BIN Directory",
                description="Legacy CGI script execution directory",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/cgi-bin/{script}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.RCE.value, BugClass.INFO_DISCLOSURE.value, BugClass.COMMAND_INJECTION.value],
            ),
            AttackSurfaceEntry(
                name="Proxy Endpoint",
                description="Apache mod_proxy endpoint for forwarding requests",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/proxy/{target}",
                parameters=["url"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.SSRF.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="User Directories",
                description="User home directory access via ~username paths",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/~{username}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.PATH_TRAVERSAL.value, BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/server-status", "/server-info", "/cgi-bin/", "/cgi-bin/test.cgi", "/icons/", "/manual/", "/~", "/icons/README", "/icons/apache_pb.png", "/icons/apache_pb.gif"],
        parameters=["url", "q", "page", "path", "file", "redirect", "next", "target"],
        authentication=["Basic auth (mod_auth_basic)", "Digest auth (mod_auth_digest)", "LDAP auth (mod_authnz_ldap)", "Form auth (mod_auth_form)", "Client certificate TLS auth", ".htpasswd / .htdigest files"],
        authorization=["mod_authz_core (Require directive)", "mod_authz_host (Allow/Deny)", "mod_authz_user", "mod_authz_groupfile", "mod_authz_owner", "mod_authz_dbd"],
        storage=["Local filesystem", "NFS", "S3 (via mod_proxy)", "WebDAV (mod_dav)"],
        background_jobs=["Log rotation (rotatelogs)", "SSL certificate reload", "Graceful restart"],
        queues=[],
        caches=["mod_cache", "mod_cache_disk", "mod_cache_socache"],
        admin_interfaces=["/server-status", "/server-info", "/manager/", "/manager/html/", "/admin/"],
        internal_apis=["/server-status?auto", "/server-info?summary", "/api/v1/", "/internal/"],
        external_apis=[],
        trust_boundaries=[
            TrustBoundary(name="Client-to-Apache", description="Incoming HTTP/HTTPS request from external client", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="Apache-to-Backend", description="Proxy pass to backend application servers", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Apache-to-Filesystem", description="File access for static content and CGI scripts", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Server-status page exposing connection pool and request details",
            "Server-info page revealing full configuration and module versions",
            "Directory listing via autoindex on sensitive directories",
            "Path traversal via mod_rewrite and mod_alias misconfiguration",
            ".htaccess bypass due to AllowOverride misconfiguration",
            "CGI script execution and shell injection via /cgi-bin/",
            "SSRF via mod_proxy and ProxyPass directives",
            "Server tokens revealing exact Apache version",
            "User enumeration via mod_userdir (~username) paths",
            "Open redirect via mod_rewrite backreferences",
            "HTTP request smuggling (CL.TE, TE.CL, TE.TE)",
            "Source code disclosure via .phps/.bak/.old files",
        ],
        investigation_areas=[
            "Check for /server-status and /server-info endpoints",
            "Verify server tokens are set to ProdOnly or minimal",
            "Check for directory listing on /, /cgi-bin/, /icons/, /backup/",
            "Inspect .htaccess files for sensitive configuration",
            "Test CGI-BIN scripts for command injection and path traversal",
            "Test ProxyPass for SSRF to internal networks",
            "Check for /~user paths for user enumeration",
            "Verify AllowOverride directives and .htaccess effectiveness",
            "Test mod_rewrite for open redirect patterns",
            "Check for HTTP methods (TRACE, PUT, DELETE, CONNECT)",
            "Test for request smuggling using various TE/CBL patterns",
            "Check for backup file disclosure (.bak, .old, ~ files)",
        ],
        tags=["apache", "webserver", "httpd", "modular"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "Apache",
            "Set-Cookie": "Apache=",
            "X-Powered-By": "PHP|ASP\\.NET",
        },
        cookies=[],
        js_indicators=[],
        file_indicators=[".htaccess", ".htpasswd", ".htdigest", "httpd.conf", "apache2.conf", "ports.conf", "sites-available/", "sites-enabled/", "mods-enabled/", "mods-available/"],
        directory_indicators=["/etc/apache2/", "/etc/httpd/", "/var/www/html/", "/var/www/cgi-bin/", "/usr/local/apache2/", "/usr/local/apache/htdocs/"],
        server_signatures=["Apache", "Apache/", "Apache-Coyote/"],
        error_page_signatures=["Apache", "Apache/", "Not Found", "The requested URL was not found on this server", "Additionally, a 404 Not Found error was encountered"],
        default_paths=["/", "/index.html", "/cgi-bin/", "/icons/", "/manual/", "/server-status", "/server-info"],
        default_files=[".htaccess", ".htpasswd", "index.html", "index.htm", "index.php", "httpd.conf", "apache2.conf", "access.log", "error.log", "php.ini"],
        metadata_patterns={"server": "Apache|Apache-Coyote", "x-powered-by": "PHP|ASP\\.NET|Apache"},
        tags=["fingerprint", "apache", "webserver"],
    ),
    recon=ReconProfile(
        directories_to_check=["/server-status", "/server-info", "/cgi-bin/", "/cgi-bin/test.cgi", "/icons/", "/icons/README", "/manual/", "/icons/apache_pb.png", "/icons/apache_pb.gif", "/phpmyadmin/", "/backup/", "/logs/"],
        files_to_check=[".htaccess", ".htpasswd", ".htdigest", "httpd.conf", "apache2.conf", "access.log", "error.log", "index.html", "index.php", "phpinfo.php", "info.php", "test.php"],
        endpoints_to_scan=["/", "/server-status", "/server-info", "/cgi-bin/", "/icons/", "/manual/", "/~", "/proxy/", "/api/"],
        version_detection_paths=["/", "/icons/apache_pb.png", "/icons/apache_pb.gif", "/icons/README", "/manual/"],
        debug_paths_to_check=["/server-status", "/server-info", "/debug", "/__debug__", "/cgi-bin/"],
        admin_paths_to_check=["/server-status", "/server-info", "/manager/", "/manager/html/", "/admin/", "/phpmyadmin/", "/adminer/"],
        tags=["recon", "apache", "webserver"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Server-status endpoint leaks internal server metrics including connection pool, request rate, and worker process details",
            impact="Reconnaissance amplification, DoS planning, connection stealing",
            attack_scenario="Access /server-status (or /server-status?auto for machine-readable format)",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Server-info endpoint exposes full Apache configuration, all loaded modules, and their settings",
            impact="Complete server fingerprinting, vulnerability targeting based on module versions, directory path leaks",
            attack_scenario="Access /server-info to view all configured directives and module versions",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="CGI-BIN directory allows execution of arbitrary CGI scripts, often including legacy or vulnerable scripts",
            impact="Remote code execution, command injection, sensitive file read",
            attack_scenario="Identify CGI scripts in /cgi-bin/ and test for shell injection and path traversal",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description=".htaccess bypass via AllowOverride misconfiguration or exposed .htaccess file reveals authentication credentials and access rules",
            impact="Authentication bypass, sensitive area access, password hash disclosure",
            attack_scenario="Access .htaccess directly via path disclosure or directory listing; modify AllowOverride to bypass restrictions",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Open proxy configuration via mod_proxy allows external attackers to route traffic through the server",
            impact="IP address spoofing, internal network scanning, anonymity abuse, SSRF",
            attack_scenario="Use CONNECT method or absolute URI requests to proxy traffic through Apache",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="nginx",
            relationship_type=KnowledgeRelationshipType.SIMILAR_TO,
            description="Apache and Nginx are both HTTP servers with different architectures",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Apache is commonly deployed as a Docker container",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="kubernetes",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Apache can run as a Kubernetes deployment with Ingress controller",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="tomcat",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Apache integrates with Tomcat via mod_jk and mod_proxy_ajp",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="django",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Apache proxies Django via mod_wsgi",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="php",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Apache typically runs PHP via mod_php or PHP-FPM",
            confidence="high",
        ),
    ],
    dependencies=["Linux/Unix/Windows", "APR", "PCRE", "OpenSSL"],
    related_packs=["nginx", "docker", "kubernetes", "tomcat", "php"],
    workflow=[
        "1. Fingerprint Apache via Server header and default paths (/icons/, /manual/)",
        "2. Check /server-status and /server-info for information disclosure",
        "3. Enumerate /cgi-bin/ for executable CGI scripts",
        "4. Check for directory listing on /, /icons/, /backup/, /logs/",
        "5. Test .htaccess files for auth bypass and sensitive configuration",
        "6. Verify ServerTokens directive (ProdOnly vs Full)",
        "7. Test mod_rewrite for open redirects via $1 backreferences",
        "8. Check for open proxy by requesting absolute URIs",
        "9. Test for HTTP request smuggling (CL.TE, TE.CL)",
        "10. Enumerate user directories via ~username paths",
        "11. Check for backup and source files (.bak, .old, .phps, ~)",
        "12. Verify HTTP method restrictions (TRACE, PUT, DELETE)",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="APACHE-01",
            category="Information Disclosure",
            description="Check /server-status for server health and connection information",
            expected_result="/server-status should return 403, 404, or require authentication",
            tools=["curl", "Burp Suite"],
            references=["https://httpd.apache.org/docs/2.4/mod/mod_status.html"],
        ),
        ManualTestChecklistItem(
            step_id="APACHE-02",
            category="Information Disclosure",
            description="Check /server-info for full configuration and module disclosure",
            expected_result="/server-info should not be accessible without proper access control",
            tools=["curl", "Burp Suite"],
            references=["https://httpd.apache.org/docs/2.4/mod/mod_info.html"],
        ),
        ManualTestChecklistItem(
            step_id="APACHE-03",
            category="CGI Execution",
            description="Enumerate /cgi-bin/ for available CGI scripts and test for RCE",
            expected_result="CGI scripts should not be present or should be properly secured against injection",
            tools=["curl", "gobuster", "ffuf"],
            references=["https://httpd.apache.org/docs/2.4/howto/cgi.html"],
        ),
        ManualTestChecklistItem(
            step_id="APACHE-04",
            category="Directory Listing",
            description="Test for directory listing on common directories without index files",
            expected_result="Directories should return 403 or 404, not list contents with autoindex",
            tools=["curl", "gobuster"],
            references=["https://httpd.apache.org/docs/2.4/mod/mod_autoindex.html"],
        ),
        ManualTestChecklistItem(
            step_id="APACHE-05",
            category="Server Tokens",
            description="Check Server header for version information disclosure",
            expected_result="Server header should not reveal minor version or OS details",
            tools=["curl"],
            references=["https://httpd.apache.org/docs/2.4/mod/core.html#servertokens"],
        ),
        ManualTestChecklistItem(
            step_id="APACHE-06",
            category="Proxy Security",
            description="Test for open proxy configuration using CONNECT and absolute URI requests",
            expected_result="Apache should not allow unrestricted proxy forwarding",
            tools=["curl", "Burp Suite"],
            references=["https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#access"],
        ),
    ],
    references=[
        {"title": "Apache HTTP Server Documentation", "url": "https://httpd.apache.org/docs/"},
        {"title": "Apache Security Tips", "url": "https://httpd.apache.org/docs/2.4/misc/security_tips.html"},
        {"title": "OWASP Apache Hardening", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Apache_Hardening_Cheat_Sheet.html"},
        {"title": "CVE Apache Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Apache+HTTP+Server"},
        {"title": "Apache Module Reference", "url": "https://httpd.apache.org/docs/2.4/mod/"},
    ],
    cwe_ids=["CWE-200", "CWE-548", "CWE-22", "CWE-918", "CWE-16", "CWE-601", "CWE-77", "CWE-444"],
    cve_ids=["CVE-2024-40890", "CVE-2024-36387", "CVE-2023-44487", "CVE-2022-26377", "CVE-2021-44790", "CVE-2021-42013", "CVE-2021-41773", "CVE-2020-1927"],
    tags=["apache", "webserver", "httpd", "c", "modular", "virtual-hosts"],
)
