"""Docker knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="docker",
    version="1.0.0",
    category=KnowledgePackCategory.CONTAINER,
    description="Docker container runtime — Docker API exposure (unauthenticated TCP socket), privileged containers, host filesystem mounts, registry secrets and credential storage, container escape, image vulnerability exploitation, Dockerfile and .env leakage, Docker Compose misconfiguration, overlay2 filesystem access.",
    technology=TechnologyProfile(
        name="Docker",
        vendor="Docker Inc.",
        language="Go",
        runtime="Docker Engine (containerd + runc)",
        description="Docker is the leading container runtime and platform for developing, shipping, and running applications. Packages applications into portable images and runs them in isolated containers using Linux kernel namespaces and cgroups.",
        common_aliases=["docker", "docker-engine", "docker-ce", "docker-ee", "moby", "containerd"],
        dependencies=["Linux (kernel 3.10+)", "containerd", "runc", "overlay2/btrfs/devicemapper", "iptables"],
        common_integrations=["Docker Compose", "Docker Swarm", "Docker Hub", "Docker Registry (ECR, GCR, ACR, Harbor)", "Docker Desktop", "Portainer", "Watchtower", "Trivy", "Docker Bench Security", "Notary"],
        architecture_description="Client-server architecture with Docker CLI communicating with dockerd daemon via REST API. Uses containerd for container lifecycle and runc for OCI runtime execution. Images are built from Dockerfiles and stored in registries.",
        request_lifecycle="docker CLI -> Docker API (/var/run/docker.sock or TCP) -> dockerd -> containerd -> runc -> container (namespaces + cgroups)",
        documentation_url="https://docs.docker.com/",
        tags=["containers", "runtime", "docker", "devops", "go"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Docker Daemon (dockerd)",
            description="Background daemon managing containers, images, networks, and volumes via REST API. Unprotected socket grants full root access to host.",
            security_relevance="high",
            common_vulnerabilities=["Docker API exposed on TCP (2375/2376) without TLS", "Docker socket (/var/run/docker.sock) mounted in containers", "Unauthenticated Docker API allows container creation", "Privilege escalation via Docker API access to host root"],
            investigation_priority=95,
            tags=["daemon", "api", "socket", "rce"],
        ),
        TechnologyComponentProfile(
            name="Docker Socket (/var/run/docker.sock)",
            description="Unix socket for Docker API communication. Access to this socket grants effective root access to the host system.",
            security_relevance="high",
            common_vulnerabilities=["Docker socket mounted into container", "Container breakout via socket access", "Host filesystem manipulation via socket", "Privileged container creation from within container"],
            investigation_priority=95,
            tags=["socket", "docker-sock", "container-escape"],
        ),
        TechnologyComponentProfile(
            name="Docker Registry / Image Storage",
            description="Container image storage (Docker Hub, private registries). Exposure of registry credentials, pulling malicious images, image layer analysis.",
            security_relevance="high",
            common_vulnerabilities=["Registry credentials stored in plaintext", "Pulling images from untrusted registries", "Image layer contains secrets (ARGS, ENV, ADD)", "Registry with no authentication"],
            investigation_priority=85,
            tags=["registry", "images", "credentials", "supply-chain"],
        ),
        TechnologyComponentProfile(
            name="Privileged Containers",
            description="Containers run with --privileged flag granting all Linux capabilities and host device access. Complete container escape vector.",
            security_relevance="high",
            common_vulnerabilities=["Privileged container escape to host", "Host device access (/dev/sda, /dev/kmsg)", "Sysfs access for kernel parameter modification", "Seccomp/AppArmor disabled with --privileged"],
            investigation_priority=95,
            tags=["privileged", "escape", "capabilities", "rce"],
        ),
        TechnologyComponentProfile(
            name="Host Mounts (Bind Mounts)",
            description="Host filesystem directories mounted into containers via -v or --mount. If sensitive directories are mounted, container can read/write host files.",
            security_relevance="high",
            common_vulnerabilities=["Host /etc/shadow or /etc/ssh mounted into container", "Host /var/run/docker.sock mounted into container", "Host /proc mounted giving access to process info", "Host root filesystem (/ or /host) mounted with write access"],
            investigation_priority=95,
            tags=["mounts", "host-path", "volumes", "escape"],
        ),
        TechnologyComponentProfile(
            name="Docker Compose",
            description="Multi-container application definition via docker-compose.yml. Exposed ports, default credentials, network exposure, sensitive environment variables.",
            security_relevance="high",
            common_vulnerabilities=["Environment variables with secrets in docker-compose.yml", "Default credentials in compose configuration", "Excessive port exposure (port mapping)", "Unrestricted container networks"],
            investigation_priority=80,
            tags=["compose", "docker-compose", "env", "configuration"],
        ),
        TechnologyComponentProfile(
            name="Dockerfile / Build Context",
            description="Image build instructions and context. Secrets in build layers, multi-stage build issues, ADD with remote URLs, base image vulnerabilities.",
            security_relevance="high",
            common_vulnerabilities=["Secrets in ENV/ARG/RUN commands that persist in layers", "Base image with known vulnerabilities (CVE)", "RUN pip/npm install without version pinning", "ADD from remote URLs without checksum verification"],
            investigation_priority=85,
            tags=["dockerfile", "build", "layers", "supply-chain"],
        ),
        TechnologyComponentProfile(
            name="Docker Networking",
            description="Container networking including bridge, host, overlay, and macvlan modes. Exposed ports, network isolation bypass, DNS rebinding.",
            security_relevance="medium",
            common_vulnerabilities=["Exposed ports on 0.0.0.0 access from any network", "Host network mode bypassing network isolation", "Overlay network eavesdropping", "DNS rebinding attacks via exposed ports"],
            investigation_priority=75,
            tags=["networking", "ports", "dns", "exposure"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Docker REST API (TCP)",
                description="Docker daemon REST API on TCP port 2375 (HTTP) or 2376 (HTTPS)",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/{api_version}/{resource}",
                parameters=["fromImage", "cmd", "Entrypoint", "Binds", "Privileged"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.RCE.value, BugClass.PRIVILEGE_ESCALATION.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Docker Socket (/var/run/docker.sock)",
                description="Docker Unix socket providing full daemon API access when mounted into containers",
                protocol="UNIX/HTTP",
                method="ANY",
                path="http://localhost/{resource}",
                parameters=["fromImage", "cmd", "Binds", "Privileged"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.RCE.value, BugClass.PRIVILEGE_ESCALATION.value, BugClass.PRIVILEGE_ESCALATION.value],
            ),
            AttackSurfaceEntry(
                name="Docker Registry",
                description="Container image registry (Docker Hub, ECR, GCR, ACR, Harbor)",
                protocol="HTTPS/HTTP",
                method="ANY",
                path="/v2/{repository}/manifests/{tag}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.BUSINESS_LOGIC.value],
            ),
            AttackSurfaceEntry(
                name="Privileged Container",
                description="Container running with --privileged flag",
                protocol="Container",
                method="EXEC",
                path="/proc/1/root",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.RCE.value, BugClass.PRIVILEGE_ESCALATION.value],
            ),
            AttackSurfaceEntry(
                name="Exposed Ports",
                description="Container ports published to the host network interface",
                protocol="HTTP/TCP",
                method="ANY",
                path="tcp://{host}:{containerPort}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
        ],
        endpoints=["http://{host}:2375/", "http://{host}:2375/version", "http://{host}:2375/info", "http://{host}:2375/containers/json", "http://{host}:2375/images/json", "http://{host}:2375/containers/{id}/exec"],
        parameters=["fromImage", "repo", "tag", "cmd", "Entrypoint", "Env", "Binds", "PortBindings", "Privileged", "CapAdd", "SecurityOpt", "VolumesFrom"],
        authentication=["Docker API with TLS client certs", "Docker Hub credentials (docker login)", "AWS ECR authorization token", "GCR/GAR access token", "Azure ACR admin credentials"],
        authorization=["Docker RBAC (Enterprise/UCP)", "Registry auth scopes", "TLS client certificate CN validation", "SSH access to Docker host"],
        storage=["Overlay2 filesystem", "Bind mounts", "Volumes (local and plugins)", "Tmpfs mounts", "Image layers (Docker Hub, private registry)"],
        background_jobs=["Container auto-restart (restart policies)", "Health checks", "Log tailing and rotation", "Docker swarm task scheduling", "Image GC and pruning"],
        queues=["Container logs queue", "Docker events stream", "Health check results"],
        caches=["Docker build cache", "Docker layer cache", "Registry pull-through cache"],
        admin_interfaces=["Portainer", "Docker Desktop UI", "Rancher", "Lazydocker", "Docker Swarm visualizer", "http://{host}:2375/"],
        internal_apis=["http://localhost:2375/", "http://{host}:2375/", "http://{host}:2376/", "unix:///var/run/docker.sock"],
        external_apis=["Docker Hub API", "AWS ECR API", "GCR API", "Azure ACR API", "Harbor API", "Quay API"],
        trust_boundaries=[
            TrustBoundary(name="CLI-to-Daemon", description="Docker client communicates with dockerd via REST API", direction="inbound", sensitivity="high"),
            TrustBoundary(name="Daemon-to-Kernel", description="Docker daemon makes kernel syscalls for namespace/cgroup creation", direction="outbound", sensitivity="critical"),
            TrustBoundary(name="Container-to-Host", description="Container processes interact with host kernel (namespaced)", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Daemon-to-Registry", description="Docker daemon pulls/pushes images from/to registry", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Docker API exposed on TCP without TLS (port 2375/2376)",
            "Docker socket mounted into container enabling escape",
            "Privileged containers with --privileged flag",
            "Host filesystem mounts exposing sensitive host directories",
            "Registry credentials stored in plaintext (config.json, ~/.docker/config.json)",
            "Image layers containing secrets (ARGS, ENV, history)",
            "Exposed container ports on 0.0.0.0 bypassing firewall",
            "Docker Compose with default credentials and secrets in env vars",
            "Old Docker versions with runc/CVE vulnerabilities",
            "Shared namespaces (--pid=host, --network=host, --ipc=host)",
            "Capabilities beyond minimum required (NET_ADMIN, SYS_ADMIN, etc.)",
            "Unrestricted container resource limits (CPU, memory, disk)",
        ],
        investigation_areas=[
            "Check for Docker API on TCP port 2375/2376 from external network",
            "Check if /var/run/docker.sock is mounted in any container",
            "List containers and check for --privileged flag",
            "Check for hostPath mounts exposing /, /etc, /root, /home",
            "Search for Docker credentials in ~/.docker/config.json",
            "Inspect image history and layers for embedded secrets",
            "Check for containers with --cap-add=ALL or CAP_SYS_ADMIN",
            "List exposed ports on host (docker ps / ss -tlnp)",
            "Check Compose files for default creds and exposed env vars",
            "Check Docker version for known CVEs",
            "Test container escape using common techniques (cgroups, /proc, nsenter)",
            "Check for shared namespaces (--pid=host, --network=host)",
        ],
        tags=["docker", "containers", "runtime", "devops"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "Docker/",
            "Api-Version": "",
            "Docker-Experimental": "",
        },
        cookies=[],
        js_indicators=[],
        file_indicators=["Dockerfile", "docker-compose.yml", "docker-compose.yaml", ".dockerignore", "Dockerfile.*", "Dockerfile.prod", "Dockerfile.dev", ".env", "docker-compose.override.yml", "Dockerfile.build"],
        directory_indicators=["/var/lib/docker/", "/var/lib/docker/containers/", "/var/lib/docker/overlay2/", "/var/lib/docker/image/", "/var/lib/docker/volumes/", "/var/run/docker.sock", "/var/run/docker/", "/etc/docker/", "/home/"],
        server_signatures=["Docker/", "Docker-", "docker"],
        error_page_signatures=["docker", "Docker", "Error response from daemon", "404 page not found", "Docker API"],
        default_paths=["/version", "/info", "/containers/json", "/images/json", "/_ping", "/v1.24/", "/v1.25/", "/v1.26/", "/v1.27/"],
        default_files=["Dockerfile", "docker-compose.yml", "docker-compose.yaml", ".dockerignore", ".env", "Dockerfile.prod", "Dockerfile.dev", "docker-entrypoint.sh", "entrypoint.sh"],
        metadata_patterns={"server": "Docker|docker", "api-version": "\\d\\.\\d+", "docker": ""},
        tags=["fingerprint", "docker", "containers"],
    ),
    recon=ReconProfile(
        directories_to_check=["/var/lib/docker/", "/var/run/docker/", "/etc/docker/", "/home/", "/root/", "/backup/", "/docker/"],
        files_to_check=["Dockerfile", "docker-compose.yml", "docker-compose.yaml", ".dockerignore", ".env", ".env.prod", ".env.dev", "config.json", "~/.docker/config.json", "/root/.docker/config.json", "credentials.json"],
        endpoints_to_scan=["http://{host}:2375/", "http://{host}:2375/version", "http://{host}:2375/info", "http://{host}:2376/"],
        port_scan_targets=[2375, 2376, 2377, 2378, 4243, 5555],
        version_detection_paths=["/version", "/info", "/_ping"],
        debug_paths_to_check=["/debug/", "/debug/pprof/", "/info", "/version"],
        admin_paths_to_check=["http://{host}:2375/", "http://{host}:9000/", "http://{host}:9001/"],
        tags=["recon", "docker", "containers"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Docker API exposed on TCP port 2375 without TLS allows anyone with network access to create privileged containers and get root on the host",
            impact="Complete host compromise — root access on the Docker host, access to all containers, data, and secrets",
            attack_scenario="Use docker -H tcp://target:2375 run -v /:/host --privileged -it alpine chroot /host to get a shell on the host filesystem as root",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Mounting /var/run/docker.sock into a container gives the container effective root access to the host Docker daemon",
            impact="Container escape to host root — attacker inside container can create and control any container including privileged ones",
            attack_scenario="From inside container: curl -s --unix-socket /var/run/docker.sock http://localhost/containers/json to list containers; then create a privileged host-mount container",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Privileged containers (--privileged) have all capabilities, no seccomp/apparmor, and access to all host devices — trivial container escape",
            impact="Complete container escape to host root — full control over host system, kernel, and all other containers",
            attack_scenario="From privileged container: mount /dev/sda /mnt && chroot /mnt to access host filesystem; or use nsenter to escape container namespace",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="HostPath volume mounts (e.g., -v /:/host) give container read/write access to the host filesystem",
            impact="Direct access to host filesystem — read all secrets, modify host configuration, install SSH keys, persist access",
            attack_scenario="Container can read /host/etc/shadow, modify /host/root/.ssh/authorized_keys, install cron jobs on host",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Docker registry credentials stored in ~/.docker/config.json in base64 revealed through image inspection, file disclosure, or exposed volumes",
            impact="Registry credential theft enables pulling/pushing images, supply chain attacks, access to private images with potential secrets",
            attack_scenario="Read ~/.docker/config.json from exposed volume or image layer; decode base64 credentials; use to push malicious images to private registry",
            complexity="medium",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="kubernetes",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Docker is commonly used as the container runtime for Kubernetes (via containerd)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="nginx",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Nginx is commonly deployed as a Docker container",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Redis is commonly deployed as a Docker container",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="rabbitmq",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="RabbitMQ is commonly deployed as a Docker container",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="django",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Django applications are containerized with Docker",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="express",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Express/Node.js applications are containerized with Docker",
            confidence="high",
        ),
    ],
    dependencies=["Linux kernel 3.10+", "containerd", "runc", "overlay2", "iptables"],
    related_packs=["kubernetes", "nginx", "redis", "rabbitmq", "django", "express"],
    workflow=[
        "1. Scan for Docker API on TCP port 2375/2376",
        "2. If API accessible, list containers, images, volumes via API",
        "3. Create a privileged host-mounted container to get host root access",
        "4. Check if /var/run/docker.sock is mounted in any container",
        "5. Check for --privileged containers: docker ps and inspect containers",
        "6. Check for hostPath mounts that expose sensitive directories",
        "7. Search for Docker credentials in ~/.docker/config.json files",
        "8. Inspect image history for secrets in build layers (docker history)",
        "9. Test container escape from non-privileged container (capabilities, cgroups)",
        "10. Check Docker Compose files for default creds and exposed ports",
        "11. Check Docker version for known CVEs (runc, containerd, Docker)",
        "12. Review exposed container ports and network configurations",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="DOCKER-01",
            category="API Exposure",
            description="Check if Docker API is exposed on TCP without TLS authentication",
            expected_result="Docker API should only be available via Unix socket or TLS-protected TCP",
            tools=["curl", "docker -H", "nmap"],
            references=["https://docs.docker.com/engine/security/protect-access/"],
        ),
        ManualTestChecklistItem(
            step_id="DOCKER-02",
            category="Container Escape",
            description="Check if any container has /var/run/docker.sock mounted",
            expected_result="Docker socket should never be mounted inside a container",
            tools=["docker inspect", "kubectl exec"],
            references=["https://docs.docker.com/engine/security/security/#docker-socket"],
        ),
        ManualTestChecklistItem(
            step_id="DOCKER-03",
            category="Privileged Containers",
            description="Check for containers running with --privileged flag",
            expected_result="Containers should not run with elevated privileges unless absolutely necessary",
            tools=["docker ps", "docker inspect", "kubectl"],
            references=["https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities"],
        ),
        ManualTestChecklistItem(
            step_id="DOCKER-04",
            category="Host Mounts",
            description="Check for hostPath volumes exposing sensitive host directories",
            expected_result="Only necessary host directories should be mounted, read-only if possible",
            tools=["docker inspect", "kubectl describe pod"],
            references=["https://docs.docker.com/storage/bind-mounts/"],
        ),
        ManualTestChecklistItem(
            step_id="DOCKER-05",
            category="Credential Exposure",
            description="Search for Docker registry credentials in config files and image layers",
            expected_result="Registry credentials should be stored securely, not in base64 in config files or image layers",
            tools=["grep", "docker history", "docker inspect"],
            references=["https://docs.docker.com/engine/reference/commandline/login/"],
        ),
        ManualTestChecklistItem(
            step_id="DOCKER-06",
            category="Image Vulnerabilities",
            description="Scan Docker images for known vulnerabilities and embedded secrets",
            expected_result="Images should be scanned and free of high/critical vulnerabilities",
            tools=["trivy", "grype", "docker scan", "snyk"],
            references=["https://docs.docker.com/engine/scan/"],
        ),
    ],
    references=[
        {"title": "Docker Security", "url": "https://docs.docker.com/engine/security/"},
        {"title": "Docker Bench Security", "url": "https://github.com/docker/docker-bench-security"},
        {"title": "OWASP Docker Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html"},
        {"title": "CVE Docker Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Docker"},
        {"title": "Container Escape Techniques", "url": "https://book.hacktricks.xyz/linux-hardening/privilege-escalation/docker-escaping"},
    ],
    cwe_ids=["CWE-306", "CWE-250", "CWE-276", "CWE-200", "CWE-668", "CWE-522", "CWE-269", "CWE-862"],
    cve_ids=["CVE-2024-21626", "CVE-2024-0053", "CVE-2023-51699", "CVE-2023-25173", "CVE-2022-24769", "CVE-2021-41092", "CVE-2020-15257", "CVE-2019-16884", "CVE-2019-5736"],
    tags=["docker", "containers", "runtime", "devops", "go"],
)
