"""Kubernetes knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="kubernetes",
    version="1.0.0",
    category=KnowledgePackCategory.KUBERNETES,
    description="Kubernetes container orchestration — kubelet API exposure, etcd access without auth, dashboard exposure, RBAC misconfiguration, service account token leakage, API server anonymous access, pod breakout, container escape, secrets enumeration.",
    technology=TechnologyProfile(
        name="Kubernetes",
        vendor="Cloud Native Computing Foundation (CNCF)",
        language="Go",
        runtime="Kubernetes (containerd/Docker/CRI-O)",
        description="Kubernetes is an open-source container orchestration platform for automating deployment, scaling, and management of containerized applications. Features service discovery, load balancing, storage orchestration, automated rollouts/rollbacks, and secret management.",
        common_aliases=["kubernetes", "k8s", "kube", "kubectl"],
        dependencies=["Linux", "containerd (or other CRI)", "etcd", "CNI plugin (Calico, Flannel, Cilium)", "CoreDNS"],
        common_integrations=["etcd", "CoreDNS", "kubelet", "kube-proxy", "kube-controller-manager", "kube-scheduler", "kube-apiserver", "Calico", "Istio", "Linkerd", "Prometheus", "Grafana", "Helm"],
        architecture_description="Control plane (API server, etcd, scheduler, controller-manager) and worker nodes (kubelet, kube-proxy, container runtime). Pods are the smallest deployable units, scheduled onto nodes by the scheduler.",
        request_lifecycle="kubectl/API client -> API server (authn/authz/admission) -> etcd (persist) -> scheduler (assign node) -> kubelet (run pod) -> container runtime (start containers)",
        documentation_url="https://kubernetes.io/docs/",
        tags=["orchestration", "containers", "cloud-native", "go", "cncf"],
    ),
    components=[
        TechnologyComponentProfile(
            name="kube-apiserver",
            description="Kubernetes API server — central control plane component exposing REST API. Anonymous access, auth bypass, privilege escalation.",
            security_relevance="high",
            common_vulnerabilities=["Anonymous access enabled", "Unauthenticated API access", "Privilege escalation via RBAC misconfiguration", "API version downgrade attacks"],
            investigation_priority=95,
            tags=["api-server", "control-plane", "api", "auth"],
        ),
        TechnologyComponentProfile(
            name="kubelet API",
            description="Node-level agent exposing an HTTP API on port 10250/10255. Unauthenticated access, pod exec, container logs, pod listing.",
            security_relevance="high",
            common_vulnerabilities=["Unauthenticated kubelet API (port 10250)", "Read-only kubelet API (port 10255) information leak", "Remote command execution via /exec endpoint", "Pod and container enumeration"],
            investigation_priority=95,
            tags=["kubelet", "node", "exec", "rce"],
        ),
        TechnologyComponentProfile(
            name="etcd",
            description="Distributed key-value store for all cluster data. Unauthenticated access exposes full cluster state including secrets, config, and RBAC policies.",
            security_relevance="high",
            common_vulnerabilities=["etcd without TLS/authentication", "Full cluster state exposure", "Secret extraction from etcd", "Service account token theft"],
            investigation_priority=95,
            tags=["etcd", "datastore", "secrets", "control-plane"],
        ),
        TechnologyComponentProfile(
            name="Kubernetes Dashboard",
            description="Web UI for cluster management. Exposed dashboard allows full cluster control, pod creation, exec access, and privilege escalation.",
            security_relevance="high",
            common_vulnerabilities=["Dashboard exposed without auth", "Default dashboard skip login", "Privilege escalation via dashboard RBAC", "Token-based auth bypass"],
            investigation_priority=90,
            tags=["dashboard", "web-ui", "management", "exposed"],
        ),
        TechnologyComponentProfile(
            name="RBAC (Role-Based Access Control)",
            description="Kubernetes authorization system controlling API access via Roles, ClusterRoles, RoleBindings, and ClusterRoleBindings.",
            security_relevance="high",
            common_vulnerabilities=["Overly permissive ClusterRoleBindings", "Service account with cluster-admin binding", "Privilege escalation via RBAC verbs (impersonate, escalate, bind)", "Wildcard access (*) on resources"],
            investigation_priority=95,
            tags=["rbac", "authorization", "iam", "permissions"],
        ),
        TechnologyComponentProfile(
            name="Service Accounts",
            description="Pod and namespace identities for API access. Automounted tokens, overprivileged service accounts, token leakage.",
            security_relevance="high",
            common_vulnerabilities=["Auto-mounted service account tokens in pods", "Overprivileged service account bindings", "Token leakage via pod logs or volume mounts", "Default service account with excessive permissions"],
            investigation_priority=90,
            tags=["service-account", "tokens", "identity", "mount"],
        ),
        TechnologyComponentProfile(
            name="Secrets & ConfigMaps",
            description="Kubernetes objects for storing configuration and sensitive data. Base64-only encoding (not encrypted), etcd access disclosure, RBAC bypass.",
            security_relevance="high",
            common_vulnerabilities=["Secrets stored as plain base64 in etcd", "ConfigMaps with sensitive data", "Secrets access via RBAC misconfiguration", "Secrets leaked in environment variables"],
            investigation_priority=90,
            tags=["secrets", "configmap", "encryption", "data"],
        ),
        TechnologyComponentProfile(
            name="Pod Security / Security Context",
            description="Pod and container security settings including privileged mode, hostPID, hostNetwork, hostPath volumes, and seccomp/apparmor.",
            security_relevance="high",
            common_vulnerabilities=["Privileged containers running as root", "HostPID and hostNetwork access for container escape", "HostPath volume mounts exposing node filesystem", "Container breakout via capabilities"],
            investigation_priority=90,
            tags=["pods", "security-context", "privileged", "escape"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Kubernetes API Server",
                description="Control plane REST API on port 6443/443",
                protocol="HTTPS",
                method="ANY",
                path="/api/{version}/{resource}",
                parameters=["namespace", "labelSelector", "fieldSelector", "watch"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value, BugClass.PRIVILEGE_ESCALATION.value],
            ),
            AttackSurfaceEntry(
                name="kubelet API",
                description="Node-level kubelet API on port 10250 (auth) or 10255 (read-only)",
                protocol="HTTPS/HTTP",
                method="ANY",
                path="/{operation}",
                parameters=["namespace", "pod", "container", "command"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.RCE.value, BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="etcd",
                description="Cluster data store on port 2379/2380",
                protocol="gRPC/HTTP",
                method="ANY",
                path="/v3/{operation}",
                parameters=["key", "range_end"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Kubernetes Dashboard",
                description="Web UI for cluster management on port 30000+ or via kubectl proxy",
                protocol="HTTPS/HTTP",
                method="ANY",
                path="/{resource}",
                parameters=["namespace"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.PRIVILEGE_ESCALATION.value],
            ),
            AttackSurfaceEntry(
                name="Kubeconfig / Service Account Tokens",
                description="Kubeconfig files and service account tokens granting API access",
                protocol="HTTPS",
                method="ANY",
                path="/var/run/secrets/kubernetes.io/serviceaccount/token",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="NodePort Services",
                description="Exposed node ports (30000-32767) for external access to services",
                protocol="HTTP/TCP",
                method="ANY",
                path="tcp://{node}:{nodePort}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
        ],
        endpoints=["/api/", "/api/v1/", "/apis/", "/openapi/v2/", "/healthz", "/livez", "/readyz", "/metrics", "/version", "/api/v1/namespaces", "/api/v1/pods", "/api/v1/secrets", "/api/v1/configmaps"],
        parameters=["namespace", "labelSelector", "fieldSelector", "watch", "limit", "continue", "pretty", "dryRun"],
        authentication=["kubeconfig (client certificate)", "Service account token (JWT)", "OIDC provider", "Webhook token authentication", "Static token file", "Basic auth (deprecated)", "Anonymous access (disabled by default)"],
        authorization=["RBAC (Role/ClusterRole + RoleBinding/ClusterRoleBinding)", "ABAC (deprecated)", "Node authorization", "Webhook authorization", "AlwaysDeny / AlwaysAllow"],
        storage=["etcd", "PV/PVC (PersistentVolume/Claim)", "CSI drivers (EBS, EFS, GCE PD, Azure Disk, Cinder)", "HostPath volumes", "ConfigMaps", "Secrets"],
        background_jobs=["CronJobs", "Jobs", "Pod lifecycle (restart, backoff)", "Horizontal Pod Autoscaler", "Cluster Autoscaler", "Node problem detector"],
        queues=["Work queues via custom operators", "RabbitMQ/Kafka/Redis for async processing"],
        caches=["kube-apiserver cache", "kubelet status cache", "CoreDNS cache"],
        admin_interfaces=["Kubernetes Dashboard", "K9s", "Lens", "Octant", "kubectl", "OpenShift Console", "Rancher"],
        internal_apis=["/api/", "/apis/", "/openapi/v2/", "/healthz", "/livez", "/readyz", "/metrics", "/version", "/api/v1/namespaces/{ns}/pods/{pod}/exec", "/api/v1/namespaces/{ns}/pods/{pod}/log"],
        external_apis=["Cloud provider APIs (AWS/GCP/Azure)", "External DNS", "Cert-manager ACME API", "External secret stores (Vault, AWS Secrets Manager)"],
        trust_boundaries=[
            TrustBoundary(name="External-to-API", description="API requests from users or CI/CD systems to kube-apiserver", direction="inbound", sensitivity="high"),
            TrustBoundary(name="API-to-etcd", description="API server reads/writes cluster state to etcd", direction="outbound", sensitivity="critical"),
            TrustBoundary(name="API-to-kubelet", description="API server communicates with kubelets for pod management", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Pod-to-API", description="Service account tokens allow pods to call the API", direction="inbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "kubelet API exposed on 10250/10255 without authentication",
            "etcd accessible on 2379 without TLS/client cert authentication",
            "Kubernetes dashboard exposed to the internet without proper auth",
            "Anonymous access to API server allowing resource enumeration",
            "Overly permissive RBAC ClusterRoleBindings granting cluster-admin",
            "Service account tokens automatically mounted in pods",
            "Default service account with excessive RBAC permissions",
            "HostPath volume mounts exposing node filesystem from containers",
            "Privileged containers running with elevated capabilities",
            "Secret enumeration via API access (stored as base64 in etcd)",
            "Kubeconfig files and tokens in CI/CD, git repos, and exposed volumes",
            "NodePort services exposing internal applications externally",
        ],
        investigation_areas=[
            "Check for unauthenticated kubelet API on port 10250/10255",
            "Test etcd port 2379 for unauthenticated access",
            "Scan for Kubernetes dashboard on common NodePort ranges",
            "Check API server anonymous access by requesting /api/v1 without credentials",
            "Enumerate service accounts and their RBAC bindings",
            "Check for privileged containers and hostPath volume mounts",
            "Look for kubeconfig files and service account tokens in repos and containers",
            "Check Secret and ConfigMap access permissions",
            "Test for RBAC privilege escalation (impersonate, escalate, bind verbs)",
            "Check for automatic mount of service account tokens (automountServiceAccountToken)",
            "Test pod exec capabilities via kubelet API",
            "Check for PodSecurityPolicy (deprecated) or OPA/Gatekeeper policies",
        ],
        tags=["kubernetes", "k8s", "orchestration", "containers", "cloud-native"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "nginx",
            "Audit-Id": "",
            "Content-Type": "application/json",
            "X-Kubernetes-Pf-Flowschema-Uid": "",
            "X-Kubernetes-Pf-Prioritylevel-Uid": "",
        },
        cookies=[],
        js_indicators=[],
        file_indicators=["kubeconfig", "config", ".kube/config", "admin.conf", "kubelet.conf", "service-account.json", ".kube/", "kubectl", "helm"],
        directory_indicators=["/etc/kubernetes/", "/var/lib/kubelet/", "/etc/kubernetes/manifests/", "/etc/kubernetes/pki/", "/var/run/secrets/kubernetes.io/", "/var/lib/etcd/", "/home/"],
        server_signatures=["kube-apiserver", "kubelet", "etcd", "nginx-ingress"],
        error_page_signatures=["NotFound", "Forbidden", "Unauthorized", "etcdserver", "api server", "kubernetes", "kubelet", "pod", "namespace"],
        default_paths=["/api/", "/api/v1/", "/apis/", "/healthz", "/livez", "/readyz", "/version", "/openapi/v2/", "/metrics"],
        default_files=[".kube/config", "kubeconfig", "admin.conf", "kubelet.conf", "service-account.json", "kubectl", "helm", "Dockerfile", "manifests/"],
        metadata_patterns={"audit-id": "", "kubernetes": "", "etcd": ""},
        tags=["fingerprint", "kubernetes", "k8s", "orchestration"],
    ),
    recon=ReconProfile(
        directories_to_check=["/api/", "/api/v1/", "/apis/", "/healthz", "/livez", "/readyz", "/version", "/openapi/v2/", "/metrics"],
        files_to_check=[".kube/config", "kubeconfig", "admin.conf", "config", "kubelet.conf", "service-account.json", "kubectl", "manifests/", "deployment.yaml", "statefulset.yaml"],
        endpoints_to_scan=["https://{host}:6443/", "https://{host}:6443/api/", "http://{host}:10250/", "http://{host}:10255/", "http://{host}:2379/", "https://{host}:2379/"],
        port_scan_targets=[6443, 443, 10250, 10255, 2379, 2380, 30000, 30001, 30080, 30090, 443, 10256, 10249],
        version_detection_paths=["/version", "/api/", "/healthz"],
        debug_paths_to_check=["/debug/", "/debug/pprof/", "/metrics", "/healthz"],
        admin_paths_to_check=["/api/v1/namespaces/kube-system/", "/api/v1/namespaces/default/", "/dashboard/", "/api/v1/namespaces/kubernetes-dashboard/"],
        tags=["recon", "kubernetes", "k8s", "orchestration"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="kubelet API exposed without authentication allows pod listing, exec, and log access on any node",
            impact="Remote command execution on any pod, container breakout, credential theft, full cluster compromise",
            attack_scenario="Access http://node:10250/pods to list all pods; use /exec/{ns}/{pod}/{container} to execute commands; use /logs/{ns}/{pod} to read logs",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="etcd accessible without authentication exposes the entire cluster state including secrets, config maps, service account tokens, and RBAC policies",
            impact="Full cluster compromise — all secrets, passwords, TLS keys, and tokens are readable from etcd",
            attack_scenario="Connect to http://etcd:2379/v3/kv/range and list all keys; extract secrets, service account tokens, and TLS certificates",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Excessive RBAC permissions on a service account allow privilege escalation from a compromised pod to cluster-admin",
            impact="Full cluster takeover — attacker can create privileged pods, read all secrets, delete resources, install backdoors",
            attack_scenario="Compromise a pod with overprivileged SA; use token from /var/run/secrets/kubernetes.io/serviceaccount/token; escalate via RBAC bindings",
            complexity="medium",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="Automatic mounting of service account tokens exposes API credentials inside every pod even when not needed",
            impact="Compromised pod can access Kubernetes API with whatever permissions the SA has — often more than intended",
            attack_scenario="Read /var/run/secrets/kubernetes.io/serviceaccount/token from a compromised pod; use token to call API server",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Kubernetes Dashboard exposed without proper authentication allows full cluster management via web UI",
            impact="Complete cluster compromise — create pods, exec into containers, read secrets, scale deployments, delete resources",
            attack_scenario="Browse to dashboard URL; if skip login is enabled or anonymous access allowed, create a privileged pod with hostPath mount to the node filesystem",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Kubernetes uses Docker (or containerd) as its container runtime",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="nginx",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Nginx Ingress Controller provides ingress routing for Kubernetes",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Redis is commonly deployed on Kubernetes for caching and session stores",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="rabbitmq",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="RabbitMQ is deployed via Kubernetes Cluster Operator for messaging",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="aws",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Kubernetes runs on AWS via EKS or self-managed on EC2",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="azure",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Kubernetes runs on Azure via AKS",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="gcp",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Kubernetes runs on GCP via GKE",
            confidence="high",
        ),
    ],
    dependencies=["Linux", "containerd/CRI-O", "etcd", "CNI plugin", "CoreDNS"],
    related_packs=["docker", "nginx", "redis", "rabbitmq", "aws", "azure", "gcp"],
    workflow=[
        "1. Scan for Kubernetes API on port 6443 and kubelet on 10250/10255",
        "2. Check API server for anonymous access (/api/v1/ without credentials)",
        "3. Check kubelet API for unauthenticated access on port 10250",
        "4. Check etcd port 2379 for unauthenticated data store access",
        "5. Scan for Kubernetes Dashboard on common NodePort ports",
        "6. If API access is available, enumerate namespaces, pods, secrets",
        "7. Check RBAC bindings for overprivileged service accounts",
        "8. Look for service account tokens in pod filesystem mounts",
        "9. Check for privileged containers and hostPath volume mounts",
        "10. Test pod exec via kubelet or API server",
        "11. Search for kubeconfig files in CI/CD env, repos, and container images",
        "12. Check for open NodePort services exposing internal apps",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="K8S-01",
            category="kubelet API",
            description="Check if kubelet API is accessible without authentication on port 10250/10255",
            expected_result="kubelet should require authentication or be firewalled",
            tools=["curl", "kubectl", "nmap"],
            references=["https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/"],
        ),
        ManualTestChecklistItem(
            step_id="K8S-02",
            category="etcd Access",
            description="Check if etcd is accessible without authentication on port 2379",
            expected_result="etcd should require TLS client certificate authentication",
            tools=["etcdctl", "curl", "nmap"],
            references=["https://etcd.io/docs/latest/op-guide/security/"],
        ),
        ManualTestChecklistItem(
            step_id="K8S-03",
            category="RBAC Misconfiguration",
            description="Check for overprivileged service accounts with cluster-admin ClusterRoleBindings",
            expected_result="Service accounts should follow principle of least privilege",
            tools=["kubectl", "kubectl-who-can", "rakkess"],
            references=["https://kubernetes.io/docs/reference/access-authn-authz/rbac/"],
        ),
        ManualTestChecklistItem(
            step_id="K8S-04",
            category="Dashboard Exposure",
            description="Check if Kubernetes Dashboard is exposed without proper authentication",
            expected_result="Dashboard should require authentication and have restricted RBAC permissions",
            tools=["curl", "browser", "kubectl proxy"],
            references=["https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/"],
        ),
        ManualTestChecklistItem(
            step_id="K8S-05",
            category="Service Account Token Leakage",
            description="Check if service account tokens are leaked in pod logs, volumes, or repos",
            expected_result="Service account tokens should not be readable from within containers without explicit need",
            tools=["kubectl exec", "grep", "file scanning"],
            references=["https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/"],
        ),
        ManualTestChecklistItem(
            step_id="K8S-06",
            category="Privileged Containers",
            description="Check for containers running with privileged: true or dangerous capabilities",
            expected_result="Containers should not run with elevated privileges unless explicitly required",
            tools=["kubectl", "kube-bench", "kube-hunter"],
            references=["https://kubernetes.io/docs/concepts/security/pod-security-standards/"],
        ),
    ],
    references=[
        {"title": "Kubernetes Documentation", "url": "https://kubernetes.io/docs/"},
        {"title": "Kubernetes Security Documentation", "url": "https://kubernetes.io/docs/concepts/security/"},
        {"title": "NSA/CISA Kubernetes Hardening Guide", "url": "https://media.defense.gov/2022/Aug/29/2003066362/-1/-1/0/CTR_KUBERNETES_HARDENING_GUIDANCE_1.2_20220829.PDF"},
        {"title": "Kube-Hunter", "url": "https://github.com/aquasecurity/kube-hunter"},
        {"title": "OWASP Kubernetes Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Kubernetes_Cheat_Sheet.html"},
    ],
    cwe_ids=["CWE-306", "CWE-200", "CWE-862", "CWE-269", "CWE-276", "CWE-522", "CWE-250", "CWE-284"],
    cve_ids=["CVE-2024-10220", "CVE-2023-5528", "CVE-2023-3676", "CVE-2022-3294", "CVE-2022-3172", "CVE-2021-25741", "CVE-2020-8554", "CVE-2020-8555"],
    tags=["kubernetes", "k8s", "orchestration", "containers", "cloud-native", "go"],
)
