"""Nginx knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="nginx",
    version="1.0.0",
    category=KnowledgePackCategory.WEBSERVER,
    description="Nginx web server, reverse proxy, and load balancer — directory listing, path traversal via misconfigured alias/location directives, SSRF via proxy_pass, server tokens information disclosure, request smuggling, misconfigured CORS proxy.",
    technology=TechnologyProfile(
        name="Nginx",
        vendor="F5 Inc.",
        language="C",
        runtime="Nginx (standalone)",
        description="Nginx is a high-performance HTTP server, reverse proxy, and load balancer known for its event-driven architecture and low resource consumption. Widely used as a static file server, TLS terminator, and API gateway.",
        common_aliases=["nginx", "nginxinc", "nginx-proxy", "openresty"],
        dependencies=["Linux/Unix", "OpenSSL", "PCRE", "zlib"],
        common_integrations=["Nginx Unit", "OpenResty", "ModSecurity (NAXSI/WAF)", "Certbot", "Let's Encrypt", "Varnish Cache", "HAProxy", "Kubernetes Ingress", "Docker"],
        architecture_description="Event-driven, asynchronous, non-blocking architecture with master process and multiple worker processes. Supports HTTP/1.1, HTTP/2, HTTP/3, reverse proxy, load balancing, and streaming.",
        request_lifecycle="Client -> HTTP request -> Nginx worker (event loop) -> Location matching -> Static file / Proxy pass / FastCGI -> Response -> Logging",
        documentation_url="https://nginx.org/en/docs/",
        tags=["webserver", "reverse-proxy", "load-balancer", "c", "http"],
    ),
    components=[
        TechnologyComponentProfile(
            name="HTTP Core Module",
            description="Core HTTP functionality including request parsing, URI processing, and response generation. Request smuggling, path normalization bypasses.",
            security_relevance="high",
            common_vulnerabilities=["HTTP request smuggling", "Path traversal via misconfigured alias", "Directory listing enabled", "Server tokens disclosure"],
            investigation_priority=90,
            tags=["http", "core", "request-smuggling", "path-traversal"],
        ),
        TechnologyComponentProfile(
            name="Proxy Module (proxy_pass)",
            description="Reverse proxy functionality forwarding requests to upstream servers. SSRF, blind SSRF, internal network scanning.",
            security_relevance="high",
            common_vulnerabilities=["SSRF via proxy_pass to internal hosts", "Host header injection", "Internal IP disclosure", "Upstream response manipulation"],
            investigation_priority=95,
            tags=["proxy", "ssrf", "reverse-proxy", "head-injection"],
        ),
        TechnologyComponentProfile(
            name="Rewrite Module",
            description="URI rewriting and redirection using regex patterns. Open redirect, regex injection, unsafe redirect targets.",
            security_relevance="medium",
            common_vulnerabilities=["Open redirect via rewrite rules", "Regex injection", "Unvalidated redirect parameters"],
            investigation_priority=75,
            tags=["rewrite", "redirect", "regex"],
        ),
        TechnologyComponentProfile(
            name="Static File Serving",
            description="Direct static file serving via root and alias directives. Path traversal when alias is misconfigured without trailing slash.",
            security_relevance="high",
            common_vulnerabilities=["Path traversal via alias without trailing slash", "Directory listing", "Source code disclosure (.php, .py, .env files)"],
            investigation_priority=90,
            tags=["static", "alias", "root", "directory-listing"],
        ),
        TechnologyComponentProfile(
            name="SSL/TLS Module",
            description="TLS termination with certificate management. Weak cipher support, protocol downgrade, certificate validation bypass.",
            security_relevance="high",
            common_vulnerabilities=["Weak TLS ciphers", "Protocol downgrade (TLS 1.0/1.1)", "Certificate validation bypass", "Heartbleed (if old OpenSSL)"],
            investigation_priority=80,
            tags=["ssl", "tls", "certificate", "crypto"],
        ),
        TechnologyComponentProfile(
            name="Nginx Configuration",
            description="nginx.conf and site configuration files. Sensitive settings exposed, default admin pages, error page disclosure.",
            security_relevance="high",
            common_vulnerabilities=["Server tokens in HTTP responses", "Default error pages revealing version", "Missing security headers", "Exposed status endpoints (stub_status)"],
            investigation_priority=85,
            tags=["config", "security-headers", "information-disclosure", "stub-status"],
        ),
        TechnologyComponentProfile(
            name="ngx_http_auth_request_module",
            description="External authentication subrequest module. Authentication bypass, subrequest injection, timing attacks.",
            security_relevance="medium",
            common_vulnerabilities=["Auth bypass via subrequest manipulation", "Cache poisoning of auth responses", "Subrequest injection"],
            investigation_priority=70,
            tags=["auth", "subrequest", "authentication"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="HTTP Proxy (proxy_pass)",
                description="Reverse proxy endpoint forwarding requests to upstream servers",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/proxy/{target}",
                parameters=["url", "uri", "path"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.SSRF.value, BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Static File Serving",
                description="Direct static file serving via root/alias directives",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/static/{file_path}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.PATH_TRAVERSAL.value, BugClass.LFI.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Nginx Status Endpoint",
                description="Stub status page showing active connections, requests, and server health",
                protocol="HTTP/HTTPS",
                method="GET",
                path="/nginx_status",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="WebDAV (if enabled)",
                description="WebDAV module for remote file management",
                protocol="HTTP/HTTPS",
                method="PROPFIND",
                path="/webdav/{path}",
                parameters=[],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.RCE.value, BugClass.PATH_TRAVERSAL.value],
            ),
        ],
        endpoints=["/", "/nginx_status", "/status", "/health", "/healthz", "/readyz", "/metrics", "/api/", "/static/", "/media/", "/uploads/"],
        parameters=["url", "uri", "path", "next", "redirect", "target", "proxy_url", "backend"],
        authentication=["Basic auth (ngx_http_auth_basic_module)", "Subrequest auth (ngx_http_auth_request_module)", "JWT auth (OpenResty/third-party)", "Client certificate TLS auth"],
        authorization=["IP allow/deny (allow/deny directives)", "Auth basic user file", "Subrequest authorization", "OpenResty Lua access control"],
        storage=["Local filesystem", "NFS", "S3 (via proxy_pass)", "CDN origins"],
        background_jobs=["Log rotation", "Cache purging", "Certificate renewal (Certbot)"],
        queues=["Nginx upstream queues"],
        caches=["Nginx proxy_cache", "FastCGI cache", "uWSGI cache"],
        admin_interfaces=["/nginx_status", "/status", "/dashboard/", "/admin/"],
        internal_apis=["/api/", "/internal/", "/upstream_conf?upstream=", "/health/", "/healthz/"],
        external_apis=["Upstream API servers", "Authentication providers", "CDN origins"],
        trust_boundaries=[
            TrustBoundary(name="Client-to-Nginx", description="Incoming HTTP/HTTPS request from external client", direction="inbound", sensitivity="medium"),
            TrustBoundary(name="Nginx-to-Upstream", description="Proxy pass to backend application servers", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Nginx-to-Filesystem", description="Static file access on local or network filesystem", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Path traversal via alias directive without trailing slash",
            "SSRF via proxy_pass to internal IP addresses",
            "Server tokens disclosure of exact nginx version",
            "Directory listing on static file locations",
            "HTTP request smuggling (chunked encoding, CL.TE/TE.CL)",
            "Open redirect via rewrite rules and return directives",
            "Internal IP disclosure in error pages or headers",
            "Misconfigured CORS proxy allowing cross-origin attacks",
            "Cache poisoning via HTTP header injection",
            "Unprotected stub_status endpoint information disclosure",
            "Split-URL path normalization bypasses",
            "Host header injection through proxy_pass",
        ],
        investigation_areas=[
            "Check for Server header disclosing nginx version",
            "Test alias directives for path traversal (alias /dir/ vs alias /dir)",
            "Probe proxy_pass with internal IP addresses and ports",
            "Check for /nginx_status or /status endpoints",
            "Test for directory listing on /static/, /uploads/, /media/",
            "Verify server_tokens is set to off",
            "Test CL.TE and TE.CL request smuggling variants",
            "Check security headers (X-Frame-Options, X-XSS-Protection, HSTS)",
            "Inspect default error pages for version info and stack traces",
            "Test open redirect via return/rewrite directives",
            "Check for CORS proxy misconfiguration",
            "Test cache poisoning via header injection",
            "Verify TLS configuration (weak ciphers, protocol versions)",
        ],
        tags=["nginx", "webserver", "reverse-proxy", "load-balancer"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "nginx/",
            "Set-Cookie": "nginx-",
        },
        cookies=[],
        js_indicators=[],
        file_indicators=["nginx.conf", "nginx.conf.default", "sites-enabled/", "sites-available/", "Dockerfile.nginx", "nginx-docker"],
        directory_indicators=["/etc/nginx/", "/etc/nginx/sites-enabled/", "/etc/nginx/sites-available/", "/etc/nginx/conf.d/", "/usr/share/nginx/html/", "/var/log/nginx/"],
        server_signatures=["nginx", "nginx/", "openresty/"],
        error_page_signatures=["nginx", "404 Not Found", "502 Bad Gateway", "nginx/"],
        default_paths=["/", "/index.html", "/nginx_status", "/status", "/health"],
        default_files=["nginx.conf", "nginx.conf.default", "fastcgi_params", "proxy_params", "mime.types"],
        metadata_patterns={"server": "nginx|openresty", "x-nginx-": ""},
        tags=["fingerprint", "nginx", "webserver"],
    ),
    recon=ReconProfile(
        directories_to_check=["/nginx_status", "/status", "/health", "/healthz", "/readyz", "/metrics", "/static/", "/media/", "/uploads/", "/assets/"],
        files_to_check=["nginx.conf", "nginx.conf.default", "proxy_params", "fastcgi_params", "Dockerfile", "docker-compose.yml", ".dockerignore"],
        endpoints_to_scan=["/", "/nginx_status", "/status", "/health", "/api/", "/static/", "/proxy/", "/images/"],
        version_detection_paths=["/", "/index.html", "/404.html", "/50x.html"],
        debug_paths_to_check=["/nginx_status", "/status", "/debug", "/__debug__/"],
        admin_paths_to_check=["/nginx_status", "/status", "/dashboard/", "/admin/"],
        tags=["recon", "nginx", "webserver"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Nginx alias directive path traversal — when alias path lacks trailing slash, requesting /alias../ bypasses the location boundary",
            impact="Unauthorized file read outside the web root, source code disclosure, system file access",
            attack_scenario="Request /static../etc/passwd when alias is set to /var/www/static (without trailing slash)",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="SSRF via proxy_pass — nginx can be used as a proxy to internal services when the proxy_pass URL includes user-controlled input",
            impact="Internal network scanning, cloud metadata access, internal service compromise",
            attack_scenario="Set proxy_pass URL to http://169.254.169.254/latest/meta-data/ or http://internal-db:5432/",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Server tokens information disclosure — server_tokens on (default) leaks exact nginx version in Server header and error pages",
            impact="Version-specific vulnerability targeting, fingerprinting for known CVEs",
            attack_scenario="Capture Server header from any response or trigger a 404/50x error page",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Directory listing on static locations — autoindex on exposes all files in directories without an index file",
            impact="Exposure of source code, backup files, database dumps, configuration files",
            attack_scenario="Navigate to /static/, /uploads/, or /media/ directory without index.html",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="HTTP request smuggling via chunked encoding differences between nginx and backend",
            impact="Cache poisoning, request hijacking, WAF bypass, cross-user request contamination",
            attack_scenario="Send CL.TE or TE.CL malformed requests targeting discrepancies between nginx and upstream server",
            complexity="high",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="apache",
            relationship_type=KnowledgeRelationshipType.SIMILAR_TO,
            description="Nginx and Apache are both HTTP servers but use different architectures (event-driven vs process/thread)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="kubernetes",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Nginx is commonly used as Ingress controller in Kubernetes (nginx-ingress)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Nginx is commonly deployed as a Docker container",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="Nginx can use Redis as a cache backend via redis2 module",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="django",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Nginx frequently proxies Django applications via uWSGI or proxy_pass",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="express",
            relationship_type=KnowledgeRelationshipType.PROXIED_BY,
            description="Nginx proxies Node.js/Express applications",
            confidence="high",
        ),
    ],
    dependencies=["Linux/Unix", "OpenSSL", "PCRE", "zlib"],
    related_packs=["apache", "kubernetes", "docker", "redis"],
    workflow=[
        "1. Fingerprint nginx via Server header containing 'nginx/' and error page signatures",
        "2. Check for directory listing on common static directories (/static/, /uploads/, /media/)",
        "3. Test alias directive for path traversal using trailing slash bypass techniques",
        "4. Probe proxy_pass endpoints with internal IPs like 127.0.0.1, 169.254.169.254",
        "5. Check for unprotected stub_status or status endpoints",
        "6. Verify server_tokens by checking Server header for version number",
        "7. Test CL.TE and TE.CL request smuggling patterns",
        "8. Check security headers and CORS configuration",
        "9. Inspect TLS configuration for weak ciphers and protocol versions",
        "10. Test for open redirect via rewrite rules and $uri variables",
        "11. Check for internal IP disclosure in error pages and headers",
        "12. Test cache poisoning via HTTP header injection",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="NGINX-01",
            category="Information Disclosure",
            description="Check if Server header reveals nginx version (server_tokens on)",
            expected_result="Server header should not contain version number",
            tools=["curl"],
            references=["https://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens"],
        ),
        ManualTestChecklistItem(
            step_id="NGINX-02",
            category="Path Traversal",
            description="Test alias directive path traversal by requesting /<location>../etc/passwd",
            expected_result="Requests should not traverse outside the defined document root",
            tools=["curl", "Burp Suite"],
            references=["https://www.acunetix.com/vulnerabilities/web/path-traversal-via-misconfigured-nginx-alias/"],
        ),
        ManualTestChecklistItem(
            step_id="NGINX-03",
            category="SSRF",
            description="Test proxy_pass for SSRF by providing internal IPs and ports in the URL parameter",
            expected_result="Nginx should restrict proxy requests to allowed upstream destinations only",
            tools=["curl", "Burp Suite"],
            references=["https://owasp.org/www-community/attacks/Server_Side_Request_Forgery"],
        ),
        ManualTestChecklistItem(
            step_id="NGINX-04",
            category="Directory Listing",
            description="Check for autoindex enabled on directories without index files",
            expected_result="Directories should not list their contents, return 403 or 404 instead",
            tools=["curl", "Burp Suite"],
            references=["https://nginx.org/en/docs/http/ngx_http_autoindex_module.html"],
        ),
        ManualTestChecklistItem(
            step_id="NGINX-05",
            category="Request Smuggling",
            description="Test CL.TE and TE.CL request smuggling between nginx and upstream",
            expected_result="Nginx should reject or normalize ambiguous transfer-encoding/Content-Length requests",
            tools=["Burp Suite", "custom scripts", "smuggler.py"],
            references=["https://portswigger.net/web-security/request-smuggling"],
        ),
        ManualTestChecklistItem(
            step_id="NGINX-06",
            category="Security Headers",
            description="Verify presence and values of security headers (X-Frame-Options, HSTS, X-Content-Type-Options)",
            expected_result="All security headers should be present with secure values",
            tools=["curl", "securityheaders.com"],
            references=["https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options"],
        ),
    ],
    references=[
        {"title": "Nginx Documentation", "url": "https://nginx.org/en/docs/"},
        {"title": "Nginx Security Hardening Guide", "url": "https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/"},
        {"title": "OWASP Nginx Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/Nginx_Cheat_Sheet.html"},
        {"title": "Nginx Reverse Proxy Security", "url": "https://docs.nginx.com/nginx/admin-guide/security-controls/"},
        {"title": "CVE Nginx Collection", "url": "https://www.cve.org/KeywordSearch?keyword=nginx"},
    ],
    cwe_ids=["CWE-22", "CWE-918", "CWE-200", "CWE-548", "CWE-444", "CWE-601", "CWE-16"],
    cve_ids=["CVE-2024-24989", "CVE-2024-24990", "CVE-2023-44487", "CVE-2021-23017", "CVE-2021-3618", "CVE-2019-20372", "CVE-2018-16843"],
    tags=["nginx", "webserver", "reverse-proxy", "load-balancer", "http", "c"],
)
