"""RabbitMQ knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="rabbitmq",
    version="1.0.0",
    category=KnowledgePackCategory.MESSAGING,
    description="RabbitMQ message broker — default management login (guest/guest), virtual host enumeration, queue snooping and message inspection, unauthenticated AMQP access, management API abuse, TLS bypass on AMQP connections, exchange binding manipulation.",
    technology=TechnologyProfile(
        name="RabbitMQ",
        vendor="VMware (Pivotal Software / VMware Tanzu)",
        language="Erlang",
        runtime="Erlang OTP (BEAM VM)",
        description="RabbitMQ is the most widely deployed open-source message broker. Supports AMQP 0-9-1, AMQP 1.0, MQTT, STOMP, and HTTP protocols. Features flexible routing, clustering, high availability, and a management UI.",
        common_aliases=["rabbitmq", "rabbitmq-server", "rabbit", "rmq"],
        dependencies=["Erlang OTP", "Linux/Unix"],
        common_integrations=["RabbitMQ Management Plugin", "RabbitMQ Prometheus", "RabbitMQ MQTT Plugin", "RabbitMQ STOMP Plugin", "RabbitMQ Shovel", "RabbitMQ Federation", "RabbitMQ Delayed Message Plugin", "Celery", "Spring AMQP", "Masstransit"],
        architecture_description="Erlang-based message broker implementing AMQP. Producers send messages to exchanges which route to queues via bindings. Consumers consume from queues. Supports direct, topic, fanout, and headers exchanges.",
        request_lifecycle="Producer -> Exchange -> Binding -> Queue -> Consumer. Messages can be routed via exchange type and binding keys, with optional persistence and acknowledgements.",
        documentation_url="https://www.rabbitmq.com/documentation.html",
        tags=["messaging", "message-broker", "amqp", "erlang", "queue"],
    ),
    components=[
        TechnologyComponentProfile(
            name="RabbitMQ Management Plugin",
            description="Web-based management UI and HTTP API on port 15672. Default credentials (guest/guest), API abuse, queue management, user administration.",
            security_relevance="high",
            common_vulnerabilities=["Default guest/guest credentials", "Management API exposed without TLS", "Brute-force on management interface", "User creation via API", "Virtual host and queue enumeration"],
            investigation_priority=95,
            tags=["management", "http-api", "default-creds", "admin"],
        ),
        TechnologyComponentProfile(
            name="AMQP 0-9-1 Protocol",
            description="Core messaging protocol on port 5672. Unauthenticated access, queue declaration/exposure, message consumption without authorization.",
            security_relevance="high",
            common_vulnerabilities=["Unauthenticated AMQP access", "Queue declaration on protected vhosts", "Message eavesdropping via basic.consume", "Exchange binding manipulation"],
            investigation_priority=90,
            tags=["amqp", "protocol", "queue", "messaging"],
        ),
        TechnologyComponentProfile(
            name="RabbitMQ Management HTTP API",
            description="RESTful API for broker management at /api/. Full broker control via API — create queues, publish messages, manage users, and monitor.",
            security_relevance="high",
            common_vulnerabilities=["Unauthenticated API access", "User creation and permission escalation", "Queue and exchange CRUD via API", "Message publish/consume via API", "Sensitive data exposure in API responses"],
            investigation_priority=95,
            tags=["api", "rest", "management", "admin"],
        ),
        TechnologyComponentProfile(
            name="RabbitMQ Configuration",
            description="rabbitmq.config and rabbitmq-env.conf. Default cookie, exposed configuration, credential storage, TLS configuration.",
            security_relevance="high",
            common_vulnerabilities=["Default Erlang cookie (clustering)", "Configuration file exposure", "Plaintext credential storage", "TLS misconfiguration or disabled TLS"],
            investigation_priority=85,
            tags=["config", "cookie", "tls", "credentials"],
        ),
        TechnologyComponentProfile(
            name="MQTT Plugin",
            description="MQTT protocol support for IoT messaging. Unauthenticated publish/subscribe, topic enumeration, wildcard subscription.",
            security_relevance="medium",
            common_vulnerabilities=["Unauthenticated MQTT publish/subscribe", "Topic enumeration via subscribe", "Wildcard subscription (#) for all topics", "Will message abuse"],
            investigation_priority=75,
            tags=["mqtt", "iot", "pubsub", "protocol"],
        ),
        TechnologyComponentProfile(
            name="STOMP Plugin",
            description="STOMP protocol support for text-based messaging. Unauthenticated sessions, header injection, frame manipulation.",
            security_relevance="medium",
            common_vulnerabilities=["Unauthenticated STOMP connections", "Header injection via STOMP frames", "Destination hijacking", "Transaction abuse"],
            investigation_priority=70,
            tags=["stomp", "text", "protocol"],
        ),
        TechnologyComponentProfile(
            name="RabbitMQ Clustering (Erlang Cookie)",
            description="Cluster node communication using shared Erlang cookie. Cookie theft enables cluster node impersonation and full broker compromise.",
            security_relevance="high",
            common_vulnerabilities=["Default Erlang cookie (.erlang.cookie)", "Cookie file readable by other users", "Cluster join from untrusted nodes", "Node-to-node communication without TLS"],
            investigation_priority=85,
            tags=["cluster", "erlang", "cookie", "node"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Management Web UI",
                description="RabbitMQ management console at port 15672 with default credentials",
                protocol="HTTP/HTTPS",
                method="ANY",
                path="/api/{endpoint}",
                parameters=["username", "password", "vhost", "queue", "exchange"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.BROKEN_AUTH.value, BugClass.INFO_DISCLOSURE.value, BugClass.PRIVILEGE_ESCALATION.value],
            ),
            AttackSurfaceEntry(
                name="AMQP Port",
                description="Core AMQP 0-9-1 protocol on port 5672",
                protocol="AMQP/TCP",
                method="RAW",
                path="amqp://{host}:5672",
                parameters=["vhost", "queue", "exchange", "routing_key"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="AMQPS (TLS)",
                description="AMQP over TLS on port 5671",
                protocol="AMQPS/TCP",
                method="RAW",
                path="amqps://{host}:5671",
                parameters=["vhost", "queue", "exchange", "routing_key"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.CRYPTO_FAILURE.value],
            ),
            AttackSurfaceEntry(
                name="MQTT Port",
                description="MQTT protocol on port 1883 for IoT messaging",
                protocol="MQTT/TCP",
                method="PUBLISH",
                path="mqtt://{host}:1883/{topic}",
                parameters=["topic", "message", "qos"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="STOMP Port",
                description="STOMP protocol on port 61613 for text-based messaging",
                protocol="STOMP/TCP",
                method="SEND",
                path="stomp://{host}:61613/{destination}",
                parameters=["destination", "message", "transaction"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Erlang Distribution Port",
                description="Epmd and Erlang distribution for clustering (epmd: 4369, distribution: random range)",
                protocol="ERLANG/TCP",
                method="RAW",
                path="epmd://{host}:4369",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.RCE.value, BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["/api/", "/api/overview", "/api/queues", "/api/exchanges", "/api/bindings", "/api/connections", "/api/channels", "/api/users", "/api/vhosts", "/api/health/checks/alarms", "/api/health/checks/local-alarms", "/api/whoami"],
        parameters=["vhost", "queue", "exchange", "routing_key", "username", "password", "channel", "connection"],
        authentication=["Default guest/guest credentials", "Custom username/password", "LDAP (with auth_backend plugin)", "TLS client certificate authentication", "No authentication (default for AMQP)"],
        authorization=["Per-vhost permissions (configure, read, write)", "Topic permissions (regex-based routing key patterns)", "User tags (management, policymaker, monitoring, administrator)", "Resource-based permissions"],
        storage=["RabbitMQ message store (Mnesia)", "Message persistence to disk", "Quorum queues (Raft-based)"],
        background_jobs=["Queue auto-deletion", "Message TTL expiration", "Dead lettering", "Federation links", "Shovel transfers", "Lazy queue draining"],
        queues=["AMQP queues (default, quorum, stream)", "MQTT queues (auto-created)", "STOMP queues", "Plugins (delayed message, consistent hash)"],
        caches=[],
        admin_interfaces=["http://{host}:15672/", "https://{host}:15671/", "/api/"],
        internal_apis=["/api/", "/api/internal/", "/rabbitmq/"],
        external_apis=["HTTP API for management", "Prometheus metrics endpoint"],
        trust_boundaries=[
            TrustBoundary(name="Client-to-Broker", description="AMQP/MQTT/STOMP connection from producer/consumer to RabbitMQ", direction="inbound", sensitivity="high"),
            TrustBoundary(name="Broker-to-Node", description="Inter-node Erlang distribution communication in cluster", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Management-API-to-Broker", description="HTTP API calls to management interface", direction="inbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Default guest/guest credentials on management UI (port 15672)",
            "Unauthenticated AMQP access allowing queue declaration and message consumption",
            "Queue snooping — listing and consuming messages from sensitive queues",
            "Virtual host enumeration via API or AMQP AUTH failure messages",
            "Management API full broker control without proper authorization",
            "Erlang cookie theft leads to full cluster compromise",
            "MQTT wildcard subscription (#) for topic enumeration",
            "TLS disabled on management or AMQP ports allowing credential interception",
            "Default Erlang cookie using well-known value",
            "Configuration file containing plaintext credentials",
        ],
        investigation_areas=[
            "Check management UI on port 15672 for default guest/guest credentials",
            "Test AMQP port 5672 with guest/guest or no credentials",
            "Enumerate virtual hosts via API /api/vhosts or AMQP AUTH probe",
            "List queues on sensitive virtual hosts (/api/queues)",
            "Consume messages from queues to inspect payloads for sensitive data",
            "Test management API for privilege escalation (create admin user)",
            "Check Erlang cookie file location and permissions",
            "Scan for additional ports (epmd 4369, distribution ports)",
            "Test MQTT port 1883 with anonymous connections and # subscription",
            "Verify TLS configuration on management and AMQP ports",
            "Check for exposed configuration files (rabbitmq.config, .erlang.cookie)",
            "Test for federation/shovel link SSRF",
        ],
        tags=["rabbitmq", "messaging", "amqp", "message-broker", "queue"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "RabbitMQ",
            "x-rabbitmq-": "",
        },
        cookies=["rabbitmq-"],
        js_indicators=["RabbitMQ", "rabbitmq-", "amqp-client"],
        file_indicators=["rabbitmq.config", "rabbitmq-env.conf", "rabbitmq.conf", ".erlang.cookie", "enabled_plugins", "rabbitmq-plugins", "rabbitmqadmin"],
        directory_indicators=["/etc/rabbitmq/", "/var/lib/rabbitmq/", "/var/log/rabbitmq/", "/usr/lib/rabbitmq/"],
        server_signatures=["RabbitMQ", "RabbitMQ/"],
        error_page_signatures=["RabbitMQ Management", "rabbit@", "AMQP", "channel error", "connection refused"],
        default_paths=["/", "/api/", "/api/overview", "/api/whoami", "/mqtt/", "/stomp/"],
        default_files=["rabbitmq.config", "rabbitmq-env.conf", "rabbitmq.conf", ".erlang.cookie", "enabled_plugins", "rabbitmq.log", "sasl.log"],
        metadata_patterns={"server": "RabbitMQ", "x-rabbitmq-": "", "rabbitmq": ""},
        tags=["fingerprint", "rabbitmq", "messaging"],
    ),
    recon=ReconProfile(
        directories_to_check=["/api/", "/api/overview", "/api/whoami", "/mqtt/", "/stomp/"],
        files_to_check=["rabbitmq.config", "rabbitmq-env.conf", "rabbitmq.conf", ".erlang.cookie", "enabled_plugins", "rabbitmqadmin"],
        endpoints_to_scan=["http://{host}:15672/", "http://{host}:15672/api/", "amqp://{host}:5672/", "mqtt://{host}:1883/"],
        port_scan_targets=[15672, 15671, 5672, 5671, 1883, 61613, 4369],
        version_detection_paths=["/api/overview", "/api/whoami"],
        debug_paths_to_check=["/api/", "/api/health/checks/alarms", "/api/health/checks/local-alarms"],
        admin_paths_to_check=["http://{host}:15672/", "/api/", "/api/users", "/api/vhosts"],
        tags=["recon", "rabbitmq", "messaging"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Default guest/guest credentials with full access to / virtual host — any attacker can log in to the management UI and admin the broker",
            impact="Full broker compromise — queue manipulation, message inspection, user management, configuration changes",
            attack_scenario="Log in to http://target:15672 with guest/guest, access all queues, create admin users, export broker data",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Unauthenticated AMQP access allows connection to virtual hosts without credentials, enabling queue snooping and message theft",
            impact="Sensitive data leakage from message queues, business logic bypass, credential theft from messages",
            attack_scenario="Connect to AMQP port without AUTH, declare queues on the default vhost, consume messages with basic.consume",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Management API allows full broker control — queue CRUD, user management, permission modification, message publish/consume",
            impact="Complete compromise of messaging infrastructure, data exfiltration, denial of service, man-in-the-middle on messages",
            attack_scenario="Use /api/users to create admin user, /api/queues to enumerate and consume messages, /api/exchanges to publish fraudulent messages",
            complexity="low",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="Virtual host enumeration via AMQP connection failure messages reveals vhost names not intended for public access",
            impact="Identifies sensitive service boundaries, internal routing topologies, attack surface expansion",
            attack_scenario="Attempt AMQP connection to various vhost names, server returns distinct errors for existing vs non-existing vhosts",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Erlang cookie exposure (default or file-readable) allows cluster node impersonation leading to full broker RCE",
            impact="Remote code execution via Erlang distribution, full broker compromise, man-in-the-middle on all messages",
            attack_scenario="Read .erlang.cookie from exposed filesystem or backup, connect to Erlang distribution port with stolen cookie, execute shell commands via erlang:system_info or spawn",
            complexity="high",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="redis",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="RabbitMQ and Redis both serve as message brokers (AMQP vs pub/sub)",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="RabbitMQ is commonly deployed as a Docker container",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="kubernetes",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="RabbitMQ is deployed on Kubernetes using RabbitMQ Cluster Operator",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="django",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Django/Celery uses RabbitMQ as a message broker",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="spring",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Spring Boot applications use RabbitMQ via Spring AMQP",
            confidence="high",
        ),
    ],
    dependencies=["Erlang OTP", "Linux/Unix"],
    related_packs=["redis", "docker", "kubernetes", "django", "spring"],
    workflow=[
        "1. Scan for RabbitMQ ports: 5672 (AMQP), 15672 (management), 1883 (MQTT), 4369 (epmd)",
        "2. Test management UI at http://target:15672 with default guest/guest credentials",
        "3. If guest/guest works, enumerate all vhosts (/api/vhosts), queues (/api/queues), users (/api/users)",
        "4. Consume messages from sensitive queues (/api/queues/{vhost}/{queue}/get)",
        "5. Test AMQP port 5672 with guest/guest or anonymous connection",
        "6. Enumerate vhosts via AMQP auth failure messages",
        "7. Test MQTT port 1883 with anonymous subscription to # topic",
        "8. Check for .erlang.cookie file on exposed filesystems or backups",
        "9. Test /api/ endpoints for unauthenticated access",
        "10. Check TLS configuration on AMQPS port 5671 and HTTPS management",
        "11. Test for Shovel/Federation link SSRF",
        "12. Attempt privilege escalation from management to admin",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="RABBITMQ-01",
            category="Default Credentials",
            description="Test management UI with default guest/guest credentials",
            expected_result="Default credentials should be disabled or restricted to localhost only",
            tools=["curl", "browser", "Burp Suite"],
            references=["https://www.rabbitmq.com/access-control.html"],
        ),
        ManualTestChecklistItem(
            step_id="RABBITMQ-02",
            category="Queue Snooping",
            description="Consume messages from queues to identify sensitive data exposure",
            expected_result="Queue messages should be encrypted or not contain sensitive data",
            tools=["rabbitmqadmin", "curl", "Python (pika)"],
            references=["https://www.rabbitmq.com/management.html#http-api"],
        ),
        ManualTestChecklistItem(
            step_id="RABBITMQ-03",
            category="Unauthenticated Access",
            description="Test AMQP connection without authentication",
            expected_result="AMQP should require valid credentials for any operation",
            tools=["Python (pika)", "netcat", "amqp-utils"],
            references=["https://www.rabbitmq.com/access-control.html"],
        ),
        ManualTestChecklistItem(
            step_id="RABBITMQ-04",
            category="Virtual Host Enumeration",
            description="Probe for virtual host enumeration via AMQP connection attempts",
            expected_result="Error messages should not distinguish between existing and non-existing virtual hosts",
            tools=["Python (pika)", "custom scripts"],
            references=["https://book.hacktricks.xyz/network-services-pentesting/5672-pentesting-rabbitmq"],
        ),
        ManualTestChecklistItem(
            step_id="RABBITMQ-05",
            category="Erlang Cookie Exposure",
            description="Check for .erlang.cookie file exposure in backups, file disclosures, or config leaks",
            expected_result=".erlang.cookie should not be accessible and should be unique per cluster",
            tools=["File system analysis", "Backup analysis", "LFI testing"],
            references=["https://www.rabbitmq.com/clustering.html#erlang-cookie"],
        ),
    ],
    references=[
        {"title": "RabbitMQ Documentation", "url": "https://www.rabbitmq.com/documentation.html"},
        {"title": "RabbitMQ Access Control", "url": "https://www.rabbitmq.com/access-control.html"},
        {"title": "RabbitMQ Management HTTP API", "url": "https://www.rabbitmq.com/management.html"},
        {"title": "HackTricks RabbitMQ Pentesting", "url": "https://book.hacktricks.xyz/network-services-pentesting/5672-pentesting-rabbitmq"},
        {"title": "CVE RabbitMQ Collection", "url": "https://www.cve.org/KeywordSearch?keyword=RabbitMQ"},
    ],
    cwe_ids=["CWE-798", "CWE-306", "CWE-200", "CWE-862", "CWE-276", "CWE-522", "CWE-863"],
    cve_ids=["CVE-2024-27309", "CVE-2023-46124", "CVE-2023-35789", "CVE-2022-39220", "CVE-2022-29158", "CVE-2021-32718", "CVE-2020-36279"],
    tags=["rabbitmq", "messaging", "amqp", "message-broker", "queue", "erlang"],
)
