"""MongoDB knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="mongodb",
    version="1.0.0",
    category=KnowledgePackCategory.DATABASE,
    description="MongoDB — unauthenticated access (no-auth mode), default/no credentials (admin:admin), NoSQL injection (JSON query injection, $where injection, $toString bypass), exposed port 27017, backup file leaks (BSON/JSON exports), admin interface exposure (mongo-express), MongoDB Atlas misconfiguration, $lookup aggregation injection, MapReduce injection, and Replica Set exploitation.",
    technology=TechnologyProfile(
        name="MongoDB",
        vendor="MongoDB Inc.",
        language="C++",
        runtime="MongoDB Server (mongod) / MongoDB Atlas (cloud)",
        description="MongoDB is a source-available cross-platform document-oriented database program. Classified as a NoSQL database, MongoDB uses JSON-like documents with optional schemas. Supports horizontal scaling via sharding, replication via replica sets, aggregation pipeline, geospatial queries, transactions, and change streams.",
        common_aliases=["mongodb", "mongo", "mongod", "atlas"],
        dependencies=["mongosh (MongoDB Shell)", "mongodb-driver (Python/Node/Java/Ruby)", "mongoose (Node.js ODM)", "PyMongo (Python)", "Spring Data MongoDB"],
        common_integrations=["mongo-express", "MongoDB Compass", "MongoDB Atlas", "Mongoose", "Morphia", "Spring Data MongoDB", "Laravel MongoDB (jenssegers)", "MongoDB Charts", "MongoDB Realm", "Kafka (via MongoDB Kafka connector)", "Debezium (CDC)", "Atlas Search", "Atlas Data Lake"],
        architecture_description="MongoDB uses a document data model with databases containing collections (analogous to tables) and documents (JSON-like BSON format). A replica set provides high availability with primary-secondary replication. Sharding distributes data across shards for horizontal scaling. Mongos provides query routing in sharded clusters.",
        request_lifecycle="Client -> mongosh/driver -> TCP connection (port 27017) -> Wire Protocol (OP_MSG) -> Authentication (SCRAM, x.509, LDAP) -> Query planning -> Document retrieval from WiredTiger storage engine -> Response",
        documentation_url="https://www.mongodb.com/docs/",
        tags=["database", "nosql", "document", "open-source", "json", "bson"],
    ),
    components=[
        TechnologyComponentProfile(
            name="MongoDB Server (mongod)",
            description="Primary database daemon listening on port 27017 by default. Manages data storage, queries, replication, and sharding.",
            security_relevance="high",
            common_vulnerabilities=["Exposed port 27017 to public internet", "No authentication enabled (default on many installs)", "Default credentials (admin:admin, root:root)", "Weak SCRAM-SHA-1 authentication algorithm", "Authorization without authentication enabled (authorization disabled)"],
            investigation_priority=95,
            tags=["server", "mongod", "port-27017", "auth"],
        ),
        TechnologyComponentProfile(
            name="MongoDB NoSQL Injection Surface",
            description="Query operators ($where, $regex, $gt, $ne, $nin, $or, $expr) and aggregation pipeline ($lookup, $match, $group) can be injected into MongoDB queries.",
            security_relevance="high",
            common_vulnerabilities=["$where JavaScript injection allowing arbitrary code execution", "$regex blind NoSQL injection for data extraction", "$gt/$ne query operator injection for authentication bypass", "$lookup aggregation injection for cross-collection data extraction", "$expr injection for comparison-based extraction", "$toString/$convert type coercion bypass for injection", "MapReduce JavaScript injection (deprecated but exploitable)"],
            investigation_priority=95,
            tags=["nosql", "injection", "javascript", "aggregation", "where"],
        ),
        TechnologyComponentProfile(
            name="MongoDB Authentication",
            description="Authentication mechanisms including SCRAM (SCRAM-SHA-1, SCRAM-SHA-256), x.509 certificates, LDAP, and Kerberos.",
            security_relevance="high",
            common_vulnerabilities=["Authentication disabled (noauth mode)", "Default admin credentials (admin:admin, root:root)", "Weak SCRAM-SHA-1 hashing", "x.509 certificate validation bypass", "LDAP authentication misconfiguration", "MongoDB Atlas API key leakage"],
            investigation_priority=95,
            tags=["auth", "scram", "noauth", "credentials", "atlas"],
        ),
        TechnologyComponentProfile(
            name="mongo-express",
            description="Web-based MongoDB administration interface written in Node.js. Often deployed for easy database management.",
            security_relevance="high",
            common_vulnerabilities=["mongo-express exposed without authentication", "Default credentials (admin:pass)", "mongo-express SSRF vulnerability (CVE-2019-10758)", "mongo-express RCE via SSRF to MongoDB", "mongo-express exposed on default port 8081", "MongoDB connection string in mongo-express config"],
            investigation_priority=90,
            tags=["mongo-express", "admin-interface", "web-ui", "ssrf", "rce"],
        ),
        TechnologyComponentProfile(
            name="MongoDB Aggregation Pipeline",
            description="Powerful data processing pipeline using stages ($match, $group, $sort, $lookup, $unwind, $project). Can be abused for data extraction.",
            security_relevance="high",
            common_vulnerabilities=["$lookup injection for cross-collection data joining", "$match injection bypassing intended filters", "$facet injection for multi-faceted extraction", "$expr injection for expression-based exploitation", "$out injection writing results to arbitrary collections"],
            investigation_priority=90,
            tags=["aggregation", "pipeline", "injection", "lookup", "match"],
        ),
        TechnologyComponentProfile(
            name="MongoDB Backup Files",
            description="Database backups using mongodump (BSON format) or mongoexport (JSON). Backup files in web-accessible directories or cloud storage.",
            security_relevance="high",
            common_vulnerabilities=["mongodump files (.bson, .json) in web-accessible directories", "Automated backup cron job output in /backup/", "Gzipped archive dump files (.tar.gz, .tgz) with full DB contents", "MongoDB Atlas snapshots shared publicly", "Unencrypted backup storage exposing sensitive data"],
            investigation_priority=85,
            tags=["backup", "dump", "mongodump", "bson", "leakage"],
        ),
        TechnologyComponentProfile(
            name="MongoDB Atlas",
            description="Fully managed cloud database service. Includes IP whitelist, VPC peering, encryption at rest, and audit logging.",
            security_relevance="high",
            common_vulnerabilities=["Atlas cluster with 0.0.0.0/0 IP whitelist (any IP access)", "Atlas API key with excessive permissions", "Atlas database user with weak password", "Atlas connection string leakage (mongodb+srv://...)", "Atlas audit logging not enabled", "Atlas serverless instances with no network restrictions"],
            investigation_priority=85,
            tags=["atlas", "cloud", "managed", "whitelist", "api-key"],
        ),
        TechnologyComponentProfile(
            name="MapReduce (Deprecated)",
            description="Legacy JavaScript-based data processing. Map and reduce functions execute JavaScript on the server.",
            security_relevance="medium",
            common_vulnerabilities=["JavaScript injection in MapReduce functions", "MapReduce server-side JavaScript execution", "Unsafe user input in map/reduce function strings", "Deprecated but still functional in older versions"],
            investigation_priority=70,
            tags=["mapreduce", "javascript", "server-side", "deprecated"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="MongoDB TCP Port",
                description="Default MongoDB port exposed to network",
                protocol="TCP",
                method="N/A",
                path="tcp://{host}:27017",
                parameters=[],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="MongoDB Client Connection",
                description="MongoDB wire protocol connection accepting queries",
                protocol="TCP",
                method="N/A",
                path="mongodb://{host}:27017/{database}",
                parameters=["authSource", "replicaSet", "ssl", "connectTimeoutMS", "socketTimeoutMS"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.NO_SQL_INJECTION.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="MongoDB HTTP Interface",
                description="Legacy MongoDB HTTP interface (port 28017) or REST API",
                protocol="HTTP",
                method="GET",
                path="http://{host}:28017/",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="mongo-express Web Interface",
                description="Web-based MongoDB administration tool",
                protocol="HTTPS",
                method="ANY",
                path="http://{host}:8081/",
                parameters=[],
                authentication_required=True,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.SSRF.value, BugClass.RCE.value],
            ),
            AttackSurfaceEntry(
                name="MongoDB Backup File",
                description="mongodump BSON/JSON file accessible via HTTP",
                protocol="HTTPS/HTTP",
                method="GET",
                path="/backup/{database}.bson",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Application API with MongoDB",
                description="REST/GraphQL API endpoints backed by MongoDB, vulnerable to NoSQL injection",
                protocol="HTTPS",
                method="ANY",
                path="/api/{resource}",
                parameters=["query", "search", "filter", "where", "id", "username", "email"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.NO_SQL_INJECTION.value, BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["tcp://{host}:27017", "tcp://{host}:27018", "tcp://{host}:27019", "http://{host}:28017/", "http://{host}:8081/", "https://{host}/mongo-express/"],
        parameters=["authSource", "authMechanism", "replicaSet", "ssl", "connectTimeoutMS", "socketTimeoutMS", "compressors", "readPreference", "w", "journal"],
        authentication=["SCRAM-SHA-256 (default MongoDB 4.0+)", "SCRAM-SHA-1 (legacy)", "MONGODB-CR (deprecated)", "x.509 (certificate auth)", "LDAP (Enterprise)", "Kerberos (Enterprise)", "AWS IAM (Atlas)", "No authentication (--noauth / security.authorization: disabled)"],
        authorization=["Role-Based Access Control (RBAC) with built-in and custom roles", "Database user roles: read, readWrite, dbAdmin, dbOwner, userAdmin", "Cluster roles: clusterAdmin, clusterManager, hostManager", "Backup/Restore roles: backup, restore", "Global roles: readAnyDatabase, readWriteAnyDatabase, userAdminAnyDatabase, dbAdminAnyDatabase, root"],
        storage=["WiredTiger (default storage engine): WiredTiger.wt, index-*.wt, collection-*.wt", "In-Memory (Enterprise)", "MMAPv1 (deprecated)", "Oplog (local.oplog.rs for replica sets)", "Journal (WiredTiger journal)", "MongoDB Atlas storage (managed)"],
        background_jobs=["Replica set election (heartbeat every 2 seconds)", "Oplog sync (secondary replication)", "Balancer (sharded cluster chunk migration)", "Change streams (real-time data changes)", "TTL index expiration (automatic document deletion)", "Index builds (foreground / background)"],
        queues=["MongoDB change streams (real-time CDC)", "Kafka (via MongoDB Kafka connector)", "RabbitMQ (via pub/sub from change streams)"],
        caches=["WiredTiger internal cache", "MongoDB Atlas global write cache", "Application-level cache (Redis / in-memory)"],
        admin_interfaces=["mongosh (CLI Shell)", "MongoDB Compass (GUI)", "mongo-express (Web)", "MongoDB Atlas UI (cloud)", "MongoDB Ops Manager (on-prem management)", "MongoDB Cloud Manager", "Studio 3T (GUI)", "Robo 3T (GUI)"],
        internal_apis=["MongoDB Wire Protocol (port 27017)", "MongoDB HTTP status interface (port 28017)", "MongoDB Sharding (mongos on port 27017)"],
        external_apis=["MongoDB Wire Protocol (TCP)", "MongoDB Atlas API (cloud)", "MongoDB Realm SDK (mobile/serverless)", "MongoDB Data API (Atlas HTTP API)"],
        trust_boundaries=[
            TrustBoundary(name="Client-to-Database", description="Application or user connects to MongoDB via TCP Wire Protocol", direction="inbound", sensitivity="high"),
            TrustBoundary(name="Primary-to-Secondary", description="Replica set members communicate for oplog sync and elections", direction="bidirectional", sensitivity="high"),
            TrustBoundary(name="Mongos-to-Shard", description="Mongos router communicates with shards in sharded cluster", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "MongoDB port 27017 exposed to public internet without authentication",
            "No authentication enabled (--noauth or security.authorization: disabled)",
            "Default admin credentials (admin:admin, root:root) unchanged",
            "NoSQL injection in web applications using $where, $regex, $gt, $ne operators",
            "mongo-express web interface exposed without authentication",
            "Backup files (.bson, .json, .tar.gz) accessible from web server",
            "MongoDB Atlas cluster with 0.0.0.0/0 IP whitelist",
            "Atlas API keys or connection strings leaked in source code",
            "MongoDB HTTP interface (port 28017) exposing server status",
            "$lookup aggregation injection for cross-collection data extraction",
            "MapReduce JavaScript injection for server-side code execution",
            "Replica set without internal authentication allowing rogue member join",
        ],
        investigation_areas=[
            "Scan for open MongoDB port 27017 (and alternate ports 27018, 27019, 28017)",
            "Attempt connection without authentication (no username/password)",
            "Test default MongoDB credentials (admin:admin, root:root)",
            "Check for mongo-express at port 8081 or /mongo-express/ path",
            "Look for MongoDB backup files (.bson, .json, .tar.gz) in web directories",
            "Test web applications for NoSQL injection ($where, $regex, $gt, $ne)",
            "Check for MongoDB connection strings in client-side JS and source code",
            "Look for MongoDB Atlas connection strings (mongodb+srv://)",
            "Check for exposed MongoDB HTTP status at port 28017",
            "Attempt $lookup aggregation injection in MongoDB-backed APIs",
            "Test for MapReduce injection if aggregation is not available",
            "Check replica set configuration for internal auth requirements",
        ],
        tags=["mongodb", "mongo", "database", "nosql", "document"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "mongo-express",
        },
        cookies=["mongo-express"],
        js_indicators=["MongoDB", "mongodb", "mongosh", "mongoose", "MongoClient", "ObjectId", "ISODate", "$where", "$regex", "$ne", "$gt", "$lt", "$in", "$nin", "aggregate", "findOne", "insertOne"],
        file_indicators=[".bson (mongodump)", ".json (mongoexport)", ".tar.gz (dump archive)", "dump/", "mongodump", "mongoexport", "mongo-express", "mongoose", "mongodb+srv://", "mongodb://"],
        directory_indicators=["/var/lib/mongodb/", "/var/log/mongodb/", "/etc/mongod.conf", "/dump/", "/backup/", "/mongodb-backup/", "/data/db/", "/mongodb/"],
        server_signatures=["MongoDB", "mongod", "mongo-express", "mongos"],
        error_page_signatures=["MongoDB", "MongoError", "MongoServerError", "OperationFailed", "AuthenticationFailed", "not authorized for query", "MongoNetworkError", "MongooseError", "CastError", "Cannot read property", "BSON", "ObjectId", "$where", "$regex"],
        default_paths=["/mongo-express/", "/mongodb/", "/dump/", "/backup/"],
        default_files=["mongod.conf", "mongodb.conf", "dump", "*.bson", "*.json (mongoexport)", "archive.tar.gz", "connection.json", ".mongorc.js", "mongoose.js"],
        metadata_patterns={"MongoDB": "MongoError|MongoServerError|mongod|ObjectId|mongodb://"},
        tags=["fingerprint", "mongodb", "database"],
    ),
    recon=ReconProfile(
        directories_to_check=["/dump/", "/backup/", "/mongodb-backup/", "/mongo-express/", "/mongodb/", "/data/db/", "/mongodb/backup/"],
        files_to_check=["dump", "*.bson", "*.json", "archive.tar.gz", "backup.tar.gz", "mongod.conf", "mongodb.conf", ".mongorc.js", "connection.json", "mongoose.js", "app.js", "server.js", "index.js", ".env", "connectionstring.txt"],
        endpoints_to_scan=["tcp://{host}:27017", "tcp://{host}:27018", "tcp://{host}:27019", "http://{host}:28017/", "http://{host}:8081/", "https://{host}/mongo-express/", "https://{host}/dump/"],
        port_scan_targets=[27017, 27018, 27019, 28017, 8081, 27001, 27002],
        version_detection_paths=["http://{host}:28017/", "/mongo-express/"],
        debug_paths_to_check=["http://{host}:28017/", "/debug/", "/mongo-express/"],
        admin_paths_to_check=["/mongo-express/", "/mongodb/", "/admin/", "/db/", "/database/", "http://{host}:8081/"],
        tags=["recon", "mongodb", "database"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="MongoDB exposed on port 27017 without authentication allows anyone to read, write, and delete all databases",
            impact="Complete data compromise -- all documents (PII, credentials, financial data), collection deletion, ransomware via drop(), and configuration changes",
            attack_scenario="Scan for open port 27017; connect with mongosh {host}:27017; use admin; show dbs; use {target_db}; db.getCollectionNames(); db.{collection}.find().pretty(); extract all data; drop databases for destruction",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="NoSQL injection via $where operator allows JavaScript code execution on the MongoDB server (sandboxed but powerful)",
            impact="Authentication bypass, complete data extraction via blind injection, and denial of service via infinite loop or resource exhaustion",
            attack_scenario='Find NoSQLi in login endpoint; inject \'{"$where": "this.password == \'admin\' || \'1\'==\'1\'"}\' in JSON body; use $where with sleep() for time-based blind extraction; extract data character by character via $where regex matching',
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="NoSQL injection via $regex, $gt, $ne operators allows authentication bypass and blind data extraction without JavaScript execution",
            impact="Authentication bypass for login forms, data extraction via blind injection (character-by-character), and API query manipulation",
            attack_scenario='Send login with JSON \'{"username": "admin", "password": {"$ne": ""}}\' to bypass password check; use $regex for blind extraction: \'{"username": {"$regex": "^a"}}\' to extract usernames; combine with $gt/$lt for range-based extraction',
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="mongo-express exposed without authentication provides web-based GUI with full MongoDB access and SSRF/RCE capabilities",
            impact="Full database control and potential remote code execution via CVE-2019-10758 (SSRF to RCE through MongoDB)",
            attack_scenario="Browse to http://host:8081/; if no auth, access any database; use mongo-express to browse, edit, delete documents; exploit CVE-2019-10758 by setting up rogue MongoDB to achieve RCE on mongo-express host",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="MongoDB Atlas cluster with 0.0.0.0/0 IP whitelist allows any IP address to attempt database connections",
            impact="Exposure to brute-force attacks, credential guessing, and potential compromise of managed database",
            attack_scenario="Discover Atlas connection string from source code; attempt to connect from attacker IP; if whitelist is 0.0.0.0/0, start authentication brute-force; use extracted creds to access and exfiltrate data",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="MongoDB dump/backup files (.bson, .json) exposed via web server or public cloud storage leak entire database contents",
            impact="Complete data breach -- every document in every collection is exposed in machine-readable format",
            attack_scenario="Discover backup files via directory brute-force (/backup/, /dump/); download .bson and .json files; restore locally with mongorestore or parse JSON directly; extract all documents for analysis",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="mysql",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="MongoDB and MySQL are competing database types (NoSQL vs SQL)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="postgresql",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="MongoDB and PostgreSQL are competing database types (NoSQL vs SQL)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="express",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="MongoDB is commonly used with Express.js (MEAN/MEVN stacks)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="nestjs",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="MongoDB is commonly used with NestJS via Mongoose ODM",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="nextjs",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="MongoDB is commonly used with Next.js for full-stack applications",
            confidence="high",
        ),
    ],
    dependencies=["mongosh", "PyMongo", "mongoose", "mongodb-driver (Java)", "mongo (Go)"],
    related_packs=["mysql", "postgresql", "express", "nestjs", "nextjs"],
    workflow=[
        "1. Scan for open MongoDB port 27017 (and alternate ports 27018, 27019, 28017)",
        "2. Attempt connection without authentication (empty credentials)",
        "3. Test default credentials (admin:admin, root:root, test:test)",
        "4. Check for mongo-express at port 8081 or /mongo-express/ path",
        "5. Look for MongoDB backup files (.bson, .json) in /backup/, /dump/, /data/",
        "6. Test web application API endpoints for NoSQL injection",
        "7. Attempt $where injection with sleep() for time-based detection",
        "8. Attempt $regex injection for blind data extraction",
        '9. Try JSON body injection with {"$gt": ""} for auth bypass',
        "10. Look for MongoDB connection strings in source code, env files, and JS",
        "11. Check for MongoDB Atlas API keys and connection strings",
        "12. Test aggregation $lookup injection for cross-collection data access",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="MONGO-01",
            category="Port Exposure",
            description="Check if MongoDB port 27017 is exposed to the internet without authentication",
            expected_result="MongoDB should not be publicly accessible; authentication must be enabled",
            tools=["nmap", "masscan", "shodan", "mongosh"],
            references=["https://www.mongodb.com/docs/manual/security/"],
        ),
        ManualTestChecklistItem(
            step_id="MONGO-02",
            category="NoSQL Injection",
            description="Test web application endpoints for NoSQL injection ($where, $regex, $gt, $ne)",
            expected_result="Application should sanitize user input before building MongoDB queries",
            tools=["Burp Suite", "Postman", "nosqli (CLI)", "custom scripts"],
            references=["https://cheatsheetseries.owasp.org/cheatsheets/NoSQL_Injection_Cheat_Sheet.html"],
        ),
        ManualTestChecklistItem(
            step_id="MONGO-03",
            category="mongo-express Exposure",
            description="Check for mongo-express web interface exposed without authentication",
            expected_result="mongo-express should be password-protected or restricted to trusted networks",
            tools=["browser", "curl", "nmap"],
            references=["https://github.com/mongo-express/mongo-express"],
        ),
        ManualTestChecklistItem(
            step_id="MONGO-04",
            category="Default Credentials",
            description="Test MongoDB with default or weak credentials",
            expected_result="MongoDB should require strong authentication (SCRAM-SHA-256)",
            tools=["mongosh", "nmap (mongodb-brute)"],
            references=["https://www.mongodb.com/docs/manual/core/security-users/"],
        ),
        ManualTestChecklistItem(
            step_id="MONGO-05",
            category="Backup File Exposure",
            description="Search for publicly accessible MongoDB backup/dump files",
            expected_result="Backup files should not be accessible from web server or public storage",
            tools=["ffuf", "gobuster", "Google dorks"],
            references=["https://www.mongodb.com/docs/database-tools/mongodump/"],
        ),
        ManualTestChecklistItem(
            step_id="MONGO-06",
            category="Atlas Configuration Review",
            description="Check MongoDB Atlas cluster configuration for 0.0.0.0/0 IP whitelist",
            expected_result="Atlas IP whitelist should restrict access to trusted IPs only",
            tools=["MongoDB Atlas UI", "curl (Atlas API)"],
            references=["https://www.mongodb.com/docs/atlas/security/ip-access-list/"],
        ),
        ManualTestChecklistItem(
            step_id="MONGO-07",
            category="Connection String Leakage",
            description="Search for leaked MongoDB connection strings in source code and config files",
            expected_result="Connection strings should not be hardcoded or committed to source control",
            tools=["git-secrets", "truffleHog", "gitleaks", "grep"],
            references=["https://www.mongodb.com/docs/manual/reference/connection-string/"],
        ),
        ManualTestChecklistItem(
            step_id="MONGO-08",
            category="$lookup Aggregation Injection",
            description="Test for $lookup aggregation injection in MongoDB-backed APIs",
            expected_result="User input should not be passed directly into aggregation pipeline stages",
            tools=["Burp Suite", "custom scripts", "mongosh"],
            references=["https://www.mongodb.com/docs/manual/reference/operator/aggregation/lookup/"],
        ),
    ],
    references=[
        {"title": "MongoDB Security Documentation", "url": "https://www.mongodb.com/docs/manual/security/"},
        {"title": "MongoDB Security Checklist", "url": "https://www.mongodb.com/docs/manual/administration/security-checklist/"},
        {"title": "OWASP NoSQL Injection Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/NoSQL_Injection_Cheat_Sheet.html"},
        {"title": "HackTricks - MongoDB Pentesting", "url": "https://book.hacktricks.xyz/network-services-pentesting/pentesting-mongodb"},
        {"title": "NoSQL Injection in MongoDB", "url": "https://www.compass-security.com/fileadmin/Research/White_Papers/2017-01-14_NoSQL_Injection_White_Paper.pdf"},
        {"title": "mongo-express RCE (CVE-2019-10758)", "url": "https://github.com/mongo-express/mongo-express/security/advisories/GHSA-h47j-hc46-8w2h"},
        {"title": "MongoDB Atlas Security", "url": "https://www.mongodb.com/docs/atlas/security/"},
    ],
    cwe_ids=["CWE-306", "CWE-521", "CWE-943", "CWE-862", "CWE-200", "CWE-798", "CWE-284", "CWE-94", "CWE-552"],
    cve_ids=["CVE-2023-3694", "CVE-2022-1234", "CVE-2021-32038", "CVE-2019-10758", "CVE-2019-2386", "CVE-2019-2391", "CVE-2018-16763", "CVE-2017-2638"],
    tags=["mongodb", "mongo", "database", "nosql", "document", "open-source"],
)
