"""MySQL knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="mysql",
    version="1.0.0",
    category=KnowledgePackCategory.DATABASE,
    description="MySQL/MariaDB — unauthenticated access (no password root), default credentials (root:root, root:empty), SQL injection (comment syntax, UNION, stacked queries), exposed port 3306, backup file leaks (.sql, .sql.gz, mysqldump exports), phpMyAdmin admin interface exposure, LOAD DATA LOCAL INFILE abuse, secure_file_priv bypass, user-defined function (UDF) injection for RCE, and information_schema exploitation.",
    technology=TechnologyProfile(
        name="MySQL / MariaDB",
        vendor="Oracle Corporation (MySQL) / MariaDB Foundation (MariaDB)",
        language="C/C++",
        runtime="MySQL Server / MariaDB Server",
        description="MySQL is the world's most popular open-source relational database management system. MariaDB is a community-developed fork maintaining high compatibility. Both support InnoDB, MyISAM, and other storage engines, ACID compliance, replication (async, semi-sync, group), partitioning, and full-text search.",
        common_aliases=["mysql", "mariadb", "my sql", "maria db"],
        dependencies=["libmysqlclient (client library)", "mysql-connector (Python/Java/PHP)", "mysqli (PHP)", "mysql2 (Ruby)"],
        common_integrations=["phpMyAdmin", "MySQL Workbench", "Adminer", "DBeaver", "DataGrip", "TablePlus", "Laravel (Eloquent)", "WordPress", "Drupal", "Joomla", "Magento", "phpBB", "MediaWiki", "MySQL Router", "ProxySQL", "Galera Cluster", "Percona Toolkit", "XtraBackup", "mysqldump", "Liquibase", "Flyway"],
        architecture_description="Client-server architecture with a single mysqld daemon managing multiple databases. Storage engines are pluggable (InnoDB by default). User authentication handled via mysql.user table with native password, caching_sha2_password, or PAM plugins. Access control at global, database, table, and column levels via GRANT/REVOKE.",
        request_lifecycle="Client -> MySQL client library (TCP 3306) -> MySQL Protocol (TLS optional) -> Authentication (mysql.user) -> Query parsing -> Optimization -> Execution -> Storage engine -> Response",
        documentation_url="https://dev.mysql.com/doc/",
        tags=["database", "sql", "relational", "open-source", "rdbms", "mysql", "mariadb"],
    ),
    components=[
        TechnologyComponentProfile(
            name="MySQL Server (mysqld)",
            description="Main database server daemon listening on port 3306. Processes client connections, authenticates users, and executes queries.",
            security_relevance="high",
            common_vulnerabilities=["Exposed port 3306 to public internet", "Unauthenticated root access (root with no password)", "Default credentials (root:root, root:password)", "Authentication bypass (CVE-2012-2122)", "Remote code execution via UDF injection", "LOAD DATA LOCAL INFILE client-side exploit"],
            investigation_priority=95,
            tags=["server", "mysqld", "port-3306", "auth"],
        ),
        TechnologyComponentProfile(
            name="Authentication System (mysql.user)",
            description="User accounts and privileges stored in mysql system database. Authentication plugins (native, caching_sha2_password, ed25519, PAM, LDAP).",
            security_relevance="high",
            common_vulnerabilities=["Root account with no password (default on many installs)", "Wildcard host (%) in user accounts allowing remote access", "Weak password hashing (mysql_native_password)", "Anonymous user accounts with no password", "Default mysql.infoschema account with weak settings", "User with excessive global privileges (GRANT ALL)"],
            investigation_priority=95,
            tags=["auth", "users", "privileges", "mysql.user", "passwords"],
        ),
        TechnologyComponentProfile(
            name="MySQL SQL Interface",
            description="SQL parser and executor. Vulnerable to SQL injection, information_schema enumeration, and subquery exploitation.",
            security_relevance="high",
            common_vulnerabilities=["SQL injection bypassing input filters (comments, double dash, #)", "UNION-based SQLi with information_schema enumeration", "Stacked queries (multi-statement) in MySQL/mysqli", "Time-based blind SQL injection (BENCHMARK, SLEEP)", "Error-based SQLi via extractvalue, updatexml", "Out-of-band SQLi via LOAD_FILE, INTO OUTFILE"],
            investigation_priority=95,
            tags=["sql", "injection", "information_schema", "union", "blind"],
        ),
        TechnologyComponentProfile(
            name="User-Defined Functions (UDF)",
            description="Custom functions written in C/C++ loaded into MySQL. Malicious UDFs can execute shell commands and read files.",
            security_relevance="high",
            common_vulnerabilities=["UDF injection for RCE via sys_exec() or custom UDF", "Loading malicious shared library (.so/.dll) into plugin directory", "UDF privilege escalation from FILE privilege", "CREATE FUNCTION with aggregate and SONAME parameters"],
            investigation_priority=90,
            tags=["udf", "rce", "plugin", "function", "privilege-escalation"],
        ),
        TechnologyComponentProfile(
            name="phpMyAdmin",
            description="Web-based administration tool for MySQL/MariaDB. Widely deployed and frequently targeted.",
            security_relevance="high",
            common_vulnerabilities=["phpMyAdmin exposed without authentication", "Default credentials (root:root, root:empty)", "Outdated phpMyAdmin version with known CVEs", "phpMyAdmin setup page left enabled (setup/index.php)", "phpMyAdmin authentication bypass in old versions", "SQL execution panel available without auth"],
            investigation_priority=95,
            tags=["phpmyadmin", "admin-interface", "web-ui", "management"],
        ),
        TechnologyComponentProfile(
            name="Backup Files / SQL Dumps",
            description="mysqldump or mysqldbexport output files (.sql, .sql.gz, .sql.bz2) containing complete database schema and data.",
            security_relevance="high",
            common_vulnerabilities=["mysqldump files left in web-accessible directories", "Automated cron job backups in /backup/, /db-backup/, /daily/", "SQL dumps in cloud storage buckets with public access", "Dump files containing plaintext passwords and sensitive data", "Incremental binlog backup exposure"],
            investigation_priority=85,
            tags=["backup", "dump", "mysqldump", "leakage", "data-exposure"],
        ),
        TechnologyComponentProfile(
            name="LOAD DATA LOCAL INFILE",
            description="Client-side file read capability. Requests from server to read client-side files. Classic MySQL credential theft attack.",
            security_relevance="high",
            common_vulnerabilities=["Rogue MySQL server exploit stealing client files", "local-infile client option enabled allowing file read", "Credential theft from ~/.my.cnf and /etc/my.cnf", "Any client-side file exfiltration (id_rsa, .bash_history, etc.)"],
            investigation_priority=85,
            tags=["load-data", "local-infile", "rogue-server", "file-read", "credentials"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="MySQL TCP Port",
                description="Default MySQL port exposed to network",
                protocol="TCP",
                method="N/A",
                path="tcp://{host}:3306",
                parameters=[],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="MySQL Client Connection",
                description="MySQL wire protocol connection accepting SQL queries",
                protocol="TCP",
                method="N/A",
                path="tcp://{host}:{port}/{database}",
                parameters=[],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.SQL_INJECTION.value, BugClass.RCE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="phpMyAdmin Web Interface",
                description="Web-based MySQL administration tool",
                protocol="HTTPS",
                method="ANY",
                path="/phpmyadmin/",
                parameters=[],
                authentication_required=True,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.RCE.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="MySQL Backup File",
                description="mysqldump SQL file accessible via HTTP",
                protocol="HTTPS/HTTP",
                method="GET",
                path="/backup/{database}.sql",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="Adminer / Alternative Admin",
                description="Adminer or other web-based MySQL admin panel",
                protocol="HTTPS",
                method="ANY",
                path="/adminer.php",
                parameters=["server", "username", "db"],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
        ],
        endpoints=["tcp://{host}:3306", "tcp://{host}:3307", "tcp://{host}:3308", "tcp://{host}:6033 (ProxySQL)", "https://{host}/phpmyadmin/", "https://{host}/pma/", "https://{host}/adminer.php", "https://{host}/backup/{db}.sql", "https://{host}/{db}.sql.gz", "https://{host}/{db}.sql"],
        parameters=["character_set_results", "character_set_client", "character_set_connection", "collation_connection", "sql_mode"],
        authentication=["mysql_native_password (legacy hash)", "caching_sha2_password (default MySQL 8+)", "ed25519 (MariaDB)", "unix_socket (Unix socket auth)", "PAM (pluggable auth module)", "LDAP authentication", "Windows native authentication (MySQL on Windows)"],
        authorization=["Global privileges (ALL, SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, SUPER, PROCESS)", "Database-level privileges", "Table-level privileges", "Column-level privileges (SELECT(col), UPDATE(col))", "Stored procedure/function privileges (EXECUTE)", "Proxy user privileges"],
        storage=["InnoDB (default): ibdata, ib_logfile, .ibd files", "MyISAM: .MYD, .MYI files", "System tablespace and file-per-table tablespaces", "Binary logs (binlog)", "Relay logs (replication)", "General query log / slow query log", "Temporary files (/tmp)"],
        background_jobs=["Event scheduler (CREATE EVENT)", "Replication threads (I/O and SQL threads)", "Group replication consistency checks", "InnoDB purge, insert buffer merge", "MySQL Router routing"],
        queues=["Binary log (binlog) for replication and change data capture", "Kafka/Confluent (via Debezium for MySQL CDC)"],
        caches=["InnoDB buffer pool (innodb_buffer_pool_size)", "InnoDB change buffer", "Query cache (deprecated in MySQL 8)", "Thread cache", "Table open cache", "Prepared statement cache"],
        admin_interfaces=["phpMyAdmin (Web)", "Adminer (Web)", "MySQL Workbench (GUI)", "DBeaver", "DataGrip", "TablePlus", "mysql CLI (CLI)", "MySQL Shell (CLI/JS/Python)", "phpPgAdmin (Web)"],
        internal_apis=["MySQL Wire Protocol (port 3306)", "MySQL X Protocol (port 33060)", "Unix socket (/var/run/mysqld/mysqld.sock)"],
        external_apis=["MySQL Wire Protocol (TCP)", "X DevAPI (MySQL 8+)"],
        trust_boundaries=[
            TrustBoundary(name="Client-to-Database", description="Application or user connects to MySQL via TCP or Unix socket", direction="inbound", sensitivity="high"),
            TrustBoundary(name="Database-to-Filesystem", description="MySQL reads/writes data files, binlogs, and temp files", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Replication-Stream", description="Replica connects to source via replication protocol over TCP", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "MySQL port 3306 exposed to public internet",
            "Root account with no password or weak password",
            "Wildcard host (%) in GRANT allowing remote access",
            "SQL injection enabling data theft and authentication bypass",
            "phpMyAdmin exposed without authentication or with default creds",
            "Backup files (.sql, .sql.gz) accessible from web server",
            "LOAD DATA LOCAL INFILE rogue server attack stealing client files",
            "UDF injection for remote code execution",
            "Out-of-band SQL injection via LOAD_FILE, INTO OUTFILE, or UNC paths",
            "FILE privilege abused to read server files (/etc/passwd, configs)",
            "Information_schema enumeration for schema discovery via SQLi",
            "Insecure file permissions on MySQL data directory",
            "Anonymous accounts with no password allowing login",
            "Old MySQL version with known authentication bypass (CVE-2012-2122)",
        ],
        investigation_areas=[
            "Scan for open MySQL port 3306 (and alternate ports 3307, 3308, 6033)",
            "Attempt connection with root and no password",
            "Test common default credentials (root:root, root:password, root:admin)",
            "Check for phpMyAdmin at /phpmyadmin/, /pma/, /admin/, /mysql/",
            "Look for backup files (.sql, .sql.gz) in web-accessible directories",
            "Check for Adminer at /adminer.php",
            "Test web applications for SQL injection in MySQL-backed endpoints",
            "Attempt LOAD_FILE via SQL injection for server file reads",
            "Test UDF injection if FILE privilege is available via SQLi",
            "Try LOAD DATA LOCAL INFILE rogue MySQL server attack",
            "Look for MySQL credentials in PHP, Node, Python, Java source code",
            "Check for Adminer / phpMyAdmin autologin configurations",
        ],
        tags=["mysql", "mariadb", "database", "sql", "rdbms"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "Apache/MySQL",
        },
        cookies=["phpMyAdmin", "phpMyAdmin_https", "pma_"],
        js_indicators=["phpMyAdmin", "pma", "mysql", "mysqli", "Adminer", "MySQL", "phpMyAdmin"],
        file_indicators=[".sql (mysqldump)", ".sql.gz", ".sql.bz2", ".my.cnf", "my.cnf", "my.ini", "mysqldump", "dump.sql", "backup.sql", "db.sql", "database.sql", "wp-config.php", "config.inc.php", "configuration.php", "settings.php", ".mysql_history"],
        directory_indicators=["/var/lib/mysql/", "/var/lib/mysql-files/", "/etc/mysql/", "/usr/share/mysql/", "/backup/", "/dumps/", "/db-backup/", "/mysql/", "/phpmyadmin/"],
        server_signatures=["MySQL", "MariaDB", "phpMyAdmin"],
        error_page_signatures=["MySQL", "mysql", "mysqli", "mysqld", "You have an error in your SQL syntax", "Warning: mysqli_", "Warning: mysql_", "Fatal error: Uncaught mysqli_", "SQLSTATE[", "PDOException", "SQL syntax", "phpMyAdmin", "MySQL said: ", "#2002", "#1045", "#1049", "#1146", "#1130"],
        default_paths=["/phpmyadmin/", "/pma/", "/adminer.php", "/mysql/", "/mysql-admin/", "/backup/", "/dumps/", "/admin/", "/db/"],
        default_files=["dump.sql", "backup.sql", "database.sql", "db.sql", "mysql_dump.sql", "wp-config.php", "config.inc.php", "configuration.php", "settings.php", ".my.cnf", "my.cnf", "my.ini"],
        metadata_patterns={"MySQL": "SQL syntax|mysqli|phpMyAdmin|MariaDB|mysql_"},
        tags=["fingerprint", "mysql", "database"],
    ),
    recon=ReconProfile(
        directories_to_check=["/phpmyadmin/", "/pma/", "/adminer.php", "/mysql/", "/mysql-admin/", "/backup/", "/dumps/", "/db-backup/", "/sql/", "/database/", "/db/", "/admin/"],
        files_to_check=["dump.sql", "backup.sql", "database.sql", "db.sql", "wp-config.php", "config.inc.php", "configuration.php", "settings.php", "config.php", "database.php", "db.php", ".my.cnf", "my.cnf", "my.ini", ".env", "connect.php", "connection.php", ".mysql_history"],
        endpoints_to_scan=["tcp://{host}:3306", "tcp://{host}:3307", "tcp://{host}:3308", "https://{host}/phpmyadmin/", "https://{host}/pma/", "https://{host}/adminer.php", "https://{host}/backup/"],
        port_scan_targets=[3306, 3307, 3308, 6033, 33060, 33061, 33062],
        version_detection_paths=["/phpmyadmin/", "/pma/", "/adminer.php"],
        debug_paths_to_check=["/phpmyadmin/setup/", "/debug/", "/phpmyadmin/phpinfo.php", "/info.php"],
        admin_paths_to_check=["/phpmyadmin/", "/pma/", "/mysql/", "/adminer.php", "/admin/", "/db/", "/database/"],
        tags=["recon", "mysql", "database"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="MySQL exposed on port 3306 with root account having no password allows full database compromise",
            impact="Complete database takeover -- all databases, tables, and data are accessible; attacker can create users, modify data, drop databases, and potentially execute code via UDF",
            attack_scenario="Scan for open port 3306; connect with mysql -h {host} -u root; if no password required, enumerate databases with SHOW DATABASES; dump all tables with mysqldump-style queries; create backdoor user with GRANT ALL PRIVILEGES",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="SQL injection in web application using MySQL enables full data theft and potential file system access",
            impact="Data exfiltration of all database contents, authentication bypass, and potential server compromise via INTO OUTFILE or LOAD_FILE",
            attack_scenario="Find SQLi via ' or 1=1 -- -; determine number of columns with ORDER BY; extract data with UNION SELECT; if FILE privilege exists, read /etc/passwd via LOAD_FILE() or write webshell via INTO OUTFILE",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="phpMyAdmin exposed without authentication or with default credentials gives full GUI-based MySQL access",
            impact="Complete database control via web interface -- browse, edit, delete, import, export, and execute arbitrary SQL queries",
            attack_scenario="Browse to /phpmyadmin/; try root:root, root:password, root:empty; if successful, use SQL tab to execute arbitrary queries; export entire database; create new admin users",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="LOAD DATA LOCAL INFILE rogue MySQL server attack allows tricking clients into sending arbitrary files from their filesystem",
            impact="Theft of sensitive client-side files -- SSH keys, database credentials, source code, and application configuration",
            attack_scenario="Set up rogue MySQL server; trick client (web app, admin tool) to connect; request client-side file via LOAD DATA LOCAL INFILE '/root/.ssh/id_rsa'; receive file contents; repeat for other sensitive files",
            complexity="high",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="User-Defined Function (UDF) injection via SQL injection with FILE privilege enables remote command execution on the database server",
            impact="Remote code execution on the MySQL server -- full OS compromise, lateral movement to other systems",
            attack_scenario="With SQL injection giving FILE privilege, download UDF shared library via INTO DUMPFILE; CREATE FUNCTION sys_exec RETURNS INTEGER SONAME 'udf.so'; execute shell commands via SELECT sys_exec('id > /tmp/out'); read output via LOAD_FILE",
            complexity="medium",
            requires_authentication=True,
        ),
        BusinessLogicConcern(
            description="MySQL backup files (.sql dumps) exposed via web server or public cloud storage leak entire database schema and data",
            impact="Complete data breach -- all tables, user credentials, PII, financial transactions, and application secrets exposed",
            attack_scenario="Directory brute-force for /backup/, /dumps/, /db/; find .sql or .sql.gz files; download and parse for sensitive data including INSERT statements, passwords, credit cards, and hashes",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="postgresql",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="MySQL and PostgreSQL are competing open-source SQL databases",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="mongodb",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="MySQL and MongoDB are competing database types (SQL vs NoSQL)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="wordpress",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="WordPress uses MySQL/MariaDB as its database backend",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="drupal",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Drupal uses MySQL/MariaDB as its primary database",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="magento",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Magento uses MySQL/MariaDB as its database backend",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="laravel",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="Laravel commonly uses MySQL/MariaDB with Eloquent ORM",
            confidence="high",
        ),
    ],
    dependencies=["libmysqlclient", "mysql-connector-python", "mysqli", "mysql2"],
    related_packs=["postgresql", "mongodb", "wordpress", "drupal", "magento", "laravel"],
    workflow=[
        "1. Scan for open MySQL port 3306 (and alternate ports 3307, 3308, 6033)",
        "2. Attempt connection with root and no password",
        "3. Test common default credentials (root:root, root:password, root:admin, root:empty)",
        "4. Check for phpMyAdmin at /phpmyadmin/, /pma/, /mysql/, /admin/",
        "5. Look for backup/SQL files in /backup/, /dumps/, /sql/, /db/",
        "6. Test web applications for MySQL SQL injection",
        "7. If SQL injection found, attempt LOAD_FILE, INTO OUTFILE, and UNION extraction",
        "8. Attempt UDF injection if FILE privilege is accessible",
        "9. Check for Adminer at /adminer.php and test for access",
        "10. Look for MySQL credentials in config files (wp-config.php, config.inc.php)",
        "11. Check for LOAD DATA LOCAL INFILE vulnerable client configurations",
        "12. Examine .my.cnf and .mysql_history for credential exposure",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="MYSQL-01",
            category="Port Exposure",
            description="Check if MySQL port 3306 is exposed to the internet or untrusted networks",
            expected_result="MySQL should not be publicly accessible; bind to 127.0.0.1 or use firewalls",
            tools=["nmap", "masscan", "shodan"],
            references=["https://dev.mysql.com/doc/refman/8.0/en/server-options.html"],
        ),
        ManualTestChecklistItem(
            step_id="MYSQL-02",
            category="Default Credentials",
            description="Test MySQL with default or weak credentials (root:empty, root:root, root:password)",
            expected_result="Root should have a strong password configured",
            tools=["mysql CLI", "nmap (mysql-brute)", "hydra"],
            references=["https://dev.mysql.com/doc/refman/8.0/en/resetting-permissions.html"],
        ),
        ManualTestChecklistItem(
            step_id="MYSQL-03",
            category="SQL Injection Testing",
            description="Test application endpoints for MySQL SQL injection",
            expected_result="Application should use parameterized queries/prepared statements",
            tools=["sqlmap", "Burp Suite", "Postman"],
            references=["https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html"],
        ),
        ManualTestChecklistItem(
            step_id="MYSQL-04",
            category="phpMyAdmin Exposure",
            description="Check for phpMyAdmin web interface exposed without authentication",
            expected_result="phpMyAdmin should be password-protected or restricted to trusted networks",
            tools=["browser", "curl", "gobuster"],
            references=["https://docs.phpmyadmin.net/en/latest/setup.html"],
        ),
        ManualTestChecklistItem(
            step_id="MYSQL-05",
            category="Backup File Exposure",
            description="Search for publicly accessible MySQL backup/dump files",
            expected_result="Backup files should not be accessible from web server or public storage",
            tools=["ffuf", "gobuster", "Google dorks"],
            references=["https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html"],
        ),
        ManualTestChecklistItem(
            step_id="MYSQL-06",
            category="UDF Injection Testing",
            description="Test for UDF injection potential via SQL injection with FILE privilege",
            expected_result="Application database user should not have FILE privilege or plugin directory write access",
            tools=["sqlmap", "mysql CLI", "custom scripts"],
            references=["https://dev.mysql.com/doc/refman/8.0/en/create-function-udf.html"],
        ),
        ManualTestChecklistItem(
            step_id="MYSQL-07",
            category="FILE Privilege Abuse",
            description="Test if LOAD_FILE and INTO OUTFILE work via SQL injection for file read/write",
            expected_result="FILE privilege should not be granted to application database users",
            tools=["sqlmap (--file-read)", "mysql CLI"],
            references=["https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_load-file"],
        ),
        ManualTestChecklistItem(
            step_id="MYSQL-08",
            category="LOAD DATA LOCAL INFILE",
            description="Test for LOAD DATA LOCAL INFILE rogue server attack potential",
            expected_result="local-infile should be disabled on client side",
            tools=["mysql CLI", "rogue_mysql_server (GitHub)"],
            references=["https://dev.mysql.com/doc/refman/8.0/en/load-data-local-security.html"],
        ),
    ],
    references=[
        {"title": "MySQL Documentation", "url": "https://dev.mysql.com/doc/"},
        {"title": "MariaDB Documentation", "url": "https://mariadb.com/kb/en/"},
        {"title": "MySQL Security Guidelines", "url": "https://dev.mysql.com/doc/refman/8.0/en/security-guidelines.html"},
        {"title": "OWASP SQL Injection Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html"},
        {"title": "HackTricks - MySQL Pentesting", "url": "https://book.hacktricks.xyz/network-services-pentesting/pentesting-mysql"},
        {"title": "MySQL LOAD DATA LOCAL INFILE Abuse", "url": "https://www.rapid7.com/blog/post/2023/07/18/eternal-blue-and-mysql-rogue-server-attacks/"},
        {"title": "CVE MySQL Collection", "url": "https://www.cve.org/KeywordSearch?keyword=MySQL"},
    ],
    cwe_ids=["CWE-306", "CWE-521", "CWE-89", "CWE-862", "CWE-200", "CWE-798", "CWE-284", "CWE-77", "CWE-552"],
    cve_ids=["CVE-2023-22102", "CVE-2023-22100", "CVE-2022-21592", "CVE-2022-21367", "CVE-2021-2389", "CVE-2021-2252", "CVE-2016-6662", "CVE-2012-2122"],
    tags=["mysql", "mariadb", "database", "sql", "rdbms", "open-source"],
)
