"""Hypothesis generation engine.

Produces ranked investigation hypotheses based on retrieved SKOs,
bug class prevalence, technology stacks, and framework-aware reasoning.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Optional, Set
from uuid import uuid4

from deephunter.core.config import ReasoningConfig
from deephunter.core.exceptions import ReasoningError
from deephunter.core.types import BugClass, Confidence, Technology
from deephunter.knowledge.models import SecurityKnowledgeObject
from deephunter.knowledge.store import KnowledgeStore
from deephunter.rag.retriever import Retriever
from deephunter.utils.logging import get_logger

logger = get_logger(__name__)


class HypothesisPriority(Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


@dataclass
class Hypothesis:
    """A single investigation hypothesis.

    Generated by the reasoning engine, each hypothesis represents
    a potential vulnerability or security concern worth investigating.
    """

    id: str = field(default_factory=lambda: f"hyp-{uuid4().hex[:12]}")
    title: str = ""
    description: str = ""
    bug_classes: List[BugClass] = field(default_factory=list)
    technology: List[Technology] = field(default_factory=list)
    priority: HypothesisPriority = HypothesisPriority.MEDIUM
    confidence: Confidence = Confidence.UNKNOWN
    rationale: str = ""
    testing_ideas: List[str] = field(default_factory=list)
    related_skos: List[str] = field(default_factory=list)
    references: List[str] = field(default_factory=list)
    created: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "title": self.title,
            "description": self.description,
            "bug_classes": [b.value for b in self.bug_classes],
            "technology": [t.value for t in self.technology],
            "priority": self.priority.value,
            "confidence": self.confidence.value,
            "rationale": self.rationale,
            "testing_ideas": self.testing_ideas,
            "related_skos": self.related_skos,
            "references": self.references,
            "created": self.created.isoformat(),
        }


class HypothesisGenerator:
    """Generates ranked investigation hypotheses from knowledge.

    The generator uses the RAG retriever to find relevant SKOs,
    then applies heuristic rules to produce hypotheses ranked
    by priority and confidence.

    Usage::

        gen = HypothesisGenerator(store, retriever, config.reasoning)
        hypotheses = gen.generate("JWT authentication")
    """

    # Rule templates mapping bug classes to hypothesis templates
    HYPOTHESIS_RULES: Dict[BugClass, Dict[str, str]] = {
        BugClass.AUTH_BYPASS: {
            "title": "Authentication bypass in {tech} application",
            "description": (
                "The application uses {tech} for authentication, "
                "which may contain common bypass patterns found in knowledge base."
            ),
            "rationale": (
                "Authentication logic is frequently discovered to have "
                "implementation flaws in {tech}-based applications."
            ),
            "test": "Test for missing or weak token validation in {tech} endpoints.",
        },
        BugClass.SQL_INJECTION: {
            "title": "SQL injection in {tech} parameters",
            "description": (
                "The application uses {tech} and may have SQL injection "
                "vulnerabilities in user-supplied parameters."
            ),
            "rationale": (
                "SQL injection remains prevalent in {tech} applications "
                "when input validation is insufficient."
            ),
            "test": "Test all user-supplied parameters for SQL injection using common payloads.",
        },
        BugClass.XSS: {
            "title": "Cross-site scripting in {tech} templates",
            "description": (
                "The application uses {tech} which may have template injection "
                "or reflection XSS vulnerabilities."
            ),
            "rationale": (
                "XSS is consistently the most reported vulnerability in "
                "web applications across all technology stacks."
            ),
            "test": "Test all input fields and URL parameters for XSS reflection.",
        },
        BugClass.IDOR: {
            "title": "Insecure direct object reference in {tech} API",
            "description": (
                "The {tech} application may expose direct object references "
                "in its API endpoints."
            ),
            "rationale": (
                "IDOR vulnerabilities are common in {tech} REST APIs "
                "when authorization checks are missing on object-level operations."
            ),
            "test": "Enumerate object IDs in API endpoints and verify authorization.",
        },
        BugClass.SSRF: {
            "title": "Server-side request forgery in {tech} application",
            "description": (
                "The {tech} application may be vulnerable to SSRF if it "
                "fetches remote resources based on user input."
            ),
            "rationale": (
                "SSRF is a critical vulnerability in {tech} applications "
                "that process URLs or fetch external content."
            ),
            "test": "Identify features that fetch URLs and test with internal address schemes.",
        },
        BugClass.RACE_CONDITION: {
            "title": "Race condition in {tech} concurrent operations",
            "description": (
                "The {tech} application may have race conditions in "
                "concurrent state-modifying operations."
            ),
            "rationale": (
                "Race conditions are frequently overlooked in {tech} "
                "applications with async processing."
            ),
            "test": "Send concurrent requests to state-modifying endpoints.",
        },
        BugClass.DESERIALIZATION: {
            "title": "Insecure deserialization in {tech} application",
            "description": (
                "The {tech} application may be vulnerable to deserialization "
                "attacks if it processes serialized objects."
            ),
            "rationale": (
                "Insecure deserialization is a critical class of vulnerability "
                "in {tech} applications handling user-supplied data."
            ),
            "test": "Identify endpoints that accept serialized formats and test with malformed payloads.",
        },
    }

    def __init__(
        self,
        store: KnowledgeStore,
        retriever: Retriever,
        config: ReasoningConfig,
    ) -> None:
        self._store = store
        self._retriever = retriever
        self._config = config

    def generate(
        self,
        context: str,
        skos: Optional[List[SecurityKnowledgeObject]] = None,
    ) -> List[Hypothesis]:
        """Generate hypotheses based on a context query and optional SKOs.

        Args:
            context: Description of the target or research focus.
            skos: Optional pre-retrieved SKOs (if not provided, uses RAG).

        Returns:
            Ranked list of Hypothesis objects.

        Raises:
            ReasoningError: If hypothesis generation fails.
        """
        try:
            if skos is None:
                scored = self._retriever.query(context)
                skos = [s for s, _ in scored]
        except Exception as exc:
            raise ReasoningError(f"Failed to retrieve context SKOs: {exc}") from exc

        bug_class_counts: Dict[BugClass, int] = {}
        tech_set: Set[Technology] = set()

        for sko in skos:
            for bc in sko.bug_classes:
                bug_class_counts[bc] = bug_class_counts.get(bc, 0) + 1
            tech_set.update(sko.technology)

        # Also scan store-wide for relevant patterns
        all_skos = self._store.list_all()
        for sko in all_skos:
            for bc in sko.bug_classes:
                if bc not in bug_class_counts:
                    bug_class_counts[bc] = 1

        tech_list = list(tech_set) if tech_set else [Technology.OTHER]

        hypotheses: List[Hypothesis] = []
        for bc, count in bug_class_counts.items():
            if count <= 0:
                continue
            rule = self.HYPOTHESIS_RULES.get(bc)
            if rule is None:
                continue

            tech_str = tech_list[0].value if tech_list else "the"
            confidence = self._confidence_from_count(count)

            hyp = Hypothesis(
                title=rule["title"].format(tech=tech_str),
                description=rule["description"].format(tech=tech_str),
                bug_classes=[bc],
                technology=tech_list[:3],
                priority=self._priority_from_confidence(confidence),
                confidence=confidence,
                rationale=rule["rationale"].format(tech=tech_str),
                testing_ideas=[rule["test"].format(tech=tech_str)],
                related_skos=[s.id for s in skos if bc in s.bug_classes][:5],
            )
            hypotheses.append(hyp)

        hypotheses.sort(key=lambda h: (h.priority.value, h.confidence.value))
        limit = self._config.hypothesis_limit
        hypotheses = hypotheses[:limit]

        logger.info("Generated %d hypotheses", len(hypotheses))
        return hypotheses

    @staticmethod
    def _confidence_from_count(count: int) -> Confidence:
        if count >= 5:
            return Confidence.HIGH
        if count >= 3:
            return Confidence.MEDIUM
        return Confidence.LOW

    @staticmethod
    def _priority_from_confidence(conf: Confidence) -> HypothesisPriority:
        mapping = {
            Confidence.HIGH: HypothesisPriority.CRITICAL,
            Confidence.MEDIUM: HypothesisPriority.HIGH,
            Confidence.LOW: HypothesisPriority.MEDIUM,
            Confidence.UNKNOWN: HypothesisPriority.LOW,
        }
        return mapping.get(conf, HypothesisPriority.MEDIUM)