from __future__ import annotations

import json
import time
from typing import Any

from deephunter.agents.base import Agent, AgentResult


class ReportGenerationWorkflow(Agent):
    """Workflow 11: Report Generation.

    Generates a structured bug bounty report from prepared findings.
    Supports Markdown, JSON, and HTML formats. Includes executive
    summary, finding details, evidence, remediation steps, and
    appendices.
    """

    def __init__(self, name: str | None = None) -> None:
        super().__init__(name or "report_gen")
        self._description = "Report generation — structured bug bounty report in Markdown/JSON/HTML"

    def execute(self, context: dict[str, Any]) -> AgentResult:
        started = time.monotonic()
        findings_data = context.get("findings", context.get("prepared_findings", []))
        target = context.get("target", context.get("program", "Unknown Target"))
        format_type = context.get("format", "markdown")
        author = context.get("author", "DeepHunter")

        if not findings_data:
            return AgentResult(agent_name=self.name, success=False, error="No findings to report")

        summary = context.get("summary", {})
        total = summary.get("total", len(findings_data))
        by_severity = summary.get("by_severity", {})

        if format_type == "json":
            report = json.dumps({
                "report": {
                    "target": target,
                    "author": author,
                    "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "summary": {"total": total, "by_severity": by_severity},
                    "findings": findings_data,
                }
            }, indent=2)
        elif format_type == "html":
            parts = [f"<html><head><title>Bug Bounty Report — {target}</title>"]
            parts.append("<style>body{font-family:sans-serif;margin:2em}table{border-collapse:collapse}")
            parts.append("th,td{border:1px solid #ccc;padding:8px}th{background:#f5f5f5}")
            parts.append(".critical{background:#ffd7d7}.high{background:#ffefd7}")
            parts.append(".medium{background:#fffdd7}.low{background:#f0ffd7}")
            parts.append("</style></head><body>")
            parts.append(f"<h1>Bug Bounty Report — {target}</h1>")
            parts.append(f"<p>Generated by {author} on {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}</p>")
            parts.append(f"<h2>Summary</h2><p>Total findings: {total}</p><ul>")
            for sev, count in by_severity.items():
                if count > 0:
                    parts.append(f"<li>{sev.capitalize()}: {count}</li>")
            parts.append("</ul>")
            parts.append("<h2>Findings</h2>")
            for f in findings_data:
                sev_class = f.get("severity", "medium")
                parts.append(f'<div class="{sev_class}">')
                parts.append(f"<h3>{f.get('title', 'Finding')}</h3>")
                parts.append(f"<p><strong>Severity:</strong> {sev_class}</p>")
                parts.append(f"<p><strong>Endpoint:</strong> <code>{f.get('endpoint', '')}</code></p>")
                parts.append(f"<p><strong>Description:</strong> {f.get('description', '')}</p>")
                if f.get("evidence"):
                    parts.append(f"<pre>{f['evidence'][:500]}</pre>")
                if f.get("remediation"):
                    parts.append(f"<p><strong>Remediation:</strong> {f['remediation']}</p>")
                parts.append("</div>")
            parts.append("</body></html>")
            report = "\n".join(parts)
        else:
            lines = [f"# Bug Bounty Report — {target}", ""]
            lines.append(f"**Generated by:** {author}")
            lines.append(f"**Date:** {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}")
            lines.append("")
            lines.append("## Summary")
            lines.append(f"**Total findings:** {total}")
            for sev, count in by_severity.items():
                if count and count > 0:
                    lines.append(f"- **{sev.capitalize()}:** {count}")
            lines.append("")
            lines.append("## Findings")
            lines.append("")
            for i, f in enumerate(findings_data, 1):
                lines.append(f"### {i}. {f.get('title', 'Untitled')}")
                lines.append(f"- **Severity:** {f.get('severity', 'unknown')}")
                lines.append(f"- **Confidence:** {f.get('confidence', 'medium')}")
                lines.append(f"- **Category:** {f.get('category', 'unknown')}")
                lines.append(f"- **Endpoint:** `{f.get('endpoint', '')}`")
                if f.get("description"):
                    lines.append(f"- **Description:** {f['description']}")
                if f.get("evidence"):
                    lines.append(f"- **Evidence:**")
                    lines.append("  ```")
                    lines.append(f"  {f['evidence'][:500]}")
                    lines.append("  ```")
                if f.get("remediation"):
                    lines.append(f"- **Remediation:** {f['remediation']}")
                if f.get("references"):
                    refs = f["references"]
                    if isinstance(refs, list):
                        for r in refs:
                            lines.append(f"- **Reference:** {r}")
                    else:
                        lines.append(f"- **Reference:** {refs}")
                lines.append("")
            report = "\n".join(lines)

        elapsed = (time.monotonic() - started) * 1000
        return AgentResult(
            agent_name=self.name,
            success=True,
            data={"report": report, "format": format_type, "target": target, "finding_count": len(findings_data)},
            execution_time_ms=elapsed,
        )
